# -*- coding: utf-8 -*-
"""Microbloques de léxico para las semanas 27-51 (tramo C1).

Dos bloques por semana, que build_course.py suma al final de la lección de
esa semana (y a su última parte, si la lección va en partes):

  1. Formación de palabras: un sufijo o un prefijo, con familias tomadas de
     la lectura larga de la semana (tools/it/tramo/wNN.json).  Los ejercicios
     «Formá la palabra» son los c1-fp-WW-* de tools/it/authored/c1_lessico.py.
  2. Colocaciones de la semana: verbo + sustantivo (y algún adjetivo +
     sustantivo) de la misma lectura, que separan un texto B2 de uno C1.
     Sus ejercicios son los c1-co-WW-*.

No es un módulo de lecciones (no tiene LESSONS): son bloques que se agregan
a las lecciones de s3.py y s4.py sin tocarlas.  Mismo formato de bloque que
tools/it/lessons/__init__.py; los controla tools/it/check_lessons.py.
"""

_CO = "Estas palabras **van juntas** en la lectura de la semana: aprendelas en bloque, verbo y sustantivo, como si fueran una sola."


def _fam(h, r, head, rows, ex, warn=None):
    b = {"h": h, "r": r, "table": {"head": head, "rows": rows}, "ex": ex}
    if warn:
        b["warn"] = warn
    return b


def _co(rows, ex, r=_CO):
    return {"h": "Colocaciones de la semana", "r": r,
            "table": {"head": ["Colocación", "Castellano"], "rows": rows}, "ex": ex}


_B = ["Base", "Derivado", "Castellano"]

EXTRA_BLOCKS = {
    27: [
        _fam("Formación: -ezza, la cualidad",
             "Adjetivo + *-ezza* = la cualidad: *amaro* → *amarezza*, *certo* → *certezza*. Es femenino.",
             _B, [["amaro", "amarezza", "amargura"], ["certo", "certezza", "certeza"],
                  ["lento", "lentezza", "lentitud"], ["triste", "tristezza", "tristeza"],
                  ["gentile", "gentilezza", "amabilidad"], ["debole", "debolezza", "debilidad"],
                  ["dolce", "dolcezza", "dulzura"], ["grande", "grandezza", "grandeza, tamaño"]],
             [["Osserva con una certa *amarezza* che tutto è cambiato.", "Observa con cierta amargura que todo cambió."],
              ["Lo struscio offre la *certezza* di un posto.", "El paseo ofrece la certeza de un lugar."]],
             "*-ezza* no siempre es «-eza»: *lentezza* es «lentitud», *dolcezza* es «dulzura», *gentilezza* es «amabilidad»."),
        _co([["cambiare volto", "cambiar de cara, transformarse"], ["alzare / abbassare la serranda", "abrir / cerrar el negocio"],
             ["abbassare le luci", "bajar las luces"], ["difendere una tradizione", "defender una tradición"],
             ["scambiare due chiacchiere", "charlar un rato"], ["avere un appuntamento", "tener una cita"],
             ["fare lo struscio", "hacer el paseo (por la calle principal)"], ["svolgere una funzione", "cumplir una función"],
             ["un rito sociale", "un rito social"]],
            [["Alle sette la piazza *cambia volto*.", "A las siete la plaza cambia de cara."],
             ["I negozianti *alzano le serrande*.", "Los comerciantes abren las persianas (los negocios)."]]),
    ],
    28: [
        _fam("Formación: -mento, la acción",
             "Verbo + *-mento* = la acción o su resultado: *investire* → *investimento*. Es masculino, como «-miento».",
             _B, [["investire", "investimento", "inversión"], ["fallire", "fallimento", "fracaso; quiebra"],
                  ["cambiare", "cambiamento", "cambio"], ["trasferire", "trasferimento", "traslado, mudanza"],
                  ["spopolare", "spopolamento", "despoblación"], ["collegare", "collegamento", "conexión"],
                  ["rinnovare", "rinnovamento", "renovación"], ["sentire", "sentimento", "sentimiento"]],
             [["Il vero *investimento* è la banda larga.", "La verdadera inversión es la banda ancha."],
              ["Sarebbe ingiusto parlare di un *fallimento*.", "Sería injusto hablar de un fracaso."]],
             "*Fallimento* es «fracaso» o «quiebra», no «fallecimiento» (= *morte*, *decesso*)."),
        _co([["mettere in vendita", "poner en venta"], ["chiarire un equivoco", "aclarar un malentendido"],
             ["risolvere un problema", "resolver un problema"], ["passare l'inverno", "pasar el invierno"],
             ["avere un merito", "tener un mérito"], ["valere la pena", "valer la pena"],
             ["rendere credibile", "volver creíble"], ["rinunciare a", "renunciar a, desistir"],
             ["le aree interne", "las zonas del interior (lejos de los servicios)"]],
            [["Il paese *mette in vendita* le case a un euro.", "El pueblo pone en venta las casas a un euro."],
             ["Bisogna *chiarire un equivoco*.", "Hay que aclarar un malentendido."]]),
    ],
    29: [
        _fam("Formación: -are → -azione",
             "Verbo en *-are* → sustantivo en *-azione*: *amministrare* → *amministrazione*. Femenino, como «-ación».",
             _B, [["amministrare", "amministrazione", "administración"], ["circolare", "circolazione", "circulación, tránsito"],
                  ["pedonalizzare", "pedonalizzazione", "peatonalización"], ["limitare", "limitazione", "limitación"],
                  ["organizzare", "organizzazione", "organización"], ["applicare", "applicazione", "aplicación"],
                  ["manifestare", "manifestazione", "manifestación; evento"], ["informare", "informazione", "información"]],
             [["Temo che l'*amministrazione* abbia avuto fretta.", "Temo que la administración haya tenido apuro."],
              ["La colpa non è stata solo della *pedonalizzazione*.", "La culpa no fue solo de la peatonalización."]],
             "*Manifestazione* es «manifestación», pero también «evento»: *una manifestazione sportiva* es un evento deportivo."),
        _co([["chiudere al traffico", "cerrar al tránsito"], ["chiedere le dimissioni", "pedir la renuncia"],
             ["fare un bilancio", "hacer un balance"], ["avere l'impressione", "tener la impresión"],
             ["assumere personale", "contratar personal"], ["rispettare i tempi", "cumplir los plazos"],
             ["prendere una decisione", "tomar una decisión"], ["costruire una città più vivibile", "construir una ciudad más habitable"],
             ["un suicidio economico", "un suicidio económico"]],
            [["Oggi vale la pena *fare un bilancio*.", "Hoy vale la pena hacer un balance."],
             ["Il Comune non ha *rispettato i tempi*.", "La municipalidad no cumplió los plazos."]]),
    ],
    30: [
        _fam("Formación: -ità, la cualidad",
             "Adjetivo + *-ità* (o *-tà*) = la cualidad: *sincero* → *sincerità*. Femenino, invariable y con tilde.",
             _B, [["sincero", "sincerità", "sinceridad"], ["credibile", "credibilità", "credibilidad"],
                  ["curioso", "curiosità", "curiosidad"], ["serio", "serietà", "seriedad"],
                  ["falso", "falsità", "falsedad"], ["vero", "verità", "verdad"],
                  ["rapido", "rapidità", "rapidez"], ["originale", "originalità", "originalidad"]],
             [["Ammette, con una *sincerità* rara, di aver sbagliato.", "Admite, con una sinceridad poco común, que se equivocó."],
              ["Una bugia fa perdere *credibilità*.", "Una mentira hace perder credibilidad."]],
             "No cambia en plural: *una verità*, *due verità*. Y *rapidità* es «rapidez», no «rapididad»."),
        _co([["sentirsi in colpa", "sentirse culpable"], ["prendere sul serio", "tomar en serio"],
             ["ricevere insulti", "recibir insultos"], ["andare in stampa", "entrar en imprenta, publicarse"],
             ["cercare un colpevole", "buscar un culpable"], ["condividere un articolo", "compartir una nota"],
             ["rilanciare una notizia", "difundir, volver a publicar una noticia"], ["controllare una notizia", "chequear una noticia"],
             ["una notizia falsa", "una noticia falsa"]],
            [["Nessuno lo *prendeva sul serio*.", "Nadie lo tomaba en serio."],
             ["Non mi ha fatto *sentire in colpa*.", "No me hizo sentir culpable."]]),
    ],
    31: [
        _fam("Formación: -tore / -trice, quién lo hace",
             "Verbo + *-tore* (masculino) o *-trice* (femenino) = la persona que hace algo: *dirigere* → *direttore*, *direttrice*.",
             ["Verbo", "Masculino", "Femenino"],
             [["dirigere", "direttore", "direttrice"], ["amministrare", "amministratore", "amministratrice"],
              ["lavorare", "lavoratore", "lavoratrice"], ["produrre", "produttore", "produttrice"],
              ["allevare", "allevatore", "allevatrice"], ["consumare", "consumatore", "consumatrice"],
              ["vendere", "venditore", "venditrice"]],
             [["Oggi Laura è una *produttrice* di formaggi.", "Hoy Laura es productora de quesos."],
              ["L'*amministratore* delegato vuole una relazione.", "El director ejecutivo quiere un informe."]],
             "Los verbos en *-durre* hacen *-duttore* / *-duttrice*: *produrre* → *produttore*, *tradurre* → *traduttrice*."),
        _co([["fare l'avvocata / il medico", "ser abogada / médico (de profesión)"], ["bruciare i ponti", "quemar las naves"],
             ["fare sacrifici", "hacer sacrificios"], ["fare i conti", "hacer las cuentas"],
             ["seguire un corso", "hacer un curso"], ["cambiare vita", "cambiar de vida"],
             ["ridere in faccia", "reírse en la cara"], ["rovinare una carriera", "arruinar una carrera"],
             ["un anno sabbatico", "un año sabático"]],
            [["Ha *fatto l'avvocata* per dodici anni.", "Fue abogada durante doce años."],
             ["Avrei *seguito un corso* serio.", "Habría hecho un curso serio."]]),
    ],
    32: [
        _fam("Formación: -anza / -enza",
             "*-anza* (de verbos en *-are*) y *-enza* (de *-ere*, *-ire*) forman sustantivos: *somigliare* → *somiglianza*.",
             _B, [["somigliare", "somiglianza", "parecido"], ["cittadino", "cittadinanza", "ciudadanía"],
                  ["tendere", "tendenza", "tendencia"], ["esistere", "esistenza", "existencia"],
                  ["appartenere", "appartenenza", "pertenencia"], ["conoscere", "conoscenza", "conocimiento"],
                  ["assente", "assenza", "ausencia"], ["presente", "presenza", "presencia"]],
             [["Quando ho ottenuto la *cittadinanza* ho deciso di partire.", "Cuando obtuve la ciudadanía decidí viajar."],
              ["Nel paese non c'era traccia della sua *presenza*.", "En el pueblo no había rastro de su presencia."]],
             "*-enza* no siempre es «-encia»: *conoscenza* es «conocimiento» y *partenza*, «partida»."),
        _co([["ottenere la cittadinanza", "obtener la ciudadanía"], ["offrire un caffè", "invitar un café"],
             ["tirare fuori", "sacar (de un cajón, de un bolsillo)"], ["rendersi conto", "darse cuenta"],
             ["rimanere in silenzio", "quedarse callado"], ["fare una promessa", "hacer una promesa"],
             ["la casa è crollata", "la casa se derrumbó"], ["le giornate limpide", "los días despejados"]],
            [["Nunziata ha *tirato fuori* una fotografia.", "Nunziata sacó una foto."],
             ["Mi sono *reso conto* di tutto sull'autobus.", "Me di cuenta de todo en el colectivo."]]),
    ],
    33: [
        _fam("Formación: -abile / -ibile, «que se puede»",
             "Verbo + *-abile* (de *-are*) o *-ibile* (de *-ere*, *-ire*) = «que se puede…»: *accettare* → *accettabile*.",
             _B, [["accettare", "accettabile", "aceptable"], ["prevedere", "prevedibile", "previsible"],
                  ["sostenere", "sostenibile", "sostenible; soportable"], ["comprendere", "comprensibile", "comprensible"],
                  ["raggiungere", "raggiungibile", "alcanzable, accesible"], ["affidare", "affidabile", "confiable"],
                  ["trasferire", "trasferibile", "transferible"]],
             [["È un rimpianto *comprensibile*, ma non è una bussola.", "Es un arrepentimiento comprensible, pero no es una brújula."],
              ["La proposta è *accettabile* solo se è chiara.", "La propuesta es aceptable solo si es clara."]],
             "*Affidabile* es «confiable», no «afable» (= *cordiale*, *gentile*)."),
        _co([["offrire un posto", "ofrecer un puesto"], ["perdere il treno", "perder el tren (también la oportunidad)"],
             ["mettere per iscritto", "poner por escrito"], ["svolgere un lavoro", "realizar un trabajo"],
             ["fare una confessione", "hacer una confesión"], ["meritare una risposta", "merecer una respuesta"],
             ["correre il rischio", "correr el riesgo"], ["un contratto a tempo indeterminato", "un contrato por tiempo indeterminado (efectivo)"]],
            [["Chi restava fermo *perdeva il treno*.", "El que se quedaba quieto perdía el tren."],
             ["Chiedi che le condizioni siano *messe per iscritto*.", "Pedí que las condiciones se pongan por escrito."]]),
    ],
    34: [
        _fam("Formación: -oso, «lleno de»",
             "Sustantivo + *-oso* = adjetivo «que tiene, lleno de»: *affetto* → *affettuoso*, *noia* → *noioso*.",
             _B, [["affetto", "affettuoso", "cariñoso"], ["noia", "noioso", "aburrido"],
                  ["rispetto", "rispettoso", "respetuoso"], ["orgoglio", "orgoglioso", "orgulloso"],
                  ["gelosia", "geloso", "celoso"], ["silenzio", "silenzioso", "silencioso"],
                  ["prezzo", "prezioso", "valioso"], ["spazio", "spazioso", "espacioso"]],
             [["Per chi ha figli ogni ora libera è *preziosa*.", "Para quien tiene hijos cada hora libre es valiosa."],
              ["È un amico *affettuoso*, ma scrive poco.", "Es un amigo cariñoso, pero escribe poco."]],
             "*Prezioso* es «valioso»; «precioso» en el sentido de «lindo» se dice *bellissimo* o *carino*."),
        _co([["fissare un appuntamento", "arreglar una cita"], ["proporre una data", "proponer una fecha"],
             ["prendere l'iniziativa", "tomar la iniciativa"], ["coltivare un'amicizia", "cultivar una amistad"],
             ["contare su qualcuno", "contar con alguien"], ["tenere il conto", "llevar la cuenta"],
             ["rimandare un messaggio", "postergar un mensaje"], ["un conto in banca", "una cuenta bancaria"],
             ["una relazione stabile", "una relación estable"]],
            [["Nessuno ha il tempo di *coltivare* questi rapporti.", "Nadie tiene tiempo de cultivar estas relaciones."],
             ["Sono persone su cui si può *contare*.", "Son personas con las que se puede contar."]]),
    ],
    35: [
        _fam("Formación: los nombres del ambiente",
             "Los problemas y los remedios del ambiente se nombran con *-mento* y *-zione*: *inquinare* → *inquinamento*.",
             _B, [["inquinare", "inquinamento", "contaminación"], ["smaltire", "smaltimento", "eliminación (de residuos)"],
                  ["riscaldare", "riscaldamento", "calentamiento; calefacción"], ["trattare", "trattamento", "tratamiento"],
                  ["depurare", "depurazione", "depuración"], ["proteggere", "protezione", "protección"],
                  ["ossigenare", "ossigenazione", "oxigenación"]],
             [["Il lago compariva solo nei rapporti sull'*inquinamento*.", "El lago aparecía solo en los informes sobre contaminación."],
              ["I volontari controllano le reti di *protezione*.", "Los voluntarios controlan las redes de protección."]],
             "*Inquinamento* es la palabra común para «contaminación»; *contaminazione* se usa más para sustancias peligrosas."),
        _co([["affidare a", "confiar, encargar a"], ["cambiare approccio", "cambiar de enfoque"],
             ["compensare le perdite", "compensar las pérdidas"], ["mantenere l'equilibrio", "mantener el equilibrio"],
             ["comunicare i risultati", "comunicar los resultados"], ["andare liscio", "salir bien, sin problemas"],
             ["organizzare un'assemblea", "organizar una asamblea"], ["invitare a partecipare", "invitar a participar"],
             ["una discarica abusiva", "un basural clandestino"]],
            [["Poi abbiamo *cambiato approccio*.", "Después cambiamos de enfoque."],
             ["Non tutto è *andato liscio*.", "No todo salió bien."]]),
    ],
    36: [
        _fam("Formación: s- y dis-, lo contrario",
             "*s-* y *dis-* delante de un adjetivo, sustantivo o verbo dan el contrario: *comodo* → *scomodo*, *abitato* → *disabitato*.",
             _B, [["comodo", "scomodo", "incómodo"], ["conosciuto", "sconosciuto", "desconocido"],
                  ["fiducia", "sfiducia", "desconfianza"], ["abitato", "disabitato", "deshabitado"],
                  ["occupato", "disoccupato", "desocupado, desempleado"], ["ordine", "disordine", "desorden"],
                  ["attento", "disattento", "distraído"], ["piacere", "dispiacere", "disgusto, pena"]],
             [["Sulle scale si incontrano *sconosciuti*.", "En la escalera te cruzás con desconocidos."],
              ["Molti appartamenti restano *disabitati*.", "Muchos departamentos quedan deshabitados."]],
             "Con algunos verbos *s-* no niega: *sbattere* es «golpear» y *scambiare*, «intercambiar»."),
        _co([["fare pace", "hacer las paces"], ["ritirare le chiavi", "retirar las llaves"],
             ["integrare un reddito", "complementar un ingreso"], ["trovare un equilibrio", "encontrar un equilibrio"],
             ["fare finta di niente", "hacerse el distraído"], ["perdere iscritti", "perder alumnos inscriptos"],
             ["gli affitti salgono", "los alquileres suben"], ["suonare il campanello", "tocar el timbre"],
             ["un provvedimento drastico", "una medida drástica"]],
            [["Si litiga per il rumore e si *fa pace* sulle scale.", "Se pelea por el ruido y se hacen las paces en la escalera."],
             ["Non si può più *fare finta di niente*.", "Ya no se puede hacer como si nada."]]),
    ],
    37: [
        _fam("Formación: -ismo e -ista",
             "*-ismo* nombra la idea o el movimiento; *-ista*, a la persona: *femminismo* → *femminista*.",
             ["Idea", "Persona", "Castellano"],
             [["femminismo", "femminista", "feminismo / feminista"], ["ottimismo", "ottimista", "optimismo / optimista"],
              ["pessimismo", "pessimista", "pesimismo / pesimista"], ["turismo", "turista", "turismo / turista"],
              ["attivismo", "attivista", "activismo / activista"], ["realismo", "realista", "realismo / realista"],
              ["giornalismo", "giornalista", "periodismo / periodista"]],
             [["Teresa non era *femminista*, ma quel giorno votò.", "Teresa no era feminista, pero ese día votó."],
              ["Rosa guardava il voto con *pessimismo*.", "Rosa miraba la votación con pesimismo."]],
             "*-ista* termina en *-a* también en masculino: *il turista*, *i turisti*, *le turiste*."),
        _co([["tirare la tenda", "correr la cortina"], ["dare istruzioni", "dar instrucciones"],
             ["fare una battuta", "hacer un chiste, un comentario"], ["fare la fila", "hacer la cola"],
             ["prendere la mano", "tomar de la mano"], ["fare il segno", "marcar (la boleta)"],
             ["allestire il seggio", "armar la mesa electoral"], ["il certificato elettorale", "el certificado electoral"]],
            [["Teresa entrò nella cabina e *tirò la tenda*.", "Teresa entró al cuarto oscuro y corrió la cortina."],
             ["Un uomo *fece una battuta* sulle donne.", "Un hombre hizo un comentario sobre las mujeres."]]),
    ],
    38: [
        _fam("Formación: ri-, otra vez",
             "*ri-* delante de un verbo = otra vez, de vuelta: *aprire* → *riaprire*, *popolare* → *ripopolare*.",
             _B, [["aprire", "riaprire", "volver a abrir"], ["popolare", "ripopolare", "repoblar"],
                  ["portare", "riportare", "traer de vuelta"], ["fare", "rifare", "rehacer"],
                  ["costruire", "ricostruire", "reconstruir"], ["pensare", "ripensare", "repensar"],
                  ["partire", "ripartire", "volver a arrancar"], ["nascere", "rinascere", "renacer"]],
             [["Il bar ha *riaperto* tutti i giorni.", "El bar volvió a abrir todos los días."],
              ["Un paese non si *ripopola* soltanto con gli incentivi.", "Un pueblo no se repuebla solo con incentivos."]],
             "No todo *ri-* es «de nuevo»: *riportare una notizia* es «informar» y *ricordare* es solo «recordar»."),
        _co([["fare un giro", "dar una vuelta"], ["rendersi conto", "darse cuenta"],
             ["impegnarsi a", "comprometerse a"], ["chiedere un sostegno", "pedir apoyo"],
             ["dare sulla valle", "dar al valle (una ventana)"], ["scrivere una lettera anonima", "escribir una carta anónima"],
             ["andarsene", "irse"], ["la stufa a legna", "la estufa a leña"]],
            [["Aveva *fatto un giro* per le case vuote.", "Había dado una vuelta por las casas vacías."],
             ["La finestra *dà sulla valle*.", "La ventana da al valle."]]),
    ],
    40: [
        _fam("Formación: in-, im-, il-, ir-",
             "*in-* niega el adjetivo; ante *p*, *b*, *m* es *im-*, ante *l* es *il-*, ante *r* es *ir-*: *soddisfatto* → *insoddisfatto*.",
             ["Adjetivo", "Contrario", "Castellano"],
             [["soddisfatto", "insoddisfatto", "insatisfecho"], ["sufficiente", "insufficiente", "insuficiente"],
              ["capace", "incapace", "incapaz"], ["giusto", "ingiusto", "injusto"],
              ["paziente", "impaziente", "impaciente"], ["leggibile", "illeggibile", "ilegible"],
              ["ragionevole", "irragionevole", "irrazonable"], ["comprensibile", "incomprensibile", "incomprensible"]],
             [["Il modulo era quasi *illeggibile*.", "El formulario era casi ilegible."],
              ["Le traduzioni erano *insufficienti*.", "Las traducciones no alcanzaban."]],
             "Ante *l* y *r* la consonante se duplica: *illeggibile*, *irragionevole*. En castellano va una sola."),
        _co([["compilare un modulo", "llenar un formulario"], ["aprire un conto", "abrir una cuenta"],
             ["rilasciare una ricevuta", "extender un comprobante"], ["prenotare un appuntamento", "sacar un turno"],
             ["perdere la pazienza", "perder la paciencia"], ["rifare la fila", "volver a hacer la cola"],
             ["fare notare", "hacer notar, señalar"], ["fare amicizia", "hacerse amigo"],
             ["un traduttore giurato", "un traductor público"]],
            [["Si va all'ufficio e si *compila un modulo*.", "Se va a la oficina y se llena un formulario."],
             ["Fatevi sempre *rilasciare una ricevuta*.", "Hacé que te den siempre un comprobante."]]),
    ],
    41: [
        _fam("Formación: nombres de acción sin sufijo",
             "Muchos sustantivos salen del verbo **sin sufijo**: *soccorrere* → *il soccorso*, *intervenire* → *l'intervento*.",
             _B, [["soccorrere", "soccorso", "auxilio"], ["intervenire", "intervento", "intervención"],
                  ["respirare", "respiro", "respiración"], ["ricoverare", "ricovero", "internación"],
                  ["salvare", "salvataggio", "rescate"], ["evacuare", "evacuazione", "evacuación"],
                  ["accertare", "accertamento", "verificación, pericia"], ["spegnere", "spegnimento", "apagado, extinción"]],
             [["L'infermiere ha controllato il *respiro* dell'anziano.", "El enfermero controló la respiración del anciano."],
              ["Secondo i primi *accertamenti* è stata una stufetta.", "Según las primeras pericias fue una estufita."]],
             "*Pronto soccorso* es la guardia del hospital; *chiamare i soccorsi* es llamar a emergencias."),
        _co([["chiamare il numero di emergenza", "llamar al número de emergencias"], ["domare un incendio", "controlar un incendio"],
             ["riportare danni", "sufrir daños"], ["rimettere in sesto", "poner en condiciones, arreglar"],
             ["dire la sua", "dar su opinión"], ["dimettere dall'ospedale", "dar de alta"],
             ["lasciare acceso", "dejar prendido"], ["non volerne sapere", "no querer saber nada"],
             ["un'intossicazione lieve", "una intoxicación leve"]],
            [["L'incendio è stato *domato* in un'ora.", "El incendio fue controlado en una hora."],
             ["L'anziano è stato *dimesso* ieri.", "Al anciano le dieron el alta ayer."]]),
    ],
    42: [
        _fam("Formación: el sustantivo del burocratese",
             "El *burocratese* prefiere el sustantivo al verbo: *provvedere* → *provvedimento*. Para entender una carta, volvé al verbo.",
             _B, [["provvedere", "provvedimento", "medida, disposición"], ["versare", "versamento", "depósito, pago"],
                  ["ricevere", "ricevimento", "atención (al público)"], ["interrompere", "interruzione", "interrupción, corte"],
                  ["comunicare", "comunicazione", "comunicación, aviso"], ["richiedere", "richiesta", "solicitud, pedido"],
                  ["sollecitare", "sollecito", "reclamo, recordatorio de pago"], ["notificare", "notifica", "notificación"]],
             [["Si procederà all'*interruzione* del servizio.", "Se procederá a interrumpir el servicio (= se corta)."],
              ["Ho ricevuto un *sollecito* di pagamento.", "Recibí un aviso de deuda vencida."]],
             "*Sollecito* no es «solícito»: es el recordatorio de algo que ya venció."),
        _co([["provvedere al pagamento", "efectuar el pago"], ["tenere conto di", "tener en cuenta"],
             ["mettere in discussione", "poner en duda, cuestionar"], ["rivolgersi a", "dirigirse a, recurrir a"],
             ["assumersi la responsabilità", "hacerse responsable"], ["rendere noto", "dar a conocer"],
             ["attenersi alle indicazioni", "atenerse a las indicaciones"], ["perdere terreno", "perder terreno"],
             ["i verbi generici", "los verbos genéricos"]],
            [["Il funzionario *tiene conto* delle conseguenze legali.", "El funcionario tiene en cuenta las consecuencias legales."],
             ["Si *rende noto* che l'ufficio chiude alle 13.", "Se hace saber que la oficina cierra a las 13."]]),
    ],
    43: [
        _fam("Formación: el sustantivo del participio",
             "Muchos sustantivos femeninos salen del participio (*scoprire* → *scoperta*) o del verbo sin terminación (*verificare* → *verifica*).",
             _B, [["scoprire", "scoperta", "descubrimiento"], ["rispondere", "risposta", "respuesta"],
                  ["proporre", "proposta", "propuesta"], ["offrire", "offerta", "oferta"],
                  ["verificare", "verifica", "verificación, control"], ["confermare", "conferma", "confirmación"],
                  ["ricercare", "ricerca", "investigación"], ["modificare", "modifica", "modificación"]],
             [["Distinguere una *scoperta* seria da una notizia gonfiata.", "Distinguir un descubrimiento serio de una noticia inflada."],
              ["La scienza procede per *conferme*.", "La ciencia avanza por confirmaciones."]],
             "*La verifica* es el control; en la escuela también es la prueba escrita."),
        _co([["perdere peso", "bajar de peso"], ["porsi una domanda", "hacerse una pregunta"],
             ["cadere nella trappola", "caer en la trampa"], ["condurre uno studio", "hacer un estudio"],
             ["trarre conclusioni", "sacar conclusiones"], ["pagare il prezzo", "pagar el precio"],
             ["riconoscere il valore", "reconocer el valor"], ["allargare le braccia", "abrir los brazos (resignado)"],
             ["una notizia gonfiata", "una noticia inflada"]],
            [["Basta *porsi* qualche *domanda*.", "Alcanza con hacerse algunas preguntas."],
             ["Non si possono *trarre conclusioni* da venti volontari.", "No se pueden sacar conclusiones de veinte voluntarios."]]),
    ],
    44: [
        _fam("Formación: -ità en la ciencia",
             "*-ità* también nombra las propiedades de la ciencia: *profondo* → *profondità*, *sensibile* → *sensibilità*.",
             _B, [["profondo", "profondità", "profundidad"], ["sensibile", "sensibilità", "sensibilidad"],
                  ["stabile", "stabilità", "estabilidad"], ["intenso", "intensità", "intensidad"],
                  ["radioattivo", "radioattività", "radiactividad"], ["complesso", "complessità", "complejidad"],
                  ["umido", "umidità", "humedad"]],
             [["I laboratori sono a millequattrocento metri di *profondità*.", "Los laboratorios están a mil cuatrocientos metros de profundidad."],
              ["Anche la *radioattività* di un bullone disturba le misure.", "Hasta la radiactividad de un bulón altera las mediciones."]],
             "*-bile* → *-bilità*: *sensibile* → *sensibilità*, *stabile* → *stabilità*, como «-bilidad»."),
        _co([["fare da scudo", "hacer de escudo"], ["dare la caccia", "salir a la caza, perseguir"],
             ["perdere la cognizione del tempo", "perder la noción del tiempo"], ["dividersi i compiti", "repartirse las tareas"],
             ["chiedere garanzie", "pedir garantías"], ["trovare applicazioni", "encontrar aplicaciones"],
             ["dare i primi risultati", "dar los primeros resultados"], ["sottrarsi a una domanda", "esquivar una pregunta"],
             ["la ricerca di punta", "la investigación de vanguardia"]],
            [["La roccia *fa da scudo* ai raggi cosmici.", "La roca hace de escudo contra los rayos cósmicos."],
             ["Altri gruppi *danno la caccia* alla materia oscura.", "Otros grupos persiguen la materia oscura."]]),
    ],
    45: [
        _fam("Formación: -evole",
             "*-evole* forma adjetivos «que produce, que merece»: *piacere* → *piacevole*, *amico* → *amichevole*.",
             _B, [["piacere", "piacevole", "agradable"], ["spiacere", "spiacevole", "desagradable"],
                  ["amico", "amichevole", "amistoso"], ["ragione", "ragionevole", "razonable"],
                  ["colpa", "colpevole", "culpable"], ["favore", "favorevole", "favorable, a favor"],
                  ["notare", "notevole", "notable, considerable"], ["lode", "lodevole", "loable"]],
             [["Sta per dirti qualcosa di *spiacevole*.", "Está por decirte algo desagradable."],
             ["Soffre con tutti tranne che con il *colpevole*.", "Sufre con todos menos con el culpable."]],
             "*Notevole* es «considerable»: *un notevole aumento* es un aumento grande, no «digno de nota»."),
        _co([["dare una risposta", "dar una respuesta"], ["sbattere la porta", "dar un portazo"],
             ["fare carriera", "hacer carrera"], ["sentirsi a casa", "sentirse en casa"],
             ["chiedere spiegazioni", "pedir explicaciones"], ["fare finta", "hacer como si"],
             ["far impazzire", "volver loco"], ["con discreta creatività", "con bastante creatividad"],
             ["un chirurgo di fama", "un cirujano famoso"]],
            [["Se ne va *sbattendo la porta*.", "Se va dando un portazo."],
             ["Difficilmente *farai carriera*.", "Difícilmente harás carrera."]]),
    ],
    46: [
        _fam("Formación: alterados que no lo son",
             "Ojo: no todo *-ino*, *-one* o *-etto* es un alterado. Muchos se volvieron **palabras propias**, o nunca lo fueron.",
             ["Palabra", "¿Alterado?", "Castellano"],
             [["gattino", "sí, de gatto", "gatito"], ["portone", "lexicalizado, de porta", "portón"],
              ["pallone", "lexicalizado, de palla", "pelota (de fútbol)"], ["fumetto", "lexicalizado, de fumo", "historieta"],
              ["giallastro", "sí, de giallo", "amarillento"], ["mattone", "no", "ladrillo"],
              ["tacchino", "no", "pavo"], ["burrone", "no", "barranco"]],
             [["Il *tacchino* non è un piccolo tacco.", "El pavo no es un taco chico."],
              ["Il *fumetto* non è un piccolo fumo.", "La historieta no es un humo chico."]],
             "*-astro* con colores y sabores = aproximado y poco agradable: *giallastro*, *dolciastro*. Con personas, despectivo: *poetastro*."),
        _co([["mettere in difficoltà", "poner en aprietos"], ["attenuare una richiesta", "suavizar un pedido"],
             ["rubare tempo", "robar tiempo"], ["esprimere disprezzo", "expresar desprecio"],
             ["dare un consiglio", "dar un consejo"], ["andare oltre", "ir más allá"],
             ["sminuire un lavoro", "restarle valor a un trabajo"], ["una sfumatura bonaria", "un matiz afable"]],
            [["Le sfumature *mettono in difficoltà* chi impara.", "Los matices ponen en aprietos a quien aprende."],
             ["Il diminutivo serve ad *attenuare* una richiesta.", "El diminutivo sirve para suavizar un pedido."]]),
    ],
    47: [
        _fam("Formación: el vocabulario de la plata",
             "La economía nombra procesos con *-mento* (*pagare* → *pagamento*) o con el verbo sin terminación (*aumentare* → *aumento*).",
             _B, [["pagare", "pagamento", "pago"], ["finanziare", "finanziamento", "financiamiento"],
                  ["spostare", "spostamento", "traslado, viaje"], ["rallentare", "rallentamento", "desaceleración"],
                  ["aumentare", "aumento", "aumento"], ["sfrattare", "sfratto", "desalojo"],
                  ["affittare", "affitto", "alquiler"], ["risparmiare", "risparmio", "ahorro"]],
             [["In caso di mancato *pagamento* paga il fondo.", "En caso de falta de pago, paga el fondo."],
              ["Per uno *sfratto* servono diciotto mesi.", "Para un desalojo hacen falta dieciocho meses."]],
             "*Affittare* sirve para los dos lados: *affitto una stanza* puede ser «doy en alquiler una pieza» o «alquilo una pieza para mí»."),
        _co([["dividere un appartamento", "compartir un departamento"], ["presentare un rapporto", "presentar un informe"],
             ["mettere sul tavolo", "poner sobre la mesa"], ["respingere un'idea", "rechazar una idea"],
             ["fare i conti", "hacer cuentas (también: arreglárselas)"], ["rinunciare al posto", "renunciar al puesto"],
             ["al secondo mandato", "en su segundo mandato"], ["spese escluse", "expensas aparte"],
             ["il canone concordato", "el alquiler acordado (con tope legal)"]],
            [["Il sindaco *mette sul tavolo* dodici milioni.", "El intendente pone sobre la mesa doce millones."],
             ["I proprietari *respingono l'idea*.", "Los propietarios rechazan la idea."]]),
    ],
    48: [
        _fam("Formación: -ale, -ano, -ese",
             "Los adjetivos de relación y los gentilicios usan *-ale*, *-ano*, *-ese*: *regione* → *regionale*, *Milano* → *milanese*.",
             _B, [["regione", "regionale", "regional"], ["dialetto", "dialettale", "dialectal"],
                  ["nazione", "nazionale", "nacional"], ["Napoli", "napoletano", "napolitano"],
                  ["Palermo", "palermitano", "palermitano"], ["Milano", "milanese", "milanés"],
                  ["Calabria", "calabrese", "calabrés"], ["Sicilia", "siciliano", "siciliano"]],
             [["Sono italiani *regionali*, perfettamente legittimi.", "Son italianos regionales, perfectamente legítimos."],
              ["Il mio accento *calabrese* l'ho perso in sei mesi.", "Mi acento calabrés lo perdí en seis meses."]],
             "Los gentilicios van con minúscula: *un milanese*, *la cucina napoletana*."),
        _co([["lasciarsi scappare", "dejar escapar, soltar"], ["far ridere", "hacer reír"],
             ["prendere in giro", "cargar, burlarse"], ["mettere in primo piano", "poner en primer plano"],
             ["entrare nei dizionari", "entrar en los diccionarios"], ["portare in classifica", "llevar a los rankings"],
             ["non rendere", "no transmitir lo mismo (una traducción)"], ["la lingua della vergogna", "la lengua de la vergüenza"],
             ["un folklore da cartolina", "un folclore de postal"]],
            [["Mia madre mi *prende in giro*.", "Mi mamá me carga."],
             ["Certe cose in italiano non *rendono*.", "Algunas cosas en italiano no suenan igual."]]),
    ],
    49: [
        _fam("Formación: el sustantivo abstracto del registro alto",
             "El registro alto piensa con sustantivos abstractos: *coerente* → *coerenza*, *maturo* → *maturità*, *consapevole* → *consapevolezza*.",
             _B, [["coerente", "coerenza", "coherencia"], ["maturo", "maturità", "madurez"],
                  ["consapevole", "consapevolezza", "conciencia"], ["rappresentare", "rappresentanza", "representación (política)"],
                  ["responsabile", "responsabilità", "responsabilidad"], ["astenersi", "astensione", "abstención"],
                  ["divergere", "divergenza", "divergencia"], ["eleggere", "elezione", "elección"]],
             [["L'argomento riguarda la *coerenza* dell'ordinamento.", "El argumento tiene que ver con la coherencia del sistema."],
              ["Manca davvero la *maturità* necessaria?", "¿De verdad falta la madurez necesaria?"]],
             "*Rappresentanza* es la representación política; *rappresentazione*, la teatral o la imagen de algo."),
        _co([["estendere il diritto di voto", "extender el derecho a voto"], ["sgombrare il campo", "despejar el terreno"],
             ["assumere responsabilità", "asumir responsabilidades"], ["adottare una soluzione", "adoptar una solución"],
             ["accordare fiducia", "otorgar confianza"], ["sollevare obiezioni", "plantear objeciones"],
             ["avanzare una proposta", "plantear una propuesta"], ["compiere scelte", "tomar decisiones"],
             ["un argomento fragile", "un argumento débil"]],
            [["L'opposizione ha *sollevato obiezioni*.", "La oposición planteó objeciones."],
             ["Il governo ha *avanzato una proposta*.", "El gobierno presentó una propuesta."]]),
    ],
    50: [
        _fam("Formación: -tore / -trice en el mundo del libro",
             "*-tore* / *-trice* también nombra los oficios del libro: *tradurre* → *traduttore*, *traduttrice*.",
             ["Verbo", "Masculino", "Femenino"],
             [["tradurre", "traduttore", "traduttrice"], ["scrivere", "scrittore", "scrittrice"],
              ["leggere", "lettore", "lettrice"], ["narrare", "narratore", "narratrice"],
              ["correggere", "correttore", "correttrice"], ["illustrare", "illustratore", "illustratrice"],
              ["edizione", "editore", "editrice"]],
             [["Ogni *traduttore* custodisce il suo museo degli orrori.", "Cada traductor guarda su museo de los horrores."],
              ["Il *lettore* argentino non ride.", "El lector argentino no se ríe."]],
             "*Editore* es quien publica (la editorial); quien corrige textos es el *redattore* o el *correttore di bozze*."),
        _co([["mettere in guardia", "poner sobre aviso"], ["fare una figuraccia", "quedar mal, pasar vergüenza"],
             ["custodire un segreto", "guardar un secreto"], ["rendere le voci", "reproducir las voces (al traducir)"],
             ["chiedere un consiglio", "pedir un consejo"], ["camminare su un filo", "caminar por la cornisa"],
             ["attribuire un ottimismo", "atribuir un optimismo"], ["smascherare un falso amico", "desenmascarar un falso amigo"],
             ["il pericolo principale", "el peligro principal"]],
            [["Un professore mi *mise in guardia*.", "Un profesor me puso sobre aviso."],
             ["Le lingue *custodiscono* i loro segreti.", "Las lenguas guardan sus secretos."]]),
    ],
    51: [
        _fam("Formación: repaso con el mundo del trabajo",
             "Repaso: el trabajo se piensa en sustantivos con *-ità* (*produttività*), *-enza* (*efficienza*) y *-zione* / *-ione* (*motivazione*, *gestione*).",
             _B, [["produttivo", "produttività", "productividad"], ["flessibile", "flessibilità", "flexibilidad"],
                  ["efficiente", "efficienza", "eficiencia"], ["reperibile", "reperibilità", "guardia pasiva, estar localizable"],
                  ["motivare", "motivazione", "motivación"], ["concentrarsi", "concentrazione", "concentración"],
                  ["gestire", "gestione", "gestión"], ["assumere", "assunzione", "contratación"]],
             [["Ridurre le ore senza perdere *efficienza*.", "Reducir las horas sin perder eficiencia."],
              ["Il secondo fattore è la *motivazione*.", "El segundo factor es la motivación."]],
             "*Assunzione* es la contratación de un empleado (*assumere* = contratar), no «asunción»."),
        _co([["concordare con i sindacati", "acordar con los gremios"], ["ricorrere a", "recurrir a"],
             ["sbrigare le commissioni", "hacer los trámites"], ["ricredersi", "cambiar de opinión"],
             ["rimettere in discussione", "volver a poner en discusión"], ["prendersi la briga", "tomarse la molestia"],
             ["accompagnare alla porta", "acompañar a la puerta (echar)"], ["prendere una decisione", "tomar una decisión"],
             ["a parità di salario", "con el mismo sueldo"]],
            [["Si è dovuto *ricorrere* a un sistema di reperibilità.", "Hubo que recurrir a un sistema de guardias."],
             ["Nessuno si era *preso la briga* di misurarlo.", "Nadie se había tomado la molestia de medirlo."]]),
    ],
}

# Los ejercicios de estos bloques van a la última parte de la lección (la que
# trae los bloques), aunque el patrón de una parte anterior los atrape.
PIN_PREFIXES = ("c1-fp-%d-", "c1-co-%d-")
