# -*- coding: utf-8 -*-
"""Consigli: un tip de uso por cada palabra de la semana (clave = vocab[0]).

No repiten la traducción: dicen cómo se usa, cómo se arma y dónde el
italiano se aparta del castellano.  Formas italianas entre *asteriscos*.
"""

TIPS = {
    # --- semana 1 ---
    "fare": "Irregular: *faccio, fai, fa, facciamo, fate, fanno*; participio *fatto*. Sirve para mil cosas: *fare colazione* (desayunar), *fare la spesa*, *fa freddo*.",
    "andare": "Irregular: *vado, vai, va, andiamo, andate, vanno*. Pide *a* con ciudades y verbos (*vado a Roma*, *vado a mangiare*) e *in* con países y lugares (*in Italia*, *in banca*).",
    "volere": "Irregular: *voglio, vuoi, vuole, vogliamo, volete, vogliono*. Va directo con infinitivo, sin preposición: *voglio mangiare*. Para pedir con cortesía: *vorrei un caffè*.",
    "mangiare": "La *i* solo marca el sonido «ch»: en *tu mangi* y *noi mangiamo* no se duplica. Pasado: *ho mangiato*, con *avere*.",
    "prendere": "Es el verbo de pedir en el bar o tomar transporte: *prendo un caffè*, *prendo il treno*. Participio irregular: *preso* (*ho preso*).",
    "macchina": "Es la palabra común para «auto»; *auto* existe pero suena más formal. Femenina: *la macchina*, plural *le macchine* (la *h* mantiene el sonido «k»).",
    "bello": "Antes de un sustantivo cambia como el artículo: *bel ragazzo*, *bello zaino*, *bell'uomo*, *bei libri*, *begli occhi*. Después del verbo, normal: *è bello*.",
    "giorno": "Masculino, plural *giorni*. Para saludar a la mañana: *buongiorno*. *Tutto il giorno* = todo el día; para la duración vivida se prefiere *giornata*.",
    "bambino": "Plural *bambini*; femenino *bambina*. Va con *avere* para sensaciones: *il bambino ha fame*, *ha sonno* (tiene hambre, sueño).",
    "figlio": "Plural *figli* (para hijos varones o mixtos). Con posesivo y familiar en singular no lleva artículo: *mio figlio*; en plural sí: *i miei figli*.",
    "stasera": "Es una sola palabra (*questa sera* abreviado), como *stamattina* y *stanotte*. Va sin preposición: *stasera esco*.",
    "abitare": "Pide *a* con ciudades (*abito a Roma*) e *in* con barrios, calles o países (*abito in via Verdi*). Con *da solo*: vivir solo.",
    # --- semana 2 ---
    "dovere": "Irregular: *devo, devi, deve, dobbiamo, dovete, devono*. Va directo con infinitivo, sin «que»: *devo studiare* (tengo que estudiar).",
    "due": "Invariable. Ojo con la hora: *sono le due* (son las dos), con artículo femenino plural. *Tutti e due* = los dos.",
    "ragazza": "Además de «chica», *la mia ragazza* es «mi novia». Plural *ragazze*; en Italia se usa hasta pasados los treinta.",
    "tre": "Invariable. En compuestos lleva tilde: *ventitré*, *trentatré*. *Siamo in tre* = somos tres.",
    "film": "Masculino e invariable: *il film*, *i film* (las palabras extranjeras no cambian en plural). No se dice *pellicola* para la película que ves.",
    "città": "Termina en vocal acentuada, así que no cambia en plural: *la città*, *le città*. *Vado in città* = voy al centro.",
    "signore": "Delante de un apellido pierde la *-e*: *il signor Rossi*. Para hablarle directo, sin artículo: *Buongiorno, signore!*",
    "fratello": "Plural *fratelli*, que también sirve para «hermanos» mixtos: *Hai dei fratelli?*. Con posesivo en singular, sin artículo: *mio fratello*.",
    "strada": "Es la calle como camino o recorrido: *attraversare la strada*. Para dar una dirección se usa *via*: *abito in via Roma*.",
    "vecchio": "Plural *vecchi*, femenino *vecchie*. Para personas mayores es más amable *anziano*. *Vecchio mio* = amigo mío (cariñoso).",
    "uomo": "Plural irregular: *uomini* (*gli uomini*). Con adjetivo: *un bell'uomo*.",
    "cugino": "Falso amigo con «primo»: en italiano *primo* es «primero». Primo es *cugino*, prima es *cugina*.",
    # --- semana 3 ---
    "piacere": "Funciona como «gustar»: *mi piace la pasta*, *mi piacciono i libri*. Pasado con *essere*: *mi è piaciuto*. *Piacere!* también es «¡un gusto!».",
    "partire": "Es «irse de viaje, salir (un medio)», no «partir» algo (eso es *dividere*, *rompere*). Pasado con *essere*: *sono partito*.",
    "arrivare": "Pasado con *essere*, así que concuerda: *è arrivata*. Pide *a* con ciudades (*arrivo a Roma*) e *in* con países (*in Italia*).",
    "scrivere": "Participio irregular: *scritto* (*ho scritto*). Se escribe *a* alguien: *scrivo a Marco*, *gli scrivo*.",
    "ragazzo": "Plural *ragazzi* («chicos», también «chicos y chicas»). *Il mio ragazzo* = mi novio.",
    "portare": "Es «llevar» y también «traer»: *porto il vino* (lo llevo), *mi porti un caffè?* (¿me traés?). También «llevar puesto»: *porta gli occhiali*.",
    "finestra": "Parece «fenestra», pero es la ventana común. La de un auto o negocio es *finestrino* / *vetrina*.",
    "moglie": "Plural irregular: *le mogli* (sin *-ie*). Con posesivo, sin artículo: *mia moglie*.",
    "zio": "El artículo es *lo* por empezar con *z*: *lo zio*, plural *gli zii* (doble *i*).",
    "acqua": "Se escribe con *cq*. Pedido típico: *un bicchiere d'acqua*; en el restorán, *acqua naturale* o *frizzante*.",
    "tavolo": "Es la mesa como mueble. Pero «¡a la mesa!» es *a tavola!*: *tavola* es la mesa puesta para comer.",
    "gentile": "Es «amable», no «gentil» de pagano. Sirve en fórmulas: *Gentile signora* (en cartas), *sei molto gentile*.",
    # --- semana 4 ---
    "piccolo": "Es el «chico» de tamaño; para «niño» se usa *bambino*. Superlativo coloquial: *piccolissimo*.",
    "estate": "Femenino: *l'estate*; *in estate* o *d'estate*. Todas las estaciones van con *in*: *in inverno*, *in primavera*, *in autunno*.",
    "figlia": "Plural *figlie*. Con posesivo, sin artículo en singular: *tua figlia*; en plural sí: *le tue figlie*.",
    "lungo": "Falso amigo: *lungo* es «largo» (de longitud); nuestro «ancho» es *largo*. Plural *lunghi*, con *h*.",
    "vicino": "Adverbio: *qui vicino* (acá cerca). Con complemento pide *a*: *vicino a casa*. Como sustantivo, *il vicino* es el vecino.",
    "scarpa": "Casi siempre en plural: *le scarpe*. Para tallas se dice *che numero porta?*",
    "insegnante": "Termina en *-e* y sirve para los dos géneros: *l'insegnante* es profesor o profesora; lo marca el artículo o el adjetivo (*simpatica*).",
    "bravo": "No es «bravo» de enojado: es «bueno, capo en algo». *Bravo in matematica*, *un bravo cuoco*. «Enojado» es *arrabbiato*.",
    "cugina": "Femenino de *cugino*. Con posesivo en singular, sin artículo: *mia cugina*.",
    "donna": "Plural *donne*. *Donna* no es título de cortesía: para «señora» se usa *signora*.",
    "brutto": "Además de «feo», es «malo, feo» en general: *brutto tempo*, *una brutta notizia*.",
    "latte": "Masculino: *il latte*. Si pedís *un latte* en el bar te dan leche; para el café con leche pedí *caffellatte* o *latte macchiato*.",
    # --- semana 5 ---
    "vedere": "Participio irregular: *visto* (*ho visto*). *Ci vediamo!* = ¡nos vemos!",
    "parlare": "Se habla *di* algo y *con* alguien: *parlo di lavoro con Marco*. Idioma sin artículo: *parla italiano*.",
    "uscire": "Irregular: *esco, esci, esce, usciamo, uscite, escono*. Pide *di* con casa: *esco di casa*; pasado con *essere*: *sono uscito*.",
    "finire": "Verbo en *-isc-*: *finisco, finisci, finisce, finiamo, finite, finiscono*. Con infinitivo pide *di*: *ho finito di mangiare*.",
    "capire": "Verbo en *-isc-*: *capisco, capisci, capisce... capiscono*. *Non ho capito* = no entendí.",
    "aspettare": "Es transitivo, sin preposición: *aspetto Marco* (espero a Marco). Para «esperar que» con deseo se usa *sperare*.",
    "sera": "Es el tramo de la tarde-noche, cuando ya oscurece. *Domani sera*, *ieri sera*; saludo: *buonasera*.",
    "guardare": "«Mirar» con atención: *guardo la TV*. «Ver» sin intención es *vedere*. *Guarda!* = ¡mirá!",
    "sorella": "Plural *sorelle*. Con posesivo en singular sin artículo: *mia sorella*.",
    "cercare": "Transitivo: *cerco il museo* (sin «a»). Con infinitivo pide *di*: *cerco di dormire* (trato de). En *tu cerchi* la *h* mantiene el sonido «k».",
    "signora": "Para hablar con ella, sin artículo: *Signora, Lei è di Roma?*. Para referirse a ella, con artículo: *la signora Bianchi*.",
    "vero": "Al final de la pregunta pide confirmación, como «¿no?»: *partite domani, vero?*. *Davvero?* = ¿en serio?",
    # --- semana 6 ---
    "dire": "Irregular: *dico, dici, dice, diciamo, dite, dicono*; participio *detto*. Decir que sí/no: *dire di sì / di no*.",
    "trovare": "Además de encontrar, sirve para opinar: *lo trovo simpatico* (me parece). *Vado a trovare la nonna* = voy a visitarla.",
    "tornare": "Pasado con *essere*: *sono tornato*. *Tornare a casa* (volver a casa), sin artículo.",
    "chiedere": "Es «pedir» y también «preguntar»: *chiedere scusa*, *chiedo a Marco*. Participio *chiesto*. «Pedir» comida en el restorán: *ordinare* o *prendere*.",
    "nonna": "Con posesivo en singular sin artículo: *mia nonna*; con diminutivo sí: *la mia nonnina*.",
    "esame": "Masculino: *l'esame*, plural *gli esami*. Rendir un examen es *dare un esame*; aprobar, *passarlo*.",
    "telefonare": "Pide *a*: *telefono a Marco*, *le telefono* (le hablo por teléfono). No es transitivo como «llamar».",
    "mattina": "*La mattina* = a la mañana (habitual); *domattina* = mañana a la mañana. Ojo: «mañana» (el día siguiente) es *domani*.",
    "bar": "Invariable: *il bar*, *i bar*. Es el café de todos los días, donde se desayuna parado: *faccio colazione al bar*.",
    "cominciare": "Con infinitivo pide *a*: *comincio a lavorare*. En *tu cominci* la *i* no se duplica.",
    "biglietto": "Sirve para boleto, entrada y también billete de banco. *Fare il biglietto* = sacar el boleto.",
    "nonno": "Plural *i nonni* (los abuelos). Con posesivo en singular, sin artículo: *mio nonno*.",
    # --- semana 7 ---
    "ufficio": "Masculino: *l'ufficio*, plural *gli uffici*. Sin artículo con *in*: *sono in ufficio*.",
    "ora": "*Che ora è?* o *Che ore sono?*. También es «ahora»: *ora vengo*.",
    "spesa": "*Fare la spesa* = hacer las compras del súper. *Fare spese* = ir de shopping.",
    "pomeriggio": "Es la tarde después del almuerzo; más tarde es *sera*. *Nel pomeriggio*, *oggi pomeriggio*.",
    "chilo": "Con cantidades pide *di*: *un chilo di mele*, *mezzo chilo di pane*.",
    "giovedì": "Los días van en minúscula y sin artículo para «este jueves»: *giovedì vado*. Con artículo es habitual: *il giovedì* = los jueves.",
    "colazione": "*Fare colazione* = desayunar. Al mediodía se almuerza: *pranzo*.",
    "olio": "Plural poco usado: *oli*. *Olio d'oliva*; «aceite de girasol» es *olio di semi*.",
    "zero": "Plural *zeri*: *tre zeri*. *Partire da zero* = empezar de cero.",
    "gennaio": "Los meses van en minúscula. Para la fecha, número + mes sin «de»: *il 5 gennaio*; el primero es *il primo*.",
    "maggio": "Como los otros meses: *a maggio* o *in maggio*. Fecha sin «de»: *il 5 maggio*.",
    # --- semana 8 ---
    "compito": "*I compiti* = la tarea escolar (en plural). *Fare i compiti* = hacer la tarea.",
    "aereo": "Es *l'aereo*, plural *gli aerei*. *Prendere l'aereo*; en avión se dice *in aereo*.",
    "domenica": "Sin artículo es «este domingo»; *la domenica* es «los domingos». Minúscula.",
    "forse": "Va con indicativo, no con subjuntivo: *forse viene* (quizás venga).",
    "penna": "Es la birome o lapicera; «lápiz» es *matita*. *Penna* también es «pluma» de ave.",
    "indirizzo": "Para mail también: *indirizzo email*. Pregunta típica: *Qual è il tuo indirizzo?*",
    "gelato": "El que vende helado es *la gelateria*. Pedido: *un cono / una coppetta con due gusti*.",
    "elementare": "*La scuola elementare* (o *le elementari*) = la primaria. También es «elemental»: *un errore elementare*.",
    # --- semana 9 ---
    "bere": "Se conjuga desde *bev-*: *bevo, bevi, beve, beviamo, bevete, bevono*; participio *bevuto*. *Qualcosa da bere* = algo para tomar.",
    "restare": "Pasado con *essere*: *sono restato*. *Restare a casa*; *mi resta poco tempo* = me queda poco tiempo.",
    "sembrare": "Funciona como «parecer»: *mi sembra giusto*. Con infinitivo, sin preposición: *non sembra disposta*; *sembra che* + subjuntivo.",
    "imparare": "Con infinitivo pide *a*: *imparo a guidare*. Idiomas con artículo: *imparare l'italiano*.",
    "dispiacere": "Se usa como «gustar»: *mi dispiace* = lo siento. *Ti dispiace se...?* = ¿te molesta si...?",
    "riuscire": "Con infinitivo pide *a*: *non riesco a dormire*. Se conjuga como *uscire*: *riesco, riesci*. Pasado con *essere*.",
    "dimenticare": "Se usa solo o pronominal: *ho dimenticato le chiavi* / *mi sono dimenticato delle chiavi*. Con infinitivo pide *di*.",
    "bicchiere": "Masculino, en *-e*. *Bicchiere da vino* (para vino) vs *di vino* (lleno de vino). «Vaso» en italiano es florero o maceta.",
    "bisogno": "Se arma con *avere*: *ho bisogno di* + cosa o infinitivo. *C'è bisogno di* = hace falta.",
    "giornata": "Es el día como duración vivida: *una bella giornata*, *buona giornata!*. *Giorno* es la unidad del calendario.",
    "autobus": "Invariable: *l'autobus*, *gli autobus*. «Tomar el colectivo» = *prendere l'autobus*; «en colectivo» = *in autobus*.",
    "giardino": "Con *in* va sin artículo: *sono in giardino*. El jardín de infantes no es *giardino*: es *la scuola materna* o *l'asilo*.",
    # --- semana 10 ---
    "aiutare": "Transitivo: *ti aiuto* (te ayudo, sin «a»). Con infinitivo pide *a*: *mi aiuti a portare?*",
    "lasciare": "Es dejar algo o a alguien: *ho lasciato le chiavi*. Con infinitivo, sin preposición: *lasciami parlare*. «Dejar de» es *smettere di*.",
    "ecco": "Presenta algo: *ecco il caffè*. Se le pegan los pronombres: *eccolo*, *eccomi* (¡acá estoy!).",
    "ascoltare": "Transitivo como «escuchar»: *la ascolto* (la escucho, a usted). «Oír» sin atención es *sentire*.",
    "offrire": "Participio irregular: *offerto*. *Offrire da bere* = invitar a tomar algo; *offro io!* = ¡invito yo!",
    "valigia": "Plural *valigie* o *valige*. *Fare la valigia* = armar la valija.",
    "pronto": "Es «listo»: *la cena è pronta*. Al atender el teléfono se dice *Pronto?*. «Pronto» de tiempo es *presto*.",
    "purtroppo": "Adverbio fijo, suele ir al principio: *purtroppo non posso*. Es de todos los días, no formal.",
    "certo": "Sola es «¡claro!». Antes del sustantivo es «cierto»: *un certo signore*. *Di certo* = seguro.",
    "albero": "Esdrújula: *àlbero*. Masculino, plural *alberi*. *Albero di Natale*.",
    "veramente": "Además de «realmente», al comienzo matiza: *veramente, preferisco restare* (la verdad es que...).",
    "beh": "Muletilla para ganar tiempo, como «y, bueno»: *Beh, non lo so*. Variante: *be'*.",
    # --- semana 11 ---
    "ricevere": "Regular en *-ere*: *ho ricevuto*. Muy usado en mails: *ho ricevuto la tua email*.",
    "rimanere": "Irregular: *rimango, rimani, rimane... rimangono*; participio *rimasto*, con *essere*. *Rimanere senza* = quedarse sin.",
    "scegliere": "Irregular: *scelgo, scegli, sceglie, scegliamo, scegliete, scelgono*; participio *scelto*.",
    "ragione": "«Tener razón» se arma con *avere*: *hai ragione*. *Dare ragione a qualcuno* = darle la razón.",
    "scorso": "Va después del sustantivo: *l'anno scorso*, *la settimana scorsa*. Concuerda en género.",
    "viaggiare": "Regular: *viaggio, viaggi*. «Viajar al exterior» = *viaggiare all'estero*. El sustantivo es *il viaggio*.",
    "ripetere": "Regular en *-ere*. Fórmula clave: *Può ripetere, per favore?*",
    "vincere": "Participio irregular: *vinto*. «Ganar plata» no es *vincere* sino *guadagnare*; ganar la lotería sí: *vincere alla lotteria*.",
    "ritornare": "Igual que *tornare*, con *essere*: *siamo ritornati*. Suena un poco más formal.",
    "fermarsi": "Pronominal: *mi fermo*, pasado *mi sono fermato*. Con infinitivo pide *a*: *mi fermo a mangiare*.",
    "povero": "Antes del sustantivo es de lástima (*povero Luca!*); después es de plata (*un uomo povero*).",
    "salire": "Irregular: *salgo, sali, sale... salgono*. Pasado con *essere* (*sono salito*), pero con objeto con *avere*: *ho salito le scale*.",
    # --- semana 12 ---
    "alzarsi": "Pronominal: *mi alzo, ti alzi, si alza*; pasado *mi sono alzato/a*. Sin *si*, *alzare* es levantar algo.",
    "tenere": "Irregular: *tengo, tieni, tiene... tengono*. Es «sostener, mantener», no «tener» (eso es *avere*). *Tenere conto di* = tener en cuenta.",
    "svegliarsi": "Pronominal: *mi sveglio*, *a che ora ti svegli?*. Sin *si*: *svegliare qualcuno* (despertar a alguien).",
    "ritardo": "*Essere in ritardo* = llegar tarde. *Arrivare in ritardo*, *scusa il ritardo*.",
    "sposarsi": "Pronominal: *si sono sposati*. «Casarse con» = *sposarsi con* o *sposare qualcuno*.",
    "scendere": "Pasado con *essere*: *sono sceso* (participio irregular). *Scendo alla prossima* = me bajo en la próxima.",
    "addormentarsi": "Pronominal: *mi addormento*. «Quedarse dormido» por la mañana, llegar tarde, se dice *non mi sono svegliato*.",
    "nipote": "Sirve para sobrino/a y para nieto/a: el contexto decide. Plural *nipoti*.",
    "verità": "Invariable: *la verità*, *le verità*. *Dire la verità* = decir la verdad; *in verità* = en realidad.",
    "solito": "*Di solito* = generalmente. *Il solito* = lo de siempre; *come al solito* = como siempre.",
    "fretta": "*Avere fretta* = estar apurado; *in fretta* = rápido, a las apuradas.",
    "togliere": "Irregular: *tolgo, togli, toglie... tolgono*; participio *tolto*. *Togliersi la giacca* = sacarse el saco.",
    # --- semana 14 ---
    "mancare": "Funciona como «gustar»: *mi manca l'Italia* (extraño Italia), *mi mancano i miei*. Pasado con *essere*: *mi è mancata*.",
    "pesce": "Masculino en *-e*: *il pesce*, plural *pesci*. Sirve para pescado y para pez: no hay dos palabras.",
    "passeggiata": "Se arma con *fare*: *fare una passeggiata* (dar un paseo). El verbo es *passeggiare*.",
    "albergo": "Sinónimo de *hotel*, muy común. Plural *alberghi*, con *h* para mantener el sonido «g».",
    "sport": "Invariable: *lo sport*, *gli sport* (artículo *lo* por la *s* + consonante). *Fare sport* = hacer deporte.",
    "cibo": "Es la comida como alimento: *cibo italiano*. La comida del mediodía es *il pranzo*; la cena, *la cena*.",
    "estero": "*All'estero* = en o al exterior, siempre con artículo: *vivo all'estero*, *vado all'estero*.",
    "canzone": "Femenino en *-e*: *la canzone*, plural *le canzoni*. El cantautor es *il cantautore*.",
    "cioè": "Aclara o corrige lo que acabás de decir: *vengo alle sei, cioè tra un'ora*. En la charla también sirve de muletilla.",
    "piscina": "Es la palabra estándar para la pileta de natación. *Andare in piscina*, sin artículo.",
    "sinistro": "*A sinistra* = a la izquierda (femenino, porque se sobreentiende *mano*). Como sustantivo, *un sinistro* es un siniestro de seguro.",
    "ristretto": "En el bar, *un ristretto* es un café corto y concentrado, con menos agua que el *espresso*. Como adjetivo, «estrecho, limitado».",
    # --- semana 15 ---
    "giocare": "Deportes y juegos piden *a*: *giocare a calcio*, *a carte*. Los instrumentos no se «juegan»: *suonare la chitarra*.",
    "malato": "*Essere malato* = estar enfermo; enfermarse es *ammalarsi*. La enfermedad es *la malattia*.",
    "paura": "Se arma con *avere*: *ho paura dei cani*. Con infinitivo: *ho paura di sbagliare*.",
    "vacanza": "*Essere / andare in vacanza*, sin artículo. En plural (*le vacanze*) es el período de vacaciones: *le vacanze estive*.",
    "capo": "Invariable en género: *il capo*, *la capo*. También es «cabeza» en frases hechas: *da capo* = desde el principio; *andare a capo* = punto y aparte.",
    "mezzanotte": "Femenino: *a mezzanotte*, sin artículo. Lo mismo *a mezzogiorno*.",
    "calcio": "Se juega *a calcio*: *giocare a calcio*. El hincha es *il tifoso*. *Calcio* también es calcio (el mineral) y «patada».",
    "fiume": "Masculino en *-e*: *il fiume*, plural *i fiumi*. Con nombre: *il fiume Po*, *il Tevere*.",
    "meraviglioso": "Concuerda como todo adjetivo en *-o*: *una serata meravigliosa*. Muy expresivo, se usa en exclamaciones.",
    "pochissimo": "Superlativo con *-issimo*: *poco* → *pochissimo* (la *h* mantiene el sonido «k»). Como adjetivo concuerda: *pochissime persone*.",
    "serata": "Es la noche como tiempo vivido o salida: *una bella serata*, *buona serata!*. *Sera* es el momento del día.",
    "ospedale": "Masculino: *l'ospedale*. *Essere in ospedale*, sin artículo.",
    # --- semana 16 ---
    "stamattina": "Contracción de *questa mattina*, como *stasera*. Va sin preposición: *stamattina mi sono alzato presto*.",
    "cravatta": "*Mettersi la cravatta*: la ropa que te ponés va con verbo pronominal y artículo, no con posesivo.",
    # --- semana 17 ---
    "cane": "Masculino en *-e*: *il cane*, plural *i cani*. *Fa un freddo cane* = hace un frío de perros.",
    "biscotto": "Plural *biscotti*. Sabor con *al*: *biscotti al cioccolato*.",
    "via": "Se usa para las direcciones: *abito in via Roma 5*. Tras un verbo es «afuera, lejos»: *andare via* (irse), *buttare via* (tirar).",
    "giacca": "Plural *giacche* (la *h* mantiene el sonido «k»). Es saco o campera; el abrigo largo es *il cappotto*.",
    "ombrello": "Masculino: *l'ombrello*, plural *gli ombrelli*. La sombrilla de playa es *l'ombrellone*.",
    "cappello": "Doble *p* y doble *l*. No confundir con *capello* (un pelo): *i capelli* = el pelo.",
    "sciare": "Acento en la *i*: *scio, scii, scia*. *Andare a sciare*; el esquí es *lo sci*.",
    "cartolina": "Es la postal que se manda. *Mandare una cartolina da Venezia* (desde, con *da*).",
    "parola": "Plural *parole*. *Parola d'onore*; *in altre parole* = en otras palabras.",
    "cappotto": "Es el abrigo largo de invierno. *Mettersi il cappotto*.",
    "computer": "Invariable y masculino: *il computer*, *i computer*. Se pronuncia a la inglesa.",
    "peccato": "*Che peccato!* o solo *Peccato!* = ¡qué lástima!. Con frase: *peccato che* + subjuntivo. Literal es «pecado».",
    # --- semana 18 ---
    "spiegare": "Se explica algo *a* alguien: *spiegami*, *gli spiego*. En *tu spieghi* la *h* mantiene el sonido «g».",
    "magari": "Solo, como respuesta, es «¡ojalá!». Con subjuntivo imperfecto expresa deseo: *magari fosse vero!*. En la charla también es «quizás»: *magari vengo*.",
    "successo": "Falso amigo: es «éxito». «Suceso» se dice *avvenimento*. Pero *è successo qualcosa* = pasó algo (de *succedere*).",
    "figurati": "Imperativo de *figurarsi*: responde a un gracias o una disculpa, como «¡de nada, por favor!». Con usted: *si figuri*.",
    "carità": "*Per carità!* rechaza con fuerza, como «¡ni loco!, ¡Dios me libre!». Invariable: *la carità*.",
    "forza": "*Forza!* anima (¡vamos!); *per forza* = obvio, a la fuerza: *Per forza! Ho lavorato dodici ore*.",
    "carino": "Es «lindo, simpático», más suave que *bello*: *una casa carina*. Dicho de alguien, también «amable»: *è stato carino*.",
    "maglietta": "Es la remera de manga corta. El suéter es *maglione*; la camiseta de fútbol, *maglia*.",
    "boh": "Interjección coloquial de «ni idea», con encogida de hombros. Solo en la charla informal.",
    "meraviglia": "*Che meraviglia!* = ¡qué maravilla!. *A meraviglia* = de maravilla. Con *di*: *che meraviglia di casa!*",
    "pasticcio": "Coloquial: un lío o un enchastre. *Che pasticcio!*, *mettersi nei pasticci* = meterse en líos.",
    "sbadato": "Es alguien distraído por costumbre. *Come sei sbadato!* La *s-* inicial niega o intensifica, como en *sfortunato*.",
    # --- semana 19 ---
    "sicuro": "*Di sicuro* = seguro. *Essere sicuro di* + infinitivo o *che* + indicativo/subjuntivo: *sono sicuro che viene*.",
    "almeno": "Una sola palabra: *almeno*. *Avrà almeno sessant'anni*: el futuro aquí es de suposición.",
    "benzina": "*Fare benzina* = cargar nafta. *Rimanere senza benzina*. El que atiende es *il benzinaio*.",
    "sciopero": "Esdrújula: *sciòpero*. *Fare sciopero* o *essere in sciopero*. Muy frecuente en noticias de transporte.",
    "incidente": "Falso amigo parcial: es sobre todo un choque o accidente. *Avere un incidente*.",
    "postino": "Viene de *posta* (correo). Oficio en *-ino*: *il postino*, *la postina*.",
    "venerdì": "Termina en vocal acentuada: invariable, *i venerdì*. *Da lunedì a venerdì*, sin artículo.",
    "stipendio": "Plural *stipendi*. *Prendere lo stipendio*; el artículo es *lo* por *s* + consonante.",
    "molto": "Como adjetivo concuerda: *molti amici*, *molte case*. Como adverbio no cambia: *sono molto stanchi*.",
    "inquinare": "Transitivo: *inquinare l'aria*. Participio *inquinato*; el sustantivo es *l'inquinamento*.",
    "sistemare": "Es ordenar, acomodar o resolver: *sistemare la camera*, *sistemare una faccenda*. *Sistemarsi* = instalarse o acomodarse en la vida.",
    "affolleranno": "Futuro de *affollare* (llenar de gente), de *folla* (multitud). El futuro italiano se arma sobre el infinitivo: *affoll-erò, -erai, -erà, -eranno*.",
    # --- semana 20 ---
    "caldo": "Es adjetivo (*il caffè è caldo*) y sustantivo: *fa caldo* (hace calor), *ho caldo* (tengo calor).",
    "riposare": "Se usa solo o pronominal: *riposare* o *riposarsi*. *Dovresti riposare di più*: condicional para aconsejar.",
    "ormai": "Marca que algo ya es un hecho o es tarde: *ormai è tardi*. Suele ir al final o al principio.",
    "zia": "Plural *zie*. Con posesivo en singular, sin artículo: *mia zia*.",
    "davvero": "Solo es «¿en serio?». En la frase refuerza: *è davvero bravo* (es realmente bueno).",
    "panino": "Es el sándwich de pan (de miga es *tramezzino*). En plural *panini*: no hay «paninis».",
    "volentieri": "Es la forma natural de aceptar: *Vieni? — Volentieri!* (¡con gusto!). Adverbio, no cambia.",
    "passaggio": "*Dare un passaggio a qualcuno* = llevarlo en auto. *Mi dai un passaggio?* = ¿me alcanzás?",
    "appuntamento": "Es cualquier cita o turno: con amigos, médico o novio. *Ho un appuntamento dal dentista*.",
    "nuvola": "Esdrújula: *nùvola*. Aumentativo típico: *nuvoloni* (nubarrones). *Nuvoloso* = nublado.",
    "leggero": "Liviano de peso y de comida: *una cena leggera*. También «ligero» de suave: *un vino leggero*.",
    "seccato": "Coloquial: molesto, fastidiado. *Sono seccato con Marco*; el verbo es *seccare* (molestar): *mi secca che...*",
    # --- semana 21 ---
    "mezzo": "Con la hora suele concordar: *le tre e mezza* (o *mezzo*). Antes del sustantivo: *mezzo chilo*, *mezz'ora*.",
    "mela": "Plural *mele*. Con *ne* para cantidades: *ne vuoi una?* (¿querés una?).",
    "stanza": "Palabra general para cualquier ambiente de la casa; el dormitorio es *la camera (da letto)*.",
    "abituarsi": "Pronominal y pide *a*: *mi sono abituato al caffè*, *abituarsi a vivere da soli*.",
    "abbastanza": "Invariable. *Ne ho abbastanza* = ya me cansé. Antes de adjetivo = «bastante»: *abbastanza bravo*.",
    "palestra": "*Andare in palestra*, sin artículo. Ojo: *ginnasio* no es gimnasio, es un tramo del liceo clásico.",
    "cipolla": "Plural *cipolle*. *Cipolle di Tropea*: la morada de Calabria, famosa.",
    "tonno": "*Una scatola di tonno*. *Tonno sott'olio* = atún en aceite.",
    "scatola": "Esdrújula: *scàtola*. *In scatola* = enlatado: *tonno in scatola*.",
    "minestra": "Sopa de verduras o caldo con pasta. *Minestrone* es la versión grande con muchas verduras.",
    "farmacista": "Termina en *-ista*: sirve para los dos géneros, *il/la farmacista*. Para ir a lo de alguien se usa *da*: *andare dal farmacista*.",
    "salsiccia": "Plural *salsicce* (sin *i*). *Panino con la salsiccia*.",
    # --- semana 22 ---
    "glielo": "Es *gli* + *lo* pegados: «se lo» a él, a ella o a usted. *Glielo dico io*. También *gliela*, *glieli*, *gliene*.",
    "spedire": "Verbo en *-isc-*: *spedisco, spedisci*. Con pronombres combinados: *te le spedisco* (te las envío).",
    "pacco": "Plural *pacchi*. *Un pacco regalo* = paquete de regalo.",
    "camicia": "Plural *camicie*. Es la camisa; la camiseta es *maglietta*.",
    "dappertutto": "Una sola palabra, con doble *p*. Sinónimo: *ovunque*.",
    "etto": "Unidad típica en la fiambrería: *un etto di prosciutto* = 100 g. Plural *etti*.",
    "formaggio": "Plural *formaggi*. Rallado: *formaggio grattugiato*. Con *ne*: *gliene tolgo un po'?*",
    "permettere": "Participio *permesso*. *Permettersi* = darse el lujo: *non me lo posso permettere*.",
    "prosciutto": "*Crudo* o *cotto*. Con pronombre de refuerzo: *me lo dai il prosciutto?* (duplica el objeto, típico hablado).",
    "stirare": "Transitivo: *stirare le camicie*. La plancha es *il ferro da stiro*.",
    "bocciati": "Participio de *bocciare* (reprobar). *Essere bocciato a un esame*; lo opuesto es *essere promosso*.",
    "imbucare": "Viene de *buca* (buzón). *Imbucare una lettera*. Con pronombres: *gliela imbuco io*.",
    # --- semana 23 ---
    "antico": "Plural *antichi*, femenino *antiche*. *Antico* es muy viejo (histórico); algo solo viejo es *vecchio*.",
    "maggiore": "Comparativo de *grande*. *Mio fratello maggiore*, *la maggior parte* (la mayoría, pierde la *-e*).",
    "vita": "*Nella mia vita*; *la vita è bella*. *Fare la bella vita* = darse la gran vida.",
    "giovane": "Termina en *-e*: sirve para los dos géneros. *Più giovane di me* = más joven que yo (comparativo con *di*).",
    "migliore": "Comparativo de *buono*. Con artículo es superlativo: *il mio migliore amico*. El adverbio es *meglio*.",
    "furbo": "Es «vivo» en sentido pícaro: *è furbo*. No siempre es crítica; *fare il furbo* = hacerse el vivo.",
    "noioso": "Es lo que aburre: *un film noioso*. «Estar aburrido» es *annoiarsi*: *mi annoio*.",
    "quartiere": "Masculino en *-e*: *il quartiere*. *Il migliore ristorante del quartiere*: superlativo + *di*.",
    "stretto": "Angosto o apretado: *pantaloni stretti*. *Stretto di Messina* = estrecho.",
    "veloce": "Termina en *-e*: sirve para los dos géneros. *Veloce come l'aereo*: comparación de igualdad con *come*.",
    "birra": "*Una birra alla spina* = chopp. Comparación: *più caro della birra* (*di* + artículo).",
    "prete": "Es el sacerdote. El título es *don*: *don Mario*.",
    # --- semana 24 ---
    "dubitare": "Pide *che* + subjuntivo: *dubito che arrivi*. También *dubitare di qualcosa*.",
    "accomodarsi": "Invita a pasar o sentarse: *si accomodi!* (usted), *accomodati!* (vos).",
    "cinese": "Termina en *-e*: sirve para los dos géneros. Idiomas y gentilicios van en minúscula: *il cinese*, *una ragazza cinese*.",
    # --- semana 25 ---
    "lamentarsi": "Pronominal y pide *di*: *si lamenta del rumore*. *Non fa che lamentarsi* = no hace más que quejarse.",
    "giusto": "Además de «justo», es «correcto»: *la risposta giusta*. *Giusto!* = ¡exacto!",
    "lieti": "Plural de *lieto*, formal. *Siamo lieti che* + subjuntivo. Fórmula: *molto lieto* al presentarse.",
    # --- semana 27 ---
    "guidare": "Es manejar un vehículo: *guidare la macchina*. *La patente di guida* = el registro.",
    "raramente": "Adverbio de *raro* + *-mente*: sinónimo de *di rado*.",
    "soprattutto": "Una sola palabra con doble *t*. Sinónimo: *specialmente*.",
    "raro": "Es «poco común», no «extraño» (eso es *strano*). *Un caso raro*.",
    "singolarmente": "*Singolo* + *-mente*: uno por uno, por separado. Registro algo formal.",
    "lentamente": "Adverbio en *-mente*; en la charla se usa más *piano*: *guida piano*.",
    "domattina": "Contracción de *domani mattina*. Va sin preposición: *ci vediamo domattina*.",
    "commessa": "La vendedora de un negocio; masculino *commesso*. *Chiedere alla commessa*.",
    "soffiare": "*Il vento soffia*. *Soffiarsi il naso* = sonarse la nariz.",
    "cattivo": "Malo de carácter o de sabor: *un uomo cattivo*, *un odore cattivo*. «Malo» de calidad suele ser *brutto* o *scarso*.",
    # --- semana 28 ---
    "comunque": "Solo, al final, es «igual, de todos modos»: *usciamo comunque*. Al principio, «en fin, de todas formas». Con subjuntivo: *comunque vada* = pase lo que pase.",
    "siccome": "Causal que va al principio de la oración, como nuestro «como»: *siccome piove, restiamo*. Si la causa va después, se usa *perché*.",
    "largo": "Falso amigo: *largo* es «ancho»; «largo» es *lungo*. *Stare alla larga* = mantenerse lejos.",
    "chiudere": "Participio irregular: *chiuso*. *Chiudere a chiave* = cerrar con llave.",
    "altrimenti": "Conecta una consecuencia: *sbrigati, altrimenti perdiamo il treno*. Sinónimo coloquial: *se no*.",
    "avanti": "*Andare avanti* = seguir, avanzar. *Avanti!* también es «¡pase!» cuando golpean la puerta.",
    "scusare": "*Scusa* (vos) / *scusi* (usted) para disculparte o llamar la atención. *Scusarsi* = pedir perdón: *mi scuso per il ritardo*.",
    "spiaggia": "Plural *spiagge*. *Andare in spiaggia* o *alla spiaggia*; el balneario pago es *lo stabilimento*.",
    "tal": "Forma trunca de *tale* delante de consonante: *a tal punto che*. *Un tale* = un tipo, un fulano.",
    "promossi": "Participio plural de *promuovere*: aprobar un examen o un año, y también ascender. *Essere promosso* ≠ *bocciato*.",
    "pioggia": "Plural *piogge*. *Sotto la pioggia* = bajo la lluvia. El verbo es *piovere*: *piove*.",
    "affare": "Masculino: *un buon affare* = un buen negocio. *Affari* = negocios; *non sono affari tuoi* = no es asunto tuyo.",
    "inoltre": "Conector para sumar un argumento, algo formal. Va al principio y con coma: *Inoltre, il prezzo è alto*.",
    "promosso": "Con *essere*: *è stato promosso*. Sirve para aprobar en la escuela y para un ascenso en el trabajo.",
    "obiettato": "Participio de *obiettare* (objetar). *Obiettare che* + indicativo; el sustantivo es *l'obiezione*.",
    # --- semana 29 ---
    "sorpreso": "Participio de *sorprendere*. *Sono sorpreso che* + subjuntivo: *sono sorpreso che tu sia qui*.",
    "rendere": "Con adjetivo es «volver, hacer»: *mi rende felice*. Participio *reso*. *Rendersi conto* = darse cuenta.",
    # --- semana 30 ---
    "guadagnare": "Es ganar plata o tiempo: *guadagnare bene*. Un partido se gana con *vincere*.",
    "insomma": "Resume o corta: *insomma, basta!*. Como respuesta, «más o menos»: *Com'è andata? — Insomma*.",
    "gamba": "Plural *gambe*. *In gamba* = capo, despierto: *è una ragazza in gamba*.",
    "dispiaciuto": "Participio de *dispiacere*, con *essere*: *mi è dispiaciuto*. *Sono dispiaciuto* = estoy apenado.",
    "assegno": "*Pagare con assegno*; *un assegno scoperto* = cheque sin fondos. Viene de *assegnare*.",
    "convenuto": "Participio de *convenire*, con *essere* cuando es «convenir, ser mejor»: *sarebbe convenuto*. *Conviene* + infinitivo = conviene.",
    "colloquio": "*Colloquio di lavoro* = entrevista laboral. Una entrevista periodística es *intervista*.",
    "traslocare": "Es mudarse de casa. El sustantivo es *il trasloco*; «mudarse de ropa» es *cambiarsi*.",
    # --- semana 31 ---
    "giornale": "Masculino en *-e*: *il giornale*. «Diario» íntimo es *il diario*. *Secondo il giornale* = según el diario.",
    "infatti": "Confirma lo dicho, «efectivamente, justamente»: no siempre equivale a «de hecho» (*in realtà* corrige).",
    "autostrada": "*In autostrada*, sin artículo. En Italia se paga peaje: *il casello*.",
    "assicurare": "*Assicurare a qualcuno che* + indicativo. *Assicurarsi* = asegurarse, y también sacar un seguro.",
    "inviato": "Participio de *inviare*, más formal que *mandare*. Como sustantivo, *l'inviato* es el corresponsal.",
    "bolletta": "Es la factura de un servicio: *la bolletta della luce*, *del gas*. Una factura de compra es *la fattura*.",
    "convinto": "Participio de *convincere*. *Sono convinto che* + subjuntivo: *sono convinto che abbia ragione*. Para un futuro visto desde el pasado, condicional compuesto: *avrebbe telefonato*.",
    "decollo": "Del verbo *decollare* (despegar). Lo contrario es *l'atterraggio*.",
    # --- semana 32 ---
    "fallo": "En el deporte es una falta: *fare fallo*. No es un «fallo» judicial (eso es *sentenza*) ni un error.",
    "genitore": "*I genitori* = los padres (papá y mamá). *Padri* son solo varones.",
    "addirittura": "Enfatiza lo inesperado: «hasta, incluso». Sola, como respuesta: *Addirittura!* = ¡nada menos!",
    "squadra": "Equipo deportivo o de trabajo: *la mia squadra*. Colectivo: el verbo va en singular.",
    "affinché": "Siempre con subjuntivo: *affinché tu lo legga*. Más formal que *perché* con subjuntivo.",
    # --- semana 33 ---
    "laurearsi": "Pronominal: *mi sono laureato in legge*. La carrera va con *in*.",
    "litigare": "Pide *con*: *ho litigato con mia sorella*. *Litigare* no es litigar en tribunales (eso es *fare causa*).",
    "debito": "Esdrújula: *dèbito*. *Avere un debito con qualcuno*; *essere in debito* = deberle.",
    "purché": "Condición que pide subjuntivo: *purché tu guidi piano*. Tilde aguda: *-ché*.",
    "barca": "Plural *barche*. *Andare in barca* = navegar. *Barca a vela* = velero.",
    # --- semana 34 ---
    "cui": "Relativo invariable que va después de preposición: *in cui*, *con cui*, *a cui*. Entre artículo y sustantivo es «cuyo»: *la ragazza il cui padre...*",
    "pigro": "*Vago* en italiano es «vago, impreciso»: el que no quiere trabajar es *pigro*. Plural *pigri*.",
    "romanzo": "Es la novela; *la novella* es un cuento o relato. *Romanzo giallo* = policial.",
    "consigliare": "*Consigliare a qualcuno di* + infinitivo: *ti consiglio di andare*. El sustantivo es *il consiglio*.",
    "magazzino": "Es depósito o almacén de mercadería. La tienda por departamentos es *i grandi magazzini*.",
    "affittare": "Sirve para alquilar y para dar en alquiler: *affittiamo una casa*, *affittasi* (se alquila). El alquiler es *l'affitto*.",
    "prezzo": "*A buon prezzo* = barato. *Quanto costa?* es más natural que preguntar por el *prezzo*.",
    "vaso": "Falso amigo: es maceta o florero. Para tomar agua se usa *il bicchiere*.",
    "esaurire": "Verbo en *-isc-*: *esaurisco*. *Esaurito* = agotado (entradas, stock) y también «quemado» de nervios.",
    "ridata": "Participio de *ridare* (devolver): *me l'ha ridata*. El participio concuerda con *la* (el objeto) antepuesto.",
    "padrona": "*La padrona di casa* = la dueña o la anfitriona. Masculino *padrone*.",
    # --- semana 35 ---
    "chiesa": "Plural *chiese*. *Andare in chiesa*, sin artículo.",
    "migliaio": "Plural irregular femenino: *un migliaio*, *migliaia di persone*. Pide *di*.",
    "stupire": "Verbo en *-isc-*: *mi stupisce*. Funciona como «gustar» y pide subjuntivo: *mi stupisce che non abbia risposto*.",
    "giugno": "Meses en minúscula: *a giugno*, *il 2 giugno* (fiesta de la República).",
    "fuoco": "Plural *fuochi*. *I vigili del fuoco* = los bomberos; *fuochi d'artificio* = fuegos artificiales.",
    "consegnare": "*Consegnare a domicilio* = entregar a domicilio. La entrega es *la consegna*.",
    "rimandare": "Es postergar: *la riunione è stata rimandata a giovedì* (a + nueva fecha). También «reenviar».",
    "punire": "Verbo en *-isc-*: *punisco*. La pasiva con *essere*: *è stato punito*.",
    "colpevole": "Termina en *-e*: sirve para los dos géneros. *Sentirsi in colpa* = sentirse culpable.",
    "iva": "Sigla de *imposta sul valore aggiunto*. Femenino: *l'Iva*; *Iva inclusa*.",
    "vigile": "*Il vigile (urbano)* dirige el tránsito; *i vigili del fuoco* son los bomberos.",
    "soffitto": "Es el techo de adentro; el de afuera es *il tetto*.",
    "rifare": "Se conjuga como *fare*: *rifaccio*, *rifatto*. *Va rifatto* = hay que rehacerlo (*andare* + participio = obligación).",
    "stampare": "*Stampare un documento*. *La stampa* es la prensa y también la impresión.",
    # --- semana 36 ---
    "pulire": "Verbo en *-isc-*: *pulisco, pulisci*. *Si dovranno pulire le finestre*: pasiva con *si*.",
    "tedesco": "Plural *tedeschi*, femenino *tedesche*. Gentilicios e idiomas en minúscula.",
    "trattoria": "Restorán familiar y barato, con cocina casera. Más informal que *ristorante*; la *osteria* es parecida.",
    "cambiamento": "Cambio como transformación: *cambiamento climatico*. Cambio de plata o el vuelto: *il cambio*, *il resto*.",
    "riavvia": "Presente de *riavviare* (reiniciar un equipo): *come si riavvia?*. *Avviare* = arrancar, iniciar.",
    "evidenziare": "Es resaltar un texto o destacar un dato. El resaltador es *l'evidenziatore*.",
    "scaricare": "Es descargar, también en sentido literal: *scaricare la spesa*. Lo opuesto: *caricare* (cargar, subir).",
    "annoiarsi": "Pronominal: *mi annoio*. Impersonal: *non ci si annoia mai* (uno nunca se aburre).",
    "sindaco": "Es el intendente o alcalde de un *comune*. Plural *sindaci*.",
    "palazzo": "Es cualquier edificio de departamentos, no solo un palacio. *Un palazzo di cinque piani*.",
    "cartella": "Carpeta (física o de la compu) y también la mochila escolar. *Cartella clinica* = historia clínica.",
    # --- semana 37 ---
    "diventare": "Pasado con *essere*: *è diventato famoso*. Va directo con adjetivo o sustantivo: *diventare medico*.",
    "ridere": "Participio irregular: *riso*. *Scoppiare a ridere* = largar la risa; *ridere di qualcuno*.",
    "giù": "*Andare giù* = bajar; *essere giù* = estar bajoneado. Lo opuesto es *su*.",
    "disperato": "*Essere disperato* = estar desesperado. Del verbo *disperare*.",
    "alba": "*All'alba* = al amanecer. El atardecer es *il tramonto*.",
    "operaio": "Plural *operai*. Adjetivo: *la classe operaia*.",
    "campanello": "*Suonare il campanello* = tocar el timbre. De *campana*.",
    "dichiarare": "*Dichiarare di* + infinitivo: *dichiarò di non saperne niente*. El sustantivo es *la dichiarazione*.",
    "scoppiato": "Participio de *scoppiare*, con *essere*. *Scoppiare a ridere / a piangere*; también *è scoppiata la guerra*.",
    "nascosto": "Participio de *nascondere*. *Di nascosto* = a escondidas. *Nascondersi* = esconderse.",
    # --- semana 38 ---
    "divano": "Es el sofá. *Sul divano* (sobre); el sillón individual es *la poltrona*.",
    "finalmente": "Expresa alivio tras la espera: *finalmente è arrivato!*. No es «finalmente» de orden (eso es *infine*).",
    "finanziario": "Plural *finanziari*. *Direttore finanziario*, *crisi finanziaria*.",
    # --- semana 40 ---
    "tagliare": "*Farsi tagliare i capelli* = cortarse el pelo en la peluquería (*fare* + infinitivo: que te lo hagan).",
    "piangere": "Participio *pianto*. *Mi ha fatto piangere* = me hizo llorar.",
    "camera": "*La camera (da letto)* = el dormitorio; en el hotel, *una camera doppia*. La cámara de fotos es *la macchina fotografica*.",
    "portone": "Aumentativo de *porta*: la puerta grande del edificio. La de tu departamento es *la porta*.",
    "sporco": "Plural *sporchi*, femenino *sporche*. *Sporcare* = ensuciar.",
    "innaffiare": "Doble *f*; también se escribe *annaffiare*. *Innaffiare le piante*.",
    "suocero": "*I suoceri* = los suegros. Femenino: *suocera*.",
    "pesante": "Termina en *-e*: sirve para los dos géneros. También «pesado» de aburrido: *che pesante!*",
    "riscaldamento": "Calefacción; *il riscaldamento globale* es el calentamiento global. *Accendere il riscaldamento*.",
    "pancia": "Coloquial para el abdomen. *Mal di pancia* = dolor de panza. Plural *pance*.",
    "gas": "Invariable: *il gas*. *La bolletta del gas*; *a tutto gas* = a toda velocidad.",
    "prestito": "Esdrújula: *prèstito*. *Chiedere un prestito*, *dare in prestito*. El verbo es *prestare*.",
    "rifiutare": "*Rifiutare di* + infinitivo = negarse a. *I rifiuti* = la basura.",
    "pasticceria": "Tienda de masas y tortas. El pastelero es *il pasticciere*; la masa, *la pasta* o *il pasticcino*.",
    "sgomberare": "Es vaciar un lugar de cosas: *sgomberare la cantina*. También desalojar: *sgomberare un edificio*.",
    # --- semana 41 ---
    "doccia": "*Fare la doccia* = bañarse (en la ducha). Plural *docce*.",
    "usignolo": "Con verbos de percepción va el infinitivo: *sentire cantare l'usignolo* (oír cantar al ruiseñor).",
    "abbaiare": "*Il cane abbaia*. Con percepción + infinitivo: *ho sentito abbaiare il cane*.",
    "arrampicarsi": "Pronominal y pide *su*: *arrampicarsi sull'albero*. *L'arrampicata* = la escalada.",
    "fan": "Invariable: *i fan*. Del fútbol, lo típico es *i tifosi*.",
    "tifare": "Pide *per*: *tifo per il Napoli*. El hincha es *il tifoso*; «hacer barra» es *fare il tifo*.",
    "benzinaio": "Es el que atiende la estación y, por extensión, la estación: *dal benzinaio* (con *da*, como en «a lo de»).",
    "pettegolezzi": "*Fare pettegolezzi* = chusmear. Quien chusmea es *pettegolo/a*.",
    "chiacchierare": "Doble *c* en dos lugares. *Fare due chiacchiere* = charlar un rato.",
    "onda": "*Le onde del mare*. *Andare in onda* = salir al aire (radio, TV).",
    "infrangersi": "Pronominal: *le onde si infrangono sugli scogli*. Con percepción: *vedere le onde infrangersi*.",
    "scogliera": "Colectivo de *scoglio* (roca en el mar). *In cima alla scogliera* = arriba del acantilado.",
    "richiesta": "*Su richiesta* = a pedido. *Fare una richiesta*; del verbo *richiedere*.",
    # --- semana 42 ---
    "prenotare": "*Prenotare un tavolo / una camera*. *Pensare a* + infinitivo: *hai pensato a prenotare?*",
    "pregare": "Además de «rezar» es «rogar»: *ti prego* = te lo ruego, por favor. *Prego* responde a *grazie*.",
    "imbrogliato": "Participio de *imbrogliare*. *Mi vergogno di aver imbrogliato*: *di* + infinitivo compuesto.",
    "costringere": "*Costringere qualcuno a* + infinitivo. Participio *costretto*.",
    "andarsene": "Es *andare* + *se ne*: *me ne vado, te ne vai, se ne va*. Pasado: *me ne sono andato*.",
    "nuotare": "*Saper nuotare* = saber nadar (habilidad con *sapere*, no *potere*).",
    "stufato": "Participio de *stufarsi*: *mi sono stufato di* + infinitivo = me harté de. Como sustantivo, *lo stufato* es un guiso.",
    "imbrogliare": "Transitivo: *imbrogliare la gente*. Un *imbroglio* es una estafa o un lío; *imbroglione*, un chanta.",
    "bevanda": "Es bebida en general, bastante formal. Para pedir algo en la charla: *qualcosa da bere*.",
    "fegato": "Esdrújula: *fégato*. *Avere fegato* = tener agallas.",
    "convegno": "Es un congreso o jornada académica. *Partecipare a un convegno* (con *a*).",
    "costretto": "Participio de *costringere*. *Essere costretto a* + infinitivo = verse obligado a.",
    "ringraziati": "Participio plural de *ringraziare*: concuerda con *li* antepuesto. *Ringraziare per* algo.",
    # --- semana 43 ---
    "cioccolatino": "Diminutivo de *cioccolato*: un bombón. *Una scatola di cioccolatini*.",
    "spingere": "Participio *spinto*. En las puertas: *spingere* (empujar) / *tirare* (tirar).",
    # --- semana 44 ---
    "attraversare": "Transitivo: *attraversare la strada* (sin «por»). El gerundio *attraversando* indica «mientras cruzaba».",
    "scoprire": "Participio irregular: *scoperto*. *Ho scoperto che...* = me enteré de que...",
    "risparmiare": "*Risparmiare soldi / tempo*. *I risparmi* = los ahorros.",
    "diritto": "Sustantivo: *avere diritto a*. Adverbio: *vai sempre diritto* (seguí derecho). El lado derecho es *destro*.",
    "tasca": "Plural *tasche*. *In tasca*, sin artículo; *mettere in tasca*.",
    "sbagliare": "Transitivo: *ho sbagliato autobus* (me tomé el colectivo equivocado). Pronominal: *mi sono sbagliato*.",
    "cittadino": "Es el ciudadano y también «urbano»: *traffico cittadino*. *La cittadinanza* = la ciudadanía.",
    # --- semana 45 ---
    "vattene": "Imperativo de *andarsene* (tú): *va'* + *te* + *ne*. Con usted: *se ne vada*. Suena brusco.",
    "pazienza": "*Ci vuole pazienza* = hace falta paciencia. *Pazienza!* solo = ¡qué se le va a hacer!",
    "baciare": "*Baciarsi* = besarse. *Baci!* al despedirse = besos.",
    "battere": "*Battere il pugno sul tavolo*. También «ganarle» a alguien: *battere la Francia*.",
    "smettere": "Pide *di*: *smettere di fumare*. Participio *smesso*. *Smettila!* = ¡cortala!",
    "scemo": "Coloquial e informal: *fare lo scemo* = hacerse el tonto. Femenino *scema*.",
    "ciao": "Es «hola» y «chau», solo informal. Con usted: *buongiorno* / *arrivederci*.",
    # --- semana 46 ---
    "prenotazione": "*A nome di* = a nombre de: *ho una prenotazione a nome Parrino*.",
    "naso": "*Nasone* = narigón (aumentativo *-one*). *Ficcare il naso* = meter la nariz.",
    "mattone": "Ladrillo; también algo pesado y aburrido: *quel libro è un mattone*.",
    "febbrone": "Aumentativo de *febbre* con *-one* (pasa a masculino): fiebre alta. *Avere la febbre*.",
    "caratteraccio": "*Carattere* + sufijo despectivo *-accio*: mal carácter. Otros: *tempaccio*, *parolaccia* (mala palabra).",
    "scarponi": "Aumentativo de *scarpa* con *-one*: botas pesadas de montaña o de esquí.",
    "attimo": "*Un attimo!* = ¡un momento!. Esdrújula: *àttimo*.",
    "grassottello": "*Grasso* + *-ottello*: diminutivo cariñoso, suaviza. El italiano usa mucho los sufijos para matizar.",
    "paesino": "Diminutivo de *paese* (pueblo) con *-ino*. Ojo: *paese* también es «país».",
    "debolina": "Diminutivo de *debole* con *-ino*: suaviza la crítica, «flojita».",
    "paroloni": "Aumentativo de *parola* con *-one* (pasa a masculino): palabras difíciles para impresionar.",
    "maluccio": "Diminutivo de *male* con *-uccio*: suaviza, «más o menos mal».",
    "staccato": "Participio de *staccare* (despegar), con *si* y *essere*: *mi si è staccato un bottone*.",
    "tacchino": "Es el pavo; el pavo real es *il pavone*.",
    "giallastro": "*Giallo* + *-astro*: color impreciso, algo despectivo. Otros: *verdastro*, *biancastro*.",
    # --- semana 47 ---
    "secolo": "Esdrújula: *sècolo*. Los siglos del arte se nombran por centenas: *il Novecento* = siglo XX.",
    "domanda": "*Fare una domanda* = hacer una pregunta; *domandare* = preguntar. *Domanda di lavoro* = solicitud.",
    "undicesimo": "Del 11 en adelante los ordinales se forman con *-esimo*: *undicesimo*, *ventesimo*. Concuerdan: *all'undicesimo piano*.",
    "ventesimo": "*Venti* + *-esimo*, perdiendo la vocal final. Concuerda: *la ventesima volta*.",
    "centinaio": "Plural femenino irregular: *un centinaio*, *centinaia di persone*. Pide *di*.",
    "dozzina": "*Una dozzina di uova*: *uovo* tiene plural femenino irregular, *le uova*.",
    "terzo": "Ordinal: *terzo, terza*. *Al terzo piano*; *un terzo* = un tercio.",
    "doppio": "*Il doppio* = el doble. *Camera doppia* = habitación doble; *doppia fila* = doble fila.",
    # --- semana 48 ---
    "dipinto": "Participio de *dipingere* usado como sustantivo: un cuadro. *Dipingere* = pintar (arte).",
    "rumore": "Masculino en *-e*. *Fare rumore*. Con dislocación: *non lo sopporto, quel rumore* (anticipa el objeto).",
    "scattate": "De *scattare*: *scattare una foto* = sacar una foto. El participio concuerda con *le* antepuesto: *le ha scattate*.",
    # --- semana 49 ---
    "nonostante": "Con sustantivo: *nonostante la pioggia*. Con verbo, *nonostante* + subjuntivo: *nonostante sia tardi*.",
    "tuttavia": "Conector formal de contraste, como *però* pero más escrito. Suele ir al principio con coma.",
    "benché": "Siempre con subjuntivo: *benché sia tardi*. Sinónimo: *sebbene*.",
    "oltre": "*Oltre a* + sustantivo = además de: *oltre al lavoro*. Solo, es «más allá»: *andare oltre*.",
    "buio": "Adjetivo y sustantivo: *è buio*, *fa buio* (oscurece). *Al buio* = a oscuras.",
    "spiegazione": "Del verbo *spiegare*. *Dare una spiegazione*; femenino en *-zione*: *le spiegazioni*.",
    "server": "Invariable: *il server*, *i server*. Tecnicismo tomado del inglés, se pronuncia a la inglesa.",
    "backup": "Invariable: *il backup*. *Fare il backup* = hacer la copia de seguridad.",
    "appartengono": "De *appartenere*, que se conjuga como *tenere*: *appartengo, appartieni, appartiene... appartengono*. Pide *a*.",
    "occorrere": "Impersonal como «hacer falta»: *occorre pazienza*, *occorrono due ore*. Con infinitivo: *occorre partire*.",
    "vantaggio": "*Avere un vantaggio*; *a vantaggio di* = en beneficio de. Opuesto: *svantaggio*.",
    "inquinamento": "Del verbo *inquinare* + *-mento*. *Inquinamento atmosferico / acustico*.",
    # --- semana 50 ---
    "sedersi": "Irregular: *mi siedo, ti siedi, si siede, ci sediamo, vi sedete, si siedono*. Pasado: *mi sono seduto*.",
    "parcheggiare": "*Parcheggiare in doppia fila*. El estacionamiento es *il parcheggio*.",
    "zucchero": "Esdrújula: *zùcchero*. *Senza zucchero* = sin azúcar. Masculino.",
    "burro": "Falso amigo: es manteca, no un animal (el burro es *l'asino*).",
    "destro": "*A destra* = a la derecha (femenino). *Destro* también es «hábil, diestro».",
    "sud": "Puntos cardinales: *a sud di* = al sur de. *Il Sud* = el sur de Italia.",
    "cassetto": "Masculino: *il cassetto*. *Nel cassetto*. Un sueño guardado: *un sogno nel cassetto*.",
    "parrucchiere": "*Andare dal parrucchiere* (con *da*: a lo de). Femenino *parrucchiera*.",
    "sicurezza": "*Cintura di sicurezza*; *per sicurezza* = por las dudas.",
    "bambina": "Plural *bambine*. *Da bambina* = de chica (cuando era nena).",
    "gonna": "Es la pollera. *Minigonna*. Femenino, plural *gonne*.",
    "biondo": "*Capelli biondi*; también la cerveza rubia: *una bionda*.",
    "scrivania": "Es el mueble, de *scrivere*. El escritorio como habitación es *lo studio*.",
    "occhio": "Plural *gli occhi*. *Costare un occhio della testa* = costar un ojo de la cara. *Occhio!* = ¡cuidado!",
    "aceto": "Masculino: *l'aceto*. *Aceto balsamico* (de Módena); *sott'aceto* = en vinagre, en escabeche.",
    # --- semana 51 ---
    "sebbene": "Siempre con subjuntivo: *sebbene sia tardi*. Igual que *benché*.",
    "tradire": "Verbo en *-isc-*: *tradisco*. *Il tradimento* = la traición (también infidelidad).",
    "cantina": "Falso amigo: es el sótano o la bodega donde se guarda el vino, no un bar. *Scendere in cantina*.",
    "ristrutturare": "Refaccionar una casa: *far ristrutturare la cucina* = mandarla a refaccionar (*fare* + infinitivo).",
    "pitturare": "Pintar paredes; en arte se usa *dipingere*. *Far pitturare le camere di bianco*.",
    "imbianchino": "De *imbiancare* (blanquear): el que pinta casas. Un artista es *un pittore*.",
    "indietro": "*Tornare indietro* = volver atrás. *Essere indietro* = estar atrasado.",
    "vassoio": "Plural *vassoi*. *Far cadere* = tirar sin querer: *ho fatto cadere il vassoio*.",
}
