# -*- coding: utf-8 -*-
"""Las palabras de las semanas 5 a 25, elegidas a mano.

Hasta la versión 2.8 estas semanas elegían solas sus palabras entre las más
frecuentes de sus ejercicios: de 4 a 12 por semana, algunas formas
conjugadas (*affolleranno*, *bocciati*, *lieti*), números sueltos y ejemplos
de un ejercicio que usaba la palabra en otro sentido.  Las semanas 14-26
quedaban en 9 palabras nuevas explícitas por semana, justo en el paso de A2
a B1.

Acá van 19-20 por semana, con el formato de las de la 27 a la 51
(tools/it/bank/parole_c1.py): palabra, castellano, un ejemplo que usa solo la
gramática ya vista (build_course.py lo comprueba con tools/it/rasgos_banco.py)
y una nota de uso que dice el régimen, el auxiliar, la colocación o el falso
amigo cuando corresponde.  Se eligen por el campo de la semana (su «sai
fare», build_course.py SAI_FARE), por frecuencia (frequenza.json) y, sobre
todo, rescatando las palabras que las lecturas de esa semana (*La
settimana*, los episodios de Martín, el dictogloss) glosaban sin enseñarlas.

Las semanas de jefe (13, 26) no traen palabras nuevas.

Formato: [palabra, castellano, ejemplo, cómo se usa]
"""

PAROLE_PONTE = {
    5: [
        ["parlare", "hablar", "Lei parla italiano?",
         "Se habla *di* algo y *con* alguien: *parlo di lavoro con Marco*. El idioma va sin artículo: *parla italiano*; con *studiare* lo lleva: *studio l'italiano*."],
        ["mangiare", "comer", "La sera mangiamo a casa.",
         "La *i* solo marca el sonido «ch»: *tu mangi*, *noi mangiamo*, sin doble *i*. *Mangiare fuori* = comer afuera."],
        ["prendere", "tomar; agarrar", "Prendo un caffè, grazie.",
         "Es el verbo de pedir en el bar y de tomar un transporte: *prendo un cornetto*, *prendo il treno*. Participio irregular *preso* (semana 11)."],
        ["scrivere", "escribir", "Scrivo una lettera al professore.",
         "Se escribe *a* alguien: *scrivo a Marco*. Participio irregular: *scritto* (*ho scritto*, semana 11)."],
        ["capire", "entender", "Non capisco la domanda.",
         "Verbo en *-isc-*: *capisco, capisci, capisce, capiamo, capite, capiscono*. *Non ho capito* = no entendí (semana 11)."],
        ["finire", "terminar", "La lezione finisce presto.",
         "En *-isc-* como *capire*: *finisco, finisci*. Con infinitivo pide *di*: *finisco di lavorare*. Pasado con *avere* si terminás algo, con *essere* si algo termina: *il film è finito*."],
        ["arrivare", "llegar", "Arrivo sempre tardi.",
         "Pide *a* con ciudades (*arrivo a Roma*) e *in* con países y lugares (*in Italia*, *in ufficio*). Pasado con *essere*: *sono arrivato*."],
        ["partire", "irse, salir de viaje", "Domani parto per Roma.",
         "Es irse de viaje o salir un medio de transporte, no «partir» algo (eso es *dividere* o *rompere*). *Partire per* + destino. Pasado con *essere*: *sono partita*."],
        ["vedere", "ver", "Dalla finestra vedo il mare.",
         "«Ver» sin intención; mirar con atención es *guardare*. Participio irregular *visto* (semana 11). *Ci vediamo!* = ¡nos vemos!"],
        ["pagare", "pagar", "Oggi pago io il caffè.",
         "En *-gare* se agrega *h* ante *i* y *e* para mantener el sonido: *tu paghi*, *noi paghiamo*. *Pagare con la carta*, *in contanti*."],
        ["conto", "la cuenta", "Il conto, per favore.",
         "En el bar y el restorán se pide *il conto*. También es la cuenta del banco: *il conto corrente*. *Fare i conti* = hacer las cuentas."],
        ["pranzo", "almuerzo", "A pranzo mangio un panino al bar.",
         "*A pranzo* = al mediodía, en el almuerzo. El verbo es *pranzare*. El desayuno es *la colazione* y la cena, *la cena*."],
        ["cena", "cena", "Dopo cena guardo un film.",
         "*A cena* (en la cena), *dopo cena* (después de cenar), sin artículo. El verbo es *cenare*. Una *cena* se hace entre las siete y media y las nueve."],
        ["giornale", "diario (periódico)", "La mattina leggo il giornale al bar.",
         "Falso amigo: no es «jornal». *Leggere il giornale*; el que los vende es *l'edicola* y el periodista, *il giornalista*."],
        ["collega", "compañero de trabajo", "Il mio collega è molto simpatico.",
         "Una sola forma en singular: *il collega*, *la collega*. Plural *i colleghi*, *le colleghe*, con *h*. No confundir con *compagno* (de clase, de equipo)."],
        ["ordinare", "pedir (en el restorán); ordenar", "Al ristorante ordiniamo una pizza e un'insalata.",
         "En el restorán es «pedir»: *ordino un piatto di pasta*. También es ordenar algo, igual que en castellano. «Pedir un favor» es otra cosa: *chiedere*."],
        ["rispondere", "responder, contestar", "Marco non risponde al telefono.",
         "Rige *a*: *rispondere a qualcuno*, *a una domanda*, *al telefono*. Participio irregular *risposto*. «Contestar» parece igual, pero *contestare* es otra cosa (cuestionar)."],
        ["ridere", "reírse", "Anna ride sempre con gli amici.",
         "No es pronominal: *rido*, no «mi rido». Rige *di*: *ridere di qualcuno*. Participio *riso*. Sonreír es *sorridere*."],
        ["provare", "probar, probarse; intentar", "Provo la pizza di questo bar.",
         "Probar una comida o una prenda: *provo la giacca*. Con infinitivo pide *a*: *provo a studiare* = intento estudiar. *Provare* también es «sentir»: *provare paura*."],
        ["pezzo", "pedazo, porción", "Prendo un pezzo di pizza.",
         "Pide *di*: *un pezzo di torta*, *di pane*. Plural *pezzi*. *Andare in pezzi* = hacerse pedazos."],
    ],
    6: [
        ["andare", "ir", "Stasera andiamo al cinema.",
         "Irregular: *vado, vai, va, andiamo, andate, vanno*. Pide *a* con ciudades y verbos (*vado a Roma*, *vado a mangiare*) e *in* con países y lugares (*in Italia*, *in banca*). Pasado con *essere*."],
        ["venire", "venir", "Vieni con noi al cinema?",
         "Irregular: *vengo, vieni, viene, veniamo, venite, vengono*. *Venire* es acercarse a donde está el que habla; por eso «ya voy» es *arrivo!*. Pasado con *essere*: *sono venuto*."],
        ["fare", "hacer", "Posso fare una domanda?",
         "Irregular: *faccio, fai, fa, facciamo, fate, fanno*; participio *fatto*. Arma mil expresiones: *fare colazione* (desayunar), *fare la spesa*, *fa freddo*, *faccio l'ingegnere*."],
        ["volere", "querer", "Vuole un caffè, signore?",
         "Irregular: *voglio, vuoi, vuole, vogliamo, volete, vogliono*. Va con infinitivo sin preposición: *voglio mangiare*. Para pedir con cortesía, *vorrei* (semana 20)."],
        ["potere", "poder", "Posso pagare con la carta?",
         "Irregular: *posso, puoi, può, possiamo, potete, possono*. Directo con infinitivo: *posso entrare?*. Pedir permiso: *posso?*; «no puedo más» = *non ce la faccio più*."],
        ["dovere", "tener que, deber", "Devo studiare stasera.",
         "Irregular: *devo, devi, deve, dobbiamo, dovete, devono*. Va con infinitivo sin «que»: *devo lavorare* (tengo que trabajar). *Dovere* también es deber plata: *ti devo dieci euro*."],
        ["sapere", "saber", "Sai dov'è la stazione?",
         "Irregular: *so, sai, sa, sappiamo, sapete, sanno*. Es saber un dato o saber hacer algo: *so nuotare*. Conocer a una persona o un lugar es *conoscere*: *conosco Roma*."],
        ["uscire", "salir (de un lugar)", "Esco di casa presto.",
         "Irregular: *esco, esci, esce, usciamo, uscite, escono*. Falso amigo de *salire* (que es «subir»). *Uscire di casa*, *uscire con gli amici*. Pasado con *essere*."],
        ["dire", "decir", "Marco dice sempre di sì.",
         "Irregular: *dico, dici, dice, diciamo, dite, dicono*; participio *detto*. Se dice algo *a* alguien. *Dire di sì / di no*: decir que sí o que no, con *di*."],
        ["stare", "estar; quedarse", "Come stai? — Sto bene, grazie.",
         "Irregular: *sto, stai, sta, stiamo, state, stanno*. Es el «estar» del ánimo y la salud (*sto bene*) y del gerundio (*sto mangiando*). Para ubicar cosas y lugares, *essere*: *Roma è in Italia*."],
        ["tornare", "volver", "Torno a casa tardi.",
         "*Tornare a casa*, sin artículo. Pasado con *essere*: *sono tornata*. «Volver a hacer» no se dice con *tornare*: *lo rifaccio* o *lo faccio di nuovo*."],
        ["trovare", "encontrar", "Non trovo le chiavi.",
         "Encontrar algo que buscás: *non trovo le chiavi*. También opinar: *lo trovo simpatico* (me parece). *Andare a trovare qualcuno* = ir a visitarlo."],
        ["incontrare", "encontrarse con (alguien)", "In piazza incontro sempre Paolo.",
         "Es cruzarte con alguien o verte con él, sin *a*: *incontro Paolo*. Encontrar algo perdido es *trovare*. *Incontrarsi* = verse, juntarse."],
        ["chiedere", "pedir; preguntar", "Chiedo il conto al cameriere.",
         "Es «pedir» y también «preguntar», siempre *a* alguien: *chiedo a Marco*. Participio *chiesto*. *Chiedere scusa* = pedir perdón. Pedir en el restorán: *ordinare* o *prendere*."],
        ["stasera", "esta noche", "Stasera guardiamo un film.",
         "Una sola palabra: *questa sera* abreviado, como *stamattina* y *stanotte*. Va sin preposición: *stasera esco*."],
        ["negozio", "negocio, local, tienda", "In via Roma c'è un negozio di scarpe.",
         "Es el local donde se vende: *negozio di scarpe*, *di alimentari*. Un negocio como trato es *un affare*. *Fare shopping* o *fare spese* = ir de compras."],
        ["fermata", "parada", "La fermata dell'autobus è qui vicino.",
         "*La fermata dell'autobus, del tram*. *Scendo alla prossima fermata* = me bajo en la próxima. Viene de *fermare* (parar)."],
        ["chiesa", "iglesia", "In piazza c'è una chiesa molto bella.",
         "El grupo *chi* suena «qui»: «kiesa». Plural *chiese*. *Andare in chiesa*, sin artículo."],
        ["salire", "subir", "Salgo sull'autobus in piazza.",
         "Falso amigo: *salire* es «subir»; «salir» es *uscire*. Irregular: *salgo, sali, sale, saliamo, salite, salgono*. *Salire in macchina*, *salire sul treno*; pasado con *essere*."],
    ],
    7: [
        ["giorno", "día", "Lavoro otto ore al giorno.",
         "Masculino, plural *giorni*. *Al giorno* = por día. *Tutto il giorno* = todo el día; para el día como tiempo vivido se prefiere *giornata* (semana 17)."],
        ["settimana", "semana", "Studio italiano due ore alla settimana.",
         "*Alla settimana* = por semana. *Il fine settimana* = el fin de semana (también *il weekend*). *La settimana prossima*, *la settimana scorsa*."],
        ["mese", "mes", "Il corso dura tre mesi.",
         "Masculino en *-e*: *il mese*, plural *i mesi*. Los meses van en minúscula y sin artículo: *a maggio*, *in luglio*."],
        ["anno", "año", "Mia sorella ha venticinque anni.",
         "La edad va con *avere*: *ho trent'anni*. Sin *ñ*: doble *n*. *Buon anno!* = ¡feliz año! *L'anno prossimo*, *l'anno scorso*."],
        ["ora", "hora; ahora", "Che ora è? — Sono le tre.",
         "Para la hora: *che ora è?* o *che ore sono?*; se responde *è l'una*, *sono le tre*. Como adverbio es «ahora»: *ora vengo*."],
        ["mattina", "mañana (parte del día)", "Il lunedì mattina lavoro dalle otto alle due.",
         "*La mattina* = a la mañana. «Mañana» (el día siguiente) es *domani*; *domani mattina* = mañana a la mañana. *Stamattina* = esta mañana."],
        ["pomeriggio", "tarde (después del mediodía)", "Il negozio apre alle quattro del pomeriggio.",
         "Es la tarde después de comer; cuando oscurece empieza la *sera*. *Nel pomeriggio*, *oggi pomeriggio*."],
        ["sera", "noche (temprano), atardecer", "Torno a casa alle sette di sera.",
         "Es el tramo que va de las seis a las once, cuando ya oscurece; después viene la *notte*. *Ieri sera*, *domani sera*; saludo: *buonasera*."],
        ["notte", "noche (de dormir)", "Di notte la città è tranquilla.",
         "Es la noche de dormir, tarde. *Di notte* = de noche. *Buonanotte* solo para ir a dormir. *Stanotte* = esta noche o anoche."],
        ["mezzogiorno", "mediodía", "A mezzogiorno mangio un panino.",
         "Sin artículo: *a mezzogiorno*, como *a mezzanotte*. Con mayúscula, *il Mezzogiorno* es el sur de Italia."],
        ["mezzo", "medio", "Sono le otto e mezza.",
         "Con la hora vale *e mezza* o *e mezzo*. Antes del sustantivo, sin artículo: *mezzo chilo*, *mezz'ora*. *In mezzo a* = en el medio de."],
        ["quarto", "cuarto", "Sono le dieci meno un quarto.",
         "Para la hora: *e un quarto* (y cuarto), *meno un quarto* (menos cuarto). Como ordinal, *il quarto piano*. «Cuarto» (habitación) es *camera* o *stanza*."],
        ["stagione", "estación (del año); temporada", "La mia stagione preferita è la primavera.",
         "Falso amigo con *stazione*, que es la estación de tren. Femenino en *-e*: *la stagione*, *le stagioni*. *Alta stagione* = temporada alta."],
        ["estate", "verano", "D'estate andiamo al mare.",
         "Parece «estate», pero es el verano. Femenino: *l'estate*. *D'estate* o *in estate*; igual *d'inverno*, *in primavera*, *in autunno*."],
        ["compleanno", "cumpleaños", "Il mio compleanno è il tre maggio.",
         "*Buon compleanno!* = ¡feliz cumpleaños! Para decir cuántos cumplís: *compio trent'anni*. Las fechas llevan artículo: *il tre maggio*."],
        ["esame", "examen", "Domani ho un esame di storia.",
         "Masculino: *l'esame*, plural *gli esami*. Rendir un examen es *dare un esame*; aprobarlo, *superarlo* o *passarlo*."],
        ["ufficio", "oficina", "Sono in ufficio dalle nove alle cinque.",
         "Con *in* y sin artículo: *sono in ufficio*, *vado in ufficio*. Plural *gli uffici*. *Da... a* para el horario: *dalle nove alle cinque*."],
        ["prezzo", "precio", "Il prezzo è di dieci euro.",
         "Doble *z*. Para preguntarlo, *quanto costa?*. *A buon prezzo* = a buen precio; *prezzo fisso* = precio fijo."],
        ["orologio", "reloj", "Non ho l'orologio: che ore sono?",
         "Es el reloj de pulsera y el de pared. Esdrújula: *orològio*, plural *orologi*. «Mi reloj adelanta / atrasa» = *è avanti / indietro*."],
    ],
    8: [
        ["destra", "derecha", "La farmacia è a destra.",
         "*A destra* = a la derecha; *sulla destra* = a mano derecha. En política también: *la destra*, *di destra*."],
        ["sinistra", "izquierda", "Il bagno è in fondo a sinistra.",
         "*A sinistra*, *sulla sinistra*. No tiene nada de «siniestro»: es la mano izquierda. *In fondo a sinistra* = al fondo a la izquierda."],
        ["dritto", "derecho (sin doblar)", "Vai sempre dritto e arrivi in piazza.",
         "*Sempre dritto* = todo derecho. También se escribe *diritto*. «Derecho» (ley) es *il diritto*; la mano derecha es *destra*."],
        ["angolo", "esquina; rincón", "Il bar è all'angolo.",
         "Esdrújula: *àngolo*. *All'angolo* = en la esquina; *dietro l'angolo* = a la vuelta de la esquina, y también «muy cerca en el tiempo»."],
        ["incrocio", "cruce, bocacalle", "All'incrocio giri a sinistra.",
         "Donde se cruzan dos calles. Plural *incroci*. Con el semáforo: *al semaforo*. Viene de *croce* (cruz)."],
        ["attraversare", "cruzar, atravesar", "Attraversi la piazza e c'è la stazione.",
         "Transitivo, sin preposición: *attraversare la strada*, *il ponte*. Doble *r* y doble *s*. Cruzar la calle por la senda: *sulle strisce*."],
        ["girare", "doblar; girar; dar vueltas", "Poi giri a destra, vicino alla chiesa.",
         "Para indicar el camino: *giri a destra* (doblás a la derecha). También es rodar una película (*girare un film*) y recorrer: *girare per la città*."],
        ["indirizzo", "dirección (postal)", "Qual è il tuo indirizzo?",
         "Falso amigo: «dirección» de una calle es *indirizzo*; *direzione* es el rumbo o la dirección de una empresa. *Indirizzo email*."],
        ["via", "calle", "Abito in via Garibaldi.",
         "Se usa en las direcciones, con *in* y sin artículo: *abito in via Verdi 5*. Detrás de un verbo es «afuera, lejos»: *andare via* (irse), *buttare via* (tirar)."],
        ["strada", "calle, camino", "È questa la strada per il centro?",
         "Es la calle como camino o recorrido: *attraversare la strada*, *la strada per Roma*. Para la dirección postal, *via*. *Per strada* = en la calle."],
        ["cercare", "buscar", "Cerco la stazione: è lontana?",
         "Transitivo, sin «a»: *cerco Marco*. Con infinitivo pide *di*: *cerco di dormire* (trato de). En *tu cerchi* la *h* mantiene el sonido «k»."],
        ["dubbio", "duda", "Ho un dubbio: è a destra o a sinistra?",
         "Masculino, plural *dubbi*. *Avere un dubbio*; *senza dubbio* = sin duda. «Dudar» es *dubitare* (semana 24)."],
        ["bello", "lindo", "È una bella casa.",
         "Antes del sustantivo cambia como el artículo: *bel ragazzo*, *bello zaino*, *bell'uomo*, *bei libri*, *begli occhi*. Después del verbo, normal: *è bello*."],
        ["ragazzo", "chico, muchacho", "Chi è quel ragazzo?",
         "Plural *ragazzi* (chicos, o chicos y chicas). *La ragazza* = la chica. *Il mio ragazzo*, *la mia ragazza* = mi novio, mi novia."],
        ["uomo", "hombre", "Quell'uomo è il mio vicino.",
         "Plural irregular: *uomini* (*gli uomini*). Con adjetivo delante: *un bell'uomo*. «Varón» en formularios: *uomo* o *maschio*."],
        ["abitare", "vivir (en un lugar)", "Dove abita Marco?",
         "Pide *a* con ciudades (*abito a Roma*) e *in* con calles, barrios o países (*abito in via Verdi*, *in Italia*). «Vivir» en general, la vida: *vivere*."],
        ["vero", "verdadero; ¿no?", "Partono lunedì, vero?",
         "Al final de la pregunta pide confirmación, como «¿no?»: *vieni, vero?*. *È vero* = es verdad. *Davvero?* = ¿en serio?"],
        ["cominciare", "empezar", "A che ora comincia?",
         "Con infinitivo pide *a*: *comincio a lavorare*. En *tu cominci* la *i* no se duplica. Sinónimo: *iniziare*."],
        ["gentile", "amable", "Siete molto gentili.",
         "Es «amable», no «gentil» de pagano. En cartas: *Gentile signora*. Para agradecer: *grazie, molto gentile!*"],
    ],
    9: [
        ["portare", "llevar; traer", "Porto il vino alla festa.",
         "Es «llevar» y también «traer»: *porto il vino* (lo llevo), *mi porti un caffè?* (¿me traés?). También «llevar puesto»: *porta gli occhiali*."],
        ["bere", "tomar, beber", "Bevo un caffè con i miei amici.",
         "Se conjuga desde *bev-*: *bevo, bevi, beve, beviamo, bevete, bevono*; participio *bevuto*. «Tomar algo» = *bere qualcosa*; *qualcosa da bere*."],
        ["aspettare", "esperar", "Aspetto l'autobus da venti minuti.",
         "Transitivo, sin «a»: *aspetto Marco*. *Da* + tiempo con presente: *aspetto da un'ora* (hace una hora que espero). Esperar con deseo es *sperare* (semana 25)."],
        ["guardare", "mirar", "Guardo la TV con mio fratello.",
         "«Mirar» con atención: *guardare la TV*, *guardare un film*. «Ver» sin intención es *vedere*. *Guarda!* = ¡mirá!"],
        ["restare", "quedarse", "Stasera resto a casa.",
         "*Restare a casa*, sin artículo. Pasado con *essere*: *sono restato*. *Mi resta poco tempo* = me queda poco tiempo. Sinónimo: *rimanere*."],
        ["imparare", "aprender", "Imparo a guidare con mio padre.",
         "Con infinitivo pide *a*: *imparo a nuotare*. Idiomas con artículo: *imparare l'italiano*. Enseñar es *insegnare* (semana 22)."],
        ["piccolo", "chico, pequeño", "La mia camera è piccola.",
         "El «chico» de tamaño; para niño se usa *bambino*. *Da piccolo* = de chico. Superlativo coloquial: *piccolissimo*."],
        ["lungo", "largo (de longitud)", "Il viaggio in treno è lungo.",
         "Falso amigo: *lungo* es «largo»; nuestro «ancho» es *largo* (semana 23). Plural *lunghi*, con *h*. *Lungo il fiume* = a lo largo del río."],
        ["biglietto", "boleto, entrada; billete", "Faccio il biglietto alla stazione.",
         "Boleto de tren o colectivo y entrada del cine; también el billete de banco. *Fare il biglietto* = sacar el boleto; *biglietto di andata e ritorno* = ida y vuelta."],
        ["aereo", "avión", "Vado a Parigi in aereo.",
         "*L'aereo*, plural *gli aerei*. El medio va con *in* y sin artículo: *in aereo*, *in treno*, *in macchina*; pero *a piedi*."],
        ["macchina", "auto", "Vado al lavoro in macchina.",
         "La palabra común para «auto»; *auto* existe y es más neutra. *In macchina* = en auto. Plural *le macchine*, con *h*."],
        ["autobus", "colectivo, ómnibus", "Prendo l'autobus in piazza.",
         "Invariable: *l'autobus*, *gli autobus*. *Prendere l'autobus*; *in autobus*. En la ciudad también *il bus*; el micro de larga distancia es *il pullman*."],
        ["binario", "andén (vía)", "Il treno per Milano parte dal binario tre.",
         "En la estación se anuncia el *binario*, no el andén: *in partenza dal binario tre*. *Il marciapiede* es la vereda y también el andén."],
        ["piede", "pie", "Vado a scuola a piedi.",
         "*A piedi* = a pie, caminando, con *a*. Plural *i piedi*. *In piedi* = parado: *stare in piedi*."],
        ["valigia", "valija", "Faccio la valigia per il viaggio.",
         "*Fare la valigia* = armar la valija. Plural *valigie* o *valige*. El equipaje en general es *il bagaglio* (semana 20)."],
        ["banca", "banco (de plata)", "Lavoro in banca da due anni.",
         "El banco donde se deposita plata es *la banca*: *vado in banca*. *Il banco* es el banco de la escuela, el mostrador o el puesto del mercado."],
        ["partenza", "salida, partida", "La partenza è alle otto dalla stazione.",
         "De *partire* (salir de viaje). En la estación: *partenze* y *arrivi*. *Essere in partenza* = estar por salir."],
        ["metropolitana", "subte", "A Milano prendo la metropolitana per andare in centro.",
         "Se abrevia *la metro*. *Prendere la metropolitana*; *in metropolitana*. La estación de subte es *la fermata della metro*."],
        ["posto", "lugar; asiento; puesto", "C'è un posto libero sul treno?",
         "Es el lugar, el asiento y el puesto de trabajo: *un posto libero*, *un posto di lavoro*. *Al posto di* = en lugar de. «Puesto» del mercado es *banco*."],
        ["guidare", "manejar", "Mio padre guida la macchina da trent'anni.",
         "Es manejar un vehículo: *guidare la macchina*. El registro es *la patente (di guida)*. «Manejar» un negocio es *gestire*."],
    ],
    10: [
        ["aiutare", "ayudar", "Ti aiuto io con la valigia.",
         "Transitivo: *ti aiuto* (te ayudo, sin «a»). Con infinitivo pide *a*: *mi aiuti a portare la valigia?*. *Aiuto!* = ¡socorro!"],
        ["signore", "señor", "Buongiorno, signore!",
         "Delante de un apellido pierde la *-e*: *il signor Rossi*. Para hablarle directo, sin artículo: *buongiorno, signore!*"],
        ["ecco", "acá está, he aquí", "Ecco il tuo caffè.",
         "Presenta algo que se da o aparece: *ecco il caffè*. Se le pegan los pronombres: *eccolo*, *eccola*, *eccomi* (¡acá estoy!)."],
        ["ascoltare", "escuchar", "Ascolto sempre la radio la mattina.",
         "Transitivo como «escuchar»: *la ascolto* (la escucho). «Oír» sin prestar atención es *sentire*: *non ti sento*."],
        ["offrire", "ofrecer; invitar", "Gli offro un caffè.",
         "Participio irregular *offerto*. *Offrire da bere* = invitar a tomar algo; *offro io!* = ¡invito yo! Lo que se ofrece va con *a*: *offro un caffè a Marco*."],
        ["giardino", "jardín", "Le ragazze sono in giardino.",
         "Con *in* va sin artículo: *sono in giardino*. El jardín de infantes no es *giardino*: es *la scuola materna* o *l'asilo*."],
        ["pronto", "listo; ¿hola? (al teléfono)", "La cena è pronta.",
         "Es «listo»: *sei pronto?*. Al atender el teléfono se dice *Pronto?*. «Pronto» de tiempo es *presto*: *a presto!*"],
        ["telefonare", "llamar por teléfono", "Le telefono domani.",
         "Pide *a*: *telefono a Marco* → *gli telefono*; *telefono a Giulia* → *le telefono*. No es transitivo como «llamar» (*la chiamo*)."],
        ["chiamare", "llamar", "Anna? La chiamo stasera.",
         "Transitivo: *ti chiamo*, *la chiamo* (a ella o a usted). *Chiamarsi* = llamarse: *mi chiamo Anna*. La *ch* suena «k»."],
        ["ringraziare", "agradecer", "La ringrazio, signora.",
         "Transitivo: se agradece *a* la persona sin preposición (*ringrazio Marco*, *lo ringrazio*) y la cosa con *di* o *per*: *ti ringrazio del regalo*."],
        ["mandare", "mandar, enviar", "Gli mando un messaggio stasera.",
         "Es «enviar»: *mandare un messaggio, una mail, una cartolina*. Se manda algo *a* alguien: *gli mando le foto*. «Mandar» en el sentido de ordenar es *ordinare*."],
        ["prestare", "prestar", "Luca non ha la penna: gli presto la mia.",
         "Se presta algo *a* alguien: *presto il libro a Luca* → *gli presto il libro*. Pedir prestado: *mi presti...?*. El préstamo es *il prestito*."],
        ["abbracciare", "abrazar", "La nonna abbraccia forte i nipoti.",
         "Transitivo: *ti abbraccio* (te abrazo; también al cerrar un mensaje, como «un abrazo»). El abrazo es *l'abbraccio*. Doble *b*."],
        ["sorridere", "sonreír", "La bambina sorride sempre.",
         "Se sonríe *a* alguien: *le sorride*. Participio *sorriso*, que también es la sonrisa: *un bel sorriso*. Reírse es *ridere*."],
        ["voler bene", "querer (a alguien)", "Gli voglio bene come a un fratello.",
         "Es el cariño a la familia y los amigos: *ti voglio bene*. *Ti amo* es solo para la pareja. Lleva pronombre indirecto: *gli voglio bene*."],
        ["permesso", "permiso", "Permesso? Posso entrare?",
         "*Permesso?* se dice al entrar a una casa o al pasar entre la gente. También es el permiso formal: *il permesso di soggiorno* (la residencia para extranjeros)."],
        ["dare", "dar", "Le do il mio numero di telefono.",
         "Irregular: *do, dai, dà, diamo, date, danno*; *dà* con tilde para distinguirlo de *da*. Se da algo *a* alguien: *gli do*, *le do*."],
        ["conoscere", "conocer", "Conosci Marco? — Sì, lo conosco bene.",
         "Personas y lugares: *conosco Roma*. Saber un dato es *sapere*. *Conoscere* en el pasado es «conocer por primera vez»: *l'ho conosciuto ieri* (semana 11)."],
        ["salutare", "saludar", "Anna saluta sempre tutti con un sorriso.",
         "Transitivo: *saluto Marco*, *lo saluto*. Al despedirte: *salutami Anna!* (saludala de mi parte). *Saluti!* cierra un mensaje: saludos."],
    ],
    11: [
        ["ricevere", "recibir", "Ho ricevuto la tua email.",
         "Regular en *-ere*: *ho ricevuto*. Muy usado en mails: *ho ricevuto il tuo messaggio*. *Ricevuta* es el recibo."],
        ["rimanere", "quedarse, permanecer", "Quanto tempo sei rimasto a Roma?",
         "Irregular: *rimango, rimani, rimane... rimangono*; participio *rimasto*, con *essere*. *Rimanere senza* = quedarse sin: *sono rimasto senza soldi*."],
        ["scegliere", "elegir", "Ho scelto il vino rosso.",
         "Irregular: *scelgo, scegli, sceglie, scegliamo, scegliete, scelgono*; participio *scelto*. La elección es *la scelta*: *non ho scelta*."],
        ["ragione", "razón", "Alla fine hai avuto ragione tu.",
         "«Tener razón» se arma con *avere*: *hai ragione*; lo contrario es *avere torto*. *Dare ragione a qualcuno* = darle la razón."],
        ["scorso", "pasado (anterior)", "L'anno scorso sono andato in Sicilia.",
         "Va después del sustantivo y concuerda: *l'anno scorso*, *la settimana scorsa*, *il mese scorso*. Es el último, el recién pasado."],
        ["viaggiare", "viajar", "L'anno scorso ho viaggiato molto.",
         "Pasado con *avere*: *ho viaggiato*. «Viajar al exterior» = *viaggiare all'estero*. El sustantivo es *il viaggio*: *buon viaggio!*"],
        ["vincere", "ganar (competencia)", "Ieri ho vinto cinquanta euro.",
         "Participio irregular *vinto*. Se gana un partido, un premio, la lotería; «ganar plata» trabajando es *guadagnare* (semana 20)."],
        ["perdere", "perder", "Ho perso il treno e sono arrivato tardi.",
         "Participio *perso* (o *perduto*). *Perdere il treno* = perder el tren. *Perdersi* = perderse (en una ciudad)."],
        ["succedere", "pasar, suceder", "Che cosa è successo?",
         "Con *essere*: *è successo*. Es el «pasar» de los hechos: *cosa succede?* (¿qué pasa?). «Pasar» por un lugar es *passare*."],
        ["assaggiare", "probar (comida)", "Hai assaggiato il tiramisù?",
         "Es probar un poco de una comida: *assaggia!*. Probarse ropa o intentar es *provare*. Doble *s* y doble *g*."],
        ["gita", "excursión, paseo", "Domenica abbiamo fatto una gita al lago.",
         "*Fare una gita* = hacer una excursión de un día. *Gita scolastica* = viaje de estudios. No es «gira» (eso es *tournée* o *giro*)."],
        ["spiaggia", "playa", "Siamo stati in spiaggia tutto il giorno.",
         "*In spiaggia* = en la playa. Plural *spiagge*. *Andare al mare* es ir a la costa; *la spiaggia* es la arena."],
        ["ponte", "puente", "Abbiamo attraversato il ponte a piedi.",
         "Masculino en *-e*: *il ponte*. *Fare il ponte* es juntar un feriado con el fin de semana: un «fin de semana largo»."],
        ["chiudere", "cerrar", "Ho chiuso la porta a chiave.",
         "Participio irregular *chiuso*. *Chiudere a chiave* = cerrar con llave. *Il negozio è chiuso* = está cerrado. Abrir es *aprire* (*aperto*)."],
        ["passare", "pasar", "Ho passato una bella serata con gli amici.",
         "Con *avere* si pasás algo (*ho passato il weekend a Roma*); con *essere* si pasás por un lugar (*sono passato da te*). *Passare a prendere* = pasar a buscar."],
        ["divertente", "divertido", "Il film è stato molto divertente.",
         "Una sola forma para los dos géneros: *un film divertente*, *una serata divertente*. Divertirse es *divertirsi*: *ci siamo divertiti*."],
        ["giro", "vuelta, paseo", "Abbiamo fatto un giro in centro.",
         "*Fare un giro* = dar una vuelta. *In giro* = por ahí. *Prendere in giro* = cargar, tomar el pelo."],
        ["mettere", "poner", "Dove hai messo le chiavi?",
         "Participio irregular *messo*. *Mettere in ordine* = ordenar. Ponerse ropa es *mettersi* (semana 16): *mi metto la giacca*."],
        ["leggere", "leer", "Hai letto il giornale oggi?",
         "Participio irregular *letto*, igual que *il letto* (la cama). *Leggo, leggi*: *gg* suena «ch» ante *e*, *i* y «g» dura ante *o*."],
    ],
    12: [
        ["alzarsi", "levantarse", "Mi alzo alle sette ed esco di casa alle otto.",
         "Pronominal: *mi alzo, ti alzi, si alza*; pasado *mi sono alzato/a* (semana 16). Sin *si*, *alzare* es levantar algo: *alzare la mano*."],
        ["svegliarsi", "despertarse", "A che ora ti svegli?",
         "Pronominal: *mi sveglio*. Sin *si*: *svegliare qualcuno* (despertar a alguien). El despertador es *la sveglia*."],
        ["addormentarsi", "dormirse, quedarse dormido", "Mio nonno si addormenta sempre dopo pranzo.",
         "Pronominal: *mi addormento*. Es empezar a dormir. «Quedarse dormido» a la mañana, llegar tarde: *non ho sentito la sveglia*."],
        ["fermarsi", "pararse, detenerse", "Il treno si ferma a Bologna.",
         "Pronominal: *mi fermo*. Con infinitivo pide *a*: *mi fermo a mangiare*. Sin *si*, *fermare* es parar algo o a alguien: *ferma la macchina!*"],
        ["sposarsi", "casarse", "Lei si sposa domani.",
         "Pronominal: *si sposano*; en pasado, *si sono sposati*. «Casarse con» = *sposarsi con* o *sposare qualcuno*: *ha sposato Luca*."],
        ["arrabbiarsi", "enojarse", "Mio padre si arrabbia quando arrivo tardi.",
         "Pronominal y con *con* para la persona: *si arrabbia con me*. «Estar enojado» = *essere arrabbiato*. Doble *b*."],
        ["sentirsi", "sentirse", "Oggi non mi sento bene.",
         "Pronominal: *mi sento bene / male / stanco*. Sin *si*, *sentire* es oír o sentir algo: *senti freddo?*"],
        ["scendere", "bajar", "Scendo alla prossima fermata.",
         "Participio irregular *sceso*, con *essere*: *sono sceso*. *Scendere dal treno*; *scendere le scale* (bajar la escalera, transitivo)."],
        ["tenere", "tener (en la mano), sostener; guardar", "Tieni, questo è per te.",
         "Irregular: *tengo, tieni, tiene... tengono*. No es el «tener» de posesión (eso es *avere*): es sostener o guardar. *Tieni!* = ¡tomá!"],
        ["ritardo", "demora, retraso", "Il treno è in ritardo.",
         "*Essere in ritardo* = llegar tarde, estar atrasado. *Scusa il ritardo* = perdón por la demora. Lo contrario: *in anticipo*."],
        ["solito", "de siempre, habitual", "Di solito mi sveglio presto.",
         "*Di solito* = generalmente. *Il solito* = lo de siempre (en el bar). *Come al solito* = como siempre."],
        ["domenica", "domingo", "La domenica mangiamo dai nonni.",
         "Sin artículo es «este domingo»: *domenica vado al mare*. Con artículo es «los domingos»: *la domenica*. Minúscula."],
        ["testa", "cabeza", "Mi fa male la testa.",
         "*Avere mal di testa* = tener dolor de cabeza; igual *mal di gola*, *mal di schiena*. *Di testa mia* = por mi cuenta. «Cabeza» no es *capo*, salvo en frases hechas (*da capo*)."],
        ["gola", "garganta", "Mi fa male la gola.",
         "*Mi fa male la gola* = me duele la garganta; *avere mal di gola*. *Gola* es también la gula: *peccato di gola*."],
        ["schiena", "espalda", "Dopo il lavoro mi fa male la schiena.",
         "Femenino: *la schiena*. *Mal di schiena* = dolor de espalda. *Schiena* suena «squiena»: *sch* = «sk»."],
        ["raffreddore", "resfrío", "Ho il raffreddore: resto a casa.",
         "Se tiene con *avere* y artículo: *ho il raffreddore*. Viene de *freddo* (frío). La gripe es *l'influenza*."],
        ["doccia", "ducha", "La mattina mi faccio la doccia.",
         "*Farsi la doccia* (o *fare la doccia*) = ducharse. Plural *docce*. El baño de inmersión es *il bagno*: *farsi il bagno*."],
        ["letto", "cama", "Stasera vado a letto presto.",
         "*Andare a letto* = irse a dormir, sin artículo. *Letto* también es el participio de *leggere*: *ho letto un libro*."],
        ["stanco", "cansado", "Sono stanco: vado a dormire.",
         "*Stanco, stanca, stanchi, stanche*, con *h* en plural. *Stanco morto* = muerto de cansancio. Cansarse es *stancarsi*."],
    ],
    14: [
        ["mancare", "faltar; extrañar", "Mi manca l'Italia.",
         "Funciona como *piacere*: lo que se extraña es el sujeto. *Mi manca l'Italia* (extraño Italia), *mi mancano i miei*. Pasado con *essere*: *mi è mancata*."],
        ["sembrare", "parecer", "Questa pizza mi sembra buona.",
         "Como *piacere*: *mi sembra giusto*. Con infinitivo, sin preposición: *sembra stanco*. *Sembra che* + congiuntivo llega en la semana 25."],
        ["dispiacere", "lamentar; molestar", "Mi dispiace, stasera non posso venire.",
         "Se usa como *piacere*: *mi dispiace* = lo siento. *Ti dispiace se apro la finestra?* = ¿te molesta si abro la ventana? Pasado con *essere*."],
        ["passeggiata", "paseo, caminata", "Ho fatto una passeggiata in centro.",
         "Se arma con *fare*: *fare una passeggiata* = salir a caminar. El verbo es *passeggiare*. La *passeggiata* de la tarde es un rito en muchos pueblos."],
        ["pesce", "pescado; pez", "Non mi piace il pesce.",
         "Masculino en *-e*: *il pesce*, plural *i pesci*. Es pescado y pez: no hay dos palabras. *Pesce d'aprile* = broma del 1.º de abril."],
        ["cibo", "comida (alimento)", "Mi piace il cibo italiano.",
         "Es la comida como alimento. La comida del mediodía es *il pranzo*; «hacer la comida» es *cucinare*."],
        ["gelato", "helado", "Mi piace il gelato al cioccolato.",
         "El sabor va con *a* + artículo: *al cioccolato*, *alla fragola*. Se pide *un cono* o *una coppetta* con *due gusti*. El local es *la gelateria*."],
        ["canzone", "canción", "Mi piace molto questa canzone.",
         "Femenino en *-e*: *la canzone*, plural *le canzoni*. El cantautor es *il cantautore*."],
        ["piscina", "pileta (de natación)", "Ai miei figli piace la piscina.",
         "Es la palabra común para la pileta. *Andare in piscina*, sin artículo. Nadar es *nuotare*."],
        ["cioè", "o sea, es decir", "Vengo tra un'ora, cioè alle sei.",
         "Aclara o corrige lo que acabás de decir. En la charla también es muletilla para ganar tiempo: *cioè... non lo so*. Lleva tilde en la *e*."],
        ["ballare", "bailar", "Ti piace ballare?",
         "Doble *l*. El baile es *il ballo*; el bailarín, *il ballerino*. *Andare a ballare* = ir a bailar."],
        ["suonare", "tocar (un instrumento); sonar", "Mio fratello suona la chitarra.",
         "Los instrumentos se tocan con *suonare*, no con *toccare*: *suono il piano*. También suena el timbre o el teléfono: *suona il telefono*."],
        ["squadra", "equipo", "Qual è la tua squadra preferita?",
         "Es el equipo deportivo y el de trabajo: *lavoro di squadra*. No es «escuadra» (eso es un instrumento de dibujo)."],
        ["partita", "partido (deportivo)", "Stasera guardiamo la partita al bar.",
         "Es el partido que se juega o se mira: *una partita di calcio*, *a carte*. Un partido político es *un partito*, con *o*."],
        ["tifoso", "hincha", "Sono tifoso della Roma.",
         "*Fare il tifo per* = hinchar por. *I tifosi* = la hinchada. Viene de *tifo*, que también es la fiebre tifoidea."],
        ["nuotare", "nadar", "D'estate mi piace nuotare al mare.",
         "Regular: *nuoto, nuoti*. El nado es *il nuoto*. Bañarse en el mar es *fare il bagno*."],
        ["tranne", "excepto, menos", "Mi piacciono tutti gli sport tranne il calcio.",
         "Invariable, delante de lo que se excluye: *tutti tranne me*. Sinónimo: *a parte*, *eccetto*."],
        ["volentieri", "con gusto", "Vieni al cinema? — Volentieri!",
         "La forma natural de aceptar una invitación: *Volentieri!*. Adverbio, no cambia. Para rechazar con cortesía: *mi dispiace, ma...*"],
        ["annoiarsi", "aburrirse", "Al museo i bambini si annoiano.",
         "Pronominal: *mi annoio*. Lo que aburre es *noioso* (semana 23): *un film noioso*. Estar aburrido: *essere annoiato*."],
    ],
    15: [
        ["bambino", "nene, niño", "Da bambino giocavo sempre in cortile.",
         "*Da bambino* = de chico, cuando era chico. Femenino *bambina*. Con *avere* para las sensaciones: *il bambino ha fame*, *ha sonno*."],
        ["giocare", "jugar", "Da piccoli giocavamo nel parco.",
         "Deportes y juegos piden *a*: *giocare a calcio*, *a carte*. Los instrumentos no se «juegan»: *suonare la chitarra*."],
        ["calcio", "fútbol; patada", "Da ragazzo giocavo a calcio.",
         "Se juega *a calcio*. También es la patada (*dare un calcio*) y el calcio, el mineral. El jugador es *il calciatore*."],
        ["pallone", "pelota (grande)", "Giocavamo a pallone in piazza.",
         "La pelota de fútbol o de básquet; la chica es *la palla*. *Giocare a pallone* = jugar a la pelota."],
        ["paura", "miedo", "Da piccola avevo paura dei cani.",
         "Se arma con *avere*: *ho paura dei cani*. Con infinitivo pide *di*: *ho paura di sbagliare*. *Fare paura* = dar miedo."],
        ["malato", "enfermo", "Non sono andato a scuola perché ero malato.",
         "*Essere malato* = estar enfermo; enfermarse es *ammalarsi*. La enfermedad es *la malattia*."],
        ["povero", "pobre", "Povero Luca, ha perso il treno!",
         "Antes del sustantivo es de lástima (*povero Luca!*); después, de plata (*un uomo povero*)."],
        ["donna", "mujer", "Quella donna era la mia maestra.",
         "Plural *donne*. *Donna* no es título de cortesía: «señora» es *signora*. La mujer como esposa es *la moglie*."],
        ["vacanza", "vacaciones", "D'estate eravamo sempre in vacanza al mare.",
         "*Essere* o *andare in vacanza*, sin artículo. En plural es el período: *le vacanze di Natale*. Las vacaciones del trabajo también son *le ferie* (semana 19)."],
        ["purtroppo", "lamentablemente, por desgracia", "Purtroppo non posso venire alla festa.",
         "Suele abrir la frase: *purtroppo no*. Es de todos los días, no formal. Lo contrario: *per fortuna*."],
        ["paese", "pueblo; país", "Mio nonno abitava in un piccolo paese.",
         "Tiene los dos sentidos: *un paese di montagna* (un pueblo) y *l'Italia è un bel paese* (un país). El contexto decide."],
        ["albero", "árbol", "In giardino c'era un albero grande.",
         "Esdrújula: *àlbero*. *Albero di Natale* = arbolito de Navidad. *Albero genealogico*."],
        ["cortile", "patio", "Il pomeriggio giocavamo in cortile.",
         "Es el patio de la casa, del edificio o de la escuela. *In cortile*, sin artículo."],
        ["barca", "bote, barco chico", "Mio nonno aveva una barca.",
         "Es el bote de remo o a vela; el barco grande es *la nave*. *Andare in barca* = salir en bote."],
        ["maestra", "maestra (de primaria)", "La mia maestra era molto simpatica.",
         "*Il maestro*, *la maestra*: de la escuela primaria (*le elementari*). Desde la secundaria es *il professore*, *la professoressa*."],
        ["compito", "tarea (escolar); deber", "Facevo i compiti dopo pranzo.",
         "*I compiti* (en plural) = la tarea del colegio; *fare i compiti*. En singular es la tarea o la obligación: *è il mio compito*. Esdrújula: *còmpito*."],
        ["voto", "nota (calificación); voto", "A scuola prendevo sempre bei voti.",
         "*Prendere un bel voto* = sacarse una buena nota. En Italia se califica del 1 al 10 y en la universidad hasta 30. También es el voto electoral."],
        ["raccontare", "contar (una historia)", "La nonna raccontava sempre molte storie.",
         "Es contar algo que pasó o una historia: *raccontami tutto!*. Contar números es *contare*. El relato es *il racconto*."],
        ["nascere", "nacer", "Sono nato a Rosario nel 1990.",
         "Pasado con *essere* y participio irregular: *sono nato/a*. *Dove sei nato?* El nacimiento es *la nascita*."],
    ],
    16: [
        ["dimenticare", "olvidar", "Ho dimenticato le chiavi a casa.",
         "Solo o pronominal: *ho dimenticato le chiavi* / *mi sono dimenticato delle chiavi*. Con infinitivo pide *di*: *ho dimenticato di chiamarti*."],
        ["bravo", "bueno (en algo), capo", "Marco è un bravo studente.",
         "No es «bravo» de enojado: es bueno en lo que hace. *Bravo in matematica*, *un bravo cuoco*. *Bravo!* felicita. «Enojado» es *arrabbiato*."],
        ["stamattina", "esta mañana", "Stamattina mi sono alzato presto.",
         "Contracción de *questa mattina*, como *stasera* y *stanotte*. Va sin preposición."],
        ["stanotte", "esta noche; anoche", "Stanotte ho dormito male.",
         "Es la noche de hoy o la que acaba de pasar: el tiempo verbal lo aclara. *Stanotte dormo da Marco* (esta noche); *stanotte ho dormito male* (anoche)."],
        ["fretta", "apuro", "Anna si è vestita in fretta.",
         "*Avere fretta* = estar apurado; *in fretta* = rápido, a las apuradas. *Non c'è fretta* = no hay apuro."],
        ["sveglia", "despertador", "Stamattina non ho sentito la sveglia.",
         "*Mettere la sveglia* = poner el despertador; *suona la sveglia*. *Sveglia!* = ¡despertate! Despertarse es *svegliarsi*."],
        ["corsa", "carrera, corrida", "Mi sono vestito e sono uscito di corsa.",
         "*Di corsa* = a las corridas, corriendo. *Fare una corsa* = salir a correr. De *correre* (correr), participio *corso*."],
        ["buio", "oscuro; oscuridad", "Quando siamo tornati era già buio.",
         "Adjetivo y sustantivo: *è buio* (está oscuro), *ho paura del buio*. Suena «búio»."],
        ["piovere", "llover", "Ieri è piovuto tutto il giorno.",
         "Verbo del tiempo: *piove*, *pioveva*. En pasado vale *è piovuto* o *ha piovuto*. La lluvia es *la pioggia*."],
        ["farsi la barba", "afeitarse", "Stamattina non mi sono fatto la barba.",
         "Se arma con *farsi*: *mi faccio la barba*, *mi sono fatto la barba*. Como *farsi la doccia*."],
        ["truccarsi", "maquillarse", "Giulia si è truccata in cinque minuti.",
         "Pronominal: *mi trucco*. El maquillaje es *il trucco*, que también es «truco»."],
        ["mettersi", "ponerse (ropa); ponerse a", "Mi sono messo la giacca e sono uscito.",
         "La ropa va con artículo, no con posesivo: *mi metto il cappotto*. *Mettersi a* + infinitivo = ponerse a: *si è messa a ridere*. Participio *messo*."],
        ["togliersi", "sacarse (ropa)", "Mi sono tolto le scarpe.",
         "Irregular: *mi tolgo, ti togli, si toglie... si tolgono*; participio *tolto*. Sin *si*, *togliere* es sacar algo: *togli il libro dal tavolo*."],
        ["sbrigarsi", "apurarse", "Sbrigati, il treno parte!",
         "Pronominal: *mi sbrigo*. *Sbrigati!* = ¡apurate! En *ti sbrighi* la *h* mantiene el sonido «g»."],
        ["trovarsi", "estar; sentirse (en un lugar)", "A Bologna mi sono trovato bene.",
         "*Trovarsi bene* = sentirse a gusto, pasarla bien en un lugar o con alguien. También «estar ubicado»: *dove si trova la stazione?*"],
        ["innamorarsi", "enamorarse", "Si sono innamorati a Parigi.",
         "Rige *di*: *innamorarsi di qualcuno*, no «con». Pasado con *essere*. *Essere innamorato* = estar enamorado."],
        ["rompersi", "romperse", "Luca si è rotto un braccio.",
         "Participio irregular *rotto*. Una parte del cuerpo va con artículo: *mi sono rotto la gamba*. *Rompere* sin *si*: romper algo."],
        ["braccio", "brazo", "Mi fa male il braccio.",
         "Plural irregular y femenino: *le braccia*. Lo mismo con *il dito* → *le dita* y *il ginocchio* → *le ginocchia*."],
        ["gamba", "pierna", "Mi sono fatto male alla gamba.",
         "*Farsi male a* = lastimarse. *In gamba* = capo, muy capaz: *è una ragazza in gamba*."],
        ["stancarsi", "cansarse", "Mi sono stancato di aspettare.",
         "Pronominal y con *di* + infinitivo: *mi stanco di aspettare*. En *ti stanchi* la *h* mantiene el sonido «k». *Stanco* = cansado."],
    ],
    17: [
        ["figlio", "hijo", "Mio figlio ha dieci anni.",
         "Plural *figli* (hijos varones o mixtos); *figlia* = hija. Con posesivo, singular sin artículo (*mio figlio*) y plural con artículo (*i miei figli*)."],
        ["marito", "marido", "Mio marito lavora in banca.",
         "Con posesivo y en singular, sin artículo: *mio marito*. La esposa es *la moglie*. *Il mio compagno* = mi pareja."],
        ["moglie", "esposa", "Mia moglie è di Napoli.",
         "Plural irregular: *le mogli*. Con posesivo, sin artículo: *mia moglie*. *Prendere moglie* = casarse (el hombre)."],
        ["fratello", "hermano", "Hai dei fratelli?",
         "Plural *fratelli*, que también vale para hermanos y hermanas juntos. Con posesivo en singular, sin artículo: *mio fratello*."],
        ["sorella", "hermana", "Mia sorella ha due figli.",
         "Plural *sorelle*. Con posesivo en singular, sin artículo: *mia sorella*; con diminutivo sí: *la mia sorellina*."],
        ["nonno", "abuelo", "Mio nonno ha novant'anni.",
         "*La nonna* = la abuela; *i nonni* = los abuelos. Con posesivo en singular, sin artículo: *mio nonno*."],
        ["cugino", "primo", "Mio cugino ha vent'anni.",
         "Falso amigo: *primo* en italiano es «primero». Primo es *cugino*; prima, *cugina*."],
        ["nipote", "sobrino; nieto", "Mio nipote è molto simpatico.",
         "Sirve para sobrino/a y para nieto/a: el contexto decide. *Il nipote*, *la nipote*, plural *i nipoti*."],
        ["zio", "tío", "Lo zio di Marco abita a Torino.",
         "El artículo es *lo* por la *z*: *lo zio*, plural *gli zii* (doble *i*). *La zia*, *le zie*."],
        ["suocera", "suegra", "Mia suocera cucina molto bene.",
         "*Il suocero* = el suegro; *i suoceri* = los suegros. Cuñado es *il cognato*; yerno y nuera, *il genero* y *la nuora*."],
        ["parente", "pariente", "A Natale vengono tutti i parenti.",
         "Falso amigo del inglés: *parenti* son los parientes, no los padres (esos son *i genitori*). *Un mio parente* = un pariente mío."],
        ["bisogno", "necesidad", "Ognuno ha bisogno di affetto.",
         "Se arma con *avere*: *ho bisogno di* + cosa o infinitivo. *C'è bisogno di* = hace falta. *Se hai bisogno, chiamami*."],
        ["giornata", "día (como duración)", "Che bella giornata!",
         "Es el día vivido, de la mañana a la noche: *buona giornata!*, *tutta la giornata*. *Giorno* es la unidad del calendario."],
        ["lasciare", "dejar", "Ho lasciato le chiavi a casa.",
         "Dejar algo o a alguien: *ho lasciato Marco*. Con infinitivo, sin preposición: *lasciami parlare*. «Dejar de» es *smettere di*."],
        ["cane", "perro", "Questo cane è di mia sorella.",
         "Masculino en *-e*: *il cane*, plural *i cani*. *Fa un freddo cane* = hace un frío de perros."],
        ["camera", "habitación, dormitorio", "La mia camera è piccola ma bella.",
         "*La camera (da letto)* es el dormitorio; en un hotel, *una camera doppia*. Falso amigo: la cámara de fotos es *la macchina fotografica*."],
        ["bagno", "baño", "La casa ha due bagni.",
         "El cuarto y también el baño de inmersión o en el mar: *fare il bagno*. *Andare in bagno*, sin artículo."],
        ["divano", "sofá, sillón", "Questo divano è molto comodo.",
         "El sofá del living; el sillón individual es *la poltrona*. *Stare sul divano* = estar tirado en el sillón."],
        ["armadio", "ropero, placard", "I vestiti sono nell'armadio.",
         "Masculino: *l'armadio*, plural *gli armadi*. Los muebles son *i mobili*."],
        ["piano", "piso (de un edificio); despacio", "Abitiamo al terzo piano.",
         "Falso amigo: *piano* es el piso de un edificio (*al terzo piano*); el piso del suelo es *il pavimento*. Como adverbio, «despacio»: *parla piano*."],
    ],
    18: [
        ["spiegare", "explicar", "Non spiega mai niente.",
         "Se explica algo *a* alguien: *spiegami*, *gli spiego*. En *tu spieghi* la *h* mantiene el sonido «g»."],
        ["magari", "¡ojalá!; quizás", "Magari domani non piove!",
         "Solo, como respuesta, es «¡ojalá!». En la charla también es «a lo mejor»: *magari vengo*. Con congiuntivo imperfetto expresa deseo (semana 30)."],
        ["peccato", "¡qué lástima!", "Non puoi venire? Che peccato!",
         "*Che peccato!* o *Peccato!* = ¡qué lástima! Literal es «pecado»."],
        ["figurati", "¡por favor!, ¡de nada!", "Grazie mille! — Figurati!",
         "Imperativo de *figurarsi*: responde a un gracias o a una disculpa, como «¡no es nada!». Con usted: *si figuri*."],
        ["forza", "fuerza; ¡vamos!", "Forza, manca poco!",
         "*Forza!* anima (¡vamos!). *Per forza* = a la fuerza, obvio: *Per forza! Ho lavorato dodici ore*."],
        ["boh", "ni idea", "Dov'è Marco? — Boh, non lo so.",
         "Interjección coloquial de «ni idea», con encogida de hombros. Solo en la charla con amigos: con un desconocido, *non lo so*."],
        ["meraviglia", "maravilla", "Che meraviglia di casa!",
         "*Che meraviglia!* = ¡qué maravilla! *A meraviglia* = de maravilla. Con *di*: *che meraviglia di casa!*"],
        ["sbadato", "distraído, despistado", "Come sei sbadato!",
         "El que se olvida todo, por costumbre. La *s-* inicial niega o invierte, como en *sfortunato*."],
        ["spendere", "gastar (plata)", "Non spendo mai niente al bar.",
         "Participio irregular *speso*. Solo para plata: «gastar» energía o tiempo se dice *usare*, *perdere tempo*. El gasto es *la spesa*."],
        ["soldi", "plata (dinero)", "Non ho più soldi.",
         "Se usa en plural: *i soldi* (la plata). *Il denaro* es más formal. *Essere senza soldi* = estar sin plata."],
        ["portafoglio", "billetera", "Non trovo più il portafoglio!",
         "De *portare* + *foglio*. Plural *portafogli*. La cartera de mujer es *la borsa*."],
        ["spesa", "compras (de comida); gasto", "Non ho fatto la spesa: non c'è niente in frigo.",
         "*Fare la spesa* = hacer las compras del súper. *Fare spese* = ir de shopping. En singular también es el gasto: *spese di casa*."],
        ["fame", "hambre", "Non ho ancora fame.",
         "Con *avere*, como en castellano: *ho fame*, *ho una fame da lupi* (tengo un hambre de lobo). Femenino en *-e*: *la fame*."],
        ["mica", "para nada, ni (refuerza el no)", "Non è mica facile!",
         "Coloquial: refuerza la negación. *Non è mica vero* = no es para nada cierto. Sin *non* al principio: *mica male!* = ¡nada mal!"],
        ["dai", "¡dale!, ¡vamos!", "Dai, vieni con noi!",
         "Del verbo *dare*, se usa para animar o insistir: *dai, andiamo!*. También para no creer: *ma dai!* = ¡no te puedo creer!"],
        ["accidenti", "¡caramba!, ¡uy!", "Accidenti, ho perso l'autobus!",
         "Enojo o sorpresa, sin grosería. Con la misma idea, más coloquial: *mannaggia!*."],
        ["meno male", "menos mal", "Meno male! Sei arrivato.",
         "Igual que en castellano: *meno male!*, *meno male che* + indicativo. Otra forma de alivio: *per fortuna*."],
        ["davvero", "de verdad; ¿en serio?", "Davvero? Non lo sapevo.",
         "Sola es «¿en serio?». Dentro de la frase refuerza: *è davvero bravo*. Sinónimo: *veramente*."],
        ["certo", "¡claro!; cierto", "Vieni anche tu? — Certo!",
         "Solo, es «¡claro!». Antes del sustantivo es «cierto»: *un certo signore*. *Di certo* = seguro."],
        ["schifo", "asco", "Che schifo, questo caffè è freddo!",
         "Coloquial: *che schifo!* = ¡qué asco! *Fare schifo* = ser horrible: *il film fa schifo*. Solo entre conocidos."],
    ],
    19: [
        ["sicuro", "seguro", "Domani pioverà di sicuro.",
         "*Di sicuro* = seguro, sin duda. *Essere sicuro di* + infinitivo o *che*: *sono sicuro che verrà*. También es «a salvo»: *un posto sicuro*."],
        ["almeno", "por lo menos", "Avrà almeno sessant'anni.",
         "Una sola palabra. Con el futuro, suposición: *avrà almeno sessant'anni* (debe de tener). *Almeno tu!* = ¡por lo menos vos!"],
        ["benzina", "nafta", "Se mi presti la macchina, ti pago la benzina.",
         "*Fare benzina* = cargar nafta. *Rimanere senza benzina*. El que atiende la estación de servicio es *il benzinaio*."],
        ["sciopero", "huelga, paro", "Domani ci sarà uno sciopero dei treni.",
         "Esdrújula: *sciòpero*. *Fare sciopero*, *essere in sciopero*. Muy frecuente en las noticias de transporte."],
        ["incidente", "accidente (de tránsito), choque", "Avrà avuto un incidente.",
         "Es sobre todo el choque o el accidente: *avere un incidente*. Un incidente menor, un problema, es *un inconveniente*."],
        ["stipendio", "sueldo", "Lo stipendio arriverà il ventisette.",
         "Plural *stipendi*. El artículo es *lo* por *s* + consonante. *Prendere lo stipendio*; *aumento di stipendio*."],
        ["sistemare", "arreglar, acomodar", "Domani sistemerò la camera.",
         "Es ordenar o resolver: *sistemare la camera*, *sistemare una faccenda*. *Sistemarsi* = instalarse, acomodarse en la vida."],
        ["colloquio", "entrevista (de trabajo)", "Lunedì avrò un colloquio di lavoro.",
         "*Colloquio di lavoro* = entrevista de trabajo. La de un periodista es *l'intervista*. *Fare un colloquio*."],
        ["azienda", "empresa", "Lavorerò in un'azienda di Modena.",
         "La palabra común para «empresa»: *un'azienda agricola*, *un'azienda di moda*. *Impresa* también existe y es más formal."],
        ["capo", "jefe; cabeza", "Il mio capo sarà in vacanza fino a lunedì.",
         "*Il capo* es el jefe, también en femenino: *la capo*. En frases hechas es «cabeza»: *da capo* = desde el principio; *andare a capo* = punto y aparte."],
        ["dipendente", "empleado", "L'azienda ha cinquanta dipendenti.",
         "Es el que trabaja en relación de dependencia: *un dipendente pubblico*. Como adjetivo, «dependiente»: *dipendente da*."],
        ["assumere", "contratar, tomar (personal)", "L'azienda assumerà dieci persone.",
         "Falso amigo: *assumere* es tomar a alguien para un trabajo; participio *assunto*. «Asumir» una responsabilidad también: *assumersi la responsabilità*."],
        ["ferie", "vacaciones (del trabajo)", "Ad agosto andrò in ferie.",
         "Siempre en plural: *le ferie*, *andare in ferie*. Son los días de licencia del trabajo; *le vacanze* es más general."],
        ["albergo", "hotel", "Dormiremo in un albergo vicino al mare.",
         "Sinónimo de *hotel*, muy común. Plural *alberghi*, con *h*. Un hotel chico y barato es *una pensione*."],
        ["estero", "exterior (el extranjero)", "L'anno prossimo andrò a lavorare all'estero.",
         "*All'estero* = en o al exterior, siempre con artículo. Como adjetivo: *politica estera*. El extranjero como persona es *lo straniero*."],
        ["traghetto", "ferry, barco (de pasajeros)", "Prenderemo il traghetto per la Sardegna.",
         "El barco que cruza a las islas con autos y pasajeros. *Prendere il traghetto*. Doble *g*."],
        ["prenotare", "reservar", "Domani prenoterò i biglietti.",
         "*Prenotare un tavolo, una camera, una visita*. La reserva es *la prenotazione*. «Reservar» en el sentido de guardar es *tenere da parte*."],
        ["ombrello", "paraguas", "Prendi l'ombrello: pioverà.",
         "*L'ombrello*, plural *gli ombrelli*. La sombrilla de playa es *l'ombrellone*. Doble *l*."],
        ["forse", "quizás, tal vez", "Forse domani verrò anch'io.",
         "Va con el indicativo, a menudo con el futuro: *forse verrò*. *Forse sì, forse no*. En la charla también *magari*."],
        ["inquinare", "contaminar", "Le macchine inquinano l'aria della città.",
         "Transitivo: *inquinare l'aria*, *il mare*. Participio *inquinato*; la contaminación es *l'inquinamento*."],
    ],
    20: [
        ["caldo", "calor; caliente", "Fa caldo: vorrei un gelato.",
         "Adjetivo (*il caffè è caldo*) y sustantivo: *fa caldo* (hace calor), *ho caldo* (tengo calor). Falso amigo: no es «caldo» (eso es *brodo*)."],
        ["riposare", "descansar", "Dovresti riposare di più.",
         "Solo o pronominal: *riposare* o *riposarsi*. El descanso es *il riposo*. *Riposati!* = ¡descansá!"],
        ["ormai", "ya (a esta altura)", "Ormai è tardi: dovremmo andare.",
         "Marca que algo ya es un hecho y no tiene vuelta: *ormai è fatta*. Distinto de *già* (ya, antes de lo esperado)."],
        ["veramente", "en realidad; realmente", "Veramente preferirei restare a casa.",
         "Al principio matiza o corrige con suavidad: *veramente, non sono d'accordo*. Dentro de la frase refuerza: *è veramente bello*."],
        ["passaggio", "aventón (en auto); paso", "Mi daresti un passaggio in centro?",
         "*Dare un passaggio a qualcuno* = llevarlo en auto. *Mi dai un passaggio?* = ¿me alcanzás? También es el paso: *di passaggio*."],
        ["appuntamento", "cita; turno", "Verrei volentieri, ma ho un appuntamento.",
         "Cualquier cita: con amigos, con el médico, con el novio. *Prendere un appuntamento* = sacar turno; *ho appuntamento dal dentista*."],
        ["leggero", "liviano", "Stasera vorrei una cena leggera.",
         "Liviano de peso y de comida. También suave: *un vino leggero*. Lo contrario es *pesante*."],
        ["guadagnare", "ganar (plata)", "Vorrei guadagnare di più.",
         "Es ganar trabajando: *guadagnare bene*. Ganar un partido o un premio es *vincere*. La ganancia es *il guadagno*."],
        ["pendolare", "persona que viaja cada día al trabajo", "Non vorrei più fare il pendolare.",
         "Sustantivo y adjetivo: *i pendolari* son los que viajan todos los días de otra ciudad al trabajo en tren. *Fare il pendolare*."],
        ["tramonto", "atardecer, puesta del sol", "Mi piacerebbe vedere il tramonto dalla terrazza.",
         "*Al tramonto* = al atardecer. El amanecer es *l'alba*. Verbo: *il sole tramonta*."],
        ["trasferirsi", "mudarse (a otra ciudad)", "Mi piacerebbe trasferirmi al mare.",
         "Es irse a vivir a otro lugar: *trasferirsi a Milano*. Mudarse de casa en la misma ciudad es *traslocare* o *cambiare casa*."],
        ["scrivania", "escritorio (mueble)", "Potrebbe lasciare i documenti sulla scrivania?",
         "Es el mueble. El escritorio como oficina es *lo studio* o *l'ufficio*."],
        ["stampare", "imprimir", "Potrei stampare questo documento?",
         "La impresora es *la stampante*; *la stampa* es la impresión y también la prensa (los diarios)."],
        ["bagaglio", "equipaje", "Potrebbe tenere il bagaglio fino alle due?",
         "Es el equipaje: *bagaglio a mano* = equipaje de mano. Plural *bagagli*. La valija es *la valigia*."],
        ["servire", "servir; hacer falta", "Le serve una penna?",
         "Como *piacere* cuando es «hacer falta»: *mi serve una penna* (necesito una lapicera), *ti servono soldi?*. Con *a*: *a cosa serve?* = ¿para qué sirve?"],
        ["gradire", "apreciar, aceptar con gusto", "Gradirebbe un caffè?",
         "Muy formal, para ofrecer: *gradisce qualcosa da bere?*. En cartas: *gradirei una risposta* = le agradecería una respuesta. Verbo en *-isc-*."],
        ["cortesia", "cortesía", "Per cortesia, potrebbe chiudere la finestra?",
         "*Per cortesia* = por favor, un poco más formal que *per favore*. *Fare una cortesia* = hacer un favor."],
        ["sconto", "descuento", "Mi farebbe uno sconto?",
         "*Fare uno sconto*; *uno sconto del dieci per cento*. El artículo es *uno* por *s* + consonante. Las liquidaciones son *i saldi*."],
        ["contanti", "efectivo", "Preferirei pagare in contanti.",
         "Siempre en plural: *pagare in contanti*. Con tarjeta: *con la carta*. El cajero automático es *il bancomat*."],
        ["accomodarsi", "ponerse cómodo; pasar, sentarse", "Vuole accomodarsi, signora?",
         "Invita a pasar o sentarse: *si accomodi!* (usted), *accomodati!* (vos). Muy usado en oficinas y consultorios."],
    ],
    21: [
        ["riuscire", "lograr, poder", "Non riesco a dormire.",
         "Con infinitivo pide *a*: *riesco a finire*. Se conjuga como *uscire*: *riesco, riesci*. Pasado con *essere*: *sono riuscito*. Es «poder» cuando cuesta."],
        ["abituarsi", "acostumbrarse", "Mi sono abituato al caffè senza zucchero.",
         "Pronominal y pide *a*: *abituarsi al freddo*, *a vivere da soli*. Con *ci*: *mi ci sono abituato*. Costumbre: *l'abitudine*."],
        ["abbastanza", "bastante; suficiente", "Ne ho abbastanza.",
         "Invariable. Antes de adjetivo, «bastante»: *abbastanza bravo*. *Ne ho abbastanza* = estoy harto, ya tengo suficiente."],
        ["palestra", "gimnasio", "Vai in palestra? — Sì, ci vado ogni giorno.",
         "*Andare in palestra*, sin artículo. Falso amigo: *il ginnasio* no es el gimnasio, es un tramo del liceo clásico."],
        ["mela", "manzana", "Ho comprato le mele: ne vuoi una?",
         "Plural *mele*. Con *ne* para las cantidades: *ne vuoi una?* (¿querés una?). El manzano es *il melo*."],
        ["cipolla", "cebolla", "Ne vuoi un po'? Sono cipolle di Tropea.",
         "Plural *cipolle*. *Cipolle di Tropea*: la morada de Calabria. Doble *l*."],
        ["scatola", "caja; lata", "Ne ho comprate due scatole.",
         "Esdrújula: *scàtola*. *In scatola* = de lata: *tonno in scatola*. La caja del súper donde se paga es *la cassa*."],
        ["minestra", "sopa", "La minestra è buona, ne vuoi un po'?",
         "Sopa de verduras o caldo con pasta. *Il minestrone* es la versión grande con muchas verduras. El caldo solo es *il brodo*."],
        ["chilo", "kilo", "Quante mele vuole? — Ne prendo un chilo.",
         "Con cantidades pide *di*: *un chilo di mele*, *mezzo chilo di pane*. Con *ne* no se repite: *ne prendo un chilo*."],
        ["etto", "cien gramos", "Del prosciutto? Ne vorrei due etti.",
         "La unidad de la fiambrería: *un etto di prosciutto* = 100 g. Plural *etti*. *Un etto e mezzo* = 150 g."],
        ["metà", "mitad", "Ho mangiato metà della torta.",
         "Invariable, con tilde. *A metà* = por la mitad: *a metà strada*. *Metà prezzo* = mitad de precio."],
        ["pesante", "pesado", "La borsa è pesante: ci sono dentro tre bottiglie.",
         "Una forma para los dos géneros. También de comida (*una cena pesante*) y de personas: *che pesante!* = ¡qué denso! Lo contrario: *leggero*."],
        ["busta", "bolsa; sobre", "Vuole una busta? — No, grazie, ne ho già una.",
         "La bolsa del súper (*una busta di plastica*) y el sobre de una carta. *La busta paga* es el recibo de sueldo."],
        ["fornaio", "panadero, panadería", "Dal fornaio ci vado ogni mattina.",
         "*Andare dal fornaio* = ir a la panadería (a lo del panadero, con *da*). También *il panificio*. De *forno* (horno)."],
        ["pentola", "olla", "Metti l'acqua nella pentola.",
         "Esdrújula: *pèntola*. La sartén es *la padella*. *Pentola a pressione* = olla a presión."],
        ["olio", "aceite", "Ci vuole un po' d'olio.",
         "*Olio d'oliva*, *olio extravergine*. *Ci vuole* + singular, *ci vogliono* + plural = hace falta: *ci vogliono due uova*."],
        ["sale", "sal", "Quanto sale ci metto? — Poco.",
         "Masculino: *il sale*. *Sale* es también «sube» (de *salire*): el contexto decide. *Salato* = salado; *dolce* = dulce."],
        ["pomodoro", "tomate", "Compro i pomodori: ne vuoi un chilo?",
         "De *pomo d'oro* (manzana de oro). Plural *pomodori*. *Salsa di pomodoro*; *pasta al pomodoro*."],
        ["fila", "fila, cola", "Al mercato c'è sempre la fila.",
         "*Fare la fila* = hacer la cola. *In fila* = en fila. *Di fila* = seguidos: *tre giorni di fila*."],
        ["chiacchierare", "charlar", "Al banco del pane ci fermiamo a chiacchierare.",
         "*Fare due chiacchiere* = charlar un rato. *Chiacchierone* = charlatán. Suena «kiakierare»."],
    ],
    22: [
        ["spedire", "enviar (por correo)", "Ti posso spedire le informazioni? Te le spedisco adesso.",
         "Verbo en *-isc-*: *spedisco, spedisci*. Es mandar por correo o paquetería; un mensaje se *manda*. El envío es *la spedizione*."],
        ["pacco", "paquete", "Dobbiamo aprire questo pacco. Ve lo apro io, se volete.",
         "Plural *pacchi*, con *h*. *Pacco regalo* = paquete de regalo. *Fare un pacco a qualcuno* = embaucarlo."],
        ["permettere", "permitir", "Non me lo permettono.",
         "Participio *permesso*. Se permite algo *a* alguien: *glielo permetto*. *Permettersi* = darse el lujo: *non me lo posso permettere*."],
        ["formaggio", "queso", "Sono tre etti di formaggio, signore. Gliene tolgo un po'?",
         "Plural *formaggi*. *Formaggio grattugiato* = queso rallado. Con *ne*: *gliene tolgo un po'?* (¿le saco un poco?)."],
        ["prosciutto", "jamón", "Me lo dai il prosciutto crudo?",
         "*Crudo* (curado) o *cotto* (cocido). *Me lo dai il prosciutto?* repite el objeto con el pronombre: es muy del habla."],
        ["stirare", "planchar", "Devo stirare queste camicie. Te le stiro io, se vuoi.",
         "Transitivo: *stirare le camicie*. La plancha es *il ferro da stiro*. No es «estirar» (eso es *tirare*, *allungare*)."],
        ["bocciare", "reprobar, bochar", "L'hanno bocciato all'esame di guida.",
         "Transitivo: el profesor boccia al alumno; el alumno *è bocciato*. Lo contrario: *essere promosso*. En la charla: *mi hanno bocciato*."],
        ["promuovere", "aprobar (el año); promover", "Sono stato promosso: ho passato tutti gli esami!",
         "En la escuela, *essere promosso* es pasar de año; *essere bocciato*, repetir. Participio *promosso*. En el trabajo, *promuovere* = ascender."],
        ["laurea", "título universitario, licenciatura", "Dopo la laurea ho lavorato un anno a Londra.",
         "*Prendere la laurea* o *laurearsi* = recibirse. *Laurea in economia*. El graduado es *il laureato*."],
        ["insegnare", "enseñar", "Me lo insegni?",
         "Se enseña algo *a* alguien: *gli insegno l'italiano*. Con infinitivo pide *a*: *mi insegni a guidare?*. Aprender es *imparare*."],
        ["ripassare", "repasar; volver a pasar", "Prima dell'esame ho ripassato tutto.",
         "Es repasar lo estudiado: *ripassare la lezione*. También volver a pasar: *ripasso più tardi*. El repaso es *il ripasso*."],
        ["capitare", "pasar, tocar (por casualidad)", "Ti è mai capitato di perdere il treno?",
         "Con *essere*: *mi è capitato*. *Capitare di* + infinitivo = pasarte algo alguna vez. *Capita!* = ¡son cosas que pasan!"],
        ["volta", "vez", "Te l'ho detto mille volte!",
         "*Una volta*, *due volte*, *a volte* (a veces), *ogni volta*. *C'era una volta* = había una vez. No es «vuelta» (eso es *giro*)."],
        ["fastidioso", "molesto", "Il rumore della strada è fastidioso.",
         "Como en castellano, es lo que molesta: *un rumore fastidioso*. *Dare fastidio* = molestar: *ti dà fastidio?*"],
        ["decina", "decena, unos diez", "Me ne ha prestati una decina.",
         "*Una decina di* = unos diez: *una decina di persone*. Igual *una ventina*, *una trentina*, *un centinaio*."],
        ["riportare", "devolver; traer de vuelta", "Te lo riporto domani.",
         "Es llevar de vuelta algo prestado: *te lo riporto*. También «informar» en el diario: *il giornale riporta che...*"],
        ["ricordo", "recuerdo; souvenir", "Ti ho portato un ricordo da Venezia.",
         "Es lo que recordás y también el souvenir de un viaje. Recordar es *ricordare* o *ricordarsi di*."],
        ["mancia", "propina", "Abbiamo lasciato la mancia al cameriere.",
         "*Lasciare la mancia*. En Italia no es obligatoria: a veces la cuenta ya trae *il coperto* o *il servizio*."],
        ["raccomandare", "recomendar", "Mi raccomando, chiamami quando arrivi!",
         "*Mi raccomando!* es «te lo pido por favor, ¡ojo!»: pide que alguien no se olvide de algo. *Una raccomandata* es una carta certificada."],
    ],
    23: [
        ["maggiore", "mayor", "Mio fratello maggiore vive a Córdoba.",
         "Comparativo de *grande*. *La maggior parte* = la mayoría, perdiendo la *-e*. *Il maggiore* = el mayor de los hermanos."],
        ["migliore", "mejor (adjetivo)", "È il mio migliore amico.",
         "Comparativo de *buono*. Con artículo es superlativo: *il migliore*. Acompaña a un sustantivo; con verbos va *meglio*."],
        ["peggiore", "peor (adjetivo)", "È stata la giornata peggiore dell'anno.",
         "Comparativo de *cattivo*. Con verbos, *peggio*: *sto peggio*. *Il peggiore* = el peor."],
        ["meglio", "mejor (adverbio)", "Oggi sto meglio di ieri.",
         "Va con verbos: *sto meglio*, *parla meglio di me*. Con sustantivos, *migliore*. *Meglio tardi che mai* = más vale tarde que nunca."],
        ["antico", "antiguo", "A Roma ho trovato una libreria antica.",
         "Plural *antichi*, *antiche*. Es muy viejo, histórico; algo solo viejo es *vecchio*."],
        ["furbo", "vivo, pícaro", "È più furbo che intelligente.",
         "Es «vivo» en sentido pícaro. *Fare il furbo* = hacerse el vivo. No siempre es crítica: a veces es elogio."],
        ["noioso", "aburrido (que aburre)", "Studiare è meno noioso che lavorare.",
         "Es lo que aburre: *un film noioso*. «Estar aburrido» es *annoiarsi*: *mi annoio*."],
        ["quartiere", "barrio", "È il migliore ristorante del quartiere.",
         "Masculino en *-e*. Superlativo + *di*: *il migliore del quartiere*. El vecino es *il vicino di casa*."],
        ["stretto", "angosto, estrecho; ajustado", "Questa strada è più stretta di quella.",
         "Angosto o apretado: *pantaloni stretti*. También el estrecho: *lo Stretto di Messina*. Participio de *stringere* (apretar)."],
        ["largo", "ancho", "Questa strada è più larga di quella.",
         "Falso amigo: *largo* es «ancho»; «largo» es *lungo*. *Una gonna larga* = una pollera amplia. *Al largo* = mar adentro."],
        ["veloce", "rápido", "Il treno è veloce come l'aereo.",
         "Una forma para los dos géneros. Como adverbio: *velocemente* o *veloce* (*corre veloce*). Comparación de igualdad: *veloce come*."],
        ["economico", "barato; económico", "Il treno è più economico dell'aereo.",
         "Falso amigo a medias: dicho de un precio es «barato». *Caro* es lo contrario. También «de economía»: *la crisi economica*."],
        ["taglia", "talle", "Avete una taglia più piccola?",
         "*Che taglia porta?* = ¿qué talle usa? El número del calzado es *il numero*. *Taglia unica* = talle único."],
        ["vestito", "vestido; traje", "Questo vestito è più elegante di quello.",
         "Es el vestido de mujer y también el traje de hombre. *I vestiti* = la ropa. Vestirse es *vestirsi*."],
        ["gonna", "pollera", "Preferisco la gonna rossa: è meno corta.",
         "Femenino: *la gonna*. *Minigonna* = minifalda. Doble *n*."],
        ["scarpa", "zapato", "Queste scarpe sono più comode di quelle.",
         "Casi siempre en plural: *le scarpe*. La zapatilla es *la scarpa da ginnastica*. Para el talle: *che numero porta?*"],
        ["giacca", "saco; campera", "La giacca blu costa meno di quella nera.",
         "Plural *giacche*, con *h*. Es saco o campera; el abrigo largo es *il cappotto*."],
        ["maglietta", "remera", "Questa maglietta è la più bella del negozio.",
         "La remera de manga corta. El pulóver es *il maglione*; la camiseta de fútbol, *la maglia*."],
        ["azzurro", "celeste, azul claro", "Il cielo oggi è più azzurro del solito.",
         "Es el celeste del cielo y el color de la selección: *gli Azzurri*. *Blu* es el azul oscuro."],
        ["giallo", "amarillo; policial", "Preferisco il giallo al verde.",
         "*Un giallo* es también una novela o película policial, por las tapas amarillas de una colección famosa. Plural *gialli*."],
    ],
    24: [
        ["dubitare", "dudar", "Dubito che arrivi in tempo.",
         "Pide *che* + congiuntivo: *dubito che venga*. También *dubitare di qualcosa*. La duda es *il dubbio*."],
        ["parere", "opinión", "A mio parere, è una buona idea.",
         "*A mio parere* = en mi opinión, un poco formal. *Chiedere un parere* = pedir una opinión. Como verbo, *parere* es «parecer» (literario)."],
        ["torto", "sin razón; injusticia", "Penso che tu abbia torto.",
         "*Avere torto* = no tener razón, lo contrario de *avere ragione*. *Dare torto a qualcuno*. *A torto* = injustamente."],
        ["d'accordo", "de acuerdo", "Non sono d'accordo con te.",
         "*Essere d'accordo con qualcuno*, *su qualcosa*. Solo, *d'accordo!* = ¡dale!, ¡está bien!. *Andare d'accordo* = llevarse bien."],
        ["secondo", "según; segundo", "Secondo me, è troppo caro.",
         "*Secondo me* = para mí, en mi opinión (con indicativo). *Secondo lui*, *secondo i giornali*. También el ordinal y el segundo del reloj."],
        ["argomento", "tema (de conversación)", "Credo che l'argomento sia interessante.",
         "Falso amigo: *argomento* es el tema del que se habla; el «argumento» de una película es *la trama*. *Cambiare argomento* = cambiar de tema."],
        ["tasse", "impuestos", "Penso che le tasse siano troppo alte.",
         "*Pagare le tasse*. *La tassa* es un impuesto puntual; los impuestos en general también son *le imposte*. «Taza» es *tazza*."],
        ["mezzi pubblici", "transporte público", "Credo che i mezzi pubblici funzionino bene.",
         "*I mezzi* = los medios de transporte: *con i mezzi* = en transporte público. *Il mezzo* también es «el medio» para hacer algo."],
        ["cancellare", "borrar; cancelar", "Credo che cancellino il concerto.",
         "Es borrar (*cancellare un file*) y también suspender un evento. Anular una reserva: *disdire*."],
        ["notizia", "noticia", "Hai sentito la notizia?",
         "*Una bella notizia*, *una brutta notizia*. *Le notizie* = las noticias; el noticiero es *il telegiornale*."],
        ["sciocchezza", "pavada, tontería", "Non dire sciocchezze!",
         "*Dire sciocchezze* = decir pavadas. También algo sin importancia: *è una sciocchezza*. Adjetivo: *sciocco*."],
        ["pettegolezzo", "chisme", "Non mi piacciono i pettegolezzi.",
         "*Fare pettegolezzi* = chusmear. El chusma es *pettegolo*, *pettegola*."],
        ["educato", "bien educado, cortés", "Mi sembra che Stefano sia molto educato.",
         "Falso amigo: *educato* es cortés, con buenos modales, no «instruido» (eso es *istruito*). Lo contrario: *maleducato*."],
        ["affidabile", "confiable", "Credo che sia una persona affidabile.",
         "Una forma para los dos géneros. De *fidarsi* (confiar): *mi fido di lui*. Lo contrario: *inaffidabile*."],
        ["faccia", "cara", "Che faccia! Sei stanco?",
         "*La faccia* es la cara; *il viso* es más cuidado. Ojo: *faccia* es también el congiuntivo de *fare*: *penso che faccia freddo*."],
        ["giudicare", "juzgar", "Non voglio giudicare nessuno.",
         "En *tu giudichi* la *h* mantiene el sonido «k». El juicio es *il giudizio*; el juez, *il giudice*."],
        ["lavatrice", "lavarropas", "Credo che la lavatrice sia rotta.",
         "De *lavare*. El lavavajillas es *la lavastoviglie*. *Fare una lavatrice* = poner un lavarropas."],
        ["sbagliare", "equivocarse; errar", "Penso che tu sbagli.",
         "*Sbagliare* o *sbagliarsi* = equivocarse. Transitivo: *ho sbagliato strada* (me equivoqué de camino). *Sbagliato* = equivocado, mal."],
        ["discutere", "discutir, debatir", "Credo che dobbiamo discutere di questo problema.",
         "Rige *di*: *discutere di politica*. Participio *discusso*. Es debatir; pelearse es *litigare*."],
    ],
    25: [
        ["lamentarsi", "quejarse", "Non fa che lamentarsi.",
         "Pronominal y pide *di*: *si lamenta del rumore*. *Non fa che lamentarsi* = no hace más que quejarse. La queja es *la lamentela*."],
        ["giusto", "justo; correcto", "Mi sembra giusto che paghi lui.",
         "Además de «justo», es «correcto»: *la risposta giusta*. *Giusto!* = ¡exacto! *Mi sembra giusto che* + congiuntivo."],
        ["ammettere", "admitir, reconocer", "Ammetto che hai ragione.",
         "Participio irregular *ammesso*. *Ammettere che* + indicativo si reconocés un hecho. *Ammesso che* + congiuntivo = suponiendo que."],
        ["sperare", "esperar (con deseo)", "Spero che tu stia bene.",
         "*Sperare che* + congiuntivo; con el mismo sujeto, *di* + infinitivo: *spero di venire*. Esperar a alguien es *aspettare*. *Speriamo!* = ¡ojalá!"],
        ["augurare", "desear (algo a alguien)", "Ti auguro che vada tutto bene.",
         "Se desea algo *a* alguien: *ti auguro buona fortuna*. *Tanti auguri!* = ¡felicidades!, en cumpleaños y fiestas."],
        ["bisognare", "hacer falta", "Bisogna che tu parli con lei.",
         "Impersonal, solo en tercera persona: *bisogna studiare*; *bisogna che* + congiuntivo. Es lo mismo que *è necessario*."],
        ["consigliare", "aconsejar; recomendar", "Ti consiglio di essere sincera.",
         "*Consigliare a qualcuno di* + infinitivo. El consejo es *il consiglio*, que también es el concejo o el directorio."],
        ["lasciarsi", "separarse, dejarse", "Marco e Giulia si sono lasciati.",
         "Es cortar una relación de pareja: *ci siamo lasciati*. *Lasciare qualcuno* = dejarlo. Lo contrario: *mettersi insieme*."],
        ["geloso", "celoso", "È geloso di tutti i tuoi amici.",
         "*Essere geloso di qualcuno*. Los celos son *la gelosia*. No tiene nada que ver con *gelato*."],
        ["coppia", "pareja", "Sono una bella coppia.",
         "La pareja como dos personas: *una coppia sposata*. Tu pareja (la persona) es *il mio compagno*, *la mia compagna*. *In coppia* = de a dos."],
        ["amicizia", "amistad", "La nostra amicizia è importante per me.",
         "Femenino, plural *amicizie*. *Fare amicizia con qualcuno* = hacerse amigo de alguien."],
        ["fare pace", "hacer las paces", "Spero che facciano pace presto.",
         "*Fare pace con qualcuno*, sin artículo. Pelearse es *litigare*. *Lasciami in pace!* = ¡dejame tranquilo!"],
        ["fiducia", "confianza", "Ho fiducia in te.",
         "*Avere fiducia in qualcuno*, con *in*. *Di fiducia* = de confianza: *il mio medico di fiducia*. Confiar es *fidarsi di*."],
        ["rapporto", "relación (entre personas)", "Ho un buon rapporto con mia sorella.",
         "Es la relación que tenés con alguien: *un buon rapporto*, *rapporto di lavoro*. Por escrito, un informe es *una relazione*. Una relación amorosa: *una storia*."],
        ["sognare", "soñar", "Sogno di vivere al mare.",
         "Con infinitivo pide *di*: *sogno di partire*. *Sognare qualcuno* = soñar con alguien. El sueño es *il sogno*; el de dormir, *il sonno*."],
        ["mi sa che", "me parece que, me da que", "Mi sa che ha ragione lei.",
         "Coloquial, para una suposición: *mi sa che piove*. Va con indicativo, a diferencia de *penso che*. Solo en la charla."],
        ["voglia", "ganas", "Non ho voglia di uscire.",
         "*Avere voglia di* + infinitivo o cosa = tener ganas. *Che voglia di...!* = ¡qué ganas de...! También es el antojo."],
        ["deluso", "desilusionado, decepcionado", "È deluso che tu non venga.",
         "Falso amigo: no es «iluso». *Essere deluso da qualcuno*. Decepcionar es *deludere*; la decepción, *la delusione*."],
        ["aspettarsi", "esperar (que pase algo)", "Mi aspetto che tu arrivi puntuale.",
         "Es esperar que algo pase, prever: *non me lo aspettavo* (no me lo esperaba). *Aspettarsi che* + congiuntivo."],
    ],
}
