# -*- coding: utf-8 -*-
"""Las palabras de las semanas 1 a 4, elegidas a mano.

build_course.py elige las palabras de cada semana entre las más frecuentes
de sus ejercicios, pero las primeras semanas heredan capítulos enteros de
los libros y así la semana 1 traía *fare, andare, volere* (los irregulares
de la semana 6) y ejemplos en pasado.  Acá van, para cada una de las cuatro
primeras semanas, palabras del campo de la semana (su «sai fare» y su tema,
build_course.py SAI_FARE) con un ejemplo que usa solo la gramática ya vista:

- semana 1, saludar y presentarte: essere y avere en presente;
- semana 2, el aula y los objetos: más c'è / ci sono y los plurales;
- semana 3, el bar: más artículos, preposiciones articuladas, partitivo,
  elisión y posesivos;
- semana 4, describir personas: más la concordancia de los adjetivos.

Sin números (llegan en la semana 7) ni presente de otros verbos (semana 5).
build_course.py comprueba cada ejemplo con tools/it/rasgos_banco.py.

Formato: [palabra, castellano, ejemplo, cómo se usa]
"""

PAROLE = {
    1: [
        ["ciao", "hola; chau",
         "Ciao, sono Giulia!",
         "Sirve para llegar y para irte, pero solo con quien tuteás. Con desconocidos: *buongiorno* al llegar, *arrivederci* al irte."],
        ["buongiorno", "buen día, buenas tardes",
         "Buongiorno, signora!",
         "Vale desde la mañana hasta media tarde, al llegar y al irte. Es una sola palabra (también *buon giorno*)."],
        ["buonasera", "buenas tardes, buenas noches",
         "Buonasera, signor Bianchi!",
         "En Italia empieza temprano, a media tarde. *Buonanotte* es solo para despedirte antes de dormir."],
        ["arrivederci", "chau, hasta luego",
         "Grazie e arrivederci!",
         "La despedida que sirve con todos. Con *Lei*, más formal: *arrivederla*. Entre amigos: *ciao* o *a presto*."],
        ["grazie", "gracias",
         "Grazie, sei molto gentile!",
         "*Grazie mille* = muchísimas gracias. Se contesta *prego*."],
        ["prego", "de nada; adelante",
         "Grazie! — Prego!",
         "La respuesta a *grazie*; también «adelante, pase» cuando abrís la puerta o das el paso. No es «ruego»."],
        ["scusa", "perdón, disculpá",
         "Scusa, sei Marco?",
         "*Scusa* con quien tuteás; con *Lei*, *scusi*. Sirve para pedir perdón y para llamar la atención de alguien."],
        ["piacere", "¡mucho gusto!",
         "Piacere, sono Anna.",
         "Al presentarte, *piacere!* o *molto piacere!*. Es el mismo *piacere* de «gustar» (*mi piace*), que llega en la semana 14."],
        ["nome", "nombre",
         "Il nome è Anna, il cognome è Russo.",
         "Masculino: *il nome*. Para preguntarlo: *come ti chiami?* (tú) o *come si chiama?* (Lei)."],
        ["cognome", "apellido",
         "Il cognome è Bianchi.",
         "En los formularios va primero: *cognome e nome*. Ojo: no es «cognombre», es el apellido."],
        ["signora", "señora",
         "La signora è di Roma.",
         "Para hablarle, sin artículo: *buongiorno, signora!*; para hablar de ella, con artículo: *la signora Rossi*."],
        ["lettera", "letra; carta",
         "La h è una lettera muta.",
         "La letra del alfabeto y también la carta que se manda. Para deletrear: *come si scrive?*"],
    ],
    2: [
        ["penna", "lapicera, birome",
         "Ci sono penne e matite.",
         "Femenino: *la penna*, plural *le penne* (como la pasta). También es la pluma de un pájaro."],
        ["matita", "lápiz",
         "Le matite sono rosse.",
         "Femenino: *la matita*, plural *le matite*. Nada que ver con «lápiz»: memorizala entera."],
        ["zaino", "mochila",
         "Lo zaino è pesante.",
         "Empieza con *z*: el artículo es *lo* (*lo zaino*), plural *gli zaini*."],
        ["sedia", "silla",
         "In aula ci sono molte sedie.",
         "Femenino, plural *le sedie*. El sillón es *la poltrona* y el sofá, *il divano*."],
        ["tavolo", "mesa",
         "Il tavolo è grande.",
         "Masculino: *il tavolo*. *La tavola* es la mesa puesta para comer: *a tavola!* = ¡a comer!"],
        ["finestra", "ventana",
         "In aula c'è una finestra grande.",
         "Parece «fenestra», pero es la ventana común. La de un auto es *il finestrino*; la de un negocio, *la vetrina*."],
        ["porta", "puerta",
         "La porta è chiusa.",
         "Sin diptongo: *porta*, no «puerta». Ojo: *porta* también es «lleva» (de *portare*)."],
        ["chiave", "llave",
         "Le chiavi sono qui.",
         "Femenino en *-e*: *la chiave*, plural *le chiavi*. El grupo *chi* suena «qui»."],
        ["borsa", "cartera, bolso",
         "La borsa è nera.",
         "La cartera o el bolso; la bolsa del súper es *il sacchetto*. *La Borsa* es también la Bolsa de valores."],
        ["lavagna", "pizarrón",
         "C'è una lavagna in aula?",
         "Femenino: *la lavagna*. *gn* suena como nuestra *ñ*: «lavaña»."],
        ["cestino", "tacho (de papeles)",
         "Il cestino è pieno.",
         "Diminutivo de *cesta*: el tachito de papeles. La basura es *la spazzatura*."],
        ["gomma", "goma de borrar",
         "Hai una gomma?",
         "La goma de borrar; también el neumático (*le gomme della macchina*) y el chicle (*gomma da masticare*)."],
    ],
    3: [
        ["cornetto", "medialuna",
         "Un cappuccino e un cornetto, per favore.",
         "Así se dice en el centro y el sur; en Milán, *brioche*. Puede ser *vuoto* o *alla crema*."],
        ["bicchiere", "vaso",
         "Un bicchiere d'acqua, per favore.",
         "Masculino: *il bicchiere*, plural *i bicchieri*. La copa de vino es *il calice*; la taza, *la tazza*."],
        ["latte", "leche",
         "Il latte è freddo.",
         "Masculino: *il latte*. Un *latte* en el bar es un vaso de leche: el café con leche es *il caffellatte* o *il latte macchiato*."],
        ["succo", "jugo",
         "Un succo d'arancia, per favore.",
         "*Succo di frutta* es el de caja; el exprimido en el momento es *la spremuta*: *una spremuta d'arancia*."],
        ["birra", "cerveza",
         "Una birra alla spina, per favore.",
         "Femenino: *la birra*. *Alla spina* = tirada; *una birra piccola* o *media*."],
        ["bancone", "barra (del bar)",
         "Sul bancone ci sono i cornetti.",
         "En Italia el café se toma de parado, *al bancone*: sale menos que sentado, *al tavolo*."],
        ["scontrino", "ticket",
         "Ecco lo scontrino.",
         "En muchos bares primero se paga en la caja y con el *scontrino* se pide en la barra."],
        ["cassa", "caja",
         "La cassa è lì.",
         "Doble *s*: *la cassa* (caja) no es *la casa*. *Alla cassa* = en la caja."],
        ["panino", "sánguche",
         "Un panino al prosciutto, per favore.",
         "Es el sánguche de pan (o el pancito). *Panini* ya es plural: no digas «paninis»."],
        ["tramezzino", "sándwich de miga",
         "Un tramezzino e una spremuta, per favore.",
         "El triangulito de pan de miga, típico de Venecia y de cualquier bar italiano."],
        ["cameriere", "mozo",
         "Il cameriere è molto gentile.",
         "Masculino en *-e*: *il cameriere*; femenino, *la cameriera*. Para llamarlo: *scusi!*"],
        ["zucchero", "azúcar",
         "Il caffè è senza zucchero.",
         "Masculino y con *z*: *lo zucchero*. *Senza zucchero* = sin azúcar."],
    ],
    4: [
        ["basso", "bajo (de estatura)",
         "Marco è basso e magro.",
         "Cuatro formas: *basso, bassa, bassi, basse*. Doble *s*. Sirve también para la voz: *parla a voce bassa*."],
        ["magro", "flaco",
         "Giulia è alta e magra.",
         "*Magro, magra*. También es «magro» de la carne: *carne magra*. Lo contrario: *grasso*, o más amable, *robusto*."],
        ["capelli", "pelo (de la cabeza)",
         "Ho i capelli neri.",
         "Siempre en plural: *i capelli* es «el pelo». El pelo del cuerpo o de un animal es *il pelo*."],
        ["occhio", "ojo",
         "Anna ha gli occhi verdi.",
         "Plural *gli occhi* (ante vocal, *gli*). Como en castellano, con *avere*: *ha gli occhi azzurri*."],
        ["biondo", "rubio",
         "Luca è biondo.",
         "*Biondo, bionda*. «Rubio» no existe en italiano; *rosso* es pelirrojo: *ha i capelli rossi*."],
        ["brutto", "feo",
         "Il tempo è brutto.",
         "Feo, y también «malo»: *brutto tempo*, *una brutta notizia*. No tiene nada que ver con «bruto»."],
        ["giovane", "joven",
         "Il professore è giovane.",
         "Termina en *-e*: una sola forma para los dos géneros, plural *giovani*. Lo contrario, para personas: *anziano*."],
        ["vecchio", "viejo",
         "Il palazzo è vecchio.",
         "*Vecchio, vecchia, vecchi, vecchie*. Para personas suena duro: mejor *anziano*."],
        ["tedesco", "alemán",
         "Hans è tedesco.",
         "Las nacionalidades van en minúscula: *è tedesco*, *è tedesca*. Plural *tedeschi*, con *h*."],
        ["lavoro", "trabajo",
         "Il lavoro è interessante.",
         "*Che lavoro fai?* = ¿de qué trabajás? También es «yo trabajo» (de *lavorare*), que llega en la semana 5."],
        ["insegnante", "docente",
         "L'insegnante è simpatica.",
         "Termina en *-e* y sirve para los dos géneros: *l'insegnante* es profesor o profesora; lo marca el adjetivo (*simpatica*)."],
        ["carino", "lindo, simpático",
         "Il bar è piccolo ma carino.",
         "Muy usado: *che carino!* = ¡qué lindo! Para personas es «lindo» y también «amable»."],
    ],
}
