# -*- coding: utf-8 -*-
"""Artículos (semana 3): ejercicios propios para las partes que el libro
casi no cubre.

La parte «Género y el, la: il, la, l'» tenía tres ejercicios y «Dónde va el
artículo (y dónde no)» dos: entrenar una parte daba una ronda de dos
preguntas.  Estos la llevan a unas quince cada una.
"""

EA = "Elegí el artículo."
WA = "Escribí el artículo determinado."
TR = "Traducí al italiano con el artículo."
TU = "Traducí al italiano."
CE = "Elegí la forma correcta."
NADA = "(nada)"

ITEMS = [
    # ================= Parte 1: género, il, la, l' =================
    dict(id="ar-g-01", type="choice", topic="articoli", level="A1", w=3, prompt=EA,
         stem="___ latte (la leche)", options=["il", "la", "l'"], answer="il",
         note="«latte» es masculino, al revés que «la leche»: il latte."),
    dict(id="ar-g-02", type="choice", topic="articoli", level="A1", w=3, prompt=EA,
         stem="___ fiore (la flor)", options=["il", "la", "l'"], answer="il",
         note="«fiore» es masculino: il fiore, i fiori."),
    dict(id="ar-g-03", type="choice", topic="articoli", level="A1", w=3, prompt=EA,
         stem="___ mano", options=["la", "il", "l'"], answer="la",
         note="«mano» termina en -o pero es femenino, como en castellano: la mano."),
    dict(id="ar-g-04", type="choice", topic="articoli", level="A1", w=3, prompt=EA,
         stem="___ foto", options=["la", "il", "l'"], answer="la",
         note="«foto» es «fotografia» acortada: femenino, la foto."),
    dict(id="ar-g-05", type="choice", topic="articoli", level="A1", w=3, prompt=EA,
         stem="___ stazione (la estación)", options=["la", "il", "l'"], answer="la",
         note="Las palabras en -ione son femeninas: la stazione, la lezione."),
    dict(id="ar-g-06", type="choice", topic="articoli", level="A1", w=3, prompt=EA,
         stem="___ città", options=["la", "il", "l'"], answer="la",
         note="Las palabras en -tà son femeninas: la città, l'università."),
    dict(id="ar-g-07", type="choice", topic="articoli", level="A1", w=3, prompt=EA,
         stem="___ sale (la sal)", options=["il", "la", "l'"], answer="il",
         note="«sale» es masculino: il sale. En -e hay que aprender el género con la palabra."),
    dict(id="ar-g-08", type="cloze", topic="articoli", level="A1", w=3, prompt=WA,
         stem="___ acqua (el agua)", answer="l'", accept=["l'", "l’"],
         note="Delante de vocal: l'acqua. Y es femenino: l'acqua fresca."),
    dict(id="ar-g-09", type="cloze", topic="articoli", level="A1", w=3, prompt=WA,
         stem="___ ora (la hora)", answer="l'", accept=["l'", "l’"],
         note="Delante de vocal, la → l': l'ora."),
    dict(id="ar-g-10", type="cloze", topic="articoli", level="A1", w=3, prompt=WA,
         stem="___ pane (el pan)", answer="il",
         note="Masculino delante de consonante: il pane."),
    dict(id="ar-g-11", type="cloze", topic="articoli", level="A1", w=3, prompt=WA,
         stem="___ notte (la noche)", answer="la",
         note="«notte» es femenino, como «la noche»: la notte."),
    dict(id="ar-g-12", type="cloze", topic="articoli", level="A1", w=3, prompt=WA,
         stem="___ amico (el amigo)", answer="l'", accept=["l'", "l’"],
         note="Masculino delante de vocal: l'amico (el plural es gli amici)."),
    dict(id="ar-g-13", type="cloze", topic="articoli", level="A1", w=3, prompt=WA,
         stem="___ chiave (la llave)", answer="la",
         note="«chiave» es femenino: la chiave."),
    dict(id="ar-g-14", type="translate", topic="articoli", level="A1", w=3, prompt=TR,
         stem="la leche", answer="il latte",
         note="Masculino en italiano: il latte."),
    dict(id="ar-g-15", type="translate", topic="articoli", level="A1", w=3, prompt=TR,
         stem="la flor", answer="il fiore",
         note="Masculino en italiano: il fiore."),
    dict(id="ar-g-16", type="translate", topic="articoli", level="A1", w=3, prompt=TR,
         stem="el agua", answer="l'acqua", accept=["l'acqua", "l’acqua"],
         note="Femenino con l' delante de vocal: l'acqua."),

    # ================= Parte 4: dónde va el artículo =================
    dict(id="ar-u-01", type="translate", topic="articoli", level="A1", w=3, prompt=TR,
         stem="mi casa", answer="la mia casa",
         note="El posesivo lleva artículo: la mia casa."),
    dict(id="ar-u-02", type="translate", topic="articoli", level="A1", w=3, prompt=TR,
         stem="tu libro", answer="il tuo libro",
         note="El posesivo lleva artículo: il tuo libro."),
    dict(id="ar-u-03", type="translate", topic="articoli", level="A1", w=3, prompt=TU,
         stem="mi padre", answer="mio padre",
         note="Pariente en singular y sin adjetivo: sin artículo, mio padre."),
    dict(id="ar-u-04", type="translate", topic="articoli", level="A1", w=3, prompt=TR,
         stem="mis amigos", answer="i miei amici",
         note="El posesivo lleva artículo: i miei amici."),
    dict(id="ar-u-05", type="translate", topic="articoli", level="A1", w=3, prompt=TU,
         stem="mi madre", answer="mia madre",
         note="Pariente en singular y sin adjetivo: sin artículo, mia madre."),
    dict(id="ar-u-06", type="choice", topic="articoli", level="A1", w=3, prompt=CE,
         stem="___ (mis hermanos)", options=["i miei fratelli", "miei fratelli", "i mio fratelli"],
         answer="i miei fratelli",
         note="Con parientes en plural el artículo vuelve: i miei fratelli."),
    dict(id="ar-u-07", type="choice", topic="articoli", level="A1", w=3, prompt=CE,
         stem="___ Italia è bella.", options=["L'", "La", NADA], answer="L'",
         note="Los países llevan artículo: l'Italia."),
    dict(id="ar-u-08", type="choice", topic="articoli", level="A1", w=3, prompt=CE,
         stem="___ Roma è bella.", options=[NADA, "La", "Il"], answer=NADA,
         note="Las ciudades van sin artículo: Roma è bella."),
    dict(id="ar-u-09", type="choice", topic="articoli", level="A1", w=3, prompt=CE,
         stem="___ Toscana è in Italia.", options=["La", NADA, "Il"], answer="La",
         note="Las regiones llevan artículo: la Toscana."),
    dict(id="ar-u-10", type="choice", topic="articoli", level="A1", w=3, prompt=CE,
         stem="___ Cuba è un'isola.", options=[NADA, "La", "Il"], answer=NADA,
         note="Las islas chicas y los países-ciudad van como las ciudades: Cuba, Malta."),
    dict(id="ar-u-11", type="choice", topic="articoli", level="A1", w=3, prompt=CE,
         stem="___ Sicilia è un'isola.", options=["La", NADA, "Il"], answer="La",
         note="Las islas grandes llevan artículo: la Sicilia, la Sardegna."),
    dict(id="ar-u-12", type="translate", topic="articoli", level="A1", w=3, prompt=TU,
         stem="Italia es linda.", answer="L'Italia è bella", accept=["L'Italia è bella", "L’Italia è bella"],
         note="El país lleva artículo: l'Italia."),
    dict(id="ar-u-13", type="choice", topic="articoli", level="A1", w=3, prompt=CE,
         stem="Mi piace ___ musica.", options=["la", NADA, "una"], answer="la",
         note="Para hablar de algo en general va el artículo: mi piace la musica."),
    dict(id="ar-u-14", type="choice", topic="articoli", level="A1", w=3, prompt=CE,
         stem="___ (mi libro)", options=["il mio libro", "mio libro", "il mia libro"],
         answer="il mio libro",
         note="El posesivo lleva artículo y concuerda con la cosa: il mio libro."),
]
