# -*- coding: utf-8 -*-
"""Puente B1→B2: falsos amigos, preposiciones, artículos y usos idiomáticos.

Un hispanohablante llega rápido a entender italiano y se estanca justo aquí:
en los puntos donde las dos lenguas se parecen demasiado.
"""

ITEMS = [
    # --- falsi amici ---
    dict(id="b2-fa-01", type="choice", topic="falsi amici",
         prompt="¿Qué significa «burro» en italiano?",
         stem="Ho comprato il burro.",
         options=["manteca", "burro (animal)", "error"], answer="manteca",
         note="El animal es «asino» o «somaro»."),
    dict(id="b2-fa-02", type="choice", topic="falsi amici",
         prompt="¿Qué significa «salire»?",
         stem="Salgo le scale.",
         options=["subir", "salir", "saltar"], answer="subir",
         note="«Salir» es «uscire». Y «uscire» con essere: sono uscito."),
    dict(id="b2-fa-03", type="choice", topic="falsi amici",
         prompt="¿Qué significa «aceto»?",
         stem="Metti un po' di aceto.",
         options=["vinagre", "aceite", "aceituna"], answer="vinagre",
         note="Aceite = «olio»; aceituna = «oliva»."),
    dict(id="b2-fa-04", type="choice", topic="falsi amici",
         prompt="¿Qué significa «guardare»?",
         stem="Guardo la televisione.",
         options=["mirar", "guardar", "cuidar"], answer="mirar",
         note="Guardar = «tenere, conservare, mettere via»."),
    dict(id="b2-fa-05", type="choice", topic="falsi amici",
         prompt="¿Qué significa «prima»?",
         stem="Arrivo prima di te.",
         options=["antes", "prima (pariente)", "primero"], answer="antes",
         note="La prima (pariente) es «cugina»."),
    dict(id="b2-fa-06", type="choice", topic="falsi amici",
         prompt="¿Qué significa «largo»?",
         stem="Un fiume largo.",
         options=["ancho", "largo", "lejano"], answer="ancho",
         note="Largo (longitud) = «lungo»."),
    dict(id="b2-fa-07", type="choice", topic="falsi amici",
         prompt="¿Qué significa «esito»?",
         stem="L'esito dell'esame.",
         options=["resultado", "éxito", "examen"], answer="resultado",
         note="Éxito = «successo». Y «successo» también es «sucedido»."),
    dict(id="b2-fa-08", type="choice", topic="falsi amici",
         prompt="¿Qué significa «imbarazzata»?",
         stem="Era imbarazzata.",
         options=["avergonzada", "embarazada", "enojada"], answer="avergonzada",
         note="Embarazada = «incinta». Error clásico y caro."),
    dict(id="b2-fa-09", type="choice", topic="falsi amici",
         prompt="¿Qué significa «pronto» al teléfono?",
         stem="Pronto?",
         options=["¿Hola?", "¿Pronto?", "¿Listo?"], answer="¿Hola?",
         note="Es el «hola» telefónico. Como adjetivo sí significa «listo»."),
    dict(id="b2-fa-10", type="choice", topic="falsi amici",
         prompt="¿Qué significa «caldo»?",
         stem="Fa caldo.",
         options=["calor", "caldo (sopa)", "frío"], answer="calor",
         note="El caldo de sopa es «brodo»."),

    # --- preposizioni e articoli ---
    dict(id="b2-prep-01", type="choice", topic="preposizioni",
         prompt="Elegí la preposición correcta.",
         stem="Vado ___ Italia.", options=["in", "a", "nella"], answer="in",
         note="Países y regiones: «in». Ciudades: «a Roma»."),
    dict(id="b2-prep-02", type="choice", topic="preposizioni",
         prompt="Elegí la preposición correcta.",
         stem="Sono ___ Milano da due anni.", options=["a", "in", "di"], answer="a",
         note="Ciudad → «a»."),
    dict(id="b2-prep-03", type="choice", topic="preposizioni",
         prompt="Elegí la preposición correcta.",
         stem="Vado ___ dentista.", options=["dal", "al", "nel"], answer="dal",
         note="«Da» + persona = a casa/al consultorio de alguien."),
    dict(id="b2-prep-04", type="choice", topic="preposizioni",
         prompt="Elegí la forma correcta.",
         stem="Studio italiano ___ tre anni.", options=["da", "per", "fa"], answer="da",
         note="«Da» + tiempo con presente = «desde hace / hace ... que»."),
    dict(id="b2-prep-05", type="choice", topic="articoli",
         prompt="Elegí el artículo correcto.",
         stem="___ zio di Marco.", options=["Lo", "Il", "L'"], answer="Lo",
         note="«Lo» ante z, s+consonante, gn, ps, x, y semiconsonántica."),
    dict(id="b2-prep-06", type="choice", topic="articoli",
         prompt="Elegí el artículo correcto.",
         stem="___ studenti sono arrivati.", options=["Gli", "I", "Li"], answer="Gli",
         note="Plural de «lo» → «gli»."),
    dict(id="b2-prep-07", type="choice", topic="articoli",
         prompt="Elegí la forma correcta.",
         stem="Mi piace ___ musica classica.", options=["la", "—", "una"], answer="la",
         note="Con gustos y categorías generales el italiano exige artículo, "
              "igual que el español."),
    dict(id="b2-prep-08", type="choice", topic="possessivi",
         prompt="Elegí la forma correcta.",
         stem="___ è arrivata.", options=["Mia sorella", "La mia sorella",
                                          "Sorella mia"], answer="Mia sorella",
         note="Parentesco singular sin artículo. Pero: «le mie sorelle», "
              "«la mia sorellina» (diminutivo → vuelve el artículo)."),

    # --- passato prossimo vs imperfetto ---
    dict(id="b2-pass-01", type="choice", topic="passato",
         prompt="Elegí el tiempo correcto.",
         stem="Mentre ___, è suonato il telefono.",
         options=["mangiavo", "ho mangiato", "mangiai"], answer="mangiavo",
         note="Fondo/duración → imperfetto; acción puntual que irrumpe → passato prossimo."),
    dict(id="b2-pass-02", type="choice", topic="passato",
         prompt="Elegí el auxiliar correcto.",
         stem="Ieri ___ al cinema.", options=["sono andato", "ho andato",
                                              "sono andare"], answer="sono andato",
         note="Verbos de movimiento y cambio de estado → «essere» + concordancia."),
    dict(id="b2-pass-03", type="choice", topic="passato",
         prompt="Elegí el auxiliar correcto.",
         stem="___ molto ieri sera.", options=["Ho piovuto", "È piovuto",
                                               "Sono piovuto"], answer="È piovuto",
         note="Verbos meteorológicos admiten los dos (è piovuto / ha piovuto); "
              "«ho piovuto» y «sono piovuto» fallan por la persona."),
    dict(id="b2-pass-04", type="cloze", topic="passato",
         prompt="Completá con el passato prossimo.",
         stem="Loro ___ (dovere) partire presto.",
         answer="hanno dovuto",
         alt=["sono dovuti", "sono dovute"],
         note="Los modales toman el auxiliar del verbo que rigen; con «partire» "
              "también es correcto «sono dovuti partire»."),
    dict(id="b2-pass-05", type="translate", topic="passato",
         prompt="Traducí al italiano.",
         stem="Cuando era chico, iba al mar todos los veranos.",
         answer="Quando ero piccolo, andavo al mare tutte le estati",
         alt=["Quando ero piccola, andavo al mare tutte le estati",
              "Quando ero piccolo, andavo al mare ogni estate",
              "Quando ero piccola, andavo al mare ogni estate",
              "Da piccolo andavo al mare tutte le estati",
              "Da piccola andavo al mare tutte le estati",
              "Da piccolo andavo al mare ogni estate",
              "Da piccola andavo al mare ogni estate",
              "Da bambino andavo al mare ogni estate",
              "Da bambina andavo al mare ogni estate",
              "Da bambino andavo al mare tutte le estati",
              "Da bambina andavo al mare tutte le estati",
              "Quando ero bambino, andavo al mare tutte le estati",
              "Quando ero bambino, andavo al mare ogni estate",
              "Quando ero bambina, andavo al mare tutte le estati",
              "Quando ero bambina, andavo al mare ogni estate"],
         note="Costumbre en el pasado → imperfetto en los dos verbos."),

    # --- espressioni idiomatiche ---
    dict(id="b2-idio-01", type="choice", topic="espressioni",
         prompt="¿Qué significa «magari»?",
         stem="— Vieni con noi? — Magari!",
         options=["¡Ojalá!", "Quizás no", "Nunca"], answer="¡Ojalá!",
         note="Solo, exclamativo = ojalá. Con imperfetto congiuntivo = deseo irreal."),
    dict(id="b2-idio-02", type="choice", topic="espressioni",
         prompt="¿Qué significa «mica»?",
         stem="Non è mica facile.",
         options=["No es nada fácil", "Es medio fácil", "Es facilísimo"],
         answer="No es nada fácil",
         note="«Mica» refuerza la negación en registro coloquial."),
    dict(id="b2-idio-03", type="choice", topic="espressioni",
         prompt="¿Qué significa «avercela con qualcuno»?",
         stem="Ce l'ha con me.",
         options=["Está enojado conmigo", "Me tiene aprecio", "Me está esperando"],
         answer="Está enojado conmigo",
         note="Otro verbo pronominale idiomático, como «farcela» y «andarsene»."),
    dict(id="b2-idio-04", type="choice", topic="espressioni",
         prompt="Elegí la forma correcta.",
         stem="___ freddo oggi.", options=["Fa", "È", "Ha"], answer="Fa",
         note="Tiempo atmosférico con «fare»: fa freddo/caldo/bel tempo."),
    dict(id="b2-idio-05", type="translate", topic="espressioni",
         prompt="Traducí al italiano.",
         stem="Tengo ganas de salir.",
         answer="Ho voglia di uscire",
         note="«Avere voglia di» + infinitivo."),
    dict(id="b2-idio-06", type="choice", topic="piacere",
         prompt="Elegí la forma correcta.",
         stem="Mi ___ i film italiani.", options=["piacciono", "piace", "piaccio"],
         answer="piacciono",
         note="«Piacere» concuerda con la cosa que gusta, igual que «gustar»."),
    dict(id="b2-idio-07", type="cloze", topic="piacere",
         prompt="Completá con el passato prossimo de «piacere».",
         stem="Le ___ (piacere) molto quella mostra.",
         answer="è piaciuta",
         note="«Piacere» va con essere y concuerda con el sujeto (la mostra)."),
    dict(id="b2-idio-08", type="choice", topic="suffissi",
         prompt="¿Qué expresa «-accio»?",
         stem="Che tempaccio!",
         options=["desprecio", "cariño", "tamaño grande"], answer="desprecio",
         note="Sufijos: -ino/-etto (cariño), -one (aumentativo), -accio "
              "(peyorativo). Cap. 6 del Soluzioni."),
]
