# -*- coding: utf-8 -*-
"""Léxico 2: colocaciones con verbo soporte y marcadores discursivos.

Dos familias donde el hispanohablante «traduce» y se equivoca:
1. collocazioni: fare/dare/prendere/avere/stare/andare... + sustantivo, justo donde
   el italiano elige un verbo distinto del castellano (fare colazione, dare un esame,
   prendere in giro, stare zitto...).
2. discorsivi: magari, mica, appunto, ormai, anzi, comunque, addirittura, insomma...
   con un diálogo breve donde solo un marcador encaja.
"""

CE = "Elegí la forma correcta."
CV = "Completá con el verbo de apoyo conjugado."
TR = "Traducí al italiano."
CM = "Elegí el marcador que encaja en el diálogo."
CG = "Completá con el marcador que corresponde a la glosa entre paréntesis."

ITEMS = [
    # ======================= COLLOCAZIONI =======================
    # --- avere (desde la semana 5) ---
    dict(id="l2-c-01", type="cloze", topic="collocazioni", level="A1", w=5,
         prompt=CV, stem="È l'una e io ___ molta fame.", answer="ho",
         note="Tener hambre → avere fame. «Fame» es femenino y va sin artículo: ho fame, ho molta fame."),
    dict(id="l2-c-02", type="choice", topic="collocazioni", level="A1", w=5,
         prompt=CE, stem="Fa caldo e i bambini ___ sete.",
         options=["hanno", "sono", "tengono"], answer="hanno",
         note="Tener sed → avere sete. «Tenere» no sirve para estos estados: tenere = sostener, guardar."),
    dict(id="l2-c-03", type="choice", topic="collocazioni", level="A1", w=5,
         prompt=CE, stem="Scusa, non posso parlare adesso: ___ fretta.",
         options=["ho", "sono", "tengo"], answer="ho",
         note="Tener apuro / estar apurado → avere fretta. Nunca *tenere fretta ni *essere fretta."),
    dict(id="l2-c-04", type="cloze", topic="collocazioni", level="A1", w=5,
         prompt=CV, stem="Sono le undici di sera e io ___ sonno.", answer="ho",
         note="Tener sueño → avere sonno. Ojo: «sonno» es el sueño de dormir; el sueño que se sueña es «sogno»."),
    dict(id="l2-c-05", type="choice", topic="collocazioni", level="A1", w=5,
         prompt=CE, stem="Mia sorella ___ paura dei cani.",
         options=["ha", "è", "tiene"], answer="ha",
         note="Tener miedo de → avere paura di. Con essere sería *è paura, imposible."),
    dict(id="l2-c-06", type="choice", topic="collocazioni", level="A1", w=5,
         prompt=CE, stem="— Roma è la capitale d'Italia. — Sì, ___ ragione.",
         options=["hai", "sei", "tieni"], answer="hai",
         note="Tener razón → avere ragione. El contrario: avere torto."),
    dict(id="l2-c-07", type="cloze", topic="collocazioni", level="A1", w=5,
         prompt=CV, stem="Mi dispiace, ma tu ___ torto: il film è del 2010.", answer="hai",
         note="Estar equivocado → avere torto (literalmente «tener entuerto»). No existe *essere torto."),
    dict(id="l2-c-08", type="choice", topic="collocazioni", level="A1", w=5,
         prompt=CE, stem="Per il viaggio ___ un passaporto.",
         options=["ho bisogno di", "bisogno", "necessito"], answer="ho bisogno di",
         note="Necesitar → avere bisogno di. «Bisogno» es sustantivo, no verbo; «necessitare» existe pero es formal y rige «di»."),
    dict(id="l2-c-09", type="cloze", topic="collocazioni", level="A1", w=5,
         prompt=CV, stem="Stasera noi ___ voglia di mangiare una pizza.", answer="abbiamo",
         note="Tener ganas de → avere voglia di + infinitivo. «Voglia» va en singular: ho voglia, no *ho voglie."),
    dict(id="l2-c-10", type="choice", topic="collocazioni", level="A1", w=5,
         prompt=CE, stem="Io ___ caldo: posso aprire la finestra?",
         options=["ho", "sono", "faccio"], answer="ho",
         note="Tener calor → avere caldo; hace calor → fa caldo. *Sono caldo significa «soy caliente»: mejor evitarlo."),
    dict(id="l2-c-11", type="choice", topic="collocazioni", level="A1", w=5,
         prompt=CE, stem="Non ___ voglia di studiare oggi.",
         options=["ho", "sono", "tengo"], answer="ho",
         note="Todos los estados «tener X» del castellano van con avere: ho voglia, ho fretta, ho sonno, ho paura."),
    dict(id="l2-c-12", type="translate", topic="collocazioni", level="A1", w=5,
         prompt=TR, stem="Tengo apuro.", answer="Ho fretta",
         note="Avere fretta. En italiano no hay *apuro en este sentido."),
    dict(id="l2-c-13", type="choice", topic="collocazioni", level="A1", w=5,
         prompt=CE, stem="Non ___ con te su questo punto.",
         options=["sono d'accordo", "sto d'accordo", "sono de accordo"], answer="sono d'accordo",
         note="Estar de acuerdo → essere d'accordo, con essere y apóstrofo: d'accordo. *Stare d'accordo es calco del castellano."),
    dict(id="l2-c-14", type="cloze", topic="collocazioni", level="A1", w=5,
         prompt=CV, stem="Noi ___ d'accordo con la proposta.", answer="siamo",
         note="Essere d'accordo con qualcuno / su qualcosa."),
    dict(id="l2-c-15", type="choice", topic="collocazioni", level="A1", w=5,
         prompt=CE, stem="Scusa, ___ in ritardo: il bus non arriva.",
         options=["sono", "ho", "vengo"], answer="sono",
         note="Estar atrasado / llegar tarde → essere in ritardo. No se dice *ho ritardo."),
    dict(id="l2-c-16", type="cloze", topic="collocazioni", level="A1", w=5,
         prompt=CV, stem="Il treno ___ in orario, per fortuna.", answer="è",
         note="Estar en hora → essere in orario (trenes, aviones). Una persona puntual «è puntuale»."),

    # --- prendere / mettere / perdere / portare (regulares, desde la 5) ---
    dict(id="l2-c-17", type="cloze", topic="collocazioni", level="A1", w=5,
         prompt=CV, stem="Ogni mattina io ___ un caffè al bar.", answer="prendo",
         note="Tomar un café → prendere un caffè. «Tomar» en el sentido de consumir es prendere; «bere» es beber."),
    dict(id="l2-c-18", type="translate", topic="collocazioni", level="A1", w=5,
         prompt=TR, stem="¿Tomamos un café?", answer="Prendiamo un caffè?",
         alt=["Prendiamo un caffè"],
         note="Prendere un caffè. Ojo con las dobles: caffè, con acento grave."),
    dict(id="l2-c-19", type="cloze", topic="collocazioni", level="A1", w=5,
         prompt=CV, stem="Per andare al lavoro lei ___ l'autobus.", answer="prende",
         note="Tomar el colectivo → prendere l'autobus. «Autobus» es masculino e invariable: l'autobus, gli autobus."),
    dict(id="l2-c-20", type="choice", topic="collocazioni", level="A1", w=5,
         prompt=CE, stem="In spiaggia ___ tutto il giorno.",
         options=["prendiamo il sole", "prendiamo sole", "facciamo il sole"], answer="prendiamo il sole",
         note="Tomar sol → prendere il sole, siempre con artículo. «Hace sol» es «c'è il sole», no *fa sole."),
    dict(id="l2-c-21", type="choice", topic="collocazioni", level="A2", w=5,
         prompt=CE, stem="Luca mi ___ sempre per il mio accento.",
         options=["prende in giro", "prende per i capelli", "prende il pelo"], answer="prende in giro",
         note="Tomar el pelo → prendere in giro. Traducir literal no funciona: «pelo» en italiano es el vello, y «capelli» son los cabellos."),
    dict(id="l2-c-22", type="translate", topic="collocazioni", level="A2", w=10,
         prompt=TR, stem="Me toman el pelo.", answer="Mi prendono in giro",
         note="Prendere in giro qualcuno; el pronombre objeto va delante del verbo: mi prendono."),
    dict(id="l2-c-23", type="choice", topic="collocazioni", level="A1", w=5,
         prompt=CE, stem="A lezione gli studenti ___ appunti.",
         options=["prendono", "fanno", "danno"], answer="prendono",
         note="Tomar apuntes → prendere appunti, sin artículo."),
    dict(id="l2-c-24", type="cloze", topic="collocazioni", level="A2", w=10,
         prompt=CV, stem="Nessuno mi ___ sul serio.", answer="prende",
         note="Tomar en serio → prendere sul serio («sul» = su + il). Lo contrario: prendere alla leggera."),
    dict(id="l2-c-25", type="cloze", topic="collocazioni", level="A1", w=5,
         prompt=CV, stem="Ogni domenica io ___ in ordine la mia camera.", answer="metto",
         note="Ordenar (la pieza) → mettere in ordine. «Ordinare» es pedir en un restaurante o dar una orden."),
    dict(id="l2-c-26", type="choice", topic="collocazioni", level="A2", w=5,
         prompt=CE, stem="Ogni mese ___ un po' di soldi per le vacanze.",
         options=["metto da parte", "metto a parte", "guardo"], answer="metto da parte",
         note="Guardar / ahorrar plata → mettere da parte (o risparmiare). Trampa: «guardare» significa mirar."),
    dict(id="l2-c-27", type="cloze", topic="collocazioni", level="A2", w=6,
         prompt="Completá con el verbo de apoyo en infinitivo.", stem="Non voglio ___ tempo con questa storia.", answer="perdere",
         note="Perder tiempo → perdere tempo, igual que en castellano. Perdere también es perder el tren, las llaves, un partido."),
    dict(id="l2-c-28", type="choice", topic="collocazioni", level="A1", w=5,
         prompt=CE, stem="Questo braccialetto mi ___ fortuna.",
         options=["porta", "dà", "fa"], answer="porta",
         note="Traer / dar suerte → portare fortuna (y portare sfortuna). No se dice *dare fortuna."),
    dict(id="l2-c-29", type="choice", topic="collocazioni", level="A2", w=5,
         prompt=CE, stem="Il bambino piange tanto, ma la mamma ___ pazienza.",
         options=["porta", "tiene", "fa"], answer="porta",
         note="Tener paciencia → avere pazienza; «portare pazienza» es aguantar con paciencia. *Tenere pazienza no existe."),

    # --- fare (irregular, desde la 6) ---
    dict(id="l2-c-30", type="choice", topic="collocazioni", level="A1", w=6,
         prompt=CE, stem="La mattina ___ colazione al bar.",
         options=["faccio", "prendo", "ho"], answer="faccio",
         note="Tomar el desayuno / desayunar → fare colazione, sin artículo. *Prendere colazione es el calco típico."),
    dict(id="l2-c-31", type="translate", topic="collocazioni", level="A1", w=7,
         prompt=TR, stem="Tomo el desayuno a las siete.", answer="Faccio colazione alle sette",
         alt=["Faccio colazione alle 7"],
         note="Fare colazione + alle + hora. Almorzar y cenar son verbos: pranzare, cenare."),
    dict(id="l2-c-32", type="choice", topic="collocazioni", level="A1", w=6,
         prompt=CE, stem="Prima di uscire ___ la doccia.",
         options=["faccio", "prendo", "lavo"], answer="faccio",
         note="Ducharse → fare la doccia; bañarse → fare il bagno. No hay verbo reflexivo: *docciarsi no existe y «bagnarsi» es mojarse."),
    dict(id="l2-c-33", type="choice", topic="collocazioni", level="A1", w=6,
         prompt=CE, stem="D'estate ___ il bagno al mare ogni giorno.",
         options=["facciamo", "ci bagniamo", "prendiamo"], answer="facciamo",
         note="Bañarse (en el mar o en la bañera) → fare il bagno. «Bagnarsi» = mojarse."),
    dict(id="l2-c-34", type="choice", topic="collocazioni", level="A1", w=6,
         prompt=CE, stem="Il sabato mattina ___.",
         options=["faccio la spesa", "faccio le compre", "compro la spesa"], answer="faccio la spesa",
         note="Hacer las compras (del súper) → fare la spesa, en singular. Ir de compras (ropa, etc.) → fare spese / fare compere / fare shopping."),
    dict(id="l2-c-35", type="translate", topic="collocazioni", level="A1", w=7,
         prompt=TR, stem="Hago las compras el sábado.", answer="Faccio la spesa il sabato",
         alt=["Faccio la spesa di sabato", "Il sabato faccio la spesa", "Di sabato faccio la spesa"],
         note="Fare la spesa. «Il sabato» o «di sabato» = los sábados (habitual)."),
    dict(id="l2-c-36", type="choice", topic="collocazioni", level="A1", w=6,
         prompt=CE, stem="Posso ___ una domanda?",
         options=["fare", "chiedere", "domandare"], answer="fare",
         note="Hacer una pregunta → fare una domanda. «Chiedere» y «domandare» son preguntar como verbo, pero con el sustantivo va fare: *chiedere una domanda es el error clásico."),
    dict(id="l2-c-37", type="cloze", topic="collocazioni", level="A1", w=6,
         prompt=CV, stem="Dopo cena noi ___ una passeggiata in centro.", answer="facciamo",
         note="Dar un paseo → fare una passeggiata. Nada de *dare."),
    dict(id="l2-c-38", type="translate", topic="collocazioni", level="A1", w=9,
         prompt=TR, stem="Damos un paseo por el centro.", answer="Facciamo una passeggiata in centro",
         alt=["Facciamo un giro in centro", "Facciamo una passeggiata nel centro", "Facciamo due passi in centro"],
         note="Fare una passeggiata / fare un giro / fare due passi. «Por el centro» → in centro."),
    dict(id="l2-c-39", type="cloze", topic="collocazioni", level="A1", w=6,
         prompt=CV, stem="Il pomeriggio io ___ un giro in bici.", answer="faccio",
         note="Dar una vuelta → fare un giro (in bici, in macchina, per il centro)."),
    dict(id="l2-c-40", type="choice", topic="collocazioni", level="A2", w=6,
         prompt=CE, stem="Andiamo a ___ due passi?",
         options=["fare", "dare", "camminare"], answer="fare",
         note="Caminar un poco / dar una vuelta → fare due passi (o quattro passi)."),
    dict(id="l2-c-41", type="choice", topic="collocazioni", level="A2", w=6,
         prompt=CE, stem="Prima di salire sul treno devi ___ il biglietto.",
         options=["fare", "togliere", "tirare"], answer="fare",
         note="Sacar el boleto → fare il biglietto (también comprare il biglietto). «Togliere» es quitar y «tirare» es tirar: no sirven para «sacar» en este sentido."),
    dict(id="l2-c-42", type="cloze", topic="collocazioni", level="A2", w=6,
         prompt=CV, stem="La macchina è quasi a secco: noi ___ benzina al prossimo distributore.", answer="facciamo",
         note="Cargar nafta → fare benzina. Llenar el tanque → fare il pieno. No se dice *caricare benzina."),
    dict(id="l2-c-43", type="cloze", topic="collocazioni", level="A2", w=6,
         prompt=CV, stem="Prima del viaggio io ___ il pieno.", answer="faccio",
         note="Fare il pieno = llenar el tanque."),
    dict(id="l2-c-44", type="choice", topic="collocazioni", level="A2", w=6,
         prompt=CE, stem="Alla posta c'è sempre tanta gente e bisogna ___.",
         options=["fare la fila", "fare la cola", "prendere la fila"], answer="fare la fila",
         note="Hacer la cola → fare la fila (o fare la coda). «Cola» en italiano es el pegamento; la cola de un animal es «coda»."),
    dict(id="l2-c-45", type="choice", topic="collocazioni", level="A2", w=6,
         prompt=CE, stem="Quando guidi devi ___ attenzione.",
         options=["fare", "mettere", "avere"], answer="fare",
         note="Prestar / poner atención → fare attenzione (a). «Prestare attenzione» también existe, más formal; *mettere attenzione no."),
    dict(id="l2-c-46", type="choice", topic="collocazioni", level="A2", w=6,
         prompt=CE, stem="Mi ___ una foto, per favore?",
         options=["fai", "togli", "prendi"], answer="fai",
         note="Sacar una foto → fare una foto (o scattare una foto). Otra vez: «sacar» no es «togliere»."),
    dict(id="l2-c-47", type="cloze", topic="collocazioni", level="A2", w=6,
         prompt="Completá con el verbo de apoyo en infinitivo.", stem="Devo ___ una telefonata a mia madre.", answer="fare",
         note="Hacer una llamada → fare una telefonata. Llamar → chiamare o telefonare a."),
    dict(id="l2-c-48", type="choice", topic="collocazioni", level="A2", w=6,
         prompt=CE, stem="Non devi ___ lo spiritoso con la professoressa.",
         options=["fare", "essere", "farti"], answer="fare",
         note="Hacerse el gracioso → fare lo spiritoso, sin reflexivo. Igual: fare il furbo (hacerse el vivo), fare lo stupido, fare il finto tonto."),
    dict(id="l2-c-49", type="choice", topic="collocazioni", level="A2", w=10,
         prompt=CE, stem="Mi ___ la testa.",
         options=["fa male", "dà male", "è male"], answer="fa male",
         note="Me duele la cabeza → mi fa male la testa (concuerda con la parte: mi fanno male i piedi). Lastimarse → farsi male."),
    dict(id="l2-c-50", type="cloze", topic="collocazioni", level="A2", w=11,
         prompt="Completá con el passato prossimo del verbo de apoyo.",
         stem="Stamattina io non ___ colazione.", answer="ho fatto",
         note="Fare colazione en pasado: ho fatto colazione. Participio irregular: fatto."),
    dict(id="l2-c-51", type="choice", topic="collocazioni", level="A2", w=11,
         prompt=CE, stem="Ieri sera Marco ___ tardi: è tornato a casa alle tre.",
         options=["ha fatto", "è stato", "ha arrivato"], answer="ha fatto",
         note="Quedarse hasta tarde / llegar tarde → fare tardi. Ojo con *ha arrivato: «arrivare» va con essere."),
    dict(id="l2-c-52", type="choice", topic="collocazioni", level="A2", w=11,
         prompt=CE, stem="Marco ___ finta di non vedermi.",
         options=["ha fatto", "si è fatto", "ha fingito"], answer="ha fatto",
         note="Hacerse el que / fingir → fare finta di + infinitivo, sin reflexivo. Existe «fingere», pero su participio es «finto», no *fingito."),

    # --- dare ---
    dict(id="l2-c-53", type="choice", topic="collocazioni", level="A2", w=6,
         prompt=CE, stem="Domani ___ un esame di storia.",
         options=["do", "rendo", "prendo"], answer="do",
         note="Rendir un examen → dare un esame: en italiano el examen lo «da» el estudiante. También se acepta fare l'esame o sostenere un esame. «Rendere» es devolver."),
    dict(id="l2-c-54", type="translate", topic="collocazioni", level="A2", w=11,
         prompt=TR, stem="Rendí un examen de matemática.", answer="Ho dato un esame di matematica",
         alt=["Ho fatto un esame di matematica", "Ho sostenuto un esame di matematica",
              "Ho dato l'esame di matematica", "Ho fatto l'esame di matematica"],
         note="Dare un esame; participio: dato. «Matematica» sin h y con una sola t."),
    dict(id="l2-c-55", type="cloze", topic="collocazioni", level="A1", w=10,
         prompt=CV, stem="Mi ___ (tu) una mano con queste valigie?", answer="dai",
         note="Dar una mano → dare una mano, igual que en castellano. Seconda persona de dare: dai."),
    dict(id="l2-c-56", type="translate", topic="collocazioni", level="A1", w=10,
         prompt=TR, stem="¿Me das una mano?", answer="Mi dai una mano?",
         alt=["Mi dai una mano"],
         note="Dare una mano a qualcuno. El pronombre indirecto «mi» va delante."),
    dict(id="l2-c-57", type="choice", topic="collocazioni", level="A2", w=6,
         prompt=CE, stem="Il rumore ___ fastidio a mia nonna.",
         options=["dà", "fa", "mette"], answer="dà",
         note="Molestar → dare fastidio a qualcuno. La forma «dà» lleva acento para distinguirla de la preposición «da»."),
    dict(id="l2-c-58", type="cloze", topic="collocazioni", level="A2", w=10,
         prompt=CV, stem="Questa musica mi ___ fastidio.", answer="dà", alt=["da"],
         note="Mi dà fastidio = me molesta. Se acepta sin acento, pero lo correcto es «dà»."),
    dict(id="l2-c-59", type="choice", topic="collocazioni", level="A2", w=6,
         prompt=CE, stem="Perché non ___ retta a tua madre? Ha ragione lei.",
         options=["dai", "fai", "presti"], answer="dai",
         note="Hacer caso → dare retta a. Ojo: «fare caso a» existe, pero significa notar, reparar en algo."),
    dict(id="l2-c-60", type="choice", topic="collocazioni", level="A2", w=6,
         prompt=CE, stem="Mi ___ un passaggio alla stazione?",
         options=["dai", "porti", "fai"], answer="dai",
         note="Llevar (en auto) / alcanzar → dare un passaggio. «Mi porti alla stazione?» también funciona, pero sin «passaggio»."),
    dict(id="l2-c-61", type="choice", topic="collocazioni", level="A2", w=6,
         prompt=CE, stem="Con il direttore io ___ sempre del Lei.",
         options=["do", "parlo", "tratto"], answer="do",
         note="Tratar de usted → dare del Lei; tutear → dare del tu. «Trattare» no se usa así."),
    dict(id="l2-c-62", type="cloze", topic="collocazioni", level="A2", w=12,
         prompt=CV, stem="Signora, possiamo ___ del tu?", answer="darci",
         note="Tutearse → darsi del tu (recíproco). Con «possiamo» el pronombre se pega al infinitivo: darci."),
    dict(id="l2-c-63", type="choice", topic="collocazioni", level="A2", w=6,
         prompt=CE, stem="Puoi ___ un'occhiata a questo documento?",
         options=["dare", "gettare", "fare"], answer="dare",
         note="Echar un vistazo → dare un'occhiata a. «Gettare» es tirar, arrojar: no se «echa» la mirada en italiano."),

    # --- andare / stare / tenere / venire ---
    dict(id="l2-c-64", type="choice", topic="collocazioni", level="A1", w=6,
         prompt=CE, stem="Domenica ___ i nonni.",
         options=["andiamo a trovare", "andiamo a visitare", "visitiamo"], answer="andiamo a trovare",
         note="Ir a visitar a alguien → andare a trovare. «Visitare» es visitar un lugar o revisar (el médico visita al paciente)."),
    dict(id="l2-c-65", type="cloze", topic="collocazioni", level="A2", w=6,
         prompt=CV, stem="Io e mio fratello ___ molto d'accordo.", answer="andiamo",
         note="Llevarse bien → andare d'accordo. Y fijate el orden: en italiano «io e mio fratello», no «mio fratello e io»."),
    dict(id="l2-c-66", type="choice", topic="collocazioni", level="A2", w=6,
         prompt=CE, stem="Quest'anno ___ di moda i pantaloni larghi.",
         options=["vanno", "stanno", "fanno"], answer="vanno",
         note="Estar de moda → andare di moda (o essere di moda). *Stare di moda es calco del castellano."),
    dict(id="l2-c-67", type="choice", topic="collocazioni", level="A2", w=11,
         prompt=CE, stem="Dove ___ a finire le mie chiavi?",
         options=["sono andate", "hanno andato", "sono andati"], answer="sono andate",
         note="¿Dónde fueron a parar? → andare a finire. Con essere y concordancia: le chiavi sono andate."),
    dict(id="l2-c-68", type="choice", topic="collocazioni", level="A1", w=6,
         prompt=CE, stem="— Come stai? — ___ bene, grazie.",
         options=["Sto", "Sono", "Vado"], answer="Sto",
         note="Estar bien / mal (de salud, de ánimo) → stare bene / male. «Sono bene» no existe."),
    dict(id="l2-c-69", type="choice", topic="collocazioni", level="A2", w=6,
         prompt=CE, stem="Devi ___ attento quando attraversi la strada.",
         options=["stare", "essere", "fare"], answer="stare",
         note="Tener cuidado → stare attento (a). Concuerda: stai attenta, state attenti. «Essere attento» es ser una persona atenta."),
    dict(id="l2-c-70", type="choice", topic="collocazioni", level="A2", w=6,
         prompt=CE, stem="Durante il film i bambini non ___ mai zitti.",
         options=["stanno", "sono", "tengono"], answer="stanno",
         note="Callarse / quedarse callado → stare zitto (zitta, zitti, zitte). Existe «tacere», más formal. *Essere zitto no."),
    dict(id="l2-c-71", type="choice", topic="collocazioni", level="A2", w=6,
         prompt=CE, stem="Il treno ___ partire, dobbiamo correre.",
         options=["sta per", "va a", "è per"], answer="sta per",
         note="Estar por / ir a + infinitivo (futuro inmediato) → stare per + infinitivo. «Andare a + infinitivo» en italiano es movimiento real: vado a comprare il pane."),
    dict(id="l2-c-72", type="cloze", topic="collocazioni", level="A2", w=6,
         prompt=CV, stem="Attenzione, la lezione ___ per cominciare.", answer="sta",
         note="Stare per + infinitivo = estar a punto de."),
    dict(id="l2-c-73", type="translate", topic="collocazioni", level="A2", w=6,
         prompt=TR, stem="Estoy por salir.", answer="Sto per uscire",
         note="Stare per + infinitivo. «Salir» → uscire, no *salire (que es subir)."),
    dict(id="l2-c-74", type="cloze", topic="collocazioni", level="B1", w=6,
         prompt=CV, stem="Io ___ molto alla mia famiglia.", answer="tengo",
         note="Tenere a qualcosa / qualcuno = importarle a uno, querer mucho. No significa «tener»: «tengo alla mia famiglia» = mi familia me importa."),
    dict(id="l2-c-75", type="choice", topic="collocazioni", level="A2", w=6,
         prompt=CE, stem="Puoi ___ d'occhio i bambini mentre cucino?",
         options=["tenere", "stare", "avere"], answer="tenere",
         note="Echarle un ojo / vigilar → tenere d'occhio."),
    dict(id="l2-c-76", type="choice", topic="collocazioni", level="B1", w=6,
         prompt=CE, stem="Devi ___ conto anche del traffico.",
         options=["tenere", "avere", "prendere"], answer="tenere",
         note="Tener en cuenta → tenere conto di. *Avere in conto no existe."),
    dict(id="l2-c-77", type="choice", topic="collocazioni", level="B1", w=6,
         prompt=CE, stem="Non voglio ___ con quella gente.",
         options=["avere a che fare", "avere che fare", "tenere a che fare"], answer="avere a che fare",
         note="Tener que ver con → avere a che fare con. «Non ha niente a che fare con» = no tiene nada que ver con."),
    dict(id="l2-c-78", type="choice", topic="collocazioni", level="A2", w=11,
         prompt=CE, stem="All'improvviso mi ___ in mente un'idea.",
         options=["è venuta", "ha venuto", "è venuto"], answer="è venuta",
         note="Ocurrírsele algo a uno → venire in mente. Con essere, y el participio concuerda con lo que viene: un'idea → venuta."),
    dict(id="l2-c-79", type="choice", topic="collocazioni", level="B1", w=11,
         prompt=CE, stem="Come ___ della festa?",
         options=["sei venuto a sapere", "hai venuto a sapere", "sei venuto a conoscere"], answer="sei venuto a sapere",
         note="Enterarse de → venire a sapere (di). Venire va con essere."),
    dict(id="l2-c-80", type="choice", topic="collocazioni", level="A2", w=10,
         prompt=CE, stem="Quando sei via, ___ tanto.",
         options=["mi manchi", "ti estraño", "ti manco"], answer="mi manchi",
         note="Extrañar a alguien → mancare, invertido como piacere: «mi manchi» = te extraño (literalmente «me faltás»). «Ti manco» sería «me extrañás»."),
    dict(id="l2-c-81", type="translate", topic="collocazioni", level="A2", w=10,
         prompt=TR, stem="Te extraño.", answer="Mi manchi",
         note="Mancare funciona como piacere: mi manchi (te extraño), mi manca Roma (extraño Roma), mi mancano i miei amici."),

    # --- prendere / mettersi al passato ---
    dict(id="l2-c-82", type="choice", topic="collocazioni", level="A2", w=11,
         prompt=CE, stem="Alla fine Laura ___ una decisione.",
         options=["ha preso", "ha fatto", "ha dato"], answer="ha preso",
         note="Tomar una decisión → prendere una decisione. Participio irregular: preso."),
    dict(id="l2-c-83", type="choice", topic="collocazioni", level="A2", w=11,
         prompt=CE, stem="Anna ___ freddo sotto la pioggia e ora è a letto con la febbre.",
         options=["ha preso", "ha fatto", "ha tenuto"], answer="ha preso",
         note="Agarrar frío / resfriarse → prendere freddo. Distinto de avere freddo (tener frío, la sensación)."),
    dict(id="l2-c-84", type="choice", topic="collocazioni", level="B1", w=11,
         prompt=CE, stem="Marco e Sara ___ in affitto una casa al mare per agosto.",
         options=["hanno preso", "hanno avuto", "hanno fatto"], answer="hanno preso",
         note="Alquilar (como inquilino) → prendere in affitto o affittare. Dare in affitto = alquilar como dueño."),
    dict(id="l2-c-85", type="choice", topic="collocazioni", level="A2", w=11,
         prompt=CE, stem="Stamattina ___ il treno delle otto.",
         options=["ho perso", "sono perso", "ho perdito"], answer="ho perso",
         note="Perdí el tren → ho perso il treno (participio perso; «perduto» también es correcto). Con avere."),
    dict(id="l2-c-86", type="choice", topic="collocazioni", level="A2", w=11,
         prompt=CE, stem="Alla fine ___ ragione tu.",
         options=["hai avuto", "sei stato", "hai tenuto"], answer="hai avuto",
         note="Tener razón en pasado: hai avuto ragione. Nada de essere ni de tenere."),
    dict(id="l2-c-87", type="choice", topic="collocazioni", level="A2", w=12,
         prompt=CE, stem="Ogni volta che vede quel film, Sara ___ a piangere.",
         options=["si mette", "mette", "si pone"], answer="si mette",
         note="Ponerse a + infinitivo → mettersi a + infinitivo. *Porsi a no; y sin pronombre «mettere» es poner algo."),
    dict(id="l2-c-88", type="choice", topic="collocazioni", level="A2", w=12,
         prompt=CE, stem="Alla fine ___ sull'orario della riunione.",
         options=["ci mettiamo d'accordo", "ci poniamo d'accordo", "mettiamo d'accordo"], answer="ci mettiamo d'accordo",
         note="Ponerse de acuerdo → mettersi d'accordo (reflexivo). Distinto de andare d'accordo (llevarse bien) y essere d'accordo (estar de acuerdo)."),
    dict(id="l2-c-89", type="translate", topic="collocazioni", level="A2", w=12,
         prompt=TR, stem="Nos ponemos de acuerdo mañana.", answer="Ci mettiamo d'accordo domani",
         alt=["Domani ci mettiamo d'accordo"],
         note="Mettersi d'accordo: ci mettiamo d'accordo."),

    # --- verbi pronominali (ne/ci desde la 21) ---
    dict(id="l2-c-90", type="choice", topic="collocazioni", level="B1", w=21,
         prompt=CE, stem="Non ce la ___ più, sono stanchissimo.",
         options=["faccio", "fo", "posso"], answer="faccio",
         note="No doy más → non ce la faccio più. Farcela = lograr, poder con algo: ce la fai? (¿podés?)."),
    dict(id="l2-c-91", type="choice", topic="collocazioni", level="B1", w=22,
         prompt=CE, stem="Alla fine ___ a finire il lavoro.",
         options=["ce l'abbiamo fatta", "ce lo abbiamo fatto", "ce l'abbiamo fatto"], answer="ce l'abbiamo fatta",
         note="Farcela en pasado: el participio concuerda siempre con «la»: ce l'ho fatta, ce l'abbiamo fatta."),
    dict(id="l2-c-92", type="choice", topic="collocazioni", level="B1", w=21,
         prompt=CE, stem="È tardi, ___.",
         options=["me ne vado", "mi vado", "me voy"], answer="me ne vado",
         note="Irse → andarsene: me ne vado, te ne vai, se ne va, ce ne andiamo, ve ne andate, se ne vanno. El «ne» es obligatorio."),
    dict(id="l2-c-93", type="choice", topic="collocazioni", level="B1", w=21,
         prompt=CE, stem="I ragazzi ___ senza salutare.",
         options=["se ne sono andati", "se ne hanno andato", "si sono andati"], answer="se ne sono andati",
         note="Andarsene al passato: essere + participio concordado, con el «ne» en el medio: se ne sono andati."),
    dict(id="l2-c-94", type="translate", topic="collocazioni", level="B1", w=21,
         prompt=TR, stem="Se fue sin decir nada.", answer="Se n'è andato senza dire niente",
         alt=["Se n'è andata senza dire niente", "Se ne è andato senza dire niente", "Se ne è andata senza dire niente",
              "Se n'è andato senza dire nulla", "Se n'è andata senza dire nulla",
              "Se ne è andato senza dire nulla", "Se ne è andata senza dire nulla"],
         note="Andarsene: se n'è andato / andata. «Ne» se apostrofa delante de «è»."),
    dict(id="l2-c-95", type="choice", topic="collocazioni", level="B1", w=21,
         prompt=CE, stem="Parlo poco tedesco, ma ___.",
         options=["me la cavo", "mi cavo", "me la salvo"], answer="me la cavo",
         note="Arreglárselas / defenderse → cavarsela: me la cavo, te la cavi, se la cava. Igual que farcela, lleva «la» fija."),
    dict(id="l2-c-96", type="choice", topic="collocazioni", level="B1", w=21,
         prompt=CE, stem="Per andare a Roma in treno ___ tre ore.",
         options=["ci vogliono", "ci vuole", "si vogliono"], answer="ci vogliono",
         note="Se necesita / se tarda → volerci, que concuerda con la cosa: ci vuole un'ora, ci vogliono tre ore."),
    dict(id="l2-c-97", type="choice", topic="collocazioni", level="B1", w=21,
         prompt=CE, stem="Quanto ___ per arrivare al lavoro?",
         options=["ci metti", "metti", "ti metti"], answer="ci metti",
         note="Tardar (una persona) → metterci: ci metto venti minuti. Volerci es impersonal (ci vogliono venti minuti); metterci tiene sujeto personal."),
    dict(id="l2-c-98", type="translate", topic="collocazioni", level="B1", w=21,
         prompt=TR, stem="Tardo veinte minutos en llegar.", answer="Ci metto venti minuti ad arrivare",
         alt=["Ci metto venti minuti per arrivare", "Ci metto 20 minuti ad arrivare", "Ci metto 20 minuti per arrivare",
              "Impiego venti minuti ad arrivare", "Impiego venti minuti per arrivare"],
         note="Metterci + tiempo + a / per + infinitivo. Con «io» como sujeto no se puede usar volerci."),

    # ======================= DISCORSIVI =======================
    dict(id="l2-d-01", type="choice", topic="discorsivi", level="A2", w=8,
         prompt=CM, stem="— Vieni al mare con noi domenica? — ___! Ma devo lavorare.",
         options=["Magari", "Mica", "Appunto"], answer="Magari",
         note="«Magari!» solo y exclamativo = ¡ojalá! / ya quisiera. Es un sí con pena, nunca un rechazo (para «ni loco» está neanche per sogno)."),
    dict(id="l2-d-02", type="cloze", topic="discorsivi", level="A2", w=8,
         prompt=CG, stem="___ (ojalá) domani non piove!", answer="Magari", alt=["magari"],
         note="Magari + indicativo = quizás, con esperanza («ojalá que»). Coloquial, muy frecuente."),
    dict(id="l2-d-03", type="choice", topic="discorsivi", level="A2", w=8,
         prompt=CM, stem="Ho la febbre e mi fa male tutto: ___ è l'influenza.",
         options=["forse", "magari", "meno male"], answer="forse",
         note="«Forse» = quizás, neutro. «Magari» lleva un deseo adentro (ojalá), así que no encaja con algo que no se quiere, como una gripe."),
    dict(id="l2-d-04", type="cloze", topic="discorsivi", level="A2", w=8,
         prompt=CG, stem="Non è ___ (para nada) vero!", answer="mica",
         note="«Mica» refuerza la negación, registro coloquial: non è mica vero = no es para nada cierto. Sin «non» va delante del verbo: mica è vero."),
    dict(id="l2-d-05", type="choice", topic="discorsivi", level="A2", w=10,
         prompt=CM, stem="— Sei arrabbiato? — No, ___ sono arrabbiato, sono solo stanco.",
         options=["mica", "magari", "appunto"], answer="mica",
         note="«Mica» delante del verbo sustituye a «non»: mica sono arrabbiato = para nada estoy enojado. Coloquial."),
    dict(id="l2-d-06", type="choice", topic="discorsivi", level="A2", w=12,
         prompt=CM, stem="— Ti piace il mio disegno? — ___ male!",
         options=["Mica", "Meno", "Anzi"], answer="Mica",
         note="«Mica male» = nada mal, está bueno. No confundir con «meno male» = menos mal."),
    dict(id="l2-d-07", type="choice", topic="discorsivi", level="B1", w=14,
         prompt=CM, stem="— Sei stanco? — ___, per questo vado a letto presto.",
         options=["Appunto", "Anzi", "Mica"], answer="Appunto",
         note="«Appunto» = justamente, exacto, precisamente (también «per l'appunto»). Como sustantivo, «gli appunti» son los apuntes."),
    dict(id="l2-d-08", type="cloze", topic="discorsivi", level="B1", w=16,
         prompt=CG, stem="— Il treno è in ritardo. — ___ (justamente), per questo sono ancora qui.",
         answer="Appunto", alt=["appunto"],
         note="Appunto confirma lo que dijo el otro y lo usa como explicación: «justamente, por eso»."),
    dict(id="l2-d-09", type="choice", topic="discorsivi", level="A2", w=12,
         prompt=CM, stem="___ è tardi, andiamo a casa.",
         options=["Ormai", "Magari", "Anzi"], answer="Ormai",
         note="«Ormai» = ya, a esta altura, con matiz de que no hay vuelta atrás. «Già» es el «ya» de algo cumplido: ho già mangiato."),
    dict(id="l2-d-10", type="choice", topic="discorsivi", level="B1", w=14,
         prompt=CM, stem="Sono le nove: ___ non arriva più.",
         options=["ormai", "già", "appunto"], answer="ormai",
         note="Ormai + negación = a esta altura ya no. «Già» no funciona con el presente negativo en este sentido."),
    dict(id="l2-d-11", type="choice", topic="discorsivi", level="B1", w=14,
         prompt=CM, stem="Non è antipatico, ___ è molto gentile.",
         options=["anzi", "infatti", "cioè"], answer="anzi",
         note="«Anzi» = al contrario, es más: corrige o da vuelta lo anterior. «Infatti» confirma, no contradice."),
    dict(id="l2-d-12", type="cloze", topic="discorsivi", level="B1", w=16,
         prompt=CG, stem="Il film mi è piaciuto, ___ (es más) lo voglio rivedere.", answer="anzi",
         note="Anzi también intensifica: «es más, incluso». Neutro, se usa en todos los registros."),
    dict(id="l2-d-13", type="choice", topic="discorsivi", level="B1", w=15,
         prompt=CM, stem="Non so se vengo alla festa; ___ ti chiamo domani.",
         options=["comunque", "siccome", "cioè"], answer="comunque",
         note="«Comunque» = de todos modos, igual, en cualquier caso. No es «como que» ni «como»: el «como» causal es «siccome»."),
    dict(id="l2-d-14", type="choice", topic="discorsivi", level="B1", w=18,
         prompt=CM, stem="È caro, ___ lo compro.",
         options=["comunque", "quindi", "infatti"], answer="comunque",
         note="Comunque = igual, así y todo. Muy usado también como muletilla para cambiar de tema: «comunque, dicevo...»."),
    dict(id="l2-d-15", type="choice", topic="discorsivi", level="B2", w=30,
         prompt=CM, stem="— Ha comprato una Ferrari. — ___? Con quello stipendio?",
         options=["Addirittura", "Appunto", "Semmai"], answer="Addirittura",
         note="«Addirittura» = incluso, hasta; solo y con entonación de pregunta expresa sorpresa por algo exagerado: ¿tanto?, ¿en serio?"),
    dict(id="l2-d-16", type="cloze", topic="discorsivi", level="B2", w=32,
         prompt=CG, stem="Ha invitato tutti, ___ (incluso, hasta) il suo ex.", answer="addirittura",
         alt=["persino", "perfino"],
         note="Addirittura = incluso, hasta (también persino / perfino). Marca que algo va más allá de lo esperado."),
    dict(id="l2-d-17", type="choice", topic="discorsivi", level="B2", w=30,
         prompt=CM, stem="— Com'è andato l'esame? — ___, non benissimo.",
         options=["Insomma", "Addirittura", "Appunto"], answer="Insomma",
         note="«Insomma» como respuesta = más o menos, así así. Al inicio de frase = en fin, en resumen; con enojo = ¡basta!"),
    dict(id="l2-d-18", type="cloze", topic="discorsivi", level="B2", w=32,
         prompt=CG, stem="Piove, fa freddo, il treno è in ritardo: ___ (en fin, en resumen) una giornata orribile.",
         answer="insomma", alt=["Insomma"],
         note="Insomma cierra una enumeración y la resume: en fin, total que."),
    dict(id="l2-d-19", type="choice", topic="discorsivi", level="A2", w=16,
         prompt=CM, stem="Anche Marco viene, e viene ___ Lucia.",
         options=["pure", "piuttosto", "mica"], answer="pure",
         note="«Pure» = anche, también (más coloquial, frecuente en el centro-sur). No es «puro»."),
    dict(id="l2-d-20", type="choice", topic="discorsivi", level="A2", w=12,
         prompt=CM, stem="— Posso entrare? — Entra ___!",
         options=["pure", "proprio", "piuttosto"], answer="pure",
         note="Imperativo + pure concede permiso: entra pure = entrá nomás, adelante. Fai pure, dica pure."),
    dict(id="l2-d-21", type="choice", topic="discorsivi", level="B1", w=14,
         prompt=CM, stem="Non ho ___ voglia di uscire.",
         options=["proprio", "pure", "piuttosto"], answer="proprio",
         note="«Proprio» = realmente, justo, precisamente; con negación = para nada. Como adjetivo sí es «propio» (la propria casa)."),
    dict(id="l2-d-22", type="cloze", topic="discorsivi", level="B1", w=15,
         prompt=CG, stem="È ___ (justo, precisamente) quello che volevo.", answer="proprio",
         note="Proprio quello = justo eso. Otros usos: proprio adesso (justo ahora), proprio tu (vos, precisamente)."),
    dict(id="l2-d-23", type="choice", topic="discorsivi", level="B1", w=20,
         prompt=CM, stem="Non mi va la pizza; ___ mangio un panino.",
         options=["piuttosto", "pure", "proprio"], answer="piuttosto",
         note="«Piuttosto» = más bien, mejor (preferencia). «Piuttosto che» = en vez de, antes que. Ojo: no tiene nada que ver con «puesto que»."),
    dict(id="l2-d-24", type="choice", topic="discorsivi", level="B1", w=14,
         prompt=CM, stem="— Hai la faccia stanca. — ___, ho dormito tre ore.",
         options=["Infatti", "Invece", "Anzi"], answer="Infatti",
         note="«Infatti» confirma lo que se acaba de decir: efectivamente, tal cual. Trampa: el «de hecho» castellano que corrige o intensifica («no es malo; de hecho es buenísimo») no es infatti, es «anzi»."),
    dict(id="l2-d-25", type="choice", topic="discorsivi", level="B1", w=16,
         prompt=CM, stem="Non è un bravo studente; ___ non studia mai.",
         options=["infatti", "anzi", "invece"], answer="infatti",
         note="Infatti da la prueba de lo dicho (no estudia → confirma que no es buen alumno). Anzi lo contradiría; invece contrasta con otra cosa."),
    dict(id="l2-d-26", type="choice", topic="discorsivi", level="A2", w=14,
         prompt=CM, stem="Io prendo il pesce; Marco ___ prende la carne.",
         options=["invece", "infatti", "anzi"], answer="invece",
         note="«Invece» = en cambio. Puede ir en el medio de la frase, como acá. «Invece di» = en vez de."),
    dict(id="l2-d-27", type="cloze", topic="discorsivi", level="B1", w=16,
         prompt=CG, stem="___ (en vez de) studiare, guarda la TV.", answer="Invece di",
         alt=["invece di", "Anziché", "anziché", "Al posto di", "al posto di"],
         note="Invece di + infinitivo = en vez de. Más formal: anziché."),
    dict(id="l2-d-28", type="choice", topic="discorsivi", level="A1", w=10,
         prompt=CM, stem="Il ristorante è buono, ___ è caro.",
         options=["però", "perciò", "perché"], answer="però",
         note="«Però» = pero (un poco más enfático que «ma»); puede ir al final: «È caro, però!». No confundir con perciò = por eso."),
    dict(id="l2-d-29", type="choice", topic="discorsivi", level="A2", w=14,
         prompt=CM, stem="Ho perso l'autobus, ___ sono arrivato tardi.",
         options=["quindi", "però", "cioè"], answer="quindi",
         note="«Quindi» = así que, por lo tanto. Muy frecuente en la lengua hablada; sinónimos: perciò, dunque."),
    dict(id="l2-d-30", type="choice", topic="discorsivi", level="B1", w=28,
         prompt=CM, stem="___, dove eravamo rimasti?",
         options=["Dunque", "Cioè", "Anzi"], answer="Dunque",
         note="«Dunque» = entonces, pues; retoma el hilo del discurso. Más formal que quindi y allora."),
    dict(id="l2-d-31", type="choice", topic="discorsivi", level="A1", w=8,
         prompt=CM, stem="— Non ho fame. — ___ non mangiamo.",
         options=["Allora", "Cioè", "Anzi"], answer="Allora",
         note="«Allora» = entonces (consecuencia). También abre un turno: «Allora, cosa facciamo?»."),
    dict(id="l2-d-32", type="choice", topic="discorsivi", level="A2", w=15,
         prompt=CM, stem="___ non c'era internet e si scrivevano lettere.",
         options=["Allora", "Ormai", "Insomma"], answer="Allora",
         note="«Allora» también es temporal: en aquel entonces. «Da allora» = desde entonces."),
    dict(id="l2-d-33", type="choice", topic="discorsivi", level="A2", w=14,
         prompt=CM, stem="Vengo tra un'ora, ___ alle sei.",
         options=["cioè", "così", "cosa"], answer="cioè",
         note="«Cioè» = o sea, es decir. También muletilla juvenil («cioè, non so...»)."),
    dict(id="l2-d-34", type="choice", topic="discorsivi", level="B1", w=18,
         prompt=CM, stem="Ho finito, ___: manca solo la conclusione.",
         options=["praticamente", "addirittura", "anzi"], answer="praticamente",
         note="«Praticamente» = prácticamente, básicamente. Muletilla coloquial muy común."),
    dict(id="l2-d-35", type="choice", topic="discorsivi", level="B1", w=20,
         prompt=CM, stem="Non mi aspettare per cena, ___ arrivo tardi.",
         options=["tanto", "così", "pure"], answer="tanto",
         note="«Tanto» al inicio de frase = total (rioplatense): «total, llego tarde». No es cantidad."),
    dict(id="l2-d-36", type="choice", topic="discorsivi", level="A2", w=18,
         prompt=CM, stem="— Grazie mille per l'aiuto! — ___!",
         options=["Figurati", "Magari", "Boh"], answer="Figurati",
         note="«Figurati» (formal: si figuri) = de nada, no es nada. También «ni lo pienses» o irónico «imaginate»."),
    dict(id="l2-d-37", type="choice", topic="discorsivi", level="A1", w=10,
         prompt=CM, stem="___ il tuo caffè.",
         options=["Ecco", "Ormai", "Beh"], answer="Ecco",
         note="«Ecco» = acá está, he aquí. Con pronombre: eccolo, eccomi. «Ecco perché» = por eso; «ecco!» = ¡eso!"),
    dict(id="l2-d-38", type="choice", topic="discorsivi", level="A2", w=10,
         prompt=CM, stem="— Vieni stasera? — ___, non lo so ancora.",
         options=["Beh", "Ecco", "Magari"], answer="Beh",
         note="«Beh» (también «be'») = bueno..., y... expresa duda o introduce una respuesta."),
    dict(id="l2-d-39", type="choice", topic="discorsivi", level="A2", w=8,
         prompt=CM, stem="___, vieni con noi! È una bella festa.",
         options=["Dai", "Boh", "Mah"], answer="Dai",
         note="«Dai» = dale, vamos (para animar). También incredulidad: «ma dai!» = ¡no me digas! Es el imperativo de dare, pero acá es interjección."),
    dict(id="l2-d-40", type="choice", topic="discorsivi", level="A2", w=8,
         prompt=CM, stem="— Dov'è Marco? — ___, non lo so.",
         options=["Boh", "Dai", "Ecco"], answer="Boh",
         note="«Boh» = ni idea, qué sé yo. Coloquial, acompañado del gesto de encoger los hombros."),
    dict(id="l2-d-41", type="choice", topic="discorsivi", level="A2", w=12,
         prompt=CM, stem="— Secondo te viene? — ___, ho i miei dubbi.",
         options=["Mah", "Dai", "Ecco"], answer="Mah",
         note="«Mah» = y... no sé, expresa escepticismo o duda. «Boh» es ni idea; «mah» es «hmm, lo dudo»."),
    dict(id="l2-d-42", type="choice", topic="discorsivi", level="B1", w=18,
         prompt=CM, stem="— Sei stanco? — ___! Ho lavorato dodici ore.",
         options=["Per forza", "Per carità", "Magari"], answer="Per forza",
         note="«Per forza» = obvio, por supuesto (no podía ser de otro modo); también «a la fuerza, sí o sí»: devo farlo per forza."),
    dict(id="l2-d-43", type="choice", topic="discorsivi", level="B1", w=20,
         prompt=CM, stem="___, hai visto Marco ieri?",
         options=["A proposito", "Appunto", "Tra l'altro"], answer="A proposito",
         note="«A proposito» = por cierto, a propósito (cambio de tema). «A proposito di» = respecto a. Hacer algo adrede es «apposta»."),
    dict(id="l2-d-44", type="choice", topic="discorsivi", level="B2", w=30,
         prompt=CM, stem="Il film è lungo e noioso; ___ costa pure tanto.",
         options=["tra l'altro", "altro che", "semmai"], answer="tra l'altro",
         note="«Tra l'altro» = además, entre otras cosas. Suma un argumento más."),
    dict(id="l2-d-45", type="choice", topic="discorsivi", level="B1", w=28,
         prompt=CM, stem="— Questo ristorante è caro. — ___, venti euro per un primo sono troppi.",
         options=["In effetti", "Invece", "Semmai"], answer="In effetti",
         note="«In effetti» = efectivamente, la verdad que sí: concede después de pensarlo. Parecido a infatti, pero más de reconocimiento."),
    dict(id="l2-d-46", type="choice", topic="discorsivi", level="B2", w=32,
         prompt=CM, stem="Non ho voglia di uscire; ___ piove.",
         options=["oltretutto", "altro che", "tutt'al più"], answer="oltretutto",
         note="«Oltretutto» = encima, además de todo. Agrega un motivo más a algo ya negativo."),
    dict(id="l2-d-47", type="choice", topic="discorsivi", level="B2", w=32,
         prompt=CM, stem="Non sono io che devo scusarmi: ___ sei tu.",
         options=["semmai", "altro che", "per forza"], answer="semmai",
         note="«Semmai» = en todo caso, si acaso. También introduce condición: semmai venisse, avvisami."),
    dict(id="l2-d-48", type="choice", topic="discorsivi", level="B2", w=34,
         prompt=CM, stem="Non ci vorrà molto: ___ mezz'ora.",
         options=["tutt'al più", "addirittura", "per forza"], answer="tutt'al più",
         note="«Tutt'al più» = a lo sumo, como mucho (también «al massimo»)."),
    dict(id="l2-d-49", type="choice", topic="discorsivi", level="B2", w=30,
         prompt=CM, stem="— Ti è piaciuto il concerto? — ___! È stato fantastico.",
         options=["Altro che", "Macché", "Mica"], answer="Altro che",
         note="«Altro che!» = ¡y cómo!, ¡ya lo creo! Con dos términos, «altro che X, Y» = nada de X, Y."),
    dict(id="l2-d-50", type="choice", topic="discorsivi", level="B1", w=20,
         prompt=CM, stem="Domani ___ piove: guarda quelle nuvole.",
         options=["di sicuro", "per carità", "semmai"], answer="di sicuro",
         note="«Di sicuro» = seguro, seguro que. Sinónimos: sicuramente, certamente."),
    dict(id="l2-d-51", type="choice", topic="discorsivi", level="B1", w=28,
         prompt=CM, stem="— Vuoi un altro pezzo di torta? — ___, sono pieno!",
         options=["Per carità", "Per forza", "Altro che"], answer="Per carità",
         note="«Per carità!» = ¡por favor, no!, ¡ni hablar! También «per carità, fai come vuoi» = bueno, allá vos."),
    dict(id="l2-d-52", type="choice", topic="discorsivi", level="A2", w=14,
         prompt=CM, stem="___ che sei arrivato: avevo paura.",
         options=["Meno male", "Mica male", "Per forza"], answer="Meno male",
         note="«Meno male (che)» = menos mal (que). «Mica male» es otra cosa: nada mal."),
    dict(id="l2-d-53", type="choice", topic="discorsivi", level="B1", w=19,
         prompt=CM, stem="___ se domani ci sarà il sole.",
         options=["Chissà", "Boh", "Magari"], answer="Chissà",
         note="«Chissà» = quién sabe, a saber. Con «che» + congiuntivo = ojalá que: chissà che non venga."),
    dict(id="l2-d-54", type="choice", topic="discorsivi", level="A2", w=12,
         prompt=CM, stem="— Oggi è domenica, i negozi sono chiusi. — ___, non ci ho pensato.",
         options=["Già", "Mica", "Anzi"], answer="Già",
         note="«Già» como respuesta = ah, cierto; claro. Además del «ya» temporal: sono già le otto."),
    dict(id="l2-d-55", type="choice", topic="discorsivi", level="A2", w=16,
         prompt=CM, stem="— Non ti piace la pasta? — ___ mi piace!",
         options=["Sì che", "Mica", "Appunto"], answer="Sì che",
         note="«Sì che» = claro que sí, refuerza la afirmación contra una duda. El contrario: «no che non mi piace»."),
    dict(id="l2-d-56", type="choice", topic="discorsivi", level="B1", w=18,
         prompt=CM, stem="— Ho vinto la lotteria! — ___! Non ci credo.",
         options=["Ma va", "Per forza", "Appunto"], answer="Ma va",
         note="«Ma va'!» (o «ma va») = ¡dale!, ¡no me digas! Incredulidad, como «ma dai»."),
    dict(id="l2-d-57", type="choice", topic="discorsivi", level="B1", w=18,
         prompt=CM, stem="— Hai finito i compiti? — ___! Non ho nemmeno cominciato.",
         options=["Macché", "Altro che", "Sì che"], answer="Macché",
         note="«Macché» = ¡qué va!, ¡para nada! Niega con énfasis. «Altro che» sería lo contrario (¡y cómo!)."),
    dict(id="l2-d-58", type="choice", topic="discorsivi", level="B1", w=18,
         prompt=CM, stem="— Mi presti la macchina? — ___!",
         options=["Neanche per sogno", "Magari", "Meno male"], answer="Neanche per sogno",
         note="«Neanche per sogno» = ni en sueños, ni loco. Un «no» rotundo; acá «magari» no encaja porque expresaría un deseo."),
    dict(id="l2-d-59", type="choice", topic="discorsivi", level="B1", w=18,
         prompt=CM, stem="___, ho dimenticato le chiavi!",
         options=["Cavolo", "Boh", "Beh"], answer="Cavolo",
         note="«Cavolo!» = ¡uy!, ¡la pucha! Eufemismo suave de una palabrota. «Col cavolo» = ni a palos; «non capisco un cavolo» = no entiendo nada."),
    dict(id="l2-d-60", type="cloze", topic="discorsivi", level="B2", w=30,
         prompt=CG, stem="___ (ojalá) avessi più tempo!", answer="Magari", alt=["magari"],
         note="Magari + congiuntivo imperfetto = deseo irreal: ojalá tuviera más tiempo. Los tres usos de magari: ¡ojalá! (solo), quizás (con indicativo), ojalá que (con congiuntivo)."),
]
