# -*- coding: utf-8 -*-
"""Mejoras estructurales, Stagione 3: semanas 27 (avverbi), 28 (connettivi)
y 35 (voce passiva). Ejercicios que cierran el desfase con la lección."""

CE = "Elegí la forma correcta."
CO = "Completá la frase."
TR = "Traducí al italiano."
VA = "Trova l'errore: tocá la palabra que está mal y corregila."

ITEMS = [
    # ================= Settimana 27: Avverbi =================
    dict(id="mj-27-01", type="choice", topic="avverbi", level="B1", w=27, prompt=CE,
         stem="Vai ___: la strada è ghiacciata.",
         options=["piano", "pianamente", "pianomente"], answer="piano",
         note="Con andare, el adjetivo masculino hace de adverbio y no cambia: andare piano."),
    dict(id="mj-27-02", type="choice", topic="avverbi", level="B1", w=27, prompt=CE,
         stem="Quella borsa costa ___.",
         options=["caro", "cara", "caramente"], answer="caro",
         note="Costare caro: el adjetivo queda en masculino singular, como adverbio fijo."),
    dict(id="mj-27-03", type="cloze", topic="avverbi", level="B1", w=27,
         prompt="Formá el adverbio a partir del adjetivo entre paréntesis.",
         stem="Il pugile ha colpito l'avversario ___ (violento).", answer="violentemente",
         note="Excepción de -mente: violento → violentemente (no «violentamente»)."),
    dict(id="mj-27-04", type="cloze", topic="avverbi", level="B1", w=27,
         prompt="Formá el adverbio a partir del adjetivo entre paréntesis.",
         stem="Mi ha sfiorato ___ il braccio (leggero).", answer="leggermente",
         note="leggero → leggermente: pierde la e y no sale «leggeramente»."),
    dict(id="mj-27-05", type="choice", topic="avverbi", level="B1", w=27, prompt=CE,
         stem="Oggi mi sento ___ di ieri.",
         options=["meglio", "migliore", "più bene"], answer="meglio",
         note="Con un verbo va el adverbio: sentirsi meglio. Migliore es adjetivo y «più bene» no existe."),
    dict(id="mj-27-06", type="choice", topic="avverbi", level="B1", w=27, prompt=CE,
         stem="La squadra ha giocato ___ della settimana scorsa.",
         options=["peggio", "peggiore", "più male"], answer="peggio",
         note="Peggio modifica al verbo (ha giocato); peggiore acompañaría a un sustantivo."),
    dict(id="mj-27-07", type="cloze", topic="avverbi", level="B1", w=27,
         prompt="Respondé con el superlativo de bene (una sola palabra).",
         stem="— Com'è andato l'esame? — ___!", answer="Benissimo",
         alt=["benissimo"],
         note="bene + -issimo = benissimo. Con male: malissimo."),
    dict(id="mj-27-08", type="choice", topic="avverbi", level="B1", w=27,
         prompt="Elegí el adverbio que significa «dentro de un rato».",
         stem="Ti richiamo ___.",
         options=["fra poco", "poco fa", "ormai"], answer="fra poco",
         note="Fra poco mira al futuro; poco fa, al pasado (hace un rato)."),
    dict(id="mj-27-09", type="choice", topic="avverbi", level="B1", w=27,
         prompt="Elegí el adverbio que significa «a esta altura».",
         stem="Sono le due di notte: ___ è troppo tardi per telefonare.",
         options=["ormai", "appena", "mai"], answer="ormai",
         note="Ormai = a esta altura, ya. Appena significa recién o apenas."),
    dict(id="mj-27-10", type="translate", topic="avverbi", level="B1", w=27, prompt=TR,
         stem="Acabo de llegar.",
         answer="Sono appena arrivato",
         alt=["Sono appena arrivata"],
         note="Appena = recién; los adverbios cortos van entre el auxiliar y el participio."),
    dict(id="mj-27-11", type="translate", topic="avverbi", level="B1", w=27, prompt=TR,
         stem="Hablá más despacio, por favor.",
         answer="Parla più piano, per favore",
         alt=["Parla più lentamente, per favore", "Parla più piano per favore",
              "Parla più lentamente per favore", "Parla più piano, per piacere"],
         note="Piano es adjetivo usado como adverbio; también vale più lentamente."),
    dict(id="mj-27-12", type="fixerr", topic="avverbi", level="B1", w=27, prompt=VA, cat="lessico",
         stem="Stanotte ho dormito buono.", bad="buono", good="bene",
         answer="Stanotte ho dormito bene.",
         note="Modifica al verbo, así que va el adverbio bene; buono acompaña a un sustantivo."),
    dict(id="mj-27-13", type="fixerr", topic="avverbi", level="B1", w=27, prompt=VA, cat="ortografia",
         stem="Mi hanno accolto gentilemente.", bad="gentilemente", good="gentilmente",
         answer="Mi hanno accolto gentilmente.",
         note="Gentile termina en vocal + -le: pierde la e, gentilmente."),

    # ================= Settimana 28: Connettivi =================
    dict(id="mj-28-01", type="choice", topic="connettivi", level="B1", w=28, prompt=CE,
         stem="Dopo ___ i piatti, ho guardato un film.",
         options=["aver lavato", "lavare", "aver lavare"], answer="aver lavato",
         note="Dopo pide infinitivo compuesto: dopo aver lavato."),
    dict(id="mj-28-02", type="cloze", topic="connettivi", level="B1", w=28,
         prompt="Completá con el conector y el infinitivo.",
         stem="Prima ___ (uscire), spegni la luce.", answer="di uscire",
         note="Prima di + infinitivo simple."),
    dict(id="mj-28-03", type="choice", topic="connettivi", level="B1", w=28, prompt=CE,
         stem="Ti aspetto ___ non arrivi.",
         options=["finché", "mentre", "dopo"], answer="finché",
         note="Finché non + verbo = hasta que."),
    dict(id="mj-28-04", type="translate", topic="connettivi", level="B1", w=28, prompt=TR,
         stem="Apenas llegue, te llamo.",
         answer="Appena arrivo, ti chiamo",
         alt=["Appena arrivo ti chiamo", "Appena arrivo, ti telefono", "Appena arrivo ti telefono",
              "Appena arriverò, ti chiamo", "Appena arriverò ti chiamo",
              "Appena sarò arrivato, ti chiamo", "Appena sarò arrivata, ti chiamo"],
         note="Appena = en cuanto. Con verbo en presente, como en «appena arrivo»."),
    dict(id="mj-28-05", type="fixerr", topic="connettivi", level="B1", w=28, prompt=VA, cat="tempo_verbale",
         stem="Dopo mangiare, sono uscito.", bad="mangiare", good="aver mangiato",
         answer="Dopo aver mangiato, sono uscito.",
         note="Dopo pide infinitivo compuesto: dopo aver mangiato."),
    dict(id="mj-28-06", type="cloze", topic="connettivi", level="B1", w=28,
         prompt="Completá con el conector que abre el argumento (ante todo).",
         stem="___ analizziamo i costi; poi discutiamo i tempi; infine decidiamo.",
         answer="Innanzitutto",
         alt=["In primo luogo", "Prima di tutto", "innanzitutto", "in primo luogo"],
         note="Innanzitutto abre; poi continúa; infine cierra."),
    dict(id="mj-28-07", type="translate", topic="connettivi", level="B1", w=28, prompt=TR,
         stem="En conclusión, el proyecto vale la pena.",
         answer="In conclusione, il progetto vale la pena",
         alt=["In conclusione il progetto vale la pena", "In conclusione, il progetto ne vale la pena",
              "In conclusione il progetto ne vale la pena"],
         note="In conclusione cierra el argumento."),
    dict(id="mj-28-08", type="translate", topic="connettivi", level="B1", w=28, prompt=TR,
         stem="Como no tenía dinero, no compré nada.",
         answer="Siccome non avevo soldi, non ho comprato niente",
         alt=["Siccome non avevo soldi, non ho comprato nulla",
              "Siccome non avevo soldi non ho comprato niente",
              "Dato che non avevo soldi, non ho comprato niente",
              "Visto che non avevo soldi, non ho comprato niente",
              "Poiché non avevo soldi, non ho comprato niente",
              "Non ho comprato niente perché non avevo soldi",
              "Non ho comprato nulla perché non avevo soldi"],
         note="Siccome suele abrir la oración; con la causa después, se prefiere perché."),
    dict(id="mj-28-09", type="cloze", topic="connettivi", level="B1", w=28,
         prompt="Completá con la conjunción italiana.",
         stem="___ Anna ___ Luca sono venuti alla festa (ni… ni).", answer="né | né",
         alt=["Né | Né"],
         note="Con né… né delante del verbo no se agrega non."),
    dict(id="mj-28-10", type="fixerr", topic="connettivi", level="B1", w=28, prompt=VA, cat="parola_in_piu",
         stem="Né Anna né Luca non sono venuti.", bad="non sono", good="sono",
         answer="Né Anna né Luca sono venuti.",
         note="Si né… né va antes del verbo, no se agrega non."),
    dict(id="mj-28-11", type="choice", topic="connettivi", level="B1", w=28,
         prompt="Elegí el conector que significa «de todos modos».",
         stem="Ha studiato poco, ___ ha preso un ottimo voto.",
         options=["comunque", "perciò", "infatti"], answer="comunque",
         note="Comunque concede: pese a lo dicho, igual. Perciò es consecuencia."),
    dict(id="mj-28-12", type="translate", topic="connettivi", level="B1", w=28, prompt=TR,
         stem="No solo estudia inglés, sino también alemán.",
         answer="Non solo studia inglese, ma anche tedesco",
         alt=["Non studia solo inglese, ma anche tedesco", "Studia non solo inglese ma anche tedesco",
              "Non solo studia inglese ma anche tedesco", "Non studia solo inglese ma anche tedesco",
              "Studia non solo inglese, ma anche tedesco"],
         note="Non solo… ma anche = no solo… sino también."),
    dict(id="mj-28-13", type="choice", topic="connettivi", level="B1", w=28,
         prompt="Elegí el conector que aclara (o sea).",
         stem="Mio fratello è enologo, ___ studia i vini.",
         options=["cioè", "anzi", "invece"], answer="cioè",
         note="Cioè precisa lo dicho; anzi lo corrige; invece contrasta."),
    dict(id="mj-28-14", type="choice", topic="connettivi", level="B1", w=28, prompt=CE,
         stem="___ fa freddo, esco senza giacca.",
         options=["Anche se", "Benché", "Affinché"], answer="Anche se",
         note="El verbo va en indicativo (fa): anche se. Benché y affinché piden congiuntivo."),

    # ================= Settimana 35: La voce passiva =================
    dict(id="mj-35-01", type="choice", topic="passivo", level="B2", w=35, prompt=CE,
         stem="Dopo il terremoto, la città ___ distrutta.",
         options=["è rimasta", "è rimasto", "ha rimasto"], answer="è rimasta",
         note="Rimanere + participio dice el resultado; va con essere y concuerda: la città → rimasta."),
    dict(id="mj-35-02", type="choice", topic="passivo", level="B2", w=35, prompt=CE,
         stem="Tutti ___ sorpresi dalla notizia.",
         options=["sono rimasti", "sono rimaste", "hanno rimasto"], answer="sono rimasti",
         note="Sujeto masculino plural: sono rimasti."),
    dict(id="mj-35-03", type="cloze", topic="passivo", level="B2", w=35,
         prompt="Completá con el passato prossimo de rimanere.",
         stem="Due turisti ___ (rimanere) feriti nell'incidente.", answer="sono rimasti",
         alt=["sono restati"],
         note="Rimanere usa essere; el participio concuerda con turisti."),
    dict(id="mj-35-04", type="translate", topic="passivo", level="B2", w=35, prompt=TR,
         stem="La ciudad quedó destruida por la inundación.",
         answer="La città è rimasta distrutta dall'alluvione",
         alt=["La città è restata distrutta dall'alluvione",
              "La città è rimasta distrutta dall'inondazione",
              "La città è rimasta distrutta dall'alluvione."],
         note="Quedó destruida = è rimasta distrutta; el agente lleva da."),
    dict(id="mj-35-05", type="fixerr", topic="passivo", level="B2", w=35, prompt=VA, cat="ausiliare",
         stem="I cittadini sono venuti sorpresi dalla decisione.", bad="sono venuti", good="sono rimasti",
         answer="I cittadini sono rimasti sorpresi dalla decisione.",
         note="Venire no forma tiempos compuestos; para el resultado usá rimanere."),
    dict(id="mj-35-06", type="choice", topic="passivo", level="B2", w=35,
         prompt="Elegí la forma que expresa obligación.",
         stem="Secondo la legge, le emissioni ___ ridotte entro il 2030.",
         options=["vanno", "vengono", "restano"], answer="vanno",
         note="Andare + participio = debe hacerse: vanno ridotte."),
    dict(id="mj-35-07", type="choice", topic="passivo", level="B2", w=35,
         prompt="Elegí la forma que describe lo que ocurre habitualmente.",
         stem="Ogni martedì i rifiuti ___ raccolti dal Comune.",
         options=["vengono", "vanno", "rimangono"], answer="vengono",
         note="Venire subraya el proceso que se repite; andare indicaría obligación."),
    dict(id="mj-35-08", type="cloze", topic="passivo", level="B2", w=35,
         prompt="Completá con la pasiva con essere (tiempo pasado).",
         stem="La nuova legge sull'ambiente ___ (approvare) ieri dal Parlamento.",
         answer="è stata approvata", alt=["fu approvata"],
         note="Hecho concluido: essere + participio concordado con legge."),
    dict(id="mj-35-09", type="cloze", topic="passivo", level="B2", w=35,
         prompt="Completá con andare + participio (obligación).",
         stem="Le foreste ___ (tutelare) con più attenzione.", answer="vanno tutelate",
         note="Andare + participio concordado: le foreste → tutelate."),
    dict(id="mj-35-10", type="translate", topic="passivo", level="B2", w=35, prompt=TR,
         stem="Los residuos se recogen todos los días.",
         answer="I rifiuti vengono raccolti ogni giorno",
         alt=["I rifiuti sono raccolti ogni giorno", "I rifiuti vengono raccolti tutti i giorni",
              "I rifiuti sono raccolti tutti i giorni"],
         note="Proceso habitual: venire + participio concordado."),
    dict(id="mj-35-11", type="translate", topic="passivo", level="B2", w=35, prompt=TR,
         stem="Los parques deben ser protegidos por el Estado.",
         answer="I parchi vanno protetti dallo Stato",
         alt=["I parchi devono essere protetti dallo Stato", "I parchi devono venire protetti dallo Stato"],
         note="Obligación: andare + participio; el agente lleva da (dallo Stato)."),
    dict(id="mj-35-12", type="choice", topic="passivo", level="B2", w=35, prompt=CE,
         stem="Il bosco è ___ chiuso al pubblico per tutta l'estate.",
         options=["rimasto", "venuto", "andato"], answer="rimasto",
         note="Rimanere + participio expresa el estado resultante; venuto y andato no valen en tiempos compuestos."),
    dict(id="mj-35-13", type="fixerr", topic="passivo", level="B2", w=35, prompt=VA, cat="ausiliare",
         stem="Il documento è venuto approvato dal consiglio.", bad="è venuto", good="è stato",
         answer="Il documento è stato approvato dal consiglio.",
         note="Venire solo en tiempos simples: viene approvato o è stato approvato."),
]
