# -*- coding: utf-8 -*-
"""Mejoras estructurales (2), Stagione 1: semana 4 (plurales en -co/-ca/-go/-ga,
molto, avere para edad y sensaciones, nacionalidades y profesiones) y semana 12
(el cuerpo con artículo, consejos de farmacia, imperativo con forma propia,
formas cortas e imperativo formal)."""

CE = "Elegí la forma correcta."
CL = "Completá con la forma correcta."
TR = "Traducí al italiano."
FX = "Trova l'errore: tocá la palabra que está mal y corregila."

ITEMS = [
    # ================= Settimana 4: Aggettivi qualificativi =================
    dict(id="mj-04-01", type="choice", topic="plurali in -co/-go", level="A1", w=4, prompt=CE,
         stem="Le strade sono ___.", options=["lunghe", "lunghi", "lunge"], answer="lunghe",
         note="Lunga → lunghe: en -ga la h conserva el sonido duro y el femenino plural cierra en -e."),
    dict(id="mj-04-02", type="choice", topic="plurali in -co/-go", level="A1", w=4, prompt=CE,
         stem="Marco e Luca sono ___.", options=["simpatici", "simpatichi", "simpatiche"],
         answer="simpatici",
         note="Simpatico es esdrújula (sim-PA-ti-co): el masculino plural hace -ci, sin h."),
    dict(id="mj-04-03", type="cloze", topic="plurali in -co/-go", level="A1", w=4, prompt=CL,
         stem="I ragazzi sono ___ (stanco).", answer="stanchi",
         note="Stanco es llana: -co → -chi, con h para conservar el sonido duro."),
    dict(id="mj-04-04", type="fixerr", topic="plurali in -co/-go", level="A1", w=4, prompt=FX,
         cat="plurali_co_go", stem="Marco e Luca sono simpatichi.", bad="simpatichi", good="simpatici",
         answer="Marco e Luca sono simpatici.",
         note="Los esdrújulos en -co hacen -ci: simpatici. La h solo aparece en las llanas (stanchi) y en el femenino (simpatiche)."),
    dict(id="mj-04-05", type="choice", topic="molto", level="A1", w=4, prompt=CE,
         stem="Le ragazze sono ___ stanche.", options=["molto", "molte", "molti"], answer="molto",
         note="Ante un adjetivo, molto es adverbio («muy») y no cambia."),
    dict(id="mj-04-06", type="choice", topic="molto", level="A1", w=4, prompt=CE,
         stem="Ho ___ amiche a Roma.", options=["molte", "molto", "molti"], answer="molte",
         note="Ante un sustantivo, molto es adjetivo y concuerda con amiche: molte."),
    dict(id="mj-04-07", type="cloze", topic="avere: sensazioni", level="A1", w=4, prompt=CL,
         stem="Luisa ha ___ fame. (molto)", answer="molta",
         note="Fame es femenino: molta fame. Ante sustantivo, molto concuerda."),
    dict(id="mj-04-08", type="fixerr", topic="avere: età", level="A1", w=4, prompt=FX,
         cat="avere_eta", stem="Io sono venti anni.", bad="sono", good="ho",
         answer="Io ho venti anni.",
         note="La edad se dice con avere, como en español: ho venti anni."),
    dict(id="mj-04-09", type="translate", topic="avere: sensazioni", level="A1", w=4, prompt=TR,
         stem="Tengo mucho calor.", answer="Ho molto caldo",
         alt=["Io ho molto caldo", "Ho molto caldo."],
         note="Caldo y freddo con avere. Caldo es sustantivo masculino: molto caldo."),
    dict(id="mj-04-10", type="translate", topic="avere: età", level="A1", w=4, prompt=TR,
         stem="Ana tiene treinta años.", answer="Anna ha trent'anni",
         alt=["Anna ha 30 anni", "Anna ha trent'anni."],
         note="Edad con avere: Anna ha trent'anni. Trenta pierde la -a ante anni."),
    dict(id="mj-04-11", type="cloze", topic="nazionalità", level="A1", w=4, prompt=CL,
         stem="Pierre e Marie sono ___ (francese).", answer="francesi",
         note="Los adjetivos en -e hacen el plural en -i para los dos géneros: francesi."),
    dict(id="mj-04-12", type="translate", topic="nazionalità", level="A1", w=4, prompt=TR,
         stem="Ellas son mexicanas.", answer="Sono messicane",
         alt=["Loro sono messicane", "Sono messicane."],
         note="Messicano es un adjetivo en -o: femenino plural messicane. Con doble s."),
    dict(id="mj-04-13", type="typed", topic="professioni", level="A1", w=4, prompt=TR,
         stem="Soy estudiante y tengo veinte años.", answer="Sono studente e ho venti anni",
         alt=["Sono studentessa e ho venti anni", "Io sono studente e ho venti anni",
              "Io sono studentessa e ho venti anni", "Sono studente e ho 20 anni",
              "Sono studentessa e ho 20 anni"],
         note="Oficio con essere y sin artículo; edad con avere. Si sos mujer, studentessa."),
    dict(id="mj-04-14", type="typed", topic="professioni", level="A1", w=4, prompt=TR,
         stem="Es cocinera y es muy simpática.", answer="È cuoca ed è molto simpatica",
         alt=["Lei è cuoca ed è molto simpatica", "È cuoca ed è molto simpatica."],
         note="Cuoco/cuoca cambia con el género; molto ante adjetivo no cambia; simpatica concuerda."),

    # ================= Settimana 12: Riflessivi e imperativo =================
    dict(id="mj-12-01", type="cloze", topic="riflessivi e corpo", level="A2", w=12,
         prompt="Completá con el artículo.", stem="Dopo il giardino, mi lavo ___ mani.",
         answer="le",
         note="Con partes del cuerpo el italiano usa el artículo, no el posesivo: mi lavo le mani."),
    dict(id="mj-12-02", type="fixerr", topic="riflessivi e corpo", level="A2", w=12, prompt=FX,
         cat="corpo_possessivo", stem="Mi lavo le mie mani con il sapone.", bad="le mie mani",
         good="le mani", answer="Mi lavo le mani con il sapone.",
         note="El reflexivo ya dice de quién son: se usa el artículo, le mani, sin posesivo."),
    dict(id="mj-12-03", type="choice", topic="riflessivi e corpo", level="A2", w=12, prompt=CE,
         stem="Dopo la corsa mi ___ male le gambe.", options=["fanno", "fa", "faccio"],
         answer="fanno",
         note="Fare male concuerda con lo que duele: le gambe (plural) → fanno."),
    dict(id="mj-12-04", type="translate", topic="riflessivi e corpo", level="A2", w=12, prompt=TR,
         stem="Marco se lava las manos y la cara.", answer="Marco si lava le mani e la faccia",
         alt=["Marco si lava le mani e il viso", "Marco si lava le mani e la faccia.",
              "Marco si lava le mani e il viso."],
         note="Reflexivo con si y artículo con las partes del cuerpo: le mani, la faccia (o il viso)."),
    dict(id="mj-12-05", type="choice", topic="imperativo", level="A2", w=12, prompt=CE,
         stem="Marco, hai la febbre? ___ una pastiglia!", options=["Prendi", "Prendo", "Prendere"],
         answer="Prendi",
         note="Imperativo de tu en -ere: igual que el presente, prendi."),
    dict(id="mj-12-06", type="choice", topic="imperativo negativo", level="A2", w=12, prompt=CE,
         stem="Luca, ___ troppo caffè!", options=["non bere", "non bevi", "non beve"],
         answer="non bere",
         note="El negativo de tu es non + infinitivo. «Non bevi» afirma que no bebe."),
    dict(id="mj-12-07", type="fixerr", topic="imperativo con pronombre", level="A2", w=12, prompt=FX,
         cat="imperativo_pronome", stem="Sono le otto: alza ti subito!", bad="alza ti",
         good="alzati", answer="Sono le otto: alzati subito!",
         note="Con el imperativo afirmativo el pronombre se pega al final: alzati."),
    dict(id="mj-12-08", type="translate", topic="farmacia", level="A2", w=12, prompt=TR,
         stem="Tomá una pastilla y descansá.", answer="Prendi una pastiglia e riposati",
         alt=["Prendi una compressa e riposati", "Prendi una pastiglia e riposati.",
              "Prendi una compressa e riposati."],
         note="Imperativo de tu: prendi; y con el reflexivo pegado, riposati."),
    dict(id="mj-12-09", type="choice", topic="imperativo irregolare", level="A2", w=12, prompt=CE,
         stem="Marco, ___ gentile con la nonna!", options=["sii", "sei", "sia"], answer="sii",
         note="Essere tiene imperativo propio: sii. «Sei» es el presente."),
    dict(id="mj-12-10", type="choice", topic="forme corte", level="A2", w=12, prompt=CE,
         stem="Ho sete: ___ l'acqua, per favore!", options=["dammi", "dami", "da mi"],
         answer="dammi",
         note="da' + mi duplica la m: dammi."),
    dict(id="mj-12-11", type="cloze", topic="forme corte", level="A2", w=12,
         prompt="Completá con el imperativo de tu + pronombre.",
         stem="Il compito? ___ subito! (fare + lo)", answer="Fallo",
         alt=["fallo"],
         note="fa' + lo duplica la l: fallo."),
    dict(id="mj-12-12", type="fixerr", topic="forme corte", level="A2", w=12, prompt=FX,
         cat="forme_corte", stem="Luca ha fame: daggli il pane.", bad="daggli", good="dagli",
         answer="Luca ha fame: dagli il pane.",
         note="Gli es la excepción: no duplica la consonante. Dagli."),
    dict(id="mj-12-13", type="choice", topic="imperativo con Lei", level="A2", w=12, prompt=CE,
         stem="Signor Rossi, ___ pure: il dottore arriva subito.",
         options=["si accomodi", "ti accomodi", "accomodati"], answer="si accomodi",
         note="Con Lei el pronombre es si y va delante: si accomodi. Ti y accomodati son de tu."),
    dict(id="mj-12-14", type="translate", topic="imperativo con Lei", level="A2", w=12, prompt=TR,
         stem="Dígame, señora.", answer="Mi dica, signora",
         alt=["Signora, mi dica", "Mi dica, signora.", "Signora, mi dica."],
         note="Imperativo formal: mi dica, con el pronombre delante."),
]
