# -*- coding: utf-8 -*-
"""Mejoras estructurales, stagione 4 (K=4): semanas 45 (costruzioni verbali
speciali) y 46 (suffissi e alterazione)."""

CE = "Elegí la forma correcta."
TR = "Traducí al italiano."
CL = "Completá."
FX = "Trova l'errore: tocá la palabra que está mal y corregila."

ITEMS = [
    # ================= Settimana 45: Costruzioni verbali speciali =================
    dict(id="mj-45-01", type="choice", topic="costruzioni", level="B2", w=45, prompt=CE,
         stem="Per arrivare a Mendoza ___ almeno otto ore.",
         options=["ci vogliono", "ci vuole", "ci metto"], answer="ci vogliono",
         note="Volerci concuerda con lo que hace falta: «otto ore» es plural, así que ci vogliono."),
    dict(id="mj-45-02", type="choice", topic="costruzioni", level="B2", w=45, prompt=CE,
         stem="Io ___ venti minuti a piedi per andare in ufficio.",
         options=["ci metto", "ci voglio", "ci vuole"], answer="ci metto",
         note="Quien tarda es «io»: metterci se conjuga con la persona. Volerci no admite sujeto personal."),
    dict(id="mj-45-03", type="cloze", topic="costruzioni", level="B2", w=45,
         prompt="Completá con el passato prossimo de metterci.",
         stem="Ieri voi ___ tre ore per tornare a casa.", answer="ci avete messo",
         note="Metterci hace el compuesto con avere y concuerda con quien tarda: ci avete messo."),
    dict(id="mj-45-04", type="cloze", topic="costruzioni", level="C1", w=45,
         prompt="Completá con el passato prossimo de volerci.",
         stem="Per finire il lavoro ___ due settimane.", answer="ci sono volute",
         alt=["ci son volute"],
         note="Volerci se conjuga con essere y el participio concuerda con lo necesario: due settimane → volute."),
    dict(id="mj-45-05", type="translate", topic="costruzioni", level="C1", w=45, prompt=TR,
         stem="Tardé una hora en encontrar estacionamiento.",
         answer="Ci ho messo un'ora a trovare parcheggio.",
         alt=["Ci ho messo un'ora a trovare il parcheggio.", "Ci ho messo un'ora per trovare parcheggio.",
              "Ci ho messo un'ora per trovare il parcheggio."],
         note="Tardar (personal) = metterci, con avere: ci ho messo."),
    dict(id="mj-45-06", type="translate", topic="costruzioni", level="C1", w=45, prompt=TR,
         stem="Para esta torta hacen falta tres huevos.",
         answer="Per questa torta ci vogliono tre uova.",
         alt=["Ci vogliono tre uova per questa torta."],
         note="Hacer falta = volerci, concordado con lo necesario: tre uova (plural) → ci vogliono."),
    dict(id="mj-45-07", type="fixerr", topic="costruzioni", level="B2", w=45, prompt=FX, cat="ci_ne",
         stem="Ogni mattina ci voglio un'ora per prepararmi.", bad="ci voglio", good="ci metto",
         answer="Ogni mattina ci metto un'ora per prepararmi.",
         note="Volerci es impersonal; para «yo tardo» va metterci: ci metto."),
    dict(id="mj-45-08", type="fixerr", topic="costruzioni", level="C1", w=45, prompt=FX, cat="pronome",
         stem="Lui si ne infischia dei consigli di tutti.", bad="si ne", good="se ne",
         answer="Lui se ne infischia dei consigli di tutti.",
         note="Con ne, el pronombre reflexivo cambia: si → se (se ne infischia, me ne vado)."),
    dict(id="mj-45-09", type="choice", topic="costruzioni", level="B2", w=45, prompt=CE,
         stem="Decidere ___ a te: io non c'entro.",
         options=["sta", "è", "va"], answer="sta",
         note="Stare a + infinitivo o + persona = corresponder: sta a te decidere."),
    dict(id="mj-45-10", type="choice", topic="costruzioni", level="C1", w=45, prompt=CE,
         stem="Dopo mesi di dubbi, alla fine ha finito ___.",
         options=["con l'accettare l'offerta", "con accettare l'offerta", "a accettare l'offerta"],
         answer="con l'accettare l'offerta",
         note="Finire con l' + infinitivo = terminar haciendo algo (equivale a finire per accettare)."),
    dict(id="mj-45-11", type="choice", topic="costruzioni", level="C1", w=45, prompt=CE,
         stem="Ieri Marta ___ comoda e siamo arrivati tardi.",
         options=["se l'è presa", "se la è preso", "ha preso"], answer="se l'è presa",
         note="Prendersela comoda es pronominal, con essere, y el participio en -a: se l'è presa."),
    dict(id="mj-45-12", type="cloze", topic="costruzioni", level="C1", w=45,
         prompt="Completá con la forma de sentirsela.",
         stem="Io non ___ di parlarle stasera.", answer="me la sento",
         note="Sentirsela = animarse a; la persona cambia y la queda fija: non me la sento di + infinitivo."),
    dict(id="mj-45-13", type="translate", topic="costruzioni", level="C1", w=45, prompt=TR,
         stem="Se ofendió por lo que dije y ahora todavía está enojada conmigo.",
         answer="Se l'è presa per quello che ho detto e adesso ce l'ha ancora con me.",
         alt=["Se l'è presa per quel che ho detto e adesso ce l'ha ancora con me.",
              "Se l'è presa per quello che ho detto e ora ce l'ha ancora con me.",
              "Se l'è presa per quel che ho detto e ora ce l'ha ancora con me."],
         note="Prendersela = el hecho de ofenderse; avercela con = el estado de enojo que sigue."),
    dict(id="mj-45-14", type="typed", topic="costruzioni", level="C1", w=45, prompt=TR,
         stem="No hace más que quejarse.",
         answer="Non fa che lamentarsi.", alt=["Non fa altro che lamentarsi."],
         note="Non fare che + infinitivo = no hacer más que."),

    # ================= Settimana 46: Suffissi e alterazione =================
    dict(id="mj-46-01", type="cloze", topic="suffissi", level="C1", w=46,
         prompt="Formá el alterado (con el interfijo que corresponda).",
         stem="cane → un ___ nero (perrito)", answer="cagnolino", alt=["cagnetto"],
         note="La raíz cambia (cagn-) y aparece el interfijo -ol-: cagnolino. «Canino» es el colmillo."),
    dict(id="mj-46-02", type="cloze", topic="suffissi", level="C1", w=46,
         prompt="Formá el alterado (con el interfijo que corresponda).",
         stem="pioggia → una ___ (llovizna)", answer="pioggerellina", alt=["pioggerella"],
         note="Interfijo -er- + -ell- + -ina: pioggerellina."),
    dict(id="mj-46-03", type="choice", topic="suffissi", level="B2", w=46, prompt=CE,
         stem="amico → un ___ di mio figlio (amiguito)",
         options=["amichetto", "amicetto", "amiccetto"], answer="amichetto",
         note="La c de amico es dura: para conservar el sonido /k/ delante de -etto va una h."),
    dict(id="mj-46-04", type="choice", topic="suffissi", level="B2", w=46, prompt=CE,
         stem="lago → un ___ di montagna (lago chico)",
         options=["laghetto", "lagetto", "lagoetto"], answer="laghetto",
         note="Como poco → pochino: la g dura pide h delante de -etto."),
    dict(id="mj-46-05", type="cloze", topic="suffissi", level="B2", w=46,
         prompt="Formá el alterado de poco.",
         stem="Ne vuoi ancora? — Solo un ___.", answer="pochino", alt=["pochetto"],
         note="poco + -ino → pochino, con h para mantener el sonido duro."),
    dict(id="mj-46-06", type="choice", topic="suffissi", level="C1", w=46, prompt=CE,
         stem="Marco parla sempre e di tutto: è un ___.",
         options=["chiacchierone", "chiacchierino", "chiacchierucolo"], answer="chiacchierone",
         note="-one sobre un verbo (chiacchierare) nombra a quien lo hace seguido; no es aumentativo de tamaño."),
    dict(id="mj-46-07", type="choice", topic="suffissi", level="C1", w=46,
         prompt="Elegí la palabra que NO es un alterado: no deriva de una base más chica o más común.",
         stem="burrone, portone, librone", options=["burrone", "portone", "librone"], answer="burrone",
         note="Burrone (barranco) es una palabra propia; portone es porta y librone es libro, alterados."),
    dict(id="mj-46-08", type="choice", topic="suffissi", level="C1", w=46,
         prompt="¿Qué sufijo da valor despectivo? Elegí.",
         stem="Non leggo quel ___: è pieno di sciocchezze.",
         options=["libraccio", "librone", "libretto"], answer="libraccio",
         note="-accio desprecia (un libro malo). -one agranda y -etto achica."),
    dict(id="mj-46-09", type="fixerr", topic="suffissi", level="C1", w=46, prompt=FX, cat="ortografia",
         stem="Ieri ho visto un amicetto di Luca.", bad="amicetto", good="amichetto",
         answer="Ieri ho visto un amichetto di Luca.",
         note="Amico + -etto: se agrega h para conservar el sonido /k/."),
    dict(id="mj-46-10", type="fixerr", topic="suffissi", level="C1", w=46, prompt=FX, cat="lessico",
         stem="Abbiamo adottato un canino di due mesi.", bad="canino", good="cagnolino",
         answer="Abbiamo adottato un cagnolino di due mesi.",
         note="Canino es el colmillo. El alterado de cane es cagnolino, con interfijo -ol-."),
    dict(id="mj-46-11", type="typed", topic="suffissi", level="C1", w=46, prompt=TR,
         stem="¡Qué día de porquería!", answer="Che giornataccia!", alt=["Che giornataccia"],
         note="Giornata + -accio: valor despectivo (giornataccia)."),
    dict(id="mj-46-12", type="translate", topic="suffissi", level="C1", w=46, prompt=TR,
         stem="Es un gruñón, pero es buena gente.",
         answer="È un brontolone, ma è una brava persona.",
         alt=["È un brontolone ma è una brava persona.", "È un brontolone, ma è una persona buona.",
              "È un brontolone ma è una persona buona."],
         note="Brontolare + -one = brontolone (el que gruñe). Buena persona = brava persona."),
    dict(id="mj-46-13", type="cloze", topic="suffissi", level="C1", w=46,
         prompt="Completá con el prefissoide.",
         stem="Faccio ___lavoro tre giorni a settimana da casa.", answer="tele", alt=["telelavoro"],
         note="Tele- (a distancia) + lavoro = telelavoro."),
    dict(id="mj-46-14", type="typed", topic="suffissi", level="C1", w=46, prompt=TR,
         stem="Pasame el control remoto.", answer="Passami il telecomando.",
         alt=["Passami il telecomando"],
         note="Tele- + comando: il telecomando es el control remoto."),
]
