# -*- coding: utf-8 -*-
"""Refuerzo: ejercicios propios para las semanas con pocos ítems.

Cada semana tiene al menos 25 ítems suyos, así las rondas de
entrenamiento no repiten siempre las mismas frases.  Semanas cubiertas:
1 ortografía, 4 adjetivos, 16 adverbios, 22 comparativos, 24 sufijos,
35 «si» pasivo e impersonal, 38 relativos, 46 construcciones verbales,
48 orden de palabras.
"""

CE = "Elegí la forma correcta."
TR = "Traducí al italiano."

# Variantes igualmente válidas de rf-38-25.
_PAESE = ["Il paese %s %s %s" % (r, v, e)
          for r in ("in cui", "dove", "nel quale")
          for v in ("è nato mio nonno", "nacque mio nonno")
          for e in ("è in Sicilia", "si trova in Sicilia")]

ITEMS = [
    # ================= Settimana 1: Suoni e ortografia =================
    dict(id="rf-1-01", type="choice", topic="ortografia", level="A1",
         prompt="Elegí la palabra que significa «pelota».",
         stem="Giochiamo a ___ in cortile.", options=["palla", "pala", "pallo"],
         answer="palla",
         note="La doble cambia la palabra: «pala» es la herramienta, «palla» la pelota."),
    dict(id="rf-1-02", type="choice", topic="ortografia", level="A1",
         prompt="Elegí el participio de «fare» (hecho).",
         stem="Hai ___ i compiti?", options=["fatto", "fato", "facto"],
         answer="fatto",
         note="«Fatto» con tt; «fato» con una sola t es el destino."),
    dict(id="rf-1-03", type="choice", topic="ortografia", level="A1",
         prompt="Elegí el número 7.",
         stem="La settimana ha ___ giorni.", options=["sette", "sete", "setté"],
         answer="sette",
         note="«Sette» = siete; «sete» = sed (ho sete). Alargá bien la t doble."),
    dict(id="rf-1-04", type="cloze", topic="ortografia", level="A1",
         prompt="Escribí el plural conservando el sonido duro [k].",
         stem="A Buenos Aires ci sono tanti ___ (parco).", answer="parchi",
         note="Para que la c siga sonando [k] ante i, se agrega h: parco → parchi."),
    dict(id="rf-1-05", type="cloze", topic="ortografia", level="A1",
         prompt="Escribí el plural conservando el sonido duro [g].",
         stem="In Lombardia ci sono molti ___ (lago).", answer="laghi",
         note="Igual que con c: g + h mantiene el sonido duro ante i/e (lago → laghi)."),
    dict(id="rf-1-06", type="choice", topic="ortografia", level="A1",
         prompt="¿En cuál la c suena como la «ch» de «chico»?",
         stem="___", options=["cena", "casa", "chiave", "cuore"], answer="cena",
         note="c + e/i = [tʃ] (cena, cibo); c + a/o/u o ch = [k]."),
    dict(id="rf-1-07", type="choice", topic="ortografia", level="A1",
         prompt="¿En cuál la g suena suave [dʒ], como en «gelato»?",
         stem="___", options=["giorno", "gatto", "ghiro", "gusto"], answer="giorno",
         note="g + e/i = [dʒ]; ante a/o/u, o con gh, suena dura como en «gato»."),
    dict(id="rf-1-08", type="choice", topic="ortografia", level="A1",
         prompt="¿Cómo se escribe «montaña»?",
         stem="___", options=["montagna", "montania", "montaña"], answer="montagna",
         note="La ñ castellana se escribe gn en italiano: montagna, Spagna, sogno."),
    dict(id="rf-1-09", type="choice", topic="ortografia", level="A1",
         prompt="¿Cómo se escribe la palabra que significa «esquí»?",
         stem="Quest'inverno vado a fare ___ a Cortina.", options=["sci", "schi", "ski"],
         answer="sci",
         note="sc + i/e suena [ʃ], como la «ll» de un porteño que «shea». Con h (schi) sería [ski]."),
    dict(id="rf-1-10", type="cloze", topic="ortografia", level="A1",
         prompt="Completá con las letras que faltan (sonido [ʃ]; significa «pescado»).",
         stem="Il pe___e è fresco oggi.", answer="sc",
         note="«Pesce»: sc ante e suena [ʃ]. «Pesche» (con h) son duraznos."),
    dict(id="rf-1-11", type="choice", topic="ortografia", level="A1",
         prompt="Elegí la grafía correcta de «ciencia».",
         stem="___", options=["scienza", "sienza", "scenza"], answer="scienza",
         note="«Scienza» conserva una i que no suena, por etimología (del latín scientia)."),
    dict(id="rf-1-12", type="choice", topic="ortografia", level="A1",
         prompt="¿Cómo se escribe correctamente?",
         stem="Prendiamo un ___ al bar?", options=["caffè", "caffé", "caffe"],
         answer="caffè",
         note="Acento grave en la e abierta final: caffè, è, tè."),
    dict(id="rf-1-13", type="choice", topic="ortografia", level="A1",
         prompt="¿Cómo se escribe correctamente?",
         stem="___ non vieni con noi?", options=["Perché", "Perchè", "Perche"],
         answer="Perché",
         note="Los compuestos de «che» llevan acento agudo (e cerrada): perché, poiché, affinché."),
    dict(id="rf-1-14", type="cloze", topic="ortografia", level="A1",
         prompt="Completá con «è» (verbo) o «e» (conjunción).",
         stem="Mia madre ___ argentina e mio padre è italiano.", answer="è",
         note="«È» con acento es el verbo essere; «e» sin acento significa «y»."),
    dict(id="rf-1-15", type="cloze", topic="ortografia", level="A1",
         prompt="Completá con «è» (verbo) o «e» (conjunción).",
         stem="Pane ___ burro, per favore.", answer="e",
         note="Acá significa «y»: sin acento. Poner «è» cambiaría la frase."),
    dict(id="rf-1-16", type="choice", topic="ortografia", level="A1",
         prompt="¿Cómo se escribe «un poco»?",
         stem="Vuoi ___ di latte nel caffè?", options=["un po'", "un pò", "un po"],
         answer="un po'",
         note="«Po'» es «poco» cortado: lleva apóstrofo, nunca acento."),
    dict(id="rf-1-17", type="choice", topic="ortografia", level="A1",
         prompt="Elegí la forma correcta.",
         stem="Stasera esco con ___ di Laura.", options=["un amico", "un'amico"],
         answer="un amico",
         note="El apóstrofo va solo en femenino (un'amica). En masculino «un» no elide: un amico."),
    dict(id="rf-1-18", type="choice", topic="ortografia", level="A1",
         prompt="¿Cómo suena la «ch» de «Michelangelo»?",
         stem="Michelangelo",
         options=["[k], como la «qu» de «queso»", "[tʃ], como la «ch» de «chico»",
                  "[ʃ], como la «sh» rioplatense"],
         answer="[k], como la «qu» de «queso»",
         note="En italiano ch = [k] siempre: Michelangelo, Chianti, chiesa."),
    dict(id="rf-1-19", type="choice", topic="ortografia", level="A1",
         prompt="Elegí la forma correcta (ellos tienen).",
         stem="Loro ___ fame.", options=["hanno", "anno", "hano"], answer="hanno",
         note="La h no suena, pero distingue: «hanno» (tienen) vs «anno» (año)."),
    dict(id="rf-1-20", type="cloze", topic="ortografia", level="A1",
         prompt="Completá con «o» (conjunción) o «ho» (verbo).",
         stem="Vuoi il tè ___ il caffè?", answer="o",
         note="«O» = o (disyunción); «ho» = tengo/he. Suenan igual."),
    dict(id="rf-1-21", type="cloze", topic="ortografia", level="A1",
         prompt="Completá con «o» (conjunción) o «ho» (verbo).",
         stem="Stasera ___ una cena con i colleghi.", answer="ho",
         note="Es el verbo avere (yo tengo): se escribe con h."),
    dict(id="rf-1-22", type="translate", topic="ortografia", level="A1",
         prompt=TR, stem="Mi abuelo tiene noventa años.",
         answer="Mio nonno ha novant'anni",
         alt=["Mio nonno ha novanta anni"],
         note="Ojo con las dobles: nonno, anni. La edad va con avere."),
    dict(id="rf-1-23", type="translate", topic="ortografia", level="A1",
         prompt=TR, stem="¿Por qué no venís al cine?",
         answer="Perché non vieni al cinema?",
         alt=["Perché non vieni al cine?"],
         note="«Perché» con acento agudo; «cinema» se lee [tʃ]inema."),
    dict(id="rf-1-24", type="translate", topic="ortografia", level="A1",
         prompt=TR, stem="La ciudad es linda.",
         answer="La città è bella",
         note="«Città» lleva acento grave y doble t; «è» con acento porque es verbo."),
    dict(id="rf-1-25", type="choice", topic="ortografia", level="A1",
         prompt="¿Cómo se escribe «hielo»?",
         stem="Un'aranciata con ___, per favore.", options=["ghiaccio", "giaccio", "ghiacio"],
         answer="ghiaccio",
         note="gh = [g] duro ante i; cci = [ttʃ] largo. Todo junto: ghiaccio."),

    # ================= Settimana 4: Aggettivi qualificativi =================
    dict(id="rf-4-01", type="choice", topic="aggettivi", level="A1",
         prompt=CE, stem="Firenze è una città ___.", options=["bella", "bello", "belle"],
         answer="bella",
         note="El adjetivo concuerda en género y número: città es femenino singular."),
    dict(id="rf-4-02", type="choice", topic="aggettivi", level="A1",
         prompt=CE, stem="Che ___ tramonto sul Río de la Plata!",
         options=["bel", "bello", "bell'"], answer="bel",
         note="«Bello» delante se comporta como el artículo: il tramonto → bel tramonto."),
    dict(id="rf-4-03", type="choice", topic="aggettivi", level="A1",
         prompt=CE, stem="Agli Uffizi abbiamo visto dei ___ quadri.",
         options=["bei", "begli", "belli"], answer="bei",
         note="i quadri → bei quadri. «Belli» solo va detrás del sustantivo."),
    dict(id="rf-4-04", type="choice", topic="aggettivi", level="A1",
         prompt=CE, stem="Tua figlia ha dei ___ occhi verdi.",
         options=["begli", "bei", "belli"], answer="begli",
         note="gli occhi → begli occhi: ante vocal, s + consonante o z se usa «begli»."),
    dict(id="rf-4-05", type="choice", topic="aggettivi", level="A1",
         prompt=CE, stem="Marco è un ___ amico.", options=["buon", "buono", "buon'"],
         answer="buon",
         note="«Buono» delante de masculino sigue a «un»: un buon amico, sin apóstrofo."),
    dict(id="rf-4-06", type="choice", topic="aggettivi", level="A1",
         prompt=CE, stem="Ha trovato un lavoro con un ___ stipendio.",
         options=["buono", "buon", "buoni"], answer="buono",
         note="Ante s + consonante se usa la forma entera: uno stipendio → un buono stipendio."),
    dict(id="rf-4-07", type="choice", topic="aggettivi", level="A1",
         prompt=CE, stem="La basilica di ___ Pietro è a Roma.",
         options=["San", "Santo", "Sant'"], answer="San",
         note="Santo ante consonante se acorta: San Pietro, San Marco."),
    dict(id="rf-4-08", type="choice", topic="aggettivi", level="A1",
         prompt=CE, stem="A Padova la festa di ___ Antonio è il 13 giugno.",
         options=["Sant'", "San", "Santo"], answer="Sant'",
         note="Ante vocal, Santo se elide: Sant'Antonio, Sant'Anna."),
    dict(id="rf-4-09", type="choice", topic="aggettivi", level="A1",
         prompt=CE, stem="Il 26 dicembre in Italia si festeggia ___ Stefano.",
         options=["Santo", "San", "Sant'"], answer="Santo",
         note="Ante s + consonante queda entero: Santo Stefano, Santo Spirito."),
    dict(id="rf-4-10", type="cloze", topic="aggettivi", level="A1",
         prompt="Completá con el adjetivo concordado.",
         stem="Le tue cugine sono molto ___ (simpatico).", answer="simpatiche",
         note="Femenino plural de -ca: -che, con h para mantener el sonido [k]."),
    dict(id="rf-4-11", type="cloze", topic="aggettivi", level="A1",
         prompt="Completá con el adjetivo concordado.",
         stem="I miei vicini sono ___ (simpatico).", answer="simpatici",
         note="Los esdrújulos en -co hacen el masculino plural en -ci: simpatici, pratici."),
    dict(id="rf-4-12", type="cloze", topic="aggettivi", level="A1",
         prompt="Completá con el adjetivo concordado.",
         stem="A Roma ci sono molti monumenti ___ (antico).", answer="antichi",
         note="Antico → antichi (se conserva [k]); femenino: antiche."),
    dict(id="rf-4-13", type="cloze", topic="aggettivi", level="A1",
         prompt="Completá con el adjetivo concordado.",
         stem="Le strade di questo quartiere sono ___ (largo).", answer="larghe",
         note="-go → -ghe en femenino plural. Ojo: «largo» es ancho, no «lungo»."),
    dict(id="rf-4-14", type="choice", topic="aggettivi", level="A1",
         prompt=CE, stem="Ho comprato due magliette ___.",
         options=["blu", "blue", "blui"], answer="blu",
         note="Invariables: blu, rosa, viola, beige. No cambian en plural."),
    dict(id="rf-4-15", type="choice", topic="aggettivi", level="A1",
         prompt="Elegí la forma correcta (rosadas).",
         stem="Mi piacciono le rose ___.", options=["rosa", "rose", "rosse"],
         answer="rosa",
         note="«Rosa» como color es invariable: le rose rosa. «Rosse» = rojas."),
    dict(id="rf-4-16", type="cloze", topic="aggettivi", level="A1",
         prompt="Completá con el adjetivo concordado.",
         stem="Luisa e Paolo sono ___ (stanco).", answer="stanchi",
         note="Con sujetos de distinto género, el adjetivo va en masculino plural."),
    dict(id="rf-4-17", type="cloze", topic="aggettivi", level="A1",
         prompt="Completá con el adjetivo concordado.",
         stem="In estate le giornate sono ___ (lungo).", answer="lunghe",
         note="lungo, lunga, lunghi, lunghe: la h mantiene el sonido [g]."),
    dict(id="rf-4-18", type="choice", topic="aggettivi", level="A1",
         prompt="Elegí según el sentido: «un hombre pobre» (sin plata).",
         stem="___", options=["un uomo povero", "un povero uomo"],
         answer="un uomo povero",
         note="Detrás = sentido literal (sin dinero). Delante = pobrecito, digno de lástima."),
    dict(id="rf-4-19", type="choice", topic="aggettivi", level="A1",
         prompt="Elegí según el sentido: «un amigo de hace muchos años».",
         stem="___", options=["un vecchio amico", "un amico vecchio"],
         answer="un vecchio amico",
         note="Delante = de larga data. Detrás = de edad avanzada."),
    dict(id="rf-4-20", type="choice", topic="aggettivi", level="A1",
         prompt=CE, stem="Dante è stato un ___ poeta.",
         options=["gran", "grandi", "grossi"], answer="gran",
         note="«Grande» delante puede acortarse: un gran poeta (también «un grande poeta»)."),
    dict(id="rf-4-21", type="cloze", topic="aggettivi", level="A1",
         prompt="Completá con el adjetivo concordado.",
         stem="Le città ___ (grande) sono spesso caotiche.", answer="grandi",
         note="Los adjetivos en -e tienen dos formas: grande / grandi, para ambos géneros."),
    dict(id="rf-4-22", type="translate", topic="aggettivi", level="A1",
         prompt=TR, stem="Tengo dos gatos negros.", answer="Ho due gatti neri",
         note="El adjetivo de color va detrás y concuerda: gatti neri."),
    dict(id="rf-4-23", type="translate", topic="aggettivi", level="A1",
         prompt=TR, stem="Las chicas argentinas son muy simpáticas.",
         answer="Le ragazze argentine sono molto simpatiche",
         note="Gentilicios con minúscula (argentine); simpatica → simpatiche."),
    dict(id="rf-4-24", type="translate", topic="aggettivi", level="A1",
         prompt=TR, stem="Es un buen libro.", answer="È un buon libro",
         note="«Buen» también se acorta en italiano: un buon libro."),
    dict(id="rf-4-25", type="translate", topic="aggettivi", level="A1",
         prompt=TR, stem="¡Qué lindos zapatos!", answer="Che belle scarpe!",
         note="«Scarpe» es femenino: belle scarpe. En exclamaciones, «che» + adjetivo delante."),

    # ================= Settimana 16: Avverbi =================
    dict(id="rf-16-01", type="cloze", topic="avverbi", level="B1",
         prompt="Formá el adverbio en -mente.",
         stem="Il nonno parla ___ (lento).", answer="lentamente",
         note="Femenino del adjetivo + -mente: lenta → lentamente."),
    dict(id="rf-16-02", type="cloze", topic="avverbi", level="B1",
         prompt="Formá el adverbio en -mente.",
         stem="La commessa mi ha risposto ___ (gentile).", answer="gentilmente",
         note="Adjetivos en -le pierden la e: gentile → gentilmente."),
    dict(id="rf-16-03", type="cloze", topic="avverbi", level="B1",
         prompt="Formá el adverbio en -mente.",
         stem="Questo problema si risolve ___ (facile).", answer="facilmente",
         note="-le → -lmente: facile → facilmente, sin la e."),
    dict(id="rf-16-04", type="cloze", topic="avverbi", level="B1",
         prompt="Formá el adverbio en -mente.",
         stem="Sono ___ (particolare) contenta di vederti.", answer="particolarmente",
         note="Adjetivos en -re también pierden la e: particolare → particolarmente."),
    dict(id="rf-16-05", type="cloze", topic="avverbi", level="B1",
         prompt="Formá el adverbio en -mente.",
         stem="Mia sorella va in palestra ___ (regolare).", answer="regolarmente",
         note="regolare → regolarmente: -re pierde la e antes de -mente."),
    dict(id="rf-16-06", type="choice", topic="avverbi", level="B1",
         prompt=CE, stem="Mina canta molto ___.", options=["bene", "buono", "buona"],
         answer="bene",
         note="Con verbos va el adverbio «bene», no el adjetivo «buono»."),
    dict(id="rf-16-07", type="choice", topic="avverbi", level="B1",
         prompt=CE, stem="Dopo la vacanza mi sento ___ di prima.",
         options=["meglio", "migliore", "più bene"], answer="meglio",
         note="Comparativo de «bene» = meglio (adverbio). «Migliore» es adjetivo."),
    dict(id="rf-16-08", type="choice", topic="avverbi", level="B1",
         prompt=CE, stem="Stanotte ho dormito ___ del solito.",
         options=["peggio", "peggiore", "più male"], answer="peggio",
         note="Comparativo de «male» = peggio. «Più male» es coloquial y se evita en la lengua cuidada."),
    dict(id="rf-16-09", type="choice", topic="avverbi", level="B1",
         prompt="Elegí el orden natural (ya comí).",
         stem="___", options=["Ho già mangiato", "Ho mangiato già", "Già ho mangiato"],
         answer="Ho già mangiato",
         note="già, mai, ancora, sempre, appena van entre auxiliar y participio."),
    dict(id="rf-16-10", type="choice", topic="avverbi", level="B1",
         prompt=CE, stem="Non sono ___ stato a Venezia.",
         options=["mai", "nunca", "ancora mai"], answer="mai",
         note="«Mai» se ubica entre auxiliar y participio: non sono mai stato."),
    dict(id="rf-16-11", type="choice", topic="avverbi", level="B1",
         prompt=CE, stem="Parla ___ l'italiano: sembra nata a Bologna.",
         options=["benissimo", "buonissimo", "molto buono"], answer="benissimo",
         note="El superlativo del adverbio: bene → benissimo; male → malissimo."),
    dict(id="rf-16-12", type="choice", topic="avverbi", level="B1",
         prompt="¿Qué significa «appena» en «Sono appena arrivato»?",
         stem="Sono appena arrivato.",
         options=["recién (acabo de)", "apenas (con dificultad)", "pronto"],
         answer="recién (acabo de)",
         note="«Appena» + tiempo compuesto = recién: «Sono appena arrivato» = recién llego."),
    dict(id="rf-16-13", type="choice", topic="avverbi", level="B1",
         prompt="¿Cómo se dice «de a poco»?",
         stem="Sto imparando ___.", options=["a poco a poco", "da poco a poco", "di poco"],
         answer="a poco a poco",
         note="«(A) poco a poco» = de a poco. «Da poco» = desde hace poco."),
    dict(id="rf-16-14", type="choice", topic="avverbi", level="B1",
         prompt="Elegí la forma correcta (mañana a la mañana).",
         stem="Ci vediamo ___ alle nove.", options=["domattina", "domani mattino", "mattina domani"],
         answer="domattina",
         note="«Domattina» = domani mattina. También existen stamattina, stasera, stanotte."),
    dict(id="rf-16-15", type="cloze", topic="avverbi", level="B1",
         prompt="Completá con un adverbio (despacito, en voz baja).",
         stem="Parla ___, il bambino dorme.", answer="piano",
         alt=["sottovoce", "a bassa voce"],
         note="«Piano» es adverbio: en voz baja o despacio. «Sottovoce» = en voz baja."),
    dict(id="rf-16-16", type="choice", topic="avverbi", level="B1",
         prompt=CE, stem="Mia nonna abita qui ___.", options=["vicino", "vicina", "vicinamente"],
         answer="vicino",
         note="Como adverbio, «vicino» es invariable aunque el sujeto sea femenino."),
    dict(id="rf-16-17", type="choice", topic="avverbi", level="B1",
         prompt=CE, stem="Parla più ___, non ti sento!", options=["forte", "fortemente", "forti"],
         answer="forte",
         note="Algunos adjetivos funcionan como adverbios sin -mente: forte, piano, chiaro, veloce."),
    dict(id="rf-16-18", type="choice", topic="avverbi", level="B1",
         prompt=CE, stem="Il vento soffiava ___.",
         options=["violentemente", "violentamente", "violentomente"],
         answer="violentemente",
         note="Varios adjetivos en -lento hacen -lentemente: violento → violentemente, fraudolento → fraudolentemente. Ojo: lento → lentamente."),
    dict(id="rf-16-19", type="cloze", topic="avverbi", level="B1",
         prompt="Formá el adverbio en -mente.",
         stem="Sei ___ (leggero) più alto di me.", answer="leggermente",
         note="leggera + mente → leggermente (se pierde la a por excepción)."),
    dict(id="rf-16-20", type="cloze", topic="avverbi", level="B1",
         prompt="Formá el adverbio en -mente.",
         stem="Il professore ha parlato ___ (breve) della vita di Petrarca.",
         answer="brevemente",
         note="Adjetivos en -e (sin l/r antes): breve → brevemente."),
    dict(id="rf-16-21", type="translate", topic="avverbi", level="B1",
         prompt=TR, stem="Hablás italiano perfectamente.",
         answer="Parli italiano perfettamente",
         alt=["Parli perfettamente italiano", "Parli perfettamente l'italiano",
              "Parli l'italiano perfettamente"],
         note="perfetta + mente → perfettamente."),
    dict(id="rf-16-22", type="translate", topic="avverbi", level="B1",
         prompt=TR, stem="Ya terminé.", answer="Ho già finito",
         alt=["Ho già terminato"],
         note="«Già» entre auxiliar y participio. El pretérito rioplatense suele ir a passato prossimo."),
    dict(id="rf-16-23", type="translate", topic="avverbi", level="B1",
         prompt=TR, stem="Siempre llega tarde.", answer="Arriva sempre tardi",
         alt=["Arriva sempre in ritardo", "È sempre in ritardo"],
         note="«Tardi» es el adverbio (tarde); «tardo» es adjetivo (tardío)."),
    dict(id="rf-16-24", type="translate", topic="avverbi", level="B1",
         prompt=TR, stem="Manejá despacio, por favor.", answer="Guida piano, per favore",
         alt=["Guida piano per favore", "Guida lentamente, per favore",
              "Guida lentamente per favore", "Per favore, guida piano",
              "Per favore guida piano", "Per favore, guida lentamente",
              "Per favore guida lentamente"],
         note="«Piano» o «lentamente». Manejar = guidare."),
    dict(id="rf-16-25", type="choice", topic="avverbi", level="B1",
         prompt="Elegí la forma correcta (sobre todo).",
         stem="Leopardi scriveva ___ di notte.",
         options=["soprattutto", "sopratutto", "sopra tuto"], answer="soprattutto",
         note="«Soprattutto» con tt: sopra + tutto se funden y la t se duplica."),

    # ================= Settimana 22: Comparativi e superlativi =================
    dict(id="rf-22-01", type="choice", topic="comparativi", level="B1",
         prompt=CE, stem="Roma è più antica ___ Buenos Aires.",
         options=["di", "che", "come"], answer="di",
         note="Ante sustantivo o nombre propio, el segundo término va con «di»."),
    dict(id="rf-22-02", type="choice", topic="comparativi", level="B1",
         prompt=CE, stem="Leggere è più rilassante ___ guardare la tv.",
         options=["che", "di", "del"], answer="che",
         note="Entre dos infinitivos se usa «che»."),
    dict(id="rf-22-03", type="cloze", topic="comparativi", level="B1",
         prompt="Completá (el más largo).",
         stem="Il Po è il fiume ___ lungo d'Italia.", answer="più",
         note="Superlativo relativo: il più + adjetivo + di."),
    dict(id="rf-22-04", type="choice", topic="comparativi", level="B1",
         prompt=CE, stem="In Argentina ci sono più mucche ___ abitanti.",
         options=["che", "di", "come"], answer="che",
         note="Al comparar dos cantidades de sustantivos se usa «che»."),
    dict(id="rf-22-05", type="choice", topic="comparativi", level="B1",
         prompt="Elegí la forma correcta (mayor).",
         stem="Mio fratello ___ vive a Córdoba.", options=["maggiore", "massimo", "maggiori"],
         answer="maggiore",
         note="maggiore/minore = mayor/menor, también para hermanos."),
    dict(id="rf-22-06", type="choice", topic="comparativi", level="B1",
         prompt=CE, stem="È il ___ ristorante del quartiere.",
         options=["migliore", "meglio", "ottimo"], answer="migliore",
         note="Superlativo relativo de buono: il migliore. «Meglio» es adverbio."),
    dict(id="rf-22-07", type="choice", topic="comparativi", level="B1",
         prompt="Elegí la forma correcta (malísima).",
         stem="La cena era ___: non ci torno più.",
         options=["pessima", "peggiore", "minima"], answer="pessima",
         note="Superlativo absoluto irregular: cattivo → pessimo, buono → ottimo."),
    dict(id="rf-22-08", type="cloze", topic="comparativi", level="B1",
         prompt="Completá con di + artículo.",
         stem="Il Colosseo è più grande ___ Pantheon.", answer="del",
         note="di + il = del. El artículo del sustantivo se combina con «di»."),
    dict(id="rf-22-09", type="cloze", topic="comparativi", level="B1",
         prompt="Completá (tan alto como).",
         stem="Luca è alto ___ suo padre.", answer="come",
         alt=["quanto"],
         note="Igualdad: (così) ... come / (tanto) ... quanto."),
    dict(id="rf-22-10", type="cloze", topic="comparativi", level="B1",
         prompt="Completá (menos).",
         stem="Oggi Sabato è ___ famoso di Borges.", answer="meno",
         note="Inferioridad: meno ... di."),
    dict(id="rf-22-11", type="cloze", topic="comparativi", level="B1",
         prompt="Formá el superlativo absoluto en -issimo.",
         stem="Il panettone di mia zia è ___ (buono).", answer="buonissimo",
         note="buono → buonissimo, o la forma irregular «ottimo»."),
    dict(id="rf-22-12", type="cloze", topic="comparativi", level="B1",
         prompt="Formá el superlativo absoluto en -issimo.",
         stem="Le strade di Napoli sono ___ (stretto).", answer="strettissime",
         note="Concuerda con strade: stretto → strettissime."),
    dict(id="rf-22-13", type="cloze", topic="comparativi", level="B1",
         prompt="Formá el superlativo absoluto en -issimo.",
         stem="L'esame di ieri era ___ (facile).", answer="facilissimo",
         note="Se saca la vocal final y se agrega -issimo: facile → facilissimo."),
    dict(id="rf-22-14", type="choice", topic="comparativi", level="B1",
         prompt=CE, stem="Il nuovo collega è più simpatico ___ bello.",
         options=["che", "di", "come"], answer="che",
         note="Entre dos cualidades del mismo sujeto: «che»."),
    dict(id="rf-22-15", type="choice", topic="comparativi", level="B1",
         prompt=CE, stem="È più facile dirlo ___ farlo.",
         options=["che", "di", "del"], answer="che",
         note="Dos verbos comparados → «che»."),
    dict(id="rf-22-16", type="choice", topic="comparativi", level="B1",
         prompt=CE, stem="Gli italiani bevono più caffè ___ tè.",
         options=["che", "di", "del"], answer="che",
         note="Dos sustantivos con el mismo verbo → «che»."),
    dict(id="rf-22-17", type="choice", topic="comparativi", level="B1",
         prompt=CE, stem="Per molti Venezia è la città più romantica ___ mondo.",
         options=["del", "che", "come"], answer="del",
         note="El segundo término del superlativo relativo va con «di» (+ artículo)."),
    dict(id="rf-22-18", type="choice", topic="comparativi", level="B1",
         prompt=CE, stem="Il Monte Bianco è la montagna ___ alta d'Europa.",
         options=["più", "molto", "tanto"], answer="più",
         note="la più alta = la más alta. «Molto alta» sería absoluto, sin «d'Europa»."),
    dict(id="rf-22-19", type="choice", topic="comparativi", level="B1",
         prompt="Elegí la forma correcta (máxima).",
         stem="La temperatura ___ di oggi è di 35 gradi.",
         options=["massima", "maggiore", "più grande"], answer="massima",
         note="massimo/minimo son superlativos de grande/piccolo en sentido técnico."),
    dict(id="rf-22-20", type="choice", topic="comparativi", level="B1",
         prompt="Elegí la forma correcta (ni la más mínima idea).",
         stem="Non ne ho la ___ idea.", options=["minima", "minore", "meno"],
         answer="minima",
         note="«Non ne ho la minima idea»: frase hecha con el superlativo «minimo»."),
    dict(id="rf-22-21", type="choice", topic="comparativi", level="B1",
         prompt=CE, stem="Il viaggio è stato più lungo ___ previsto.",
         options=["del", "che", "come"], answer="del",
         note="«Più ... del previsto» = más ... de lo previsto."),
    dict(id="rf-22-22", type="translate", topic="comparativi", level="B1",
         prompt=TR, stem="Mi hermana es más alta que yo.",
         answer="Mia sorella è più alta di me",
         note="Ante pronombre: di + forma tónica (di me, di te)."),
    dict(id="rf-22-23", type="translate", topic="comparativi", level="B1",
         prompt=TR, stem="Es el peor día de mi vida.",
         answer="È il giorno peggiore della mia vita",
         alt=["È il peggior giorno della mia vita", "È il peggiore giorno della mia vita"],
         note="peggiore puede ir antes o después; delante se acorta a menudo: il peggior giorno."),
    dict(id="rf-22-24", type="translate", topic="comparativi", level="B1",
         prompt=TR, stem="Hoy hace menos frío que ayer.",
         answer="Oggi fa meno freddo di ieri",
         alt=["Oggi fa meno freddo che ieri"],
         note="El frío se «hace» también en italiano: fa freddo."),
    dict(id="rf-22-25", type="translate", topic="comparativi", level="B1",
         prompt=TR, stem="Este café está riquísimo.",
         answer="Questo caffè è buonissimo",
         alt=["Questo caffè è ottimo"],
         note="Superlativo absoluto: buonissimo u ottimo. «Estar rico» → essere buono."),

    # ================= Settimana 24: Suffissi e alterazione =================
    dict(id="rf-24-01", type="choice", topic="suffissi", level="B1",
         prompt="¿Qué significa «casetta»?", stem="casetta",
         options=["casita", "casona", "casucha"], answer="casita",
         note="-etto/-etta: diminutivo neutro o afectivo."),
    dict(id="rf-24-02", type="choice", topic="suffissi", level="B1",
         prompt="¿Qué es «un librone»?", stem="un librone",
         options=["un libro grande y gordo", "un libro viejo", "un libro malo"],
         answer="un libro grande y gordo",
         note="-one es aumentativo: librone, nasone, gattone."),
    dict(id="rf-24-03", type="choice", topic="suffissi", level="B1",
         prompt="¿Qué significa «parolaccia»?", stem="Non dire parolacce!",
         options=["mala palabra, insulto", "palabra larga", "palabrita"],
         answer="mala palabra, insulto",
         note="-accio/-accia: despectivo. Parolaccia = mala palabra."),
    dict(id="rf-24-04", type="choice", topic="suffissi", level="B1",
         prompt="Elegí el diminutivo afectuoso de «gatto».",
         stem="Che carino quel ___!", options=["gattino", "gattone", "gattaccio"],
         answer="gattino",
         note="-ino: pequeño y tierno. -one agranda, -accio desprecia."),
    dict(id="rf-24-05", type="cloze", topic="suffissi", level="B1",
         prompt="Formá el diminutivo con -ino.",
         stem="Il mio ___ (fratello) ha tre anni.", answer="fratellino",
         note="fratello → fratellino = hermanito."),
    dict(id="rf-24-06", type="cloze", topic="suffissi", level="B1",
         prompt="Formá el aumentativo con -one.",
         stem="Cyrano de Bergerac aveva un ___ (naso).", answer="nasone",
         note="naso → nasone = narigón, nariz enorme."),
    dict(id="rf-24-07", type="cloze", topic="suffissi", level="B1",
         prompt="Formá el despectivo con -accia.",
         stem="Gli ha scritto una ___ (lettera) piena di insulti.", answer="letteraccia",
         note="-accio/-accia agrega valor negativo: letteraccia = carta fea, agresiva."),
    dict(id="rf-24-08", type="choice", topic="suffissi", level="B1",
         prompt="¿Cuál NO es un diminutivo de otra palabra?",
         stem="___", options=["postino", "gattino", "ragazzino"], answer="postino",
         note="Falsos alterados: postino (cartero), mattone, tacchino, lampone. Son palabras propias."),
    dict(id="rf-24-09", type="choice", topic="suffissi", level="B1",
         prompt="¿Qué es «un mattone»?", stem="un mattone",
         options=["un ladrillo", "una mata grande", "un loco"], answer="un ladrillo",
         note="Falso aumentativo: no viene de «matto». Un mattone = un ladrillo (y un libro pesado)."),
    dict(id="rf-24-10", type="choice", topic="suffissi", level="B1",
         prompt="¿Qué es «un tacchino»?", stem="A Natale mangiamo il tacchino.",
         options=["un pavo", "un taquito", "un tacón chico"], answer="un pavo",
         note="Falso diminutivo: tacchino = pavo. Tacco = taco del zapato."),
    dict(id="rf-24-11", type="choice", topic="suffissi", level="B1",
         prompt="Elegí la forma correcta (fiebre muy alta).",
         stem="Il bambino ha un ___.", options=["febbrone", "febbrona", "febbretta"],
         answer="febbrone",
         note="Con -one muchos femeninos pasan a masculino: la febbre → un febbrone."),
    dict(id="rf-24-12", type="choice", topic="suffissi", level="B1",
         prompt="¿Qué es «una stradina»?", stem="Ci siamo persi in una stradina di Trastevere.",
         options=["una callecita angosta", "una avenida ancha", "una autopista"],
         answer="una callecita angosta",
         note="strada → stradina: diminutivo con -ina."),
    dict(id="rf-24-13", type="cloze", topic="suffissi", level="B1",
         prompt="Formá el diminutivo con -etta.",
         stem="Abitano in una ___ (casa) in campagna.", answer="casetta",
         note="casa → casetta. También existe «casina», pero acá se pide -etta."),
    dict(id="rf-24-14", type="cloze", topic="suffissi", level="B1",
         prompt="Formá el diminutivo con -etto.",
         stem="Vorrei solo un ___ (pezzo) di torta.", answer="pezzetto",
         note="pezzo → pezzetto = pedacito."),
    dict(id="rf-24-15", type="cloze", topic="suffissi", level="B1",
         prompt="Formá el despectivo con -accio.",
         stem="Tuo zio ha proprio un ___ (carattere)!", answer="caratteraccio",
         note="carattere → caratteraccio = mal carácter."),
    dict(id="rf-24-16", type="choice", topic="suffissi", level="B1",
         prompt="¿Qué matiz tiene «poetastro»?", stem="un poetastro",
         options=["poeta malo, de poca monta", "poeta famoso", "poeta joven"],
         answer="poeta malo, de poca monta",
         note="-astro es despectivo: poetastro, medicastro."),
    dict(id="rf-24-17", type="choice", topic="suffissi", level="B1",
         prompt="¿Qué significa «giallastro»?", stem="un colore giallastro",
         options=["amarillento, de un tono feo", "amarillísimo", "amarillo brillante"],
         answer="amarillento, de un tono feo",
         note="Con colores, -astro indica un tono impreciso y poco lindo: giallastro, verdastro."),
    dict(id="rf-24-18", type="choice", topic="suffissi", level="B1",
         prompt="¿Cómo se llama el texto que Da Ponte escribió para «Don Giovanni» de Mozart?",
         stem="il ___ di Da Ponte", options=["libretto", "librone", "libraccio"],
         answer="libretto",
         note="Diminutivo lexicalizado: libretto = texto de una ópera (y también libreta)."),
    dict(id="rf-24-19", type="choice", topic="suffissi", level="B1",
         prompt="¿Qué son «gli scarponi»?", stem="Per il trekking servono gli scarponi.",
         options=["botas de montaña", "zapatos rotos", "zapatitos"],
         answer="botas de montaña",
         note="Aumentativo lexicalizado: scarpa → scarpone = bota de montaña o de esquí."),
    dict(id="rf-24-20", type="choice", topic="suffissi", level="B1",
         prompt="¿Qué es «l'ombrellone»?", stem="Abbiamo affittato un ombrellone a Rimini.",
         options=["la sombrilla de playa", "un paraguas roto", "una sombra grande"],
         answer="la sombrilla de playa",
         note="ombrello → ombrellone: aumentativo que ya es palabra propia."),
    dict(id="rf-24-21", type="cloze", topic="suffissi", level="B1",
         prompt="Formá el diminutivo con -ina.",
         stem="La mia ___ (nonna) prepara i biscotti ogni domenica.", answer="nonnina",
         note="nonna → nonnina: tono cariñoso."),
    dict(id="rf-24-22", type="cloze", topic="suffissi", level="B1",
         prompt="Formá el aumentativo con -one.",
         stem="Hai visto quel ___ (gatto)? Pesa dieci chili!", answer="gattone",
         note="gatto → gattone = gatazo."),
    dict(id="rf-24-23", type="translate", topic="suffissi", level="B1",
         prompt="Traducí al italiano usando un diminutivo.",
         stem="Esperá un ratito.", answer="Aspetta un attimino",
         alt=["Aspetta un momentino", "Aspetta un minutino", "Aspetta un pochino"],
         note="attimo → attimino, momento → momentino: diminutivos muy de todos los días."),
    dict(id="rf-24-24", type="translate", topic="suffissi", level="B1",
         prompt="Traducí al italiano usando un diminutivo.",
         stem="¡Qué lindo perrito!", answer="Che bel cagnolino!",
         alt=["Che bel cagnetto", "Che cagnolino carino", "Che carino il cagnolino"],
         note="cane → cagnolino (con el interfijo -ol-) o cagnetto."),
    dict(id="rf-24-25", type="translate", topic="suffissi", level="B1",
         prompt="Traducí al italiano usando un sufijo despectivo.",
         stem="Tuvo un día horrible.", answer="Ha avuto una giornataccia",
         alt=["Ha passato una giornataccia"],
         note="giornata + -accia = giornataccia: día de porquería."),

    # ================= Settimana 35: Si passivante e si impersonale =================
    dict(id="rf-35-01", type="choice", topic="si impersonale", level="B2",
         prompt=CE, stem="In questo negozio si ___ biciclette usate.",
         options=["vendono", "vende", "venduto"], answer="vendono",
         note="Si passivante: el verbo concuerda con el objeto plural (biciclette)."),
    dict(id="rf-35-02", type="choice", topic="si impersonale", level="B2",
         prompt=CE, stem="In Argentina si ___ molta carne.",
         options=["mangia", "mangiano", "mangiamo"], answer="mangia",
         note="«Molta carne» es singular → verbo en singular."),
    dict(id="rf-35-03", type="choice", topic="si impersonale", level="B2",
         prompt=CE, stem="Nelle giornate limpide da Torino si ___ le Alpi.",
         options=["vedono", "vede", "vedi"], answer="vedono",
         note="Los Alpes son plural: si vedono."),
    dict(id="rf-35-04", type="choice", topic="si impersonale", level="B2",
         prompt=CE, stem="In agosto si ___ al mare.", options=["va", "vanno", "andiamo"],
         answer="va",
         note="Si impersonal con verbo sin objeto: siempre 3ª persona singular."),
    dict(id="rf-35-05", type="choice", topic="si impersonale", level="B2",
         prompt=CE, stem="Quando si è ___, tutto sembra facile.",
         options=["felici", "felice", "felicità"], answer="felici",
         note="Con si impersonal + essere, el adjetivo va en plural: si è felici."),
    dict(id="rf-35-06", type="cloze", topic="si impersonale", level="B2",
         prompt="Completá con el presente (si passivante).",
         stem="A Bologna si ___ (fare) dei tortellini buonissimi.", answer="fanno",
         note="El objeto plural (tortellini) manda: si fanno."),
    dict(id="rf-35-07", type="cloze", topic="si impersonale", level="B2",
         prompt="Completá con el presente.",
         stem="Nei locali pubblici non si ___ (potere) fumare.", answer="può",
         note="Modal + infinitivo sin objeto → 3ª singular: non si può."),
    dict(id="rf-35-08", type="cloze", topic="si impersonale", level="B2",
         prompt="Completá con el presente.",
         stem="In Italia si ___ (usare) molto il treno.", answer="usa",
         note="«Il treno» es singular: si usa."),
    dict(id="rf-35-09", type="cloze", topic="si impersonale", level="B2",
         prompt="Completá con el presente.",
         stem="Al Teatro Colón si ___ (ascoltare) le opere di Verdi e Puccini.",
         answer="ascoltano",
         note="Objeto plural (le opere) → verbo plural."),
    dict(id="rf-35-10", type="cloze", topic="si impersonale", level="B2",
         prompt="Completá con el passato prossimo.",
         stem="Ieri sera, in quella trattoria, si ___ (mangiare) benissimo.",
         answer="è mangiato",
         note="Con si, los tiempos compuestos van siempre con essere: si è mangiato."),
    dict(id="rf-35-11", type="cloze", topic="si impersonale", level="B2",
         prompt="Completá con el passato prossimo.",
         stem="Alla festa si ___ (bere) troppi spritz.", answer="sono bevuti",
         note="Si passivante con objeto plural: essere y participio concordados (sono bevuti)."),
    dict(id="rf-35-12", type="choice", topic="si impersonale", level="B2",
         prompt=CE, stem="Al carnevale di Venezia ci si ___ divertiti molto.",
         options=["è", "sono", "ha"], answer="è",
         note="Con verbos reflexivos: «ci si» + è + participio en plural."),
    dict(id="rf-35-13", type="choice", topic="si impersonale", level="B2",
         prompt="Elegí la forma correcta con si impersonal (uno se levanta).", stem="In campagna ___ alza presto.",
         options=["ci si", "si si", "si"], answer="ci si",
         note="Reflexivo impersonal: no se dice «si si», sino «ci si alza»."),
    dict(id="rf-35-14", type="choice", topic="si impersonale", level="B2",
         prompt="Elegí la forma correcta (enfermos).",
         stem="Quando si è ___, si resta a casa.", options=["malati", "malato", "malata"],
         answer="malati",
         note="Si è + adjetivo en plural masculino, aunque el verbo esté en singular."),
    dict(id="rf-35-15", type="choice", topic="si impersonale", level="B2",
         prompt=CE, stem="Oggi in ufficio si ___ lavorato tutto il giorno.",
         options=["è", "ha", "sono"], answer="è",
         note="Aunque lavorare lleve avere, con si impersonal va essere: si è lavorato."),
    dict(id="rf-35-16", type="choice", topic="si impersonale", level="B2",
         prompt="¿Qué significa?", stem="Si dice che il nuovo sindaco sia onesto.",
         options=["Dicen que el nuevo intendente es honesto", "Él dice que es honesto",
                  "Se dijo honesto"],
         answer="Dicen que el nuevo intendente es honesto",
         note="«Si dice che» = dicen que / se dice que; suele pedir congiuntivo."),
    dict(id="rf-35-17", type="choice", topic="si impersonale", level="B2",
         prompt=CE, stem="In Italia non si ___ il cappuccino dopo pranzo.",
         options=["beve", "bevono", "bevi"], answer="beve",
         note="Objeto singular (il cappuccino) → si beve."),
    dict(id="rf-35-18", type="cloze", topic="si impersonale", level="B2",
         prompt="Completá con el imperfetto.",
         stem="Nel Medioevo i libri si ___ (scrivere) a mano.", answer="scrivevano",
         note="Si passivante en imperfetto: concuerda con «i libri»."),
    dict(id="rf-35-19", type="cloze", topic="si impersonale", level="B2",
         prompt="Completá con el imperfetto.",
         stem="Nel Rinascimento a Firenze si ___ (costruire) palazzi splendidi.",
         answer="costruivano",
         note="Palazzi es plural → si costruivano."),
    dict(id="rf-35-20", type="choice", topic="si impersonale", level="B2",
         prompt="Elegí la forma correcta con si impersonal (uno lo toma).", stem="Il caffè? ___ beve al banco, in piedi.",
         options=["Lo si", "Si lo", "Se lo"], answer="Lo si",
         note="Pronombre directo + si: lo si, la si, li si (nunca «si lo»)."),
    dict(id="rf-35-21", type="choice", topic="si impersonale", level="B2",
         prompt=CE, stem="Del cambiamento climatico ___ parla ogni giorno.",
         options=["se ne", "si ne", "ne si"], answer="se ne",
         note="si + ne → se ne: se ne parla."),
    dict(id="rf-35-22", type="translate", topic="si impersonale", level="B2",
         prompt=TR, stem="Acá se habla italiano.", answer="Qui si parla italiano",
         alt=["Si parla italiano qui", "Qui si parla l'italiano", "Qua si parla italiano"],
         note="Igual que en español: si + 3ª persona."),
    dict(id="rf-35-23", type="translate", topic="si impersonale", level="B2",
         prompt=TR, stem="En Argentina se cena tarde.", answer="In Argentina si cena tardi",
         alt=["In Argentina si cena tardi la sera"],
         note="«Tardi» es el adverbio; si impersonal con verbo intransitivo."),
    dict(id="rf-35-24", type="translate", topic="si impersonale", level="B2",
         prompt=TR, stem="Se alquilan departamentos.", answer="Si affittano appartamenti",
         alt=["Affittasi appartamenti"],
         note="Si passivante plural. En los carteles aparece la forma fija «affittasi»."),
    dict(id="rf-35-25", type="translate", topic="si impersonale", level="B2",
         prompt=TR, stem="Cuando uno es joven, se enamora fácilmente.",
         answer="Quando si è giovani, ci si innamora facilmente",
         alt=["Quando si è giovani ci si innamora facilmente",
              "Quando si è giovani, ci si innamora con facilità",
              "Quando si è giovani ci si innamora con facilità"],
         note="«Uno» impersonal → si; con reflexivo → ci si; adjetivo en plural (giovani)."),

    # ================= Settimana 38: Pronomi relativi =================
    dict(id="rf-38-01", type="choice", topic="relativi", level="B2",
         prompt=CE, stem="Il romanzo ___ sto leggendo è di Calvino.",
         options=["che", "cui", "il quale"], answer="che",
         note="Objeto directo sin preposición → che. «Il quale» no funciona como objeto."),
    dict(id="rf-38-02", type="choice", topic="relativi", level="B2",
         prompt=CE, stem="La città ___ sono nato è Rosario.",
         options=["in cui", "che", "cui"], answer="in cui",
         note="Lugar: in cui (o dove). «Che» no lleva preposición."),
    dict(id="rf-38-03", type="choice", topic="relativi", level="B2",
         prompt=CE, stem="Il ragazzo ___ ho prestato la bici non me l'ha ridata.",
         options=["a cui", "che", "di cui"], answer="a cui",
         note="Prestare qualcosa A qualcuno → a cui."),
    dict(id="rf-38-04", type="choice", topic="relativi", level="B2",
         prompt=CE, stem="È un argomento ___ non so niente.",
         options=["di cui", "che", "in cui"], answer="di cui",
         note="Sapere qualcosa DI qualcosa → di cui."),
    dict(id="rf-38-05", type="choice", topic="relativi", level="B2",
         prompt=CE, stem="Lo scrittore, ___ romanzi sono tradotti in trenta lingue, vive a Napoli.",
         options=["i cui", "che i", "di cui i"], answer="i cui",
         note="Cuyo: artículo del objeto poseído + cui (i cui romanzi)."),
    dict(id="rf-38-06", type="choice", topic="relativi", level="B2",
         prompt=CE, stem="Elena Ferrante, ___ opera più famosa è «L'amica geniale», usa uno pseudonimo.",
         options=["la cui", "che la", "il cui"], answer="la cui",
         note="El artículo concuerda con lo poseído (opera, fem.), no con el poseedor."),
    dict(id="rf-38-07", type="choice", topic="relativi", level="B2",
         prompt=CE, stem="___ mi preoccupa è il prezzo.",
         options=["Quello che", "Che", "Il che"], answer="Quello che",
         note="«Lo que» = quello che / ciò che. «Che» solo no alcanza."),
    dict(id="rf-38-08", type="choice", topic="relativi", level="B2",
         prompt=CE, stem="L'Argentina ha vinto la partita, ___ ci ha sorpreso tutti.",
         options=["il che", "che", "quello che"], answer="il che",
         note="«Il che» retoma toda la frase anterior (lo cual)."),
    dict(id="rf-38-09", type="choice", topic="relativi", level="B2",
         prompt="Completá el refrán.", stem="___ dorme non piglia pesci.",
         options=["Chi", "Che", "Quale"], answer="Chi",
         note="«Chi» = el que / quien, sin antecedente. Siempre con verbo en singular."),
    dict(id="rf-38-10", type="cloze", topic="relativi", level="B2",
         prompt="Completá con el relativo (con la que).",
         stem="Questa è la penna ___ ho firmato il contratto.", answer="con cui",
         alt=["con la quale"],
         note="Preposición + cui, o preposición articulada + quale."),
    dict(id="rf-38-11", type="cloze", topic="relativi", level="B2",
         prompt="Completá con el relativo (por el que).",
         stem="Il motivo ___ sono venuto è semplice.", answer="per cui",
         alt=["per il quale"],
         note="per cui / per il quale = por el que."),
    dict(id="rf-38-12", type="cloze", topic="relativi", level="B2",
         prompt="Completá con el relativo (en la que).",
         stem="La casa ___ è nato Leopardi è a Recanati.", answer="in cui",
         alt=["nella quale", "dove"],
         note="Lugar: in cui, nella quale o dove."),
    dict(id="rf-38-13", type="cloze", topic="relativi", level="B2",
         prompt="Completá con el relativo (a las que).",
         stem="Le persone ___ abbiamo chiesto aiuto sono state gentili.", answer="a cui",
         alt=["alle quali", "cui"],
         note="Chiedere A qualcuno → a cui o alle quali (en registro culto, «cui» solo)."),
    dict(id="rf-38-14", type="cloze", topic="relativi", level="B2",
         prompt="Completá con el relativo (de donde).",
         stem="Il paese ___ viene mia nonna è in Calabria.", answer="da cui",
         alt=["dal quale"],
         note="Venire DA → da cui / dal quale."),
    dict(id="rf-38-15", type="choice", topic="relativi", level="B2",
         prompt="Elegí el relativo que deja claro que la que vive en París es la hermana.",
         stem="Ho conosciuto la sorella di Marco, ___ vive a Parigi.",
         options=["la quale", "il quale", "che"], answer="la quale",
         note="«Il/la quale» marca género y número: sirve para evitar ambigüedades."),
    dict(id="rf-38-16", type="choice", topic="relativi", level="B2",
         prompt=CE, stem="Mi piace il modo ___ parla.",
         options=["in cui", "che", "cui"], answer="in cui",
         note="«Il modo in cui» = la manera en que."),
    dict(id="rf-38-17", type="choice", topic="relativi", level="B2",
         prompt=CE, stem="È una cosa ___ tengo molto.",
         options=["a cui", "che", "di cui"], answer="a cui",
         note="Tenere A qualcosa = importarle a uno algo → a cui."),
    dict(id="rf-38-18", type="choice", topic="relativi", level="B2",
         prompt="Elegí la forma correcta (quién).", stem="Dimmi ___ ha rotto il vaso.",
         options=["chi", "che", "il quale"], answer="chi",
         note="Sin antecedente, referido a persona: chi."),
    dict(id="rf-38-19", type="cloze", topic="relativi", level="B2",
         prompt="Completá con el relativo (cuyo).",
         stem="Il medico, ___ figlio studia con me, è molto bravo.", answer="il cui",
         note="il cui + sustantivo masculino singular."),
    dict(id="rf-38-20", type="cloze", topic="relativi", level="B2",
         prompt="Completá con el relativo (cuyas).",
         stem="Le Dolomiti, ___ cime sono innevate, sembrano vicinissime.", answer="le cui",
         note="le cui + sustantivo femenino plural (cime)."),
    dict(id="rf-38-21", type="choice", topic="relativi", level="B2",
         prompt=CE, stem="Ecco la ragione per ___ non ti ho chiamato.",
         options=["cui", "che", "quale"], answer="cui",
         note="Tras preposición: cui (o «la quale», con artículo)."),
    dict(id="rf-38-22", type="translate", topic="relativi", level="B2",
         prompt=TR, stem="La chica con la que salgo es italiana.",
         answer="La ragazza con cui esco è italiana",
         alt=["La ragazza con la quale esco è italiana"],
         note="Con la que → con cui / con la quale."),
    dict(id="rf-38-23", type="translate", topic="relativi", level="B2",
         prompt=TR, stem="Es el libro del que todos hablan.",
         answer="È il libro di cui tutti parlano",
         alt=["È il libro di cui parlano tutti", "È il libro del quale tutti parlano",
              "È il libro del quale parlano tutti"],
         note="Parlare DI → di cui / del quale."),
    dict(id="rf-38-24", type="translate", topic="relativi", level="B2",
         prompt=TR, stem="No entiendo lo que decís.",
         answer="Non capisco quello che dici",
         alt=["Non capisco ciò che dici", "Non capisco cosa dici",
              "Non capisco che cosa dici"],
         note="Lo que = quello che / ciò che."),
    dict(id="rf-38-25", type="translate", topic="relativi", level="B2",
         prompt=TR, stem="El pueblo donde nació mi abuelo está en Sicilia.",
         answer=_PAESE[0], alt=_PAESE[1:],
         note="Lugar: in cui, dove o nel quale. Pueblo = paese."),

    # ================= Settimana 46: Costruzioni verbali speciali =================
    dict(id="rf-46-01", type="choice", topic="costruzioni", level="C1",
         prompt=CE, stem="Se la festa non ti piace, ___ pure.",
         options=["vattene", "vatti", "vanno"], answer="vattene",
         note="Imperativo de andarsene: vattene (tú), andatevene (vosotros)."),
    dict(id="rf-46-02", type="choice", topic="costruzioni", level="C1",
         prompt="Elegí el futuro de «farcela» (noi).",
         stem="Non preoccuparti, ce la ___.", options=["faremo", "faremmo", "facciamo"],
         answer="faremo",
         note="farcela = lograrlo. Futuro: ce la farò, ce la faremo."),
    dict(id="rf-46-03", type="choice", topic="costruzioni", level="C1",
         prompt=CE, stem="Ce l'ha ___ me perché non l'ho invitato.",
         options=["con", "a", "per"], answer="con",
         note="avercela con qualcuno = estar enojado con alguien."),
    dict(id="rf-46-04", type="choice", topic="costruzioni", level="C1",
         prompt=CE, stem="Non te la ___: era solo una battuta.",
         options=["prendere", "prendi", "prende"], answer="prendere",
         note="Imperativo negativo de tú = non + infinitivo: non te la prendere."),
    dict(id="rf-46-05", type="choice", topic="costruzioni", level="C1",
         prompt=CE, stem="All'esame di storia Giulia se l'è ___ bene.",
         options=["cavata", "cavato", "cavati"], answer="cavata",
         note="cavarsela = arreglárselas. El participio concuerda con «la»: se l'è cavata."),
    dict(id="rf-46-06", type="choice", topic="costruzioni", level="C1",
         prompt=CE, stem="Per fare un buon ragù ___ almeno tre ore.",
         options=["ci vogliono", "ci mettono", "ci vuole"], answer="ci vogliono",
         note="volerci concuerda con lo que se necesita: ci vogliono tre ore."),
    dict(id="rf-46-07", type="choice", topic="costruzioni", level="C1",
         prompt="Elegí la forma correcta (vos, cuánto tardás).",
         stem="Quanto tempo ___ per arrivare in ufficio?",
         options=["ci metti", "ci vuoi", "ti vuole"], answer="ci metti",
         note="metterci tiene sujeto personal: io ci metto, tu ci metti."),
    dict(id="rf-46-08", type="choice", topic="costruzioni", level="C1",
         prompt=CE, stem="Stavo ___ uscire quando hai chiamato.",
         options=["per", "a", "di"], answer="per",
         note="stare per + infinitivo = estar por / a punto de."),
    dict(id="rf-46-09", type="choice", topic="costruzioni", level="C1",
         prompt=CE, stem="Dopo tanto discutere, ___ per accettare.",
         options=["ha finito", "ha smesso", "si è messo"], answer="ha finito",
         note="finire per + infinitivo = terminar por / acabar haciendo algo."),
    dict(id="rf-46-10", type="choice", topic="costruzioni", level="C1",
         prompt=CE, stem="Appena ha saputo la notizia, si è messo ___ piangere.",
         options=["a", "di", "per"], answer="a",
         note="mettersi a + infinitivo = ponerse a."),
    dict(id="rf-46-11", type="cloze", topic="costruzioni", level="C1",
         prompt="Completá con el passato prossimo de «andarsene».",
         stem="Luisa ___ senza salutare.", answer="se n'è andata",
         alt=["se ne è andata"],
         note="andarsene: me ne sono andato, se n'è andata. Auxiliar essere."),
    dict(id="rf-46-12", type="cloze", topic="costruzioni", level="C1",
         prompt="Completá con el passato prossimo de «farcela» (noi).",
         stem="Alla fine ___ a prendere l'ultimo treno.", answer="ce l'abbiamo fatta",
         alt=["ce la abbiamo fatta"],
         note="farcela con avere; el participio concuerda con «la»: fatta."),
    dict(id="rf-46-13", type="cloze", topic="costruzioni", level="C1",
         prompt="Completá con el presente de «farcela» (io).",
         stem="Non ___ più con questo caldo.", answer="ce la faccio",
         note="Non ce la faccio più = no doy más."),
    dict(id="rf-46-14", type="cloze", topic="costruzioni", level="C1",
         prompt="Completá con el presente de «avercela» (tu).",
         stem="Perché ___ con me?", answer="ce l'hai",
         note="avercela con = tenérsela jurada, estar enojado con alguien."),
    dict(id="rf-46-15", type="cloze", topic="costruzioni", level="C1",
         prompt="Completá con el presente de «volerci».",
         stem="Con i bambini ci ___ tanta pazienza.", answer="vuole",
         note="Algo singular → ci vuole; plural → ci vogliono."),
    dict(id="rf-46-16", type="cloze", topic="costruzioni", level="C1",
         prompt="Completá con el presente de «metterci» (voi).",
         stem="Quanto ___ ad arrivare a Mar del Plata?", answer="ci mettete",
         note="metterci + tiempo + a/per + infinitivo = tardar."),
    dict(id="rf-46-17", type="choice", topic="costruzioni", level="C1",
         prompt="¿Qué significa «smettila»?", stem="Smettila di fare lo scemo!",
         options=["cortala, basta", "sacátelo", "ponételo"], answer="cortala, basta",
         note="smetterla (di) = dejar de, cortarla."),
    dict(id="rf-46-18", type="choice", topic="costruzioni", level="C1",
         prompt="¿Qué significa?", stem="Delle sue critiche me ne infischio.",
         options=["me importan un pepino", "me dan miedo", "me voy enseguida"],
         answer="me importan un pepino",
         note="infischiarsene (di) = no dar importancia a algo."),
    dict(id="rf-46-19", type="choice", topic="costruzioni", level="C1",
         prompt=CE, stem="Non stare lì ___ guardarmi: aiutami!",
         options=["a", "per", "di"], answer="a",
         note="stare a + infinitivo = quedarse haciendo algo."),
    dict(id="rf-46-20", type="choice", topic="costruzioni", level="C1",
         prompt=CE, stem="Non me la ___ di guidare di notte.",
         options=["sento", "sente", "sentono"], answer="sento",
         note="sentirsela (di) = animarse, sentirse capaz."),
    dict(id="rf-46-21", type="choice", topic="costruzioni", level="C1",
         prompt=CE, stem="Se la prende ___: arriva sempre in ritardo.",
         options=["comoda", "comodo", "comodamente"], answer="comoda",
         note="prendersela comoda = tomárselo con calma; «comoda» concuerda con «la»."),
    dict(id="rf-46-22", type="translate", topic="costruzioni", level="C1",
         prompt=TR, stem="Me voy, se hizo tarde.", answer="Me ne vado, si è fatto tardi",
         alt=["Me ne vado: si è fatto tardi", "Me ne vado si è fatto tardi",
              "Me ne vado, è tardi", "Vado via, si è fatto tardi"],
         note="Irse = andarsene. «Se hizo tarde» = si è fatto tardi."),
    dict(id="rf-46-23", type="translate", topic="costruzioni", level="C1",
         prompt=TR, stem="No te enojes conmigo.", answer="Non prendertela con me",
         alt=["Non te la prendere con me", "Non arrabbiarti con me", "Non ti arrabbiare con me"],
         note="prendersela con = enojarse con alguien. Negativo: non + infinitivo."),
    dict(id="rf-46-24", type="translate", topic="costruzioni", level="C1",
         prompt=TR, stem="Estaba por llamarte.", answer="Stavo per chiamarti",
         alt=["Stavo per telefonarti"],
         note="stare per + infinitivo = estar por hacer algo."),
    dict(id="rf-46-25", type="translate", topic="costruzioni", level="C1",
         prompt=TR, stem="Se necesitan dos horas para llegar.",
         answer="Ci vogliono due ore per arrivare",
         alt=["Servono due ore per arrivare", "Occorrono due ore per arrivare"],
         note="volerci en plural porque «due ore» es plural."),

    # ================= Settimana 48: Ordine delle parole e dislocazioni =================
    dict(id="rf-48-01", type="choice", topic="ordine", level="C1",
         prompt="Elegí el pronombre de retoma.",
         stem="La pasta ___ cucino io stasera.", options=["la", "lo", "ne"], answer="la",
         note="Objeto directo dislocado a la izquierda → se retoma con lo/la/li/le."),
    dict(id="rf-48-02", type="choice", topic="ordine", level="C1",
         prompt="Elegí el pronombre de retoma.",
         stem="I compiti, ___ hai fatti?", options=["li", "le", "ne"], answer="li",
         note="i compiti → li, y el participio concuerda: fatti."),
    dict(id="rf-48-03", type="choice", topic="ordine", level="C1",
         prompt="Elegí el pronombre de retoma.",
         stem="Di questa storia non ___ voglio più sapere niente.",
         options=["ne", "ci", "la"], answer="ne",
         note="Complemento con «di» dislocado → se retoma con ne."),
    dict(id="rf-48-04", type="choice", topic="ordine", level="C1",
         prompt="Elegí el pronombre de retoma.",
         stem="Al mare, quest'anno, non ___ andiamo.", options=["ci", "ne", "lo"], answer="ci",
         note="Lugar con «a/in» dislocado → se retoma con ci."),
    dict(id="rf-48-05", type="choice", topic="ordine", level="C1",
         prompt="Elegí el pronombre de retoma.",
         stem="A tua madre, ___ hai detto la verità?", options=["le", "la", "lo"],
         answer="le",
         note="Indirecto femenino dislocado → le. Como en español: «a tu madre, le dijiste»."),
    dict(id="rf-48-06", type="choice", topic="ordine", level="C1",
         prompt="Elegí la forma correcta.",
         stem="___ Leonardo che ha dipinto la Gioconda, non Raffaello.",
         options=["È stato", "Ha stato", "Era stata"], answer="È stato",
         note="Frase escindida: essere + elemento en foco + che."),
    dict(id="rf-48-07", type="choice", topic="ordine", level="C1",
         prompt=CE, stem="È per questo ___ non sono venuto.",
         options=["che", "cui", "il che"], answer="che",
         note="En la frase escindida el nexo es siempre «che», aunque haya preposición: è per questo che."),
    dict(id="rf-48-08", type="choice", topic="ordine", level="C1",
         prompt="Elegí el orden natural para dar una noticia.",
         stem="___", options=["È nato il figlio di Giulia", "Il figlio di Giulia nato è",
                              "Nato è il figlio di Giulia"],
         answer="È nato il figlio di Giulia",
         note="Con verbos como nascere, arrivare, morire, la información nueva va detrás del verbo."),
    dict(id="rf-48-09", type="choice", topic="ordine", level="C1",
         prompt=CE, stem="C'è tuo fratello ___ ti cerca.",
         options=["che", "il quale", "cui"], answer="che",
         note="Presentativo: c'è + sustantivo + che. Muy de la lengua hablada."),
    dict(id="rf-48-10", type="choice", topic="ordine", level="C1",
         prompt="Elegí el pronombre (dislocación a la derecha).",
         stem="Non ___ sopporto più, quel rumore.", options=["lo", "la", "ne"], answer="lo",
         note="El pronombre anticipa lo que viene después: lo ... quel rumore."),
    dict(id="rf-48-11", type="choice", topic="ordine", level="C1",
         prompt="Elegí el pronombre de retoma.",
         stem="Le chiavi, dove ___ hai messe?", options=["le", "li", "ne"], answer="le",
         note="le chiavi → le, y el participio concuerda: messe."),
    dict(id="rf-48-12", type="choice", topic="ordine", level="C1",
         prompt="Elegí el pronombre de retoma.",
         stem="Di soldi, non ___ ho.", options=["ne", "li", "ci"], answer="ne",
         note="Cantidad (partitivo) dislocada → ne: di soldi non ne ho."),
    dict(id="rf-48-13", type="cloze", topic="ordine", level="C1",
         prompt="Completá con el pronombre de retoma.",
         stem="Il giornale ___ compra sempre mio padre.", answer="lo",
         note="Il giornale (objeto) al principio → lo compra. El sujeto va al final, en foco."),
    dict(id="rf-48-14", type="cloze", topic="ordine", level="C1",
         prompt="Completá con el pronombre de retoma.",
         stem="Queste foto di Palermo ___ ha scattate Letizia Battaglia.", answer="le",
         note="Objeto femenino plural → le; el participio concuerda (scattate)."),
    dict(id="rf-48-15", type="cloze", topic="ordine", level="C1",
         prompt="Completá con el pronombre de retoma.",
         stem="A Marco ___ piace il calcio, a me no.", answer="gli",
         note="Indirecto masculino dislocado → gli, igual que el «le» del español."),
    dict(id="rf-48-16", type="cloze", topic="ordine", level="C1",
         prompt="Completá con el pronombre de retoma.",
         stem="Del viaggio in Patagonia ___ parliamo domani.", answer="ne",
         note="Parlare DI → ne."),
    dict(id="rf-48-17", type="cloze", topic="ordine", level="C1",
         prompt="Completá con el pronombre de retoma (elidido ante «ho»).",
         stem="Quel film non ___ho mai visto.", answer="l'",
         note="lo + ho → l'ho. «Film» es masculino en italiano."),
    dict(id="rf-48-18", type="cloze", topic="ordine", level="C1",
         prompt="Completá la frase escindida.",
         stem="È a te ___ devo chiedere scusa.", answer="che",
         note="Frase escindida: è + foco + che. No se usa «a cui»."),
    dict(id="rf-48-19", type="cloze", topic="ordine", level="C1",
         prompt="Completá la frase escindida.",
         stem="È nel 1861 ___ nasce il Regno d'Italia.", answer="che",
         alt=["quando"],
         note="Frase escindida temporal: è + fecha + che (o quando)."),
    dict(id="rf-48-20", type="choice", topic="ordine", level="C1",
         prompt="Respuesta a «¿Quién guió a los Mil?»: elegí la que pone en foco a Garibaldi.",
         stem="___",
         options=["È stato Garibaldi a guidare i Mille",
                  "I Mille li ha guidati",
                  "Garibaldi, i Mille, li guidò"],
         answer="È stato Garibaldi a guidare i Mille",
         note="Escindida implícita: essere + foco + a + infinitivo."),
    dict(id="rf-48-21", type="choice", topic="ordine", level="C1",
         prompt=CE, stem="Sono stati i Romani ___ costruire questa strada.",
         options=["a", "di", "per"], answer="a",
         note="Escindida implícita: sono stati i Romani a costruire."),
    dict(id="rf-48-22", type="translate", topic="ordine", level="C1",
         prompt="Traducí al italiano manteniendo el orden (objeto al principio).",
         stem="Al vino lo trajo Luca.", answer="Il vino l'ha portato Luca",
         alt=["Il vino lo ha portato Luca", "Il vino lo portò Luca"],
         note="En italiano el objeto dislocado no lleva «a»: il vino l'ha portato Luca."),
    dict(id="rf-48-23", type="translate", topic="ordine", level="C1",
         prompt="Traducí al italiano manteniendo el orden (objeto al principio).",
         stem="Esa película ya la vi.", answer="Quel film l'ho già visto",
         alt=["Quel film lo ho già visto", "Quel film, l'ho già visto"],
         note="Película = film (masculino): se retoma con lo/l'."),
    dict(id="rf-48-24", type="translate", topic="ordine", level="C1",
         prompt=TR, stem="Es Marta la que tiene razón.", answer="È Marta che ha ragione",
         alt=["È Marta ad avere ragione", "È Marta a avere ragione"],
         note="«Es X el/la que» → è X che, o è X a + infinitivo."),
    dict(id="rf-48-25", type="translate", topic="ordine", level="C1",
         prompt="Traducí al italiano con el verbo delante.",
         stem="Llegaron tus amigos.", answer="Sono arrivati i tuoi amici",
         note="Con verbos inacusativos el sujeto nuevo va detrás: sono arrivati i tuoi amici."),
]
