# -*- coding: utf-8 -*-
"""Palabras de la semana — tramo C1 (semanas 27-51): el léxico da leitura.

Se suman a las 15 de s3.py y s4.py: léxico B1-C1 tomado de la leitura longa o
la escuta longa de esa semana (tools/pt/tramo/wNN.json), con un ejemplo sacado
o adaptado de ese texto y el uso (colocaciones, falsos amigos, registro).  Doce
por semana desde v3 (antes cinco): lo que el alumno ya leía sin que nadie se lo
enseñara pasa a enseñarse y a volver en el repaso.  En la 32 y la 34 entran,
además, los campos que faltaban: política y ciudadanía (eleição, segundo turno,
Câmara Municipal, STF, INSS) y medio ambiente (mata atlântica, reciclagem,
efeito estufa, garimpo, manguezal).
"""

VOCAB = {
27: [
    ["o recém-chegado", "el recién llegado", "Nas cidades pequenas, todo mundo se conhece, e o recém-chegado demora a ser convidado.", "*Recém* + participio, con guion: *recém-chegado*, *recém-casado*, *recém-nascido*. Femenino: *a recém-chegada*."],
    ["o mutirão", "el trabajo comunitario, la jornada solidaria", "Se você quiser fazer amigos, vai ter que participar do mutirão da praça.", "Trabajo voluntario y colectivo de vecinos: *mutirão de limpeza*. También campaña masiva: *mutirão de vacinação*. Muy brasileño."],
    ["integrar-se", "integrarse, adaptarse (a un grupo o lugar)", "Se vocês forem para o Canadá, pensem também em como a família vai se integrar.", "Con *a* o *em*: *integrar-se à comunidade*, *integrar-se na escola*. Sustantivo: *a integração*."],
    ["o alerta", "el aviso de peligro, la advertencia", "Quem acompanha esse tipo de mudança faz um alerta: o interior não é o paraíso.", "Masculino en portugués: *o alerta*, *fazer um alerta*, *dar o alerta*. Como adjetivo, *ficar alerta* = estar atento."],
    ["fazer as contas", "sacar cuentas, calcular si conviene", "Com o trabalho remoto, muitas famílias das grandes capitais começaram a fazer as contas.", "Evaluar costos y beneficios: *fiz as contas e não vale a pena*. Siempre *as contas*, en plural; distinto de *no fim das contas* (al fin y al cabo)."],
    ["a cidadezinha", "el pueblito", "Foram onze horas de estrada entre São Paulo e uma cidadezinha no sul de Minas Gerais.", "Diminutivo de *cidade*: el *-zinha* achica y da cariño. Ojo: en Brasil, *o interior* es todo lo que no es capital ni costa."],
    ["cair", "caer; cortarse (internet, la llamada)", "A internet cai quando chove, e o hospital mais próximo fica a quarenta minutos.", "Para servicios que se cortan, *cair*: *a internet caiu*, *a ligação caiu*. La luz, en cambio, *acaba*: *acabou a luz*."],
    ["bater", "golpear; tocar (la puerta)", "Ninguém vai bater na sua porta.", "*Bater na porta* (con *em*), *bater palmas* (aplaudir), *bater papo* (charlar). El timbre se *toca*: *tocar a campainha*."],
    ["o telhado", "el techo (de tejas)", "Eles vão dizer como é o inverno, onde fica o médico bom, quem conserta o telhado.", "El techo exterior es *o telhado* (de *telha*, teja); el de adentro, *o teto*. *Goteira* = gotera."],
    ["caber", "entrar (en un lugar); corresponder", "A geladeira que não cabia na porta finalmente encontrou o seu lugar.", "Irregular como en español: *eu caibo*, *coube*. Con *em*: *não cabe na porta*. Figurado: *não cabe a mim decidir* = no me corresponde."],
    ["a vaga", "el puesto vacante; el lugar (de estacionamiento, en un curso)", "Quando você tiver o diploma traduzido e reconhecido, aí sim você começa a procurar vaga.", "*Vaga de emprego* = puesto vacante; *vaga na garagem* = cochera; *vaga na faculdade* = lugar en la universidad."],
    ["o intervalo", "la tanda, el corte; el recreo", "Voltamos depois do intervalo com mais perguntas.", "En radio y tele, *intervalo (comercial)* = tanda; en el fútbol, el entretiempo; en la escuela, el recreo."],
],
28: [
    ["a encruzilhada", "la encrucijada", "Aos dezessete anos, muitos jovens se sentem numa encruzilhada diante do vestibular.", "Cruce de caminos y, sobre todo, momento de decisión difícil: *estar numa encruzilhada*. Frecuente en prensa y ensayo."],
    ["aliviado", "más tranquilo, con alivio", "A senhora levou o iogurte mais simples de todos e pareceu aliviada.", "De *aliviar*; *ficar aliviado*, *suspirar aliviado*. Exclamación: *que alívio!*."],
    ["o rótulo", "la etiqueta (de un envase), el cartel", "Eu, que tinha passado cinco minutos comparando rótulos, saí com dois iogurtes.", "La etiqueta con datos de un producto: *ler o rótulo*. Figurado: *colocar rótulos nas pessoas* = etiquetarlas. Verbo: *rotular*."],
    ["largar", "dejar, abandonar; soltar", "Se eu largasse o emprego no banco, abriria uma pousada na Bahia.", "Mucho más usado que en castellano: *largar tudo*, *largar o emprego*, *largar o cigarro*. También soltar: *larga a minha mão!*."],
    ["desconfiar", "sospechar, no fiarse", "Desconfio que a gente confunde liberdade com quantidade de opções.", "*Desconfiar de alguém* = desconfiar; *desconfiar que* = sospechar que. Sustantivo: *a desconfiança*."],
    ["o corredor", "el pasillo", "Se meu avô entrasse naquele corredor do supermercado, sairia de mãos vazias.", "Sobre todo, pasillo (*corredor do hospital*); también el atleta. *Sair de mãos vazias* = irse con las manos vacías."],
    ["acertar em cheio", "dar en el clavo", "Nesse ponto, o colunista acerta em cheio.", "*Acertar* = atinar, acertar; *em cheio* = de lleno. También *acertar na mosca*."],
    ["em sã consciência", "en su sano juicio", "Ninguém em sã consciência gostaria de voltar a um tempo em que a família decidia a profissão.", "Fórmula fija: *sã* es el femenino de *são* (sano), como en *são e salvo*."],
    ["o vestibulando", "el que rinde el examen de ingreso", "Não estou propondo que os vestibulandos sorteiem o curso.", "De *vestibular*, el examen de ingreso a la universidad (hoy, sobre todo, el *Enem*). *Prestar vestibular* = rendirlo."],
    ["a temporada", "un tiempo, una estadía", "Antes de pedir demissão, eu passaria uma temporada trabalhando numa pousada.", "*Passar uma temporada* = pasar un tiempo (en un lugar). También temporada de fútbol o de series."],
    ["de graça", "gratis", "O próximo passo é tirar umas férias longas e trabalhar lá de graça.", "*De graça* = gratis (*grátis* también existe). Ojo: *sem graça* = sin gracia o avergonzado; *graças a* = gracias a."],
    ["o hóspede", "el huésped", "Lavando lençol, atendendo hóspede reclamando do chuveiro.", "El que se aloja; el que recibe es *o anfitrião*. *Hospedagem* = alojamiento."],
],
29: [
    ["o estagiário", "el pasante, el practicante", "As boas empresas são as primeiras a quererem estagiários bem informados.", "De *o estágio* = la pasantía (no «estadio», que es *estádio*). Femenino: *a estagiária*."],
    ["o recesso", "el receso, las vacaciones (de pasantes, escuelas, Congreso)", "Depois de um ano no mesmo lugar, vocês têm direito a um recesso de trinta dias.", "Pausa de actividades: *recesso escolar*, *recesso parlamentar*, *recesso de fim de ano*. Para el pasante reemplaza a *férias*."],
    ["o lembrete", "el recordatorio", "Por fim, um lembrete: guardem uma cópia do termo de compromisso.", "De *lembrar*. *Deixar um lembrete na geladeira*; en el celular, *criar um lembrete*. Masculino."],
    ["o encrenqueiro", "el problemático, el que arma lío", "Conhecer os seus direitos não é ser encrenqueiro.", "De *a encrenca* = el lío: *meter-se numa encrenca*. Coloquial. Femenino: *encrenqueira*."],
    ["o capricho", "el esmero, el cuidado (y también el antojo)", "É importante eles verem que o horário da faculdade é uma coisa séria, não um capricho.", "Como en castellano, antojo; pero también esmero: *fazer com capricho* = hacer con esmero; *caprichado* = bien hecho, abundante."],
    ["o estágio", "la pasantía, las prácticas", "Todo semestre, milhares de universitários começam o primeiro estágio.", "*Fazer estágio* = hacer una pasantía; *estágio obrigatório* o *não obrigatório*. El estadio es *o estádio*."],
    ["a jornada", "el horario de trabajo", "Para quem está no ensino superior, a jornada não pode passar de seis horas por dia.", "*Jornada de trabalho*; *dupla jornada* = trabajo afuera más la casa. *Passar de* = superar."],
    ["o auxílio", "la ayuda, el subsidio", "A empresa deve pagar uma bolsa e um auxílio-transporte.", "En el lenguaje de derechos: *auxílio-transporte*, *auxílio-doença* (licencia paga). *A bolsa* es la beca o el estipendio."],
    ["o orientador", "el tutor; el director (de tesis)", "Antes de pedirem demissão, conversem com o supervisor e com o professor orientador.", "En la universidad, *orientador* = director de tesis y *orientando* = su tesista. Verbo: *orientar*."],
    ["de boca", "de palabra (un acuerdo)", "Esse acordo de horário foi feito por escrito ou só de boca?", "*Um acordo de boca* = sin papel. Lo contrario: *por escrito*."],
    ["a escala", "el cronograma de turnos", "Guarde tudo: mensagens, escala, e-mails.", "En el trabajo, *escala* = el cronograma: *escala de plantão*, *escala 6x1* (seis días y uno libre)."],
    ["mandar embora", "echar, despedir", "Eu tenho medo de ser mandada embora.", "Coloquial: *mandar alguém embora* = despedirlo o echarlo. Formal: *demitir*. *Ir embora* = irse."],
],
30: [
    ["enganado", "equivocado", "Eu teria jurado que conhecia todas as histórias da minha avó. Estava enganada.", "*Estar enganado* = estar equivocado (de *enganar* = engañar). *Se não me engano* = si no me equivoco."],
    ["desperdiçar", "desperdiciar", "Minha avó tinha o costume de quem aprendeu a não desperdiçar nada, nem papel.", "Con *ç*. Sustantivo: *o desperdício*. En el habla también *jogar fora*."],
    ["o enterro", "el entierro", "Ela só voltou à Paraíba quarenta anos depois, para o enterro de uma irmã.", "*Ir ao enterro*; el velorio es *o velório*. Verbo: *enterrar*."],
    ["a ferrovia", "el ferrocarril, la vía férrea", "Seu Aurélio tinha quinze anos quando foi trabalhar na ferrovia.", "La red o la vía; el tren es *o trem*. Adjetivo: *ferroviário* (*estação ferroviária*), que también es el empleado."],
    ["calar", "callar", "A memória de uma família é feita tanto do que se conta quanto do que se cala.", "Transitivo o pronominal: *calar um segredo*, *calar-se*. Refrán: *quem cala consente*. *Cala a boca!* es brusco."],
    ["o guarda-roupa", "el ropero", "Eu nunca tinha reparado naquela caixa, escondida no alto do guarda-roupa.", "Compuesto verbo + sustantivo, como *guarda-chuva* y *guarda-sol*. Plural: *os guarda-roupas*. *Reparar em* = fijarse en."],
    ["o sertão", "el sertón, el interior semiárido del Nordeste", "As cartas eram de um rapaz de uma cidadezinha do sertão da Paraíba.", "*Sertanejo* = el que vive en el sertón (y la música *sertaneja*, del interior del Sudeste). Clave para leer a Graciliano Ramos y Guimarães Rosa."],
    ["o roçado", "la chacrita, el sembrado", "Ele falava da seca, da mãe doente, de um roçado que não tinha dado nada naquele ano.", "Parcela sembrada para comer, típica del Nordeste. *Dar* = rendir: *o roçado não deu nada*."],
    ["costurar para fora", "coser por encargo", "A moça teria plantado feijão em vez de costurar para fora.", "*Para fora* = para afuera, como trabajo. Mismo molde: *lavar roupa para fora*. La costurera es *a costureira*."],
    ["ir parar", "ir a parar, terminar (en un lugar)", "O senhor pode contar como foi parar na ferrovia?", "*Ir parar em* = terminar en un lugar sin planearlo: *a carta foi parar no lixo*. Sin la *a* del español."],
    ["apitar", "tocar el silbato; pitar", "Quando o trem saiu, o maquinista apitou três vezes.", "De *apito* (silbato). El árbitro *apita o jogo*. Coloquial: *ele não apita nada aqui* = no pinta nada."],
    ["desistir", "echarse atrás, renunciar a algo", "Na véspera da viagem, conheceu minha bisavó num baile e desistiu.", "Más frecuente que en español: *desistir de* + infinitivo. *Não desista!* = ¡no te rindas! *Na véspera* = la víspera."],
],
31: [
    ["a redação", "la redacción (de un diario); también la composición escolar", "Na manhã em que visitamos a redação, a jornalista estava revisando os obituários.", "El lugar donde trabajan los periodistas y el texto escrito: *a redação do Enem*. Verbo: *redigir*."],
    ["o boato", "el rumor", "Um áudio anônimo tinha espalhado o boato de que a água estava contaminada.", "*Espalhar um boato*, *desmentir um boato*. Más de prensa que *fofoca*, que es chisme personal."],
    ["desmentir", "negar públicamente, decir que es falso", "Ela disse que o prefeito ia desmentir no rádio, mas que ninguém ia acreditar.", "Conjuga como *sentir*: *eu desminto*. Sustantivo: *o desmentido*. Verbo de decir típico de noticias."],
    ["fiscalizar", "controlar, supervisar", "O professor afirmou que, sem imprensa local, ninguém fiscaliza as contas da prefeitura.", "Más amplio que en castellano: *fiscalizar obras*, *fiscalizar o governo*. Sustantivo: *a fiscalização*; el inspector es *o fiscal*."],
    ["o esclarecimento", "la aclaración", "O jornal publicou uma nota de esclarecimento dizendo que o título foi alterado.", "De *esclarecer* = aclarar. *Nota de esclarecimento* = comunicado aclaratorio; *pedir esclarecimentos*."],
    ["o veículo", "el vehículo; el medio (de comunicación)", "O semanário é hoje o único veículo de imprensa de uma região de seis municípios.", "*Veículo de comunicação*, *de imprensa*: los medios. En plural, *os veículos* = los medios."],
    ["o obituário", "la necrológica", "Marlene estava revisando, de caneta vermelha, a página de obituários.", "La sección del diario con las muertes. *Caneta* = birome."],
    ["o contraponto", "la contracara, la otra versión", "Os boatos passam a circular sem nenhum contraponto nos grupos de mensagens.", "*Fazer um contraponto* = presentar la otra postura. En periodismo, *ouvir o outro lado*."],
    ["esvaziar", "vaciar", "As pessoas esvaziaram os supermercados em poucas horas.", "De *vazio*: *esvaziar*. Figurado: *o centro esvaziou* (se quedó sin gente). Lo contrario: *encher*."],
    ["o assinante", "el suscriptor", "Se conseguisse quinhentos assinantes, o projeto se pagaria.", "De *assinar* = firmar y suscribirse: *assinar uma revista*. *A assinatura* = la firma y la suscripción."],
    ["a estante", "la biblioteca (el mueble)", "Marlene nos mostrou a coleção do jornal, numa estante que ocupa uma parede inteira.", "El mueble con estantes es *a estante*; cada tabla, *a prateleira*. La institución es *a biblioteca*."],
    ["dar a entender", "insinuar, hacer pensar", "A frase foi tirada de contexto e o texto deu a entender que ele ia demitir metade da equipe.", "Igual que en español. Y *tirar de contexto* = sacar de contexto: verbos de la prensa y de los desmentidos."],
],
32: [
    ["o receio", "el temor, el recelo", "Entendo a intenção do projeto, mas confesso um receio: perde-se uma forma de ler a cidade.", "*Ter receio de* = temer. Verbo: *recear* (*eu receio*). Más formal y matizado que *medo*."],
    ["o guincho", "la grúa (de remolque)", "Na frente da farmácia, proíbe-se estacionar: o carro fica sujeito a guincho.", "En carteles: *sujeito a guincho* = se remolcará. Verbo: *guinchar* = remolcar (y también chillar)."],
    ["a mercearia", "el almacén (de barrio)", "Na parede da mercearia, pintaram a frase: Não se vende fiado.", "Falso amigo: no es «mercería» (esa es *o armarinho*). Negocio chico de comestibles, como el almacén de barrio."],
    ["estreito", "angosto, estrecho", "Não há nome nem telefone, só uma seta apontando para uma escada estreita.", "*Uma rua estreita*; contrario: *amplo*. Sustantivo: *o estreito* = el estrecho (geografía)."],
    ["o domicílio", "la casa, el lugar donde se vive", "Na porta, uma placa anuncia: Fazem-se unhas a domicílio.", "*A domicílio* = a domicilio, sin crase: *entrega a domicílio*. En formularios, *domicílio* = dirección legal."],
    ["colar", "pegar (con pegamento)", "Aprendi que se descobre mais sobre um bairro lendo os avisos colados nas portas.", "Falso amigo: *colar* es pegar (y, en la escuela, copiarse). *Cola* = pegamento; *o colar* = el collar."],
    ["o aviso", "el cartel, la advertencia", "Aprendi a ler os avisos colados nas portas do centro.", "*Aviso* = cartel o advertencia. *Aviso prévio* = preaviso (laboral)."],
    ["o chaveiro", "el cerrajero; el llavero", "No chaveiro da esquina, faz-se cópia de chave na hora.", "Doble sentido: el cerrajero y el llavero. *Fazer uma cópia da chave*."],
    ["o comprovante de residência", "el comprobante de domicilio", "O adesivo se retira na subprefeitura com comprovante de residência.", "El papel que te piden en todo trámite: una factura de luz o de agua a tu nombre. *Comprovante de pagamento* = comprobante de pago."],
    ["a eleição", "la elección", "A eleição para prefeito e vereador acontece a cada quatro anos.", "Plural *as eleições*; *eleitor* = votante. *Ir às urnas* = ir a votar; en Brasil la urna es electrónica y el voto, obligatorio de 18 a 70 años."],
    ["o segundo turno", "la segunda vuelta, el balotaje", "Se nenhum candidato tiver mais da metade dos votos, vai ter segundo turno.", "*Ganhar no primeiro turno*. Para prefeito, solo en las ciudades de más de 200 mil electores."],
    ["a Câmara Municipal", "el Concejo Deliberante", "O projeto que proíbe cartazes ainda precisa ser votado na Câmara Municipal.", "Donde se sientan los *vereadores*. En Brasilia, *a Câmara dos Deputados* y *o Senado* forman *o Congresso*."],
    ["o projeto de lei", "el proyecto de ley", "Os vereadores discutem um projeto de lei sobre as placas do centro histórico.", "*Aprovar*, *vetar*, *sancionar um projeto de lei*. Aprobado, *a lei entra em vigor*."],
    ["o STF", "la Corte Suprema (Supremo Tribunal Federal)", "A decisão final ficou com o STF.", "Se dice «esse-tê-efe». Sus miembros son *ministros*, no «jueces». *Recorrer ao STF* = llegar a la Corte."],
    ["o INSS", "la seguridad social (como la ANSES)", "O INSS paga a aposentadoria de quem contribuiu.", "*Instituto Nacional do Seguro Social*: jubilaciones (*aposentadoria*) y licencias. *Contribuir para o INSS* = hacer aportes."],
],
33: [
    ["o cartório", "la escribanía, el registro (civil, de la propiedad)", "Numa tarde de março, entrou no cartório um velho com uma caixa de madeira.", "Oficina donde se certifican firmas, documentos y actos: *reconhecer firma no cartório*. El escribano es *o tabelião*."],
    ["deparar-se com", "toparse con, encontrarse con", "Em vinte anos de ofício, o tabelião nunca se deparou com uma cláusula assim.", "Pronominal y con *com*: *deparar-se com um problema*. Escrito y formal; en el habla, *dar de cara com*."],
    ["pregar uma peça", "hacer una broma, jugar una mala pasada", "O engenheiro saiu convencido de que o velho lhe pregou uma peça.", "*Pregar uma peça em alguém* o *pregar-lhe uma peça*. *A peça* también es pieza (de un reloj, de teatro)."],
    ["as entrelinhas", "las entrelíneas", "Quem lê o testamento com atenção descobre muita coisa nas entrelinhas.", "Casi siempre en plural: *ler nas entrelinhas* = leer entre líneas, captar lo implícito."],
    ["com vagar", "despacio, sin apuro", "O velho abriu a caixa com vagar sobre a mesa do tabelião.", "Literario: *com vagar* = con calma. Adjetivo: *vagaroso* = lento. En el habla: *devagar*."],
    ["o tabelião", "el escribano", "Um velho relojoeiro procura o tabelião da cidade para fazer um testamento curioso.", "Trabaja en el *cartório* (la escribanía y el registro). Femenino: *a tabeliã*."],
    ["o cômodo", "el ambiente, la habitación", "Os seus bens resumiam-se a uma casa de dois cômodos.", "Falso amigo: como sustantivo, cada ambiente de la casa. Como adjetivo sí es «cómodo», aunque se dice más *confortável*."],
    ["o relojoeiro", "el relojero", "O velho chamava-se Joaquim Pereira e era o único relojoeiro da vila.", "Oficio en *-eiro*: *relojoeiro*, *sapateiro*, *padeiro*."],
    ["a cláusula", "el artículo (de un contrato o de un testamento)", "A cláusula era clara, e o prazo ainda não tinha se esgotado.", "Lenguaje jurídico: *cláusula do contrato*. *Esgotar-se o prazo* = vencerse."],
    ["o herdeiro", "el heredero", "Os juízes costumavam desconfiar de herdeiros incertos.", "*Herdar* = heredar; *a herança* = la herencia. La sucesión se tramita en el *inventário*."],
    ["a lavadeira", "la lavandera", "Foi a filha da lavadeira quem pediu para tentar montar o relógio.", "De *lavar*: el oficio de las mujeres pobres del Brasil de 1900. Hoy, *lavanderia* = lavadero."],
    ["o ferreiro", "el herrero", "Apareceram candidatos de toda parte: ferreiros, estudantes, um padre.", "De *ferro*. Refrán: *em casa de ferreiro, espeto de pau* (en casa de herrero, cuchillo de palo)."],
],
34: [
    ["a enchente", "la inundación, la crecida", "A enchente não é um acidente: é consequência do modo como construímos.", "De *encher* (llenar). Sinónimos: *inundação*; *alagamento* es más puntual (una calle anegada)."],
    ["boiar", "flotar", "Toda vez que a cidade fica debaixo d'água, circulam imagens de carros boiando.", "*A boia* = la boya. Coloquial: *ficar boiando* = no entender nada, quedarse afuera de la conversación."],
    ["todavia", "sin embargo, no obstante (falso amigo)", "Reconheço o peso desses argumentos. Todavia, eles partem de uma falsa oposição.", "Falso amigo: conector adversativo formal, como *contudo* y *no entanto*. «Todavía» se dice *ainda*."],
    ["ao passo que", "mientras que (contraste)", "Um parque inundável serve de praça, ao passo que um piscinão passa o ano vazio.", "Conector de contraste, formal, sinónimo de *enquanto*. No indica tiempo ni ritmo."],
    ["sobrecarregado", "sobrecargado, saturado", "Com calçadas permeáveis, o sistema de drenagem deixa de ficar sobrecarregado.", "De *sobrecarregar*. Con personas: *estou sobrecarregado de trabalho* = tapado de trabajo."],
    ["alagar", "inundar(se), anegarse", "Parques que alagam de propósito ajudam a cidade a absorver a chuva.", "Para calles y barrios: *a rua alagou*. *O alagamento* = el anegamiento; *a enchente*, la crecida grande."],
    ["o cano", "el tubo, la cañería", "A proposta é reter a água, em vez de expulsá-la por meio de canos.", "Caño de agua o de gas: *o cano estourou*. Coloquial: *entrar pelo cano* = salir mal parado."],
    ["o piscinão", "el gran reservorio pluvial", "Um piscinão de concreto passa a maior parte do ano vazio.", "Aumentativo de *piscina*: los reservorios contra inundaciones de São Paulo."],
    ["a embalagem", "el envase, el packaging", "A maior parte do plástico no mar vem de embalagens e de redes de pesca.", "*Embalar* = envasar. Molde: *embalagem descartável*, *embalagem retornável*."],
    ["o reflorestamento", "la reforestación", "O reflorestamento da Tijuca, no século XIX, recuperou a mata destruída pelo café.", "La Floresta da Tijuca se replantó desde 1861. *Reflorestar* = reforestar."],
    ["a reciclagem", "el reciclaje", "A reciclagem começa em casa, com a separação do lixo.", "*Reciclar*; *material reciclável*. *Catador* = cartonero."],
    ["a mata atlântica", "la selva atlántica", "Hoje resta pouco mais de dez por cento da mata atlântica original.", "El bosque de la costa, del Nordeste al Sur; la Floresta da Tijuca, en Río, es *mata atlântica*. *Mata* = monte, bosque."],
    ["o manguezal", "el manglar", "O manguezal protege a costa e serve de berçário para os peixes.", "También *mangue*; muy presente en Recife (el *manguebeat* de Chico Science)."],
    ["o efeito estufa", "el efecto invernadero", "Os gases do efeito estufa aumentam a temperatura do planeta.", "*Estufa* = invernadero (y estufa). *Emissões de carbono*."],
    ["o garimpo", "la minería ilegal (de oro)", "O garimpo ilegal contamina os rios da Amazônia com mercúrio.", "*Garimpeiro* = buscador de oro. Problema central en las tierras indígenas."],
],
35: [
    ["recorrer a", "recurrir a", "Rodrigo recorreu a um despachante depois de perder três manhãs na fila.", "Régimen con *a*: *recorrer a alguém*. En derecho, *recorrer de uma decisão* = apelarla; *o recurso*."],
    ["visar", "apuntar a, tener como objetivo", "Nosso trabalho visa à segurança do cidadão, não a burlar regras.", "En la norma, con *a*: *visa ao lucro*, *visa à segurança*; en el habla, sin preposición. *Visar um documento* = visarlo."],
    ["burlar", "eludir, violar (una norma) (no «burlarse»)", "Um despachante sério não ajuda ninguém a burlar a lei.", "Falso amigo: *burlar a fiscalização* = eludirla. Burlarse de alguien es *zombar de* o *tirar sarro de*."],
    ["o expediente", "el horario laboral, la jornada", "A gente nem trabalha no mesmo andar: eu mal vejo ele durante o expediente.", "*Durante o expediente*, *fim de expediente*. También «recurso, artimaña». El expediente administrativo es *o processo*."],
    ["constranger", "incomodar, avergonzar; presionar", "Ninguém pode usar o cargo para constranger o outro na frente dos colegas.", "*Ficar constrangido* = sentir vergüenza o incomodidad; *uma situação constrangedora*. Sustantivo: *o constrangimento*."],
    ["de cor", "de memoria", "Ela assiste diariamente a um espetáculo que conhece de cor.", "*Saber de cor* (del latín *cor*, corazón). No confundir con *a cor* (el color)."],
    ["o despachante", "el gestor (de trámites)", "Rodrigo contratou um despachante depois de perder três manhãs no cartório.", "El que hace trámites por otros: *despachante de trânsito*."],
    ["o atalho", "el atajo", "Tem muita gente que associa despachante a jeitinho, a atalho.", "*Pegar um atalho* = cortar camino. En la compu, *atalho de teclado*."],
    ["a repartição", "la oficina pública", "O intermediário informal circula na porta das repartições.", "*Repartição pública*; el que trabaja ahí es *o funcionário público*."],
    ["preencher", "llenar, completar (un formulario)", "Eu passo mais tempo respondendo a dúvidas do que preenchendo formulários.", "*Preencher um formulário*, *uma vaga* (cubrir un puesto), *os requisitos* (reunir). Con doble *e*."],
    ["o carimbo", "el sello", "Enquanto existir papel, carimbo e gente com pressa, alguém vai precisar de mim.", "El sello de goma; *carimbar* = sellar: *carimbar o passaporte*."],
    ["o assédio", "el acoso", "Se isso acontecer, pode configurar assédio, e a empresa tem o dever de agir.", "*Assédio moral* (en el trabajo) y *assédio sexual*. *Configurar* = constituir, en el lenguaje jurídico."],
],
36: [
    ["à medida que", "conforme, a la par que (progresivamente)", "A língua se corrige aos poucos, à medida que é lida.", "Con crase: indica proporción. No confundir con *na medida em que* = en tanto que, dado que."],
    ["à luz de", "a la luz de", "O pedido será analisado à luz da legislação vigente.", "Formal: *à luz dos fatos*, *à luz da lei*. Lleva crase porque *luz* es femenino."],
    ["convir", "convenir", "Convém lembrar que a crase não é um acento qualquer.", "Casi siempre *convém* + infinitivo = conviene. Conjuga como *vir*: *convém*, *convinha*, *conveio*."],
    ["o zelo", "el celo, el esmero", "Quem põe crase onde não deve erra por excesso de zelo, não por descaso.", "Cuidado y dedicación: *com zelo*; adjetivo *zeloso*. Los celos amorosos son *o ciúme*."],
    ["o térreo", "la planta baja", "O balcão de atendimento fica no térreo da prefeitura, à esquerda de quem entra.", "*O térreo* o *o andar térreo*; el primer piso es *o primeiro andar*. En ascensores, *T*."],
    ["a senha", "el número (de turno); la contraseña", "Retire sua senha junto à recepção.", "Dos sentidos frecuentes: el número de la fila y la contraseña (*senha do banco*)."],
    ["dispensar", "prescindir de; eximir; echar", "Quando a expressão começa sem artigo, o par também dispensa o artigo.", "Falso amigo: no es disculpar. *Dispensa apresentação* = no necesita presentación; *foi dispensado* = lo eximieron (o lo echaron)."],
    ["a armadilha", "la trampa", "Há ainda as armadilhas: «devido à chuva» leva crase.", "*Cair numa armadilha*. Hacer trampa en el juego es *trapacear*."],
    ["o deslize", "el desliz, el descuido", "Esses deslizes mostram que o falante percebe que ali há um «a» importante.", "Error menor: *cometer um deslize*. De *deslizar* (resbalar)."],
    ["contornar", "esquivar, sortear; rodear", "Muitos redatores preferem contornar o problema com fórmulas neutras.", "*Contornar a situação* = sortearla. Literal: rodear (*contornar a praça*)."],
    ["mexer com", "afectar, conmover; meterse con", "É uma notícia que mexeu com muita gente.", "*Mexer* = mover, revolver; *não mexe nisso!* = ¡no toques eso!"],
    ["o aposentado", "el jubilado", "Um senhor aposentado reclamou do fechamento às segundas.", "*Aposentar-se* = jubilarse; *a aposentadoria* la paga el *INSS*. *Aposento* es habitación, en registro literario."],
],
37: [
    ["a encosta", "la ladera", "Toda vez que o céu escurece sobre as encostas, os moradores ficam em alerta.", "Ladera de un cerro: *contenção de encostas*. No confundir con *a ladeira*, que es la calle en pendiente."],
    ["íngreme", "empinado, escarpado", "Nos morros, as construções se equilibram em terrenos íngremes.", "Igual en masculino y femenino: *uma rua íngreme*, *uma subida íngreme*. Sinónimo: *inclinado*."],
    ["a antecedência", "la anticipación", "O sistema emitiu alertas com cerca de quarenta minutos de antecedência.", "*Com antecedência* = con anticipación; *com dois dias de antecedência*. Muy usado en avisos y reservas."],
    ["ponderar", "señalar con cautela, matizar", "Não estamos falando de prever catástrofes, pondera a geóloga.", "Como verbo de decir = observar, objetar con prudencia (no «elogiar»). También sopesar: *ponderar os prós e os contras*."],
    ["compensar", "convenir, valer la pena", "Tem modelo de celular que eu nem pego mais, porque não compensa.", "*Não compensa* = no conviene, no rinde. *Compensa mais consertar do que comprar outro*."],
    ["o reassentamento", "la reubicación (de familias)", "Se necessário, a prefeitura deve fazer o reassentamento das famílias.", "Traslado de familias en zonas de riesgo, *desde que negociado* con los vecinos."],
    ["a rachadura", "la grieta", "Os moradores indicaram quais muros já tinham rachaduras.", "De *rachar* = agrietar. En el habla, *rachar a conta* = dividir la cuenta."],
    ["abrigar-se", "refugiarse, ponerse a resguardo", "Quarenta minutos bastam para que uma família deixe a casa e se abrigue num ponto seguro.", "*Abrigo* = refugio (el abrigo de ropa es *casaco*). *Abrigar* también es albergar: *o prédio abriga um museu*."],
    ["minar", "socavar, debilitar", "Alertas falsos podem minar a credibilidade do sistema.", "Figurado, como en español: *minar a confiança*. *A mina* es la mina y, en el habla de São Paulo, la chica."],
    ["a assistência técnica", "el servicio técnico", "O Diego tem uma assistência técnica de celulares em Campinas.", "*Levar na assistência* = llevar al service. *Garantia* = garantía."],
    ["o parafuso", "el tornillo", "É parafuso com formato esquisito que só a ferramenta deles abre.", "Coloquial: *ter um parafuso a menos* = faltarle un tornillo."],
    ["malfeito", "mal hecho", "O cliente acha que eu fiz um serviço malfeito.", "Adjetivo en una palabra: *um serviço malfeito*; lo contrario, *benfeito*."],
],
38: [
    ["a legenda", "el subtítulo (no «la leyenda»)", "Eu sempre vejo a série com legenda porque o som do meu notebook é horrível.", "Falso amigo: subtítulo y epígrafe de foto; *filme legendado*. La leyenda es *a lenda*."],
    ["a dublagem", "el doblaje", "Durante décadas, as legendas e a dublagem corrigiam a fala dos personagens.", "Verbo *dublar*: *filme dublado* vs. *legendado*. *O dublador* = actor de doblaje."],
    ["estranhar", "extrañar lo raro, sorprenderse (no «echar de menos»)", "A gente percebeu que o público estranhava a legenda diferente do ator.", "Falso amigo: *estranhar* = encontrar raro. Echar de menos es *sentir falta* o *ter saudade*."],
    ["rebater", "rebatir, refutar", "Outros rebatem que o problema está justamente no oposto.", "Verbo de opinión muy de prensa: *rebater um argumento*, *rebater as críticas*."],
    ["o plantão", "la guardia (turno)", "Vou chegar tarde na festa, porque tenho plantão no hospital até as oito.", "*Estar de plantão*, *farmácia de plantão*; *o plantonista* = el de guardia. En prensa, *plantão de notícias* = último momento."],
    ["o descompasso", "el desfase, el desajuste", "O personagem diz «cadê a chave?», e a legenda escreve outra coisa: um pequeno descompasso.", "De *compasso* (ritmo). *Estar em descompasso com* = no ir al mismo ritmo."],
    ["o surdo", "el sordo", "Quem é surdo depende da legenda para acompanhar a história.", "*Surdez* = sordera; *Libras* = la lengua de señas brasileña."],
    ["a periferia", "los barrios populares de las afueras", "Numa série sobre adolescentes da periferia, a fala crua faz parte da história.", "En Brasil, *periferia* no es solo geografía: es la ciudad pobre, lejos del centro."],
    ["inédito", "sin precedentes; no publicado", "As plataformas digitais aproximaram a escrita da fala de um modo inédito.", "*Um texto inédito* (no publicado); *um fato inédito* (sin precedentes). Muy de prensa."],
    ["ainda bem", "menos mal", "Ainda bem, porque ontem eu quase vi um spoiler.", "*Ainda bem que* + indicativo = menos mal que: *ainda bem que você veio*."],
    ["sem noção", "desubicado", "O pessoal não tem noção: manda print do final sem avisar nada.", "*Não ter noção* = ser un desubicado; *que cara sem noção!* *O print* = la captura de pantalla."],
    ["engrenar", "agarrar ritmo, arrancar", "Lá pelo terceiro episódio a coisa engrenou.", "De *engrenagem*: *engrenar a marcha* = poner el cambio. Figurado: *o projeto engrenou*."],
],
40: [
    ["a evasão", "la deserción (escolar)", "O estudo identifica os fatores associados à evasão no primeiro ano de graduação.", "*Evasão escolar* = abandono de los estudios; también *evasão fiscal*. Verbo: *evadir-se*."],
    ["trancar", "cerrar con llave; congelar (la matrícula)", "Dos entrevistados, vinte e sete tinham trancado ou abandonado o curso.", "*Trancar a porta*; en la universidad, *trancar a matrícula* = suspenderla temporalmente. *A tranca* = la traba."],
    ["decorrer de", "derivar de, resultar de", "A evasão no primeiro ano não decorre de um único fator.", "Formal: *decorrer de* = resultar de. *No decorrer do ano* = en el transcurso del año; *decorrente de* = derivado de."],
    ["o acolhimento", "el recibimiento, la contención", "Recomenda-se um programa de acolhimento nas primeiras semanas de aula.", "De *acolher* = recibir, amparar. Frecuente en educación, salud y asistencia social."],
    ["tampouco", "tampoco", "Tampouco se pode desconsiderar a dimensão afetiva da permanência.", "Formal y escrito; en el habla se dice *também não*. Suele ir al inicio: *tampouco* + verbo."],
    ["a abordagem", "el enfoque", "A escolha de uma abordagem mista justifica-se pela insuficiência dos dados quantitativos.", "Palabra clave del registro académico: *abordagem qualitativa*, *nova abordagem*. Verbo: *abordar*."],
    ["o ingressante", "el ingresante", "A pesquisa analisou os registros de cerca de 4.800 ingressantes.", "De *ingressar* = ingresar. En el habla, el de primer año es *o calouro*."],
    ["a reprovação", "el aplazo, la desaprobación", "Verificou-se uma forte relação entre a reprovação em disciplinas introdutórias e o abandono.", "*Ser reprovado* = desaprobar; *ser aprovado* = aprobar. *Disciplina* = materia."],
    ["a monitoria", "la ayudantía, la tutoría de pares", "Poucos estudantes recorreram à monitoria.", "Ayudantía a cargo de alumnos avanzados; el ayudante es *o monitor*."],
    ["o desempenho", "el rendimiento, el desempeño", "A percepção de pertencimento mostrou-se tão relevante quanto o desempenho acadêmico.", "*Desempenho escolar*, *profissional*; *desempenhar um papel* = desempeñar un papel."],
    ["o rascunho", "el borrador", "Normal, todo mundo faz isso no primeiro rascunho.", "*Fazer um rascunho*. La goma de borrar es *a borracha* (¡falso amigo!)."],
    ["a banca", "el jurado (de tesis, de examen)", "Prefiro receber uma versão revisada daqui a duas semanas, para a banca ler com calma.", "*Banca examinadora*. Ojo: *banca* es también el puesto de diarios (*banca de jornal*)."],
],
41: [
    ["dar-se ao trabalho de", "tomarse el trabajo de", "O relógio simplesmente parara, e ninguém se dera ao trabalho de consertá-lo.", "Frecuente en negativa: *nem se deu ao trabalho de responder* = ni se molestó en responder."],
    ["voltar atrás", "echarse atrás, retractarse", "A cada carta, ele achava que não tinha o direito de voltar atrás.", "*Voltar atrás numa decisão*, *não volto atrás*. Con sentido de desdecirse, no de regresar."],
    ["o maço", "el atado, el paquete", "Numa gaveta, presa por um elástico, Helena encontrou um maço de envelopes.", "*Maço de cigarros*, *maço de cartas*, *maço de coentro*. Con *ç*; no confundir con *massa*."],
    ["empoeirado", "polvoriento", "Ela subiu a escada da torre e abriu a tampa empoeirada do relógio.", "De *a poeira* = el polvo (ojo: *o polvo* es el pulpo). *Tirar a poeira* = quitar el polvo."],
    ["cumprir a palavra", "cumplir su palabra", "Concluíra, com a lógica cruel dos jovens, que ele cumprira a palavra.", "Contrario: *faltar com a palavra*. *Dar a palavra* = prometer; *palavra de honra*."],
    ["macio", "suave (al tacto), blando", "Lidas tantas vezes, as cartas tinham o papel macio como tecido.", "Para texturas: *pele macia*, *carne macia*. Macizo se dice *maciço*."],
    ["a tampa", "la tapa", "Ela abriu a tampa empoeirada e ficou olhando o mecanismo.", "*Tampa da panela*; *tampar* = tapar. *Empoeirado* = polvoriento (de *poeira*)."],
    ["a engrenagem", "el engranaje", "O pai passara a vida inclinado sobre engrenagens minúsculas.", "También figurado: *a engrenagem do Estado*. *Passara*: mais-que-perfeito simple."],
    ["a camada", "la capa", "O mais-que-perfeito é um tempo que organiza camadas de memória.", "*Camada de tinta*, *camada de ozônio*; *camadas sociais*."],
    ["empilhar", "apilar", "Ao empilhar lembranças, o narrador transforma suspeita em fato consumado.", "De *pilha* (pila), que es también la pila eléctrica."],
    ["coitado", "pobre (que da lástima)", "E a Macabéa, coitada, não tem voz nem para se defender.", "*Coitado!* = ¡pobre! Con nombre: *coitada da Macabéa*."],
    ["a datilógrafa", "la dactilógrafa", "Macabéa é uma moça alagoana, datilógrafa, que vive no Rio.", "Oficio de antes de la computadora; *datilografar* = escribir a máquina."],
],
42: [
    ["por via das dúvidas", "por las dudas", "Por via das dúvidas, a dona das flores afixou um cartaz na barraca.", "Equivale al rioplatense «por las dudas». Registro neutro; también *na dúvida*."],
    ["o tombamento", "la declaración de patrimonio histórico", "Tendo conseguido o tombamento do prédio, os moradores salvaram o cinema.", "De *tombar* = declarar bien protegido (y también caer). *Um prédio tombado* no puede demolerse."],
    ["a vaquinha", "la colecta, la vaquita", "A reforma foi paga em parte com uma vaquinha on-line de três mil pessoas.", "*Fazer uma vaquinha* = juntar plata entre varios, como «hacer una vaca». *Vaquinha virtual* = financiamiento colectivo."],
    ["espremido", "apretujado, exprimido", "A notícia saiu espremida entre um acidente na marginal e a previsão de chuva.", "De *espremer* = exprimir (*espremer uma laranja*) y apretar. *Espremido no ônibus* = apretado."],
    ["lacrado", "sellado, clausurado", "Ela chorou quando viu as portas do cinema lacradas.", "De *lacrar* = sellar, clausurar: *embalagem lacrada*. En redes, *lacrar* = dejar a alguien sin respuesta."],
    ["o recapeamento", "la repavimentación", "A transferência seria provisória, enquanto durassem as obras de recapeamento da avenida.", "*Recapear o asfalto*. *As obras* = las obras públicas."],
    ["o feirante", "el puestero de la feria", "O grito do feirante anunciava a primeira fornada de pastel.", "*Feira livre* = la feria callejera; *freguês* = el cliente habitual; *fornada* = hornada."],
    ["o coentro", "el cilantro", "O feirante arrumava os maços de coentro com delicadeza.", "Imprescindible en la cocina del Nordeste. *Salsinha* = perejil; *cheiro-verde* = perejil y cebolla de verdeo."],
    ["atrapalhar", "estorbar, complicar", "Há quem diga que a feira suja a rua e atrapalha o trânsito.", "Muy frecuente: *não quero atrapalhar* (no quiero molestar); *atrapalhado* = enredado."],
    ["o tempero", "el condimento, la sazón", "Na feira, a moça recém-chegada da Bahia encontra o tempero da sua terra.", "*Temperar* = condimentar (no «templar»). *Comida sem tempero* = sosa."],
    ["não adianta", "no sirve de nada", "Não adianta reabrir e ficar vazio.", "*Adiantar* = adelantar y servir: *não adianta chorar*."],
    ["a bilheteria", "la boletería", "Dona Iolanda trabalhou na bilheteria por quase vinte anos.", "De *bilhete* = entrada. *Sucesso de bilheteria* = éxito de taquilla."],
],
43: [
    ["a posse", "la asunción (de un cargo); la posesión", "Fui aprovada num concurso, e a posse é daqui a três semanas.", "*Tomar posse* = asumir un cargo; *posse do presidente*. También posesión: *ter a posse de um imóvel*."],
    ["o rodeio", "el rodeo, la vuelta (al hablar)", "Ele gosta de mensagem objetiva: diga logo no começo o que precisa, sem rodeio.", "*Sem rodeios* = sin vueltas; *fazer rodeios*. También el rodeo de ganado."],
    ["o desabafo", "el desahogo", "Adjetivos excessivos e desabafos emocionais tendem a enfraquecer o pedido.", "Verbo *desabafar* = desahogarse: *precisava desabafar com alguém*."],
    ["o fecho", "el cierre (de una carta)", "Atenciosamente se tornou o fecho padrão de quase todas as situações formais.", "Cierre de un texto; de *fechar*. *Fecho ecler* = cierre relámpago."],
    ["o anexo", "el adjunto (de un correo)", "Anexe ao e-mail o comprovante de aprovação no concurso, com a data da posse.", "*Em anexo* = adjunto: *segue em anexo o relatório*. Verbo: *anexar*."],
    ["o órgão público", "el organismo público", "Profissionais experientes hesitam antes de responder a um órgão público.", "*Órgão* = órgano y organismo. Con tilde: *ór-gão*."],
    ["hesitar", "dudar, vacilar", "Profissionais experientes hesitam antes de responder a um órgão público.", "Más formal que *vacilar*, que en el habla es «mandarse una macana»."],
    ["o suporte", "el soporte, el medio", "Há, por fim, a questão do suporte: carta ou e-mail.", "El medio en que se escribe: *suporte digital*. *Suporte técnico* = soporte."],
    ["enfraquecer", "debilitar", "Desabafos emocionais tendem a enfraquecer o pedido.", "De *fraco* (débil); lo contrario, *fortalecer*."],
    ["conferir", "chequear, verificar", "Vale conferir se o destinatário é, de fato, a pessoa responsável pelo assunto.", "Sobre todo, verificar (*confere!* = ¡correcto!). *Conferir um título* = otorgarlo."],
    ["a homologação", "la aprobación oficial", "O seu processo está parado na etapa de homologação.", "*Homologar* = aprobar oficialmente un trámite o un título."],
    ["a ata", "el acta", "Falta a ata de defesa assinada por todos os membros da banca.", "*Ata de reunião*; *lavrar a ata*. Sin *c*: *ata*."],
],
44: [
    ["o deboche", "la burla, la sorna", "Alguns aumentativos carregam desprezo ou deboche, como espertalhão.", "*Em tom de deboche*. Verbo: *debochar de* = burlarse de. Adjetivo: *debochado*."],
    ["torcer o nariz", "fruncir la nariz, mostrar desagrado", "Os gramáticos mais conservadores torcem o nariz para esses exageros.", "*Torcer o nariz para algo*. Ojo: *torcer* solo = alentar a un equipo."],
    ["o jeitinho", "la maña, el atajo (a veces trampa)", "O famoso jeitinho resumiria uma maneira de contornar obstáculos com flexibilidade.", "Diminutivo de *jeito*: flexibilidad creativa o pequeña trampa, según quién lo diga. *Dar um jeitinho*."],
    ["o recado", "el mensaje, el aviso (que se deja)", "Ninguém conjuga eu sexto, mas todo mundo entende o recado.", "*Deixar um recado* = dejar un mensaje; *dar o recado*; *recado dado* = mensaje recibido."],
    ["o espertalhão", "el vivo, el pícaro", "Um espertalhão é alguém esperto demais, que quer levar vantagem.", "Aumentativo despectivo de *esperto* (vivo, listo). Femenino: *espertalhona*."],
    ["o atendente", "el empleado que atiende", "O cliente não está pedindo que o atendente saia correndo: está sendo gentil.", "En un mostrador o un call center; femenino *a atendente*. *Atendimento* = la atención al cliente."],
    ["o encurtamento", "el acortamiento", "O encurtamento corta a palavra pela metade: aniversário vira niver.", "*Refri*, *niver*, *facul*: palabras cortadas, muy de los jóvenes."],
    ["o carinho", "el cariño", "Paulão pode ser simplesmente o Paulo querido, dito com carinho.", "*Com carinho* = con cariño; *carinhoso* = cariñoso. *Fazer carinho* = acariciar."],
    ["o concurseiro", "el que estudia para concursos públicos", "O sufixo -eiro hoje produz concurseiro, quem passa anos estudando para concursos.", "Los empleos públicos se ganan por *concurso*: *passar no concurso*. *-eiro* forma oficios y aficiones."],
    ["sextou", "¡llegó el viernes!", "Um dos exemplos mais saborosos é sextou, forma verbal inventada a partir de «sexta-feira».", "Verbo inventado, en perfeito: *sextou!* Informal, de redes y de oficina. También *sabadou*."],
    ["encurtar", "acortar", "A primeira é encurtar: Fernanda vira Nanda, Gabriela vira Gabi.", "De *curto* (corto): *encurtar o caminho*. *Virar* = convertirse."],
    ["a leveza", "la liviandad, la buena onda", "O conselho é: se incomodar, diga com leveza.", "De *leve* (liviano). *Com leveza* = sin dramatizar."],
],
45: [
    ["embaraçado", "avergonzado, incómodo (no «embarazada»)", "Perguntar a uma colega se ela está embaraçada pode deixá-la constrangida.", "Falso amigo clásico: embarazada es *grávida*. *Embaraçar* = avergonzar, y también enredar."],
    ["a escrivaninha", "el escritorio (el mueble)", "O escritório não é o móvel onde escrevo: esse é a escrivaninha.", "El mueble; *o escritório* es la oficina. Femenino: *a escrivaninha*."],
    ["folgado", "holgado, suelto; (coloquial) aprovechado", "Uma camiseta folgada não aperta o corpo.", "*Roupa folgada*. De una persona, *folgado* = fresco, caradura. *A folga* = el franco del trabajo."],
    ["a pegadinha", "la trampa, la pregunta capciosa; la cámara oculta", "O caminho inverso, do português para o espanhol, também tem as suas pegadinhas.", "*Cair numa pegadinha* = caer en la trampa. En la tele, *programa de pegadinhas* = de cámara oculta."],
    ["o crachá", "la credencial, la tarjeta identificatoria", "Quando me pediram o apelido para o crachá, respondi com o sobrenome.", "La tarjeta con nombre y foto que se cuelga en el trabajo o en un evento. Masculino, con tilde: *o crachá*."],
    ["caprichar", "esmerarse", "Resolvi caprichar no português: «Que comida exquisita!».", "*Caprichar em algo* = esmerarse; *caprichado* = bien hecho. Nada que ver con el antojo."],
    ["o anfitrião", "el anfitrión", "A anfitriã sorriu com educação e perguntou se eu preferia outra coisa.", "Femenino *anfitriã*; plural *anfitriões*. El invitado es *o convidado*."],
    ["o tropeço", "el tropiezo", "Vale a pena rir dos próprios tropeços.", "*Tropeçar* = tropezar. Figurado: error menor."],
    ["embriagado", "ebrio", "Pedi uma borracha e fiquei esperando que o vendedor não pensasse que eu estava embriagada.", "*Embriagado* = borracho (formal); en el habla, *bêbado*. Y *borracha* = goma de borrar."],
    ["o parquinho", "la plaza de juegos", "Brincar é o que as crianças fazem no parquinho.", "Diminutivo de *parque*: la plaza con juegos. *Brincar* = jugar (los chicos)."],
    ["o molho", "la salsa", "O que você chama de salsa, aqui é molho.", "Falso amigo: *salsa* en Brasil es el perejil (*salsinha*). *Ficar de molho* = quedarse quieto, en remojo."],
    ["o azeite", "el aceite de oliva", "O que vai na salada é o óleo, ou o azeite, se for de oliva.", "*Azeite* = aceite de oliva; *óleo* = aceite de cocina o de motor."],
],
46: [
    ["o sotaque", "el acento (regional)", "Muitos brasileiros entendem o sotaque angolano melhor que o de Lisboa.", "Tonada de una región: *sotaque carioca*, *sotaque gaúcho*. El acento gráfico es *o acento*."],
    ["a parcela", "la parte, la porción; también la cuota", "Em Angola, o português é a língua materna de uma parcela crescente da população.", "*Uma parcela da população* = una parte. En compras, *em dez parcelas* = en diez cuotas."],
    ["o preconceito", "el prejuicio (no «preconcepto»)", "Você já sentiu algum tipo de preconceito por causa da sua forma de falar?", "*Preconceito contra*; adjetivo *preconceituoso*. Ojo: *prejuízo* = pérdida, daño."],
    ["de mão única", "de una mano, unidireccional", "A influência entre o português e as línguas africanas nunca foi de mão única.", "Literal: *rua de mão única* = de una mano. Contrario: *mão dupla*. Figurado: relación en un solo sentido."],
    ["saltar aos olhos", "saltar a la vista", "Na pronúncia, a diferença entre Lisboa e São Paulo salta aos olhos.", "Ser evidente. El texto juega con *salta aos ouvidos* porque se trata de pronunciación."],
    ["o frigorífico", "la heladera (en Portugal)", "O banheiro, em Portugal, é a casa de banho, e a geladeira é o frigorífico.", "En Brasil, *geladeira*; allá, *frigorífico* es el matadero industrial. Otros pares: *ônibus / autocarro*, *trem / comboio*."],
    ["a rapariga", "la chica (en Portugal y Angola); ofensivo en partes de Brasil", "Um português pode chamar de rapariga a jovem que um brasileiro chamaria de moça.", "Palabra trampa: neutra en Portugal, insulto en el Nordeste. En Brasil, *moça* o *menina*."],
    ["o quimbundo", "el kimbundu (lengua de Angola)", "Os meus avós falavam quimbundo, os meus pais ainda entendem.", "Lengua bantú de Luanda que dio muchas palabras al portugués de Brasil: *caçula*, *moleque*, *quitanda*."],
    ["a quitanda", "la verdulería del barrio", "Palavras do cotidiano brasileiro, como caçula, cafuné e quitanda, têm origem africana.", "Almacén chico de frutas y verduras. *Caçula* = el hijo menor; *cafuné* = caricia en la cabeza."],
    ["a turma", "el grupo, la clase, los compañeros", "Metade da turma diz bué também, de brincadeira.", "División de un curso y grupo de amigos: *a minha turma*. *Galera* es más informal."],
    ["o candongueiro", "la combi colectiva (en Luanda)", "Em Luanda, a gente anda de candongueiro, aquelas vans azuis e brancas.", "El transporte popular de Luanda; en Brasil, *van* o *lotação*; en Mozambique, *chapa*."],
    ["engolir", "tragar", "O português europeu tende a engolir as vogais átonas.", "*Engolir* comida y palabras; *engolir sapo* = tragarse un sapo. *Eu engulo*."],
],
47: [
    ["descambar", "degenerar, derivar (en algo peor)", "O debate sobre a tarifa zero rapidamente descambou para a caricatura.", "*Descambar para* o *em*: siempre hacia algo negativo. *A discussão descambou em briga*."],
    ["o reajuste", "el aumento, la actualización (de precios o sueldos)", "A cada reajuste da passagem, parte dos usuários desiste do ônibus.", "*Reajuste salarial*, *reajuste da tarifa*. Verbo: *reajustar*."],
    ["sucateado", "deteriorado, desmantelado (por abandono)", "Um sistema gratuito, porém lotado e sucateado, dificilmente convenceria alguém.", "De *a sucata* = chatarra. *Sucatear* un servicio público = dejarlo deteriorar por falta de inversión."],
    ["a fatia", "la tajada, la porción", "Os moradores das periferias gastam uma fatia desproporcional da renda com transporte.", "*Fatia de pão* = rebanada; figurado: *fatia do mercado*, *fatia do orçamento*."],
    ["o afastamento", "la licencia (médica); el alejamiento", "O esgotamento dos funcionários custa caro, com afastamentos por estresse.", "*Afastamento por doença* = licencia por enfermedad. Verbo *afastar(-se)* = alejar(se), apartar(se)."],
    ["a gratuidade", "la gratuidad", "Há os que veem na gratuidade dos ônibus a solução para todos os males urbanos.", "*Gratuito* = gratis. *Tarifa zero* = transporte sin boleto."],
    ["o esgotamento", "el agotamiento; el burnout", "O modelo atual dá sinais evidentes de esgotamento.", "De *esgotar* = agotar: *ingressos esgotados*. *Esgotamento profissional* = burnout."],
    ["a renda", "el ingreso (de una persona o familia)", "Os moradores das periferias gastam uma fatia desproporcional da renda com transporte.", "Falso amigo: no es la renta de un alquiler (*aluguel*). *Imposto de renda* = impuesto a las ganancias; *baixa renda*."],
    ["a frota", "la flota", "Alguém terá de pagar o combustível, os salários e a renovação da frota.", "*Frota de ônibus*, *de táxis*. Frotar se dice *esfregar*."],
    ["engavetar", "cajonear", "O pior cenário seria a Câmara engavetar o assunto mais uma vez.", "De *gaveta* (cajón): *engavetar um projeto*. Lo contrario: *desengavetar*."],
    ["o adoecimento", "el enfermarse (por el trabajo)", "Tem um custo que as empresas raramente colocam na conta: o do adoecimento.", "De *adoecer* = enfermarse. *Afastamento por doença* = licencia por enfermedad."],
    ["o patrão", "el patrón, el jefe", "Isso custa caro, e custa para todo mundo, inclusive para o patrão.", "Coloquial para el empleador (formal: *o empregador*). Femenino: *a patroa*."],
],
48: [
    ["sustentar", "sostener (una idea); mantener", "Há também quem sustente que o foco deveria estar no uso de celulares à noite.", "Verbo de opinión: *sustentar que*. También mantener económicamente: *sustentar a família*."],
    ["queixar-se", "quejarse", "Muitos professores se queixam de turmas apáticas logo cedo.", "*Queixar-se de*, más formal que *reclamar*. *A queixa* = la queja; *prestar queixa* = hacer una denuncia."],
    ["o ouvidor / a ouvidora", "el defensor del lector, el ombudsman", "A ouvidora do jornal recebe as críticas dos leitores e escreve uma coluna semanal.", "*A ouvidoria* = oficina de reclamos de una empresa, un diario o un organismo público."],
    ["reacender", "reavivar, reabrir (un debate)", "Os resultados reacenderam uma discussão antiga entre educadores, médicos e famílias.", "Literal: volver a encender (de *acender*). *Reacender o debate*, *reacender a polêmica*."],
    ["amarrado", "atado", "O horário escolar está amarrado ao horário de trabalho das famílias.", "De *amarrar* = atar: *amarrar o cadarço*. *Estar amarrado a* = depender de."],
    ["a sonolência", "la somnolencia", "Os alunos que começavam mais tarde relatavam menos sonolência.", "De *sono* (el sueño de dormir). *Estar com sono* = tener sueño."],
    ["a preguiça", "la pereza, la fiaca", "O problema não se resume a preguiça ou excesso de tela.", "*Preguiçoso* = vago; *que preguiça!* = ¡qué fiaca! También el animal, el perezoso."],
    ["o deslocamento", "el traslado, el viaje (diario)", "Há muitos fatores envolvidos: renda familiar, tempo de deslocamento, trabalho fora da escola.", "*Deslocamento casa-trabalho*. De *deslocar-se* = trasladarse."],
    ["o turno", "la franja horaria (mañana, tarde, noche)", "Os adolescentes do turno da manhã dormem uma hora e meia a menos.", "En la escuela: *turno da manhã / da tarde*. *Trabalhar em turnos*."],
    ["advertir", "avisar de un riesgo, prevenir", "O diretor reconhece a importância dos resultados, mas adverte para os riscos.", "Verbo de decir: *advertir para* + riesgo. *A advertência*."],
    ["as aspas", "las comillas", "A citação entre aspas tem que ser fiel, palavra por palavra.", "*Entre aspas* = entre comillas (y figurado: supuesto). *Abrir / fechar aspas*."],
    ["relatar", "contar, informar", "Os alunos que dormiam menos relatavam irritação com mais frequência.", "Verbo de decir del informe: *relatar* = contar, informar. *O relato*."],
],
49: [
    ["a gíria", "la jerga, el argot", "Com cliente, escreva frases claras, completas, sem gíria e sem abreviação.", "Vocabulario coloquial de un grupo: *gíria carioca*, *gíria dos jovens*. Parecido al uso de «lunfardo»."],
    ["embaralhar", "mezclar, confundir", "As novas tecnologias embaralharam ainda mais as fronteiras entre o formal e o informal.", "De *o baralho* = el mazo: *embaralhar as cartas*. Figurado: *embaralhar as ideias*."],
    ["a bronca", "el reto, la reprimenda", "Fica tranquilo, não é bronca, tá? É só uma conversa.", "*Dar uma bronca* = retar; *levar uma bronca* = ser retado. No es «enojo» como en el Río de la Plata."],
    ["em apuros", "en aprietos", "Quem aprende português na rua pode se ver em apuros na hora de escrever uma carta.", "*Estar em apuros*, *ver-se em apuros*. Casi siempre en plural."],
    ["o posicionamento", "la postura, la respuesta oficial", "O cliente respondeu bem seco: aguardo posicionamento formal da empresa.", "*Posicionamento da empresa* = su postura oficial. *Posicionar-se sobre* = pronunciarse sobre."],
    ["o gestor", "el gerente, el jefe", "Muitos gestores consideram desrespeitoso um «blz» vindo de um funcionário.", "*Gestão* = gestión: *gestor de projetos*."],
    ["o estranhamento", "la extrañeza", "Responder a um «bora tomar um açaí?» com uma frase solene causa estranhamento.", "De *estranhar*: *causar estranhamento*. Muy de ensayo."],
    ["a ferramenta", "la herramienta", "O WhatsApp, que nasceu para conversas pessoais, virou ferramenta de trabalho.", "*Caixa de ferramentas*; *ferramenta de busca*."],
    ["antiquado", "anticuado", "Muitos jovens acham antiquado um e-mail que começa com «Prezado».", "Con *qu*. Sinónimos: *ultrapassado*; para personas, *careta* (coloquial)."],
    ["enrolado", "complicado, tapado de cosas", "Você disse que o financeiro estava enrolado.", "Coloquial: *estou enrolado* = estoy complicado. *Enrolar alguém* = dar vueltas, chamuyar."],
    ["seco", "cortante, poco amable", "Ele respondeu bem seco: «Prezado Lucas, aguardo posicionamento formal da empresa».", "*Responder seco* = sin cortesía. Coloquial: *estar seco por algo* = morirse de ganas."],
    ["o cargo", "el puesto (de trabajo)", "No final, atenciosamente, o seu nome completo e o seu cargo.", "Puesto de trabajo: *assumir o cargo*. «Hacerse cargo» se dice *encarregar-se*."],
],
50: [
    ["pagar o pato", "pagar los platos rotos", "No fim, quem acaba pagando o pato é sempre o organizador da festa.", "Cargar con la culpa o el costo de lo que hicieron otros. Coloquial y muy frecuente."],
    ["tirar de letra", "hacer algo con los ojos cerrados", "Pelo que você está contando, você tirou de letra e salvou a festa.", "Resolver algo con facilidad: *tirei a prova de letra*."],
    ["fazer vista grossa", "hacer la vista gorda", "O dono do bufê queria que a gente fizesse vista grossa para a multa do contrato.", "*Fazer vista grossa para algo*: con *para*. Adjetivo *grossa*, no «gorda»."],
    ["ao pé da letra", "al pie de la letra, literalmente", "Quem traduz as expressões ao pé da letra acaba pisando na bola.", "*Levar ao pé da letra* = tomar literalmente; *traduzir ao pé da letra*."],
    ["dar com a língua nos dentes", "irse de boca, contar un secreto", "Ela deu com a língua nos dentes e contou o segredo para todo mundo.", "Revelar lo que no se debía. Coloquial; sinónimo neutro: *deixar escapar*."],
    ["o orelhão", "el teléfono público", "A expressão vem do tempo dos orelhões, que funcionavam com fichas.", "El teléfono público diseñado en 1971 por Chu Ming Silveira; de ahí *cair a ficha*."],
    ["decorar", "memorizar; adornar", "Não tente decorar listas: o dicionário foi feito para consultar.", "Falso amigo parcial: *decorar* = aprender de memoria (*decorar a tabuada*); también adornar."],
    ["enfiar o pé na jaca", "zarparse (con la comida o la bebida)", "Enfiar o pé na jaca é exagerar, sobretudo na comida ou na bebida.", "*Enfiar* = meter; la *jaca* es una fruta tropical enorme. Muy de fin de año."],
    ["sem eira nem beira", "sin un peso, sin nada", "Sem eira nem beira quer dizer sem recurso nenhum.", "*Eira* = era (para trillar) y *beira* = alero: quien no tiene ni eso."],
    ["ficar uma fera", "ponerse hecho una furia", "Quando a noiva viu que não tinha bufê, ficou uma fera.", "*Fera* = fiera; coloquial, *ser fera em algo* = ser un genio en algo."],
    ["suar a camisa", "romperse el lomo, esforzarse", "Eu suei a camisa, isso sim.", "*Suar* = transpirar. Del fútbol: *suar a camisa do time*."],
    ["ficar de molho", "quedarse quieto, hacer reposo", "Agora eu vou ficar de molho uns dias.", "*De molho* = en remojo: *deixar o feijão de molho*. Figurado: reposo."],
],
51: [
    ["esvaziar-se", "vaciarse", "O centro, que durante décadas foi o coração das cidades, esvaziou-se.", "De *vazio*. Transitivo: *esvaziar a sala*; pronominal: *a cidade se esvazia no feriado*."],
    ["aquém de", "por debajo de, sin llegar a", "Um técnico admite que os primeiros resultados ficaram aquém do esperado.", "*Ficar aquém do esperado* = no estar a la altura. Contrario: *além de* = más allá de."],
    ["o cortiço", "el conventillo", "No centro vivem trabalhadores informais e famílias em cortiços.", "Casa antigua dividida en piezas, como el conventillo porteño. Clásico: *O Cortiço*, de Aluísio Azevedo."],
    ["a incorporadora", "la desarrolladora inmobiliaria", "Os críticos temem que as grandes incorporadoras lucrem com apartamentos pequenos e caros.", "Empresa que promueve y vende edificios nuevos. Distinta de *a construtora*, que los construye."],
    ["a moradia", "la vivienda", "Milhares de pessoas procuram moradia perto do trabalho e do transporte.", "*Moradia popular*, *movimento de moradia*, *direito à moradia*. De *morar*."],
    ["desbotado", "desteñido", "Faixas de «aluga-se» desbotadas pelo sol contam uma história que se repete.", "*Desbotar* = desteñirse (la ropa, un cartel). *Faixa* = pasacalle."],
    ["tombado", "declarado patrimonio histórico", "Alguns prédios são tombados pelo patrimônio histórico.", "*Tombar* = declarar patrimonio (y también volcar). *O tombamento*; el IPHAN protege los bienes federales."],
    ["a requalificação", "la revitalización (urbana)", "Os defensores do retrofit falam em requalificação do centro.", "Término del urbanismo; *retrofit* = reforma de un edificio viejo."],
    ["o licenciamento", "la habilitación, los permisos", "Algumas prefeituras passaram a oferecer um licenciamento mais rápido.", "*Licenciamento ambiental*, *de obras*. *Licença* = permiso."],
    ["a creche", "la guardería, el jardín maternal", "O retrofit precisa vir acompanhado de habitação social, de creches e de transporte.", "Del francés *crèche*; de 0 a 3 años. Después viene la *pré-escola*."],
    ["o déficit habitacional", "la falta de viviendas", "Os movimentos de moradia lembram o déficit habitacional da cidade.", "Faltan millones de viviendas en Brasil; *movimento de moradia* = organización de los sin techo."],
    ["o entulho", "los escombros", "Pense no concreto, no aço, no transporte do entulho.", "Colectivo singular: *o entulho*. *Caçamba de entulho* = volquete."],
],
}
