# -*- coding: utf-8 -*-
"""Congiuntivo, concordanza dei tempi e periodo ipotetico (Soluzioni, capp. 21, 24).

Escrito para hispanohablantes: casi todos los ítems atacan un punto donde el
español y el italiano NO coinciden, que es donde se estanca la gente que llega
a B2 con el italiano "que se entiende".
"""

ITEMS = [
    # --- congiuntivo presente: disparadores ---
    dict(id="c1-cong-01", type="choice", topic="congiuntivo",
         prompt="Elegí la forma correcta.",
         stem="Benché ___ tardi, sono usciti lo stesso.",
         options=["fosse", "era", "sarebbe"], answer="fosse",
         note="«Benché/sebbene/quantunque» exigen congiuntivo. En español "
              "«aunque era tarde» va en indicativo: es el error nº1 del hispanohablante."),
    dict(id="c1-cong-02", type="choice", topic="congiuntivo",
         prompt="Elegí la forma correcta.",
         stem="Penso che Marco ___ ragione.",
         options=["abbia", "ha", "avrebbe"], answer="abbia",
         note="Verbos de opinión (pensare, credere, ritenere, immaginare) piden "
              "congiuntivo. En español «creo que tiene razón» va en indicativo."),
    dict(id="c1-cong-03", type="choice", topic="congiuntivo",
         prompt="Elegí la forma correcta.",
         stem="So che Marco ___ ragione.",
         options=["ha", "abbia", "avesse"], answer="ha",
         note="«Sapere» afirma un hecho: indicativo. Contrastalo con «penso che abbia»."),
    dict(id="c1-cong-04", type="choice", topic="congiuntivo",
         prompt="Elegí la forma correcta.",
         stem="Non dico che ___ disonesto, dico solo che è distratto.",
         options=["sia", "è", "fosse"], answer="sia",
         note="La negación de un verbo declarativo lo vuelve subjetivo: «dico che è» "
              "pero «non dico che sia»."),
    dict(id="c1-cong-05", type="choice", topic="congiuntivo",
         prompt="Elegí la forma correcta (registro cuidado).",
         stem="Si dice che ___ molto brava.",
         options=["sia", "è", "era"], answer="sia",
         note="«Si dice che» (se dice que) introduce rumor, no hecho: congiuntivo."),
    dict(id="c1-cong-06", type="choice", topic="congiuntivo",
         prompt="Elegí la forma correcta.",
         stem="È chiaro che non ___ intenzione di aiutarci.",
         options=["ha", "abbia", "avesse"], answer="ha",
         note="«È chiaro/evidente/certo che» = certeza: indicativo. Pero "
              "«non è chiaro che...» → congiuntivo."),
    dict(id="c1-cong-07", type="choice", topic="congiuntivo",
         prompt="Elegí la forma correcta.",
         stem="Aspetto che ___ il treno.",
         options=["arrivi", "arriva", "arriverà"], answer="arrivi",
         note="«Aspettare che» y «prima che» piden congiuntivo («finché non» lo "
              "admite, aunque suele ir con indicativo)."),
    dict(id="c1-cong-08", type="choice", topic="congiuntivo",
         prompt="Elegí la forma correcta.",
         stem="Ti telefono prima che tu ___ di casa.",
         options=["esca", "esci", "uscirai"], answer="esca",
         note="«Prima che» + congiuntivo siempre. Si el sujeto no cambia: "
              "«prima di uscire» + infinitivo."),
    dict(id="c1-cong-09", type="choice", topic="congiuntivo",
         prompt="Elegí la forma correcta.",
         stem="Cerco una segretaria che ___ il cinese.",
         options=["sappia", "sa", "saprebbe"], answer="sappia",
         note="Relativa de antecedente no identificado (busco una, cualquiera) → "
              "congiuntivo. «Ho una segretaria che sa il cinese» → indicativo."),
    dict(id="c1-cong-10", type="choice", topic="congiuntivo",
         prompt="Elegí la forma correcta.",
         stem="È il libro più bello che io ___ mai letto.",
         options=["abbia", "ho", "avessi"], answer="abbia",
         note="Tras superlativo relativo + relativa: congiuntivo."),
    dict(id="c1-cong-11", type="choice", topic="congiuntivo",
         prompt="Elegí la forma correcta.",
         stem="Chiunque ___ quella porta, dovrà pagare i danni.",
         options=["abbia aperto", "ha aperto", "apriva"], answer="abbia aperto",
         note="Indefinidos en -unque (chiunque, qualunque, dovunque, comunque) "
              "rigen congiuntivo."),
    dict(id="c1-cong-12", type="cloze", topic="congiuntivo",
         prompt="Completá con el congiuntivo presente.",
         stem="Bisogna che tu ___ (venire) subito.",
         answer="venga",
         note="«Bisogna che» + congiuntivo. Ojo: «bisogna venire» (impersonal) "
              "va con infinitivo, sin «che»."),
    dict(id="c1-cong-13", type="cloze", topic="congiuntivo",
         prompt="Completá con el congiuntivo presente.",
         stem="Può darsi che loro non ___ (sapere) niente.",
         answer="sappiano",
         note="*può darsi che* («puede ser que») expresa posibilidad y pide congiuntivo, como en castellano. Con *forse* («quizás»), en cambio, va el indicativo."),
    dict(id="c1-cong-14", type="choice", topic="congiuntivo",
         prompt="¿Cuál exige congiuntivo?",
         stem="___ sia già partito.",
         options=["Credo che", "Forse", "So che"], answer="Credo che",
         note="«Forse» es adverbio, no conjunción: «Forse è già partito» (indicativo)."),

    # --- concordanza dei tempi ---
    dict(id="c1-conc-01", type="choice", topic="concordanza",
         prompt="Elegí la forma correcta.",
         stem="Credevo che ___ già partito.",
         options=["fosse", "sia", "era"], answer="fosse",
         note="Verbo principal en pasado + anterioridad → congiuntivo trapassato."),
    dict(id="c1-conc-02", type="choice", topic="concordanza",
         prompt="Elegí la forma correcta.",
         stem="Credo che ieri ___ troppo.",
         options=["abbia lavorato", "lavori", "avesse lavorato"],
         answer="abbia lavorato",
         note="Principal en presente + acción pasada → congiuntivo passato."),
    dict(id="c1-conc-03", type="choice", topic="concordanza",
         prompt="Elegí la forma correcta.",
         stem="Volevo che tu mi ___ la verità.",
         options=["dicessi", "dica", "avessi detto"], answer="dicessi",
         note="Principal en pasado + simultaneidad/posterioridad → congiuntivo imperfetto."),
    dict(id="c1-conc-04", type="choice", topic="concordanza",
         prompt="Elegí la forma correcta.",
         stem="Speravo che ___ tutto bene.",
         options=["andasse", "vada", "andrà"], answer="andasse",
         note="Regla de oro: pasado en la principal → imperfetto o trapassato en la subordinada."),
    dict(id="c1-conc-05", type="cloze", topic="concordanza",
         prompt="Completá con el congiuntivo trapassato.",
         stem="Non sapevo che voi ___ (arrivare) il giorno prima.",
         answer="foste arrivati",
         alt=["foste arrivate"],
         note="Anterioridad respecto de un pasado: trapassato del congiuntivo, con «essere»."),
    dict(id="c1-conc-06", type="choice", topic="concordanza",
         prompt="Elegí la forma correcta.",
         stem="Mi ha detto che ___ il giorno dopo.",
         options=["sarebbe partito", "partirebbe", "sarebbe stato partito"],
         answer="sarebbe partito",
         note="El «futuro en el pasado» italiano es el condizionale PASSATO. "
              "El español usa el condicional simple («dijo que partiría»): "
              "es el segundo gran error del hispanohablante."),
    dict(id="c1-conc-07", type="translate", topic="concordanza",
         prompt="Traducí al italiano.",
         stem="Me prometió que vendría.",
         answer="Mi ha promesso che sarebbe venuto",
         alt=["Mi promise che sarebbe venuto",
              "Mi ha promesso che sarebbe venuta",
              "Mi promise che sarebbe venuta",
              "Mi ha promesso di venire",
              "Mi promise di venire"],
         note="«que vendría» → «che sarebbe venuto», nunca «che verrebbe»."),

    # --- periodo ipotetico ---
    dict(id="c1-ipot-01", type="choice", topic="periodo ipotetico",
         prompt="Elegí la forma correcta (irrealtà nel presente).",
         stem="Se ___ più tempo, verrei con voi.",
         options=["avessi", "avrei", "ho"], answer="avessi",
         note="Tipo II: se + congiuntivo imperfetto → condizionale presente."),
    dict(id="c1-ipot-02", type="choice", topic="periodo ipotetico",
         prompt="Elegí la forma correcta (irrealtà nel passato).",
         stem="Se me l'avessi detto, ti ___.",
         options=["avrei aiutato", "aiutassi", "avessi aiutato"],
         answer="avrei aiutato",
         note="Tipo III: se + congiuntivo trapassato → condizionale passato."),
    dict(id="c1-ipot-03", type="choice", topic="periodo ipotetico",
         prompt="Elegí la forma correcta (realtà).",
         stem="Se ___ tempo, ti chiamo.",
         options=["ho", "avessi", "avrei"], answer="ho",
         note="Tipo I: hipótesis real → indicativo en las dos partes."),
    dict(id="c1-ipot-04", type="choice", topic="periodo ipotetico",
         prompt="¿Cuál es INCORRECTA en italiano estándar?",
         stem="Se ___ ricco, comprerei una casa al mare.",
         options=["sarei", "fossi", "diventassi"], answer="sarei",
         note="Nunca condizionale detrás de «se». En español tampoco, pero el "
              "calco «si sería» aparece igual: cuidado."),
    dict(id="c1-ipot-05", type="cloze", topic="periodo ipotetico",
         prompt="Completá el periodo ipotetico misto.",
         stem="Se ___ (studiare) di più allora, adesso avresti un buon lavoro.",
         answer="avessi studiato",
         note="Mixto: condición en el pasado (trapassato) con consecuencia en el "
              "presente (condizionale presente)."),
    dict(id="c1-ipot-06", type="translate", topic="periodo ipotetico",
         prompt="Traducí al italiano.",
         stem="Si hubiera sabido, no habría venido.",
         answer="Se avessi saputo, non sarei venuto",
         alt=["Se lo avessi saputo, non sarei venuto",
              "Se l'avessi saputo, non sarei venuto",
              "Se avessi saputo, non sarei venuta",
              "Se lo avessi saputo, non sarei venuta",
              "Se l'avessi saputo, non sarei venuta"],
         note="«hubiera sabido» → avessi saputo; «habría venido» → sarei venuto "
              "(venire va con essere)."),
    dict(id="c1-ipot-07", type="choice", topic="periodo ipotetico",
         prompt="Elegí la alternativa que NO cambia el sentido.",
         stem="Se avessi saputo, sarei venuto. ≈",
         options=["Avessi saputo, sarei venuto!",
                  "Sapevo e sono venuto.",
                  "Se so, vengo."],
         answer="Avessi saputo, sarei venuto!",
         note="Se puede omitir «se» y dejar el congiuntivo solo; es frecuente sobre todo en exclamaciones y en la lengua expresiva."),
    dict(id="c1-ipot-08", type="choice", topic="periodo ipotetico",
         prompt="Elegí la forma correcta.",
         stem="Magari ___ vero!",
         options=["fosse", "è", "sarebbe"], answer="fosse",
         note="*Magari* + congiuntivo imperfetto expresa un deseo poco probable, como «¡ojalá fuera!»: el tiempo es el mismo que en castellano."),
    dict(id="c1-ipot-09", type="cloze", topic="periodo ipotetico",
         prompt="Completá con el verbo adecuado.",
         stem="Nel caso in cui ___ (piovere), la festa sarà rimandata.",
         answer="piova",
         note="«Nel caso in cui», «a patto che», «purché», «a meno che (non)» → congiuntivo."),
    dict(id="c1-ipot-10", type="choice", topic="periodo ipotetico",
         prompt="Elegí la forma correcta.",
         stem="Verrò, a meno che non ___ troppo tardi.",
         options=["sia", "è", "sarà"], answer="sia",
         note="El «non» de «a meno che non» es expletivo: no niega nada."),
]
