# -*- coding: utf-8 -*-
"""Voz pasiva, causativo, formas no finitas, conectivos y orden de palabras
(Soluzioni, capp. 16, 23, 26, 27, 28, 29).

Es la mitad "de arriba" del C1: no son formas nuevas, es saber elegir el
registro y la construcción idiomática correcta.
"""

ITEMS = [
    # --- passivo ---
    dict(id="c1-pass-01", type="choice", topic="passivo",
         prompt="Elegí la pasiva correcta de «Il direttore firma i contratti».",
         stem="I contratti ___ dal direttore.",
         options=["sono firmati", "vengono firmato", "si firma"],
         answer="sono firmati",
         note="Pasiva con essere: el participio concuerda con el sujeto."),
    dict(id="c1-pass-02", type="choice", topic="passivo",
         prompt="¿Cuál subraya el proceso y no el estado?",
         stem="La porta ___ chiusa alle otto.",
         options=["viene", "è", "sta"], answer="viene",
         note="«Venire» + participio marca la acción; «essere» puede leerse como "
              "estado resultante. Solo en tiempos simples."),
    dict(id="c1-pass-03", type="choice", topic="passivo",
         prompt="Elegí la forma que expresa obligación.",
         stem="Questo modulo ___ compilato entro venerdì.",
         options=["va", "viene", "è stato"], answer="va",
         note="*andare* + participio expresa obligación en pasiva: *va compilato*, "
              "«tiene que ser completado». No tiene equivalente directo en castellano "
              "y es muy frecuente en el lenguaje administrativo."),
    dict(id="c1-pass-04", type="cloze", topic="passivo",
         prompt="Reescribí con el «si passivante».",
         stem="In Italia si ___ (mangiare) molte verdure.",
         answer="mangiano",
         note="El «si passivante» concuerda con el objeto: verdure (plural) → "
              "mangiano. Error típico: dejar «si mangia»."),
    dict(id="c1-pass-05", type="choice", topic="passivo",
         prompt="Elegí la forma correcta (si impersonale).",
         stem="Quando si è stanchi, si ___ presto.",
         options=["va a dormire", "vanno a dormire", "si dorme"],
         answer="va a dormire",
         note="«Si» impersonal + verbo en 3ª singular; el adjetivo, en cambio, "
              "va en plural masculino: «si è stanchi»."),
    dict(id="c1-pass-06", type="translate", topic="passivo",
         prompt="Traducí al italiano (pasiva refleja).",
         stem="Aquí se venden libros usados.",
         answer="Qui si vendono libri usati",
         alt=["Qua si vendono libri usati", "Si vendono libri usati qui"],
         note="Plural obligatorio en el verbo: «si vendono», no «si vende»."),

    # --- causativo ---
    dict(id="c1-caus-01", type="choice", topic="causativo",
         prompt="Elegí la forma correcta.",
         stem="___ riparare la macchina.",
         options=["Ho fatto", "Ho fatta", "Sono fatto"], answer="Ho fatto",
         note="Para decir que otro hace el trabajo se usa *fare* + infinitivo: "
              "*ho fatto riparare la macchina*. El castellano dice «hice arreglar» o "
              "«mandé a arreglar»; el participio *fatto* no concuerda."),
    dict(id="c1-caus-02", type="choice", topic="causativo",
         prompt="¿Cómo se dice «se lo hice leer (a él)»?",
         stem="___ ho fatto leggere.",
         options=["Glielo", "Lo gli", "Gli"], answer="Glielo",
         note="En el causativo con dos complementos, la persona pasa a indirecto: "
              "gliel(o) ho fatto leggere."),
    dict(id="c1-caus-03", type="choice", topic="causativo",
         prompt="Elegí la diferencia correcta.",
         stem="«Lascio parlare Marco» significa…",
         options=["Dejo que Marco hable", "Hago que Marco hable",
                  "Marco me deja hablar"],
         answer="Dejo que Marco hable",
         note="*lasciare* + infinitivo = «dejar que» (permiso: *lascio parlare Marco*); *fare* + infinitivo = «hacer que» (causa). Los dos van sin «que»."),
    dict(id="c1-caus-04", type="translate", topic="causativo",
         prompt="Traducí al italiano.",
         stem="Me corté el pelo (fui a la peluquería).",
         answer="Mi sono fatto tagliare i capelli",
         alt=["Mi sono fatta tagliare i capelli"],
         note="Causativo reflexivo: si lo hizo otro por vos, «farsi + infinito». "
              "«Mi sono tagliato i capelli» = te lo cortaste vos."),
    dict(id="c1-caus-05", type="choice", topic="percezione",
         prompt="Elegí la forma correcta.",
         stem="Dalla finestra ho visto Maria ___.",
         options=["uscire", "di uscire", "uscendo"],
         answer="uscire",
         note="Verbos de percepción + infinitivo sin preposición. «Che usciva» "
              "también vale; «uscendo» se referiría al sujeto (yo)."),

    # --- infinito, gerundio, participio ---
    dict(id="c1-nonfin-01", type="choice", topic="gerundio",
         prompt="Elegí la forma correcta.",
         stem="___ molto, ha imparato l'italiano in fretta.",
         options=["Studiando", "Studiare", "Studiato"], answer="Studiando",
         note="Gerundio con valor causal/modal, con el mismo sujeto que la principal."),
    dict(id="c1-nonfin-02", type="choice", topic="gerundio",
         prompt="Elegí la forma correcta.",
         stem="Pur ___ stanco, ha continuato.",
         options=["essendo", "essere", "stato"], answer="essendo",
         note="*pur* + gerundio tiene valor concesivo («aunque»): *pur essendo stanco*. Es una alternativa culta a *benché* + congiuntivo."),
    dict(id="c1-nonfin-03", type="choice", topic="participio",
         prompt="Elegí la forma correcta.",
         stem="___ la lettera, uscì di casa.",
         options=["Scritta", "Scrivendo", "Scrivere"], answer="Scritta",
         note="Participio absoluto: «scritta la lettera» = una vez escrita la carta. "
              "Concuerda con el objeto. Registro escrito/narrativo."),
    dict(id="c1-nonfin-04", type="choice", topic="infinito",
         prompt="Elegí la forma correcta.",
         stem="Dopo ___ mangiato, siamo usciti.",
         options=["aver", "avere di", "essere"], answer="aver",
         note="«Dopo» + infinito compuesto, nunca gerundio. Ojo: «dopo essere "
              "arrivati» con verbos de essere."),
    dict(id="c1-nonfin-05", type="translate", topic="gerundio",
         prompt="Traducí al italiano.",
         stem="Sigo estudiando italiano.",
         answer="Continuo a studiare l'italiano",
         alt=["Continuo a studiare italiano", "Sto continuando a studiare l'italiano"],
         note="«Seguir + gerundio» NO se calca: italiano usa «continuare A + "
              "infinito». «Sto studiando» es solo acción en curso ahora."),
    dict(id="c1-nonfin-06", type="choice", topic="gerundio",
         prompt="Elegí la forma correcta (mientras esperaba).",
         stem="___ il treno, ho letto il giornale.",
         options=["Aspettando", "Avendo aspettato", "Aspettato"],
         answer="Aspettando",
         note="Simultaneidad con el mismo sujeto → gerundio simple. «Avendo "
              "aspettato» y «aspettato» marcan anterioridad: la espera ya terminó."),

    # --- connettivi e registro ---
    dict(id="c1-conn-01", type="choice", topic="connettivi",
         prompt="Elegí el conector adecuado (concesivo, registro alto).",
         stem="___ le difficoltà, il progetto va avanti.",
         options=["Nonostante", "Siccome", "Affinché"], answer="Nonostante",
         note="«Nonostante/malgrado» + sustantivo o + congiuntivo."),
    dict(id="c1-conn-02", type="choice", topic="connettivi",
         prompt="Elegí el conector adecuado (causal, al inicio).",
         stem="___ piove, restiamo a casa.",
         options=["Siccome", "Perché", "Quindi"], answer="Siccome",
         note="«Perché» causal no abre la frase; «siccome/poiché/dato che» sí."),
    dict(id="c1-conn-03", type="choice", topic="connettivi",
         prompt="Elegí el conector final.",
         stem="Te lo spiego ___ tu capisca.",
         options=["affinché", "perché non", "sebbene"], answer="affinché",
         note="Para expresar finalidad con otro sujeto: *affinché* (o *perché*) + congiuntivo, como «para que» + subjuntivo."),
    dict(id="c1-conn-04", type="choice", topic="connettivi",
         prompt="Elegí la correcta.",
         stem="Non mi aiuta; ___, mi critica.",
         options=["anzi", "invece di", "piuttosto che"], answer="anzi",
         note="«Anzi» refuerza o corrige lo dicho: es más / al contrario."),
    dict(id="c1-conn-05", type="choice", topic="connettivi",
         prompt="Elegí el conector adecuado.",
         stem="È stanco; ___ finisce il lavoro.",
         options=["tuttavia", "dunque", "ossia"], answer="tuttavia",
         note="*tuttavia* y *eppure* oponen («sin embargo»); *dunque* saca una consecuencia («por lo tanto»). Acá hay oposición: está cansado pero termina."),

    # --- ordine delle parole e dislocazioni (cap. 29) ---
    dict(id="c1-ord-01", type="choice", topic="ordine",
         prompt="Elegí la dislocación correcta.",
         stem="Il pane ___ compro io.",
         options=["lo", "ne", "—"], answer="lo",
         note="Dislocación a la izquierda: el objeto anticipado se retoma "
              "obligatoriamente con pronombre. Rasgo muy italiano y muy oral."),
    dict(id="c1-ord-02", type="choice", topic="ordine",
         prompt="Elegí la forma marcada (focalización).",
         stem="___ che non capisco.",
         options=["È questo", "Questo è", "Ecco questo"], answer="È questo",
         note="Frase escindida: «è questo che...» pone el foco en el elemento."),
    dict(id="c1-ord-03", type="choice", topic="ordine",
         prompt="Elegí la correcta.",
         stem="A Roma ___ sono stato molte volte.",
         options=["ci", "vi ci", "ne"], answer="ci",
         note="Dislocación de un locativo: se retoma con «ci»."),
    dict(id="c1-ord-04", type="translate", topic="ordine",
         prompt="Traducí al italiano con dislocación a la derecha.",
         stem="Ya lo sabía, eso.",
         answer="Lo sapevo già, questo",
         alt=["Già lo sapevo, questo"],
         note="Dislocación a la derecha: el pronombre anticipa y el elemento "
              "aparece al final como refuerzo."),

    # --- preposizioni con verbi (cap. 28) ---
    dict(id="c1-prep-01", type="choice", topic="preposizioni",
         prompt="Elegí la preposición correcta.",
         stem="Domani comincio ___ studiare il tedesco.",
         options=["a", "di", "—"], answer="a",
         note="cominciare A, continuare A, riuscire A, provare A."),
    dict(id="c1-prep-02", type="choice", topic="preposizioni",
         prompt="Elegí la preposición correcta.",
         stem="Allora, decidi ___ partire o no?",
         options=["di", "a", "per"], answer="di",
         note="decidere DI, cercare DI, finire DI, smettere DI."),
    dict(id="c1-prep-03", type="choice", topic="preposizioni",
         prompt="Elegí la correcta (sin preposición).",
         stem="Preferisco ___ restare qui.",
         options=["—", "di", "a"], answer="—",
         note="Modales y preferire/desiderare/amare van con infinitivo desnudo."),
    dict(id="c1-prep-04", type="choice", topic="preposizioni",
         prompt="Elegí la correcta.",
         stem="Mi dimentico sempre ___ chiamarla.",
         options=["di", "a", "per"], answer="di",
         note="dimenticarsi DI, ricordarsi DI, accorgersi DI, pentirsi DI."),
    dict(id="c1-prep-05", type="translate", topic="preposizioni",
         prompt="Traducí al italiano.",
         stem="No logro terminar a tiempo.",
         answer="Non riesco a finire in tempo",
         alt=["Non riesco a terminare in tempo"],
         note="«riuscire A» + infinitivo: riesco a finire, no «riesco finire»."),

    # --- comparativi e superlativi (cap. 5) ---
    dict(id="c1-comp-01", type="choice", topic="comparativi",
         prompt="Elegí la forma correcta.",
         stem="Questo vino è migliore ___ quello.",
         options=["di", "che", "come"], answer="di",
         note="«Di» ante sustantivo/pronombre; «che» al comparar dos cualidades o "
              "dos elementos de la misma clase gramatical."),
    dict(id="c1-comp-02", type="choice", topic="comparativi",
         prompt="Elegí la forma correcta.",
         stem="È più furbo ___ intelligente.",
         options=["che", "di", "del"], answer="che",
         note="Dos adjetivos comparados entre sí → «che»."),
    dict(id="c1-comp-03", type="choice", topic="comparativi",
         prompt="Elegí el superlativo irregular.",
         stem="Questo è il ___ problema di tutti (el peor).",
         options=["peggiore", "più cattivo", "pessimo"], answer="peggiore",
         note="buono→migliore/ottimo; cattivo→peggiore/pessimo; "
              "grande→maggiore/massimo; piccolo→minore/minimo."),
    dict(id="c1-comp-04", type="choice", topic="comparativi",
         prompt="Elegí la forma correcta.",
         stem="Ha più soldi ___ non sembri.",
         options=["di quanto", "che", "di quello"], answer="di quanto",
         note="Comparación con verbo conjugado: «di quanto (non) + congiuntivo»."),
]
