# -*- coding: utf-8 -*-
"""Mejoras 3 (A), Stagione 3: más producción en las semanas 28 (connettivi),
29 (congiuntivo passato), 32 (concordanza dei tempi), 33 (periodo
ipotetico), 37 (passato remoto) y 38 (discorso indiretto).  Esas semanas
eran casi todo cloze y choice: acá el alumno traduce, transforma y corrige."""

TR = "Traducí al italiano."
VA = "Trova l'errore: tocá la palabra que está mal y corregila."
P28 = "Uní o reescribí la frase con el conector entre paréntesis."
P29 = "Empezá con lo que está entre paréntesis y usá el congiuntivo passato."
P32 = "Reescribí la frase empezando como se indica."
P33 = "Reescribí la situación como hipótesis con «se»."
P37 = "Pasá la frase al passato remoto."
P38 = "Pasá la frase al discurso indirecto."


def _fx(id, w, topic, level, cat, stem, bad, good, note, goodAlt=None):
    d = dict(id=id, type="fixerr", topic=topic, level=level, w=w, prompt=VA, cat=cat,
             stem=stem, bad=bad, good=good, answer=stem.replace(bad, good, 1), note=note)
    if goodAlt:
        d["goodAlt"] = goodAlt
    return d


ITEMS = [
    # ================= Settimana 28: Connettivi =================
    dict(id="m3-28-01", type="translate", topic="connettivi", level="B1", w=28, prompt=TR,
         stem="Yo me quedo en casa; mi hermana, en cambio, sale con sus amigas.",
         answer="Io resto a casa; mia sorella, invece, esce con le sue amiche",
         alt=["Io rimango a casa; mia sorella, invece, esce con le sue amiche",
              "Io resto a casa, invece mia sorella esce con le sue amiche",
              "Io rimango a casa, invece mia sorella esce con le sue amiche",
              "Io resto a casa, mentre mia sorella esce con le sue amiche",
              "Io rimango a casa, mentre mia sorella esce con le sue amiche",
              "Io sto a casa; mia sorella, invece, esce con le sue amiche",
              "Io sto a casa, invece mia sorella esce con le sue amiche"],
         note="*invece* contrasta dos sujetos y suele ir después del segundo: *mia sorella, invece, esce*. "
              "También sirve *mentre* (mientras que) entre las dos partes."),
    dict(id="m3-28-02", type="translate", topic="connettivi", level="B1", w=28, prompt=TR,
         stem="No tengo ni tiempo ni ganas de discutir.",
         answer="Non ho né tempo né voglia di discutere",
         alt=["Non ho né il tempo né la voglia di discutere",
              "Non ho né tempo né voglia di litigare"],
         note="Con *né… né* detrás del verbo, el *non* va delante: *non ho né tempo né voglia*. "
              "«Ganas» se dice *voglia*, en singular."),
    dict(id="m3-28-03", type="translate", topic="connettivi", level="B1", w=28, prompt=TR,
         stem="No es caro; es más, cuesta poquísimo.",
         answer="Non è caro, anzi costa pochissimo",
         alt=["Non è caro, anzi, costa pochissimo",
              "Non è caro; anzi, costa pochissimo"],
         note="*anzi* corrige o refuerza lo dicho yendo más lejos: «no es caro; es más, cuesta poquísimo». "
              "No tiene un calco castellano directo."),
    dict(id="m3-28-04", type="translate", topic="connettivi", level="B1", w=28, prompt=TR,
         stem="Hablaba tan rápido que nadie lo entendía.",
         answer="Parlava così veloce che nessuno lo capiva",
         alt=["Parlava così velocemente che nessuno lo capiva",
              "Parlava tanto veloce che nessuno lo capiva",
              "Parlava talmente veloce che nessuno lo capiva",
              "Parlava così in fretta che nessuno lo capiva"],
         note="*così… che* (tan… que) da la consecuencia: *così* delante del adverbio, *che* delante del resultado. "
              "No lo confundas con *così… come*, que compara."),
    dict(id="m3-28-05", type="translate", topic="connettivi", level="B1", w=28, prompt=TR,
         stem="Dado que el tren no salía, tomamos un taxi.",
         answer="Dato che il treno non partiva, abbiamo preso un taxi",
         alt=["Visto che il treno non partiva, abbiamo preso un taxi",
              "Siccome il treno non partiva, abbiamo preso un taxi",
              "Poiché il treno non partiva, abbiamo preso un taxi",
              "Abbiamo preso un taxi perché il treno non partiva",
              "Abbiamo preso un taxi dato che il treno non partiva"],
         note="*dato che*, *visto che* y *siccome* abren la frase con la causa. *perché* causal, en cambio, "
              "suele ir después de la principal: *abbiamo preso un taxi perché…*"),
    dict(id="m3-28-06", type="typed", topic="connettivi", level="B1", w=28, prompt=P28,
         stem="Prima faccio colazione, poi vado al lavoro. (prima di)",
         answer="Prima di andare al lavoro, faccio colazione",
         alt=["Faccio colazione prima di andare al lavoro",
              "Prima di andare a lavorare, faccio colazione",
              "Faccio colazione prima di andare a lavorare"],
         note="Con el mismo sujeto, *prima di* + infinitivo: *prima di andare*. "
              "Si el sujeto cambia, *prima che* + congiuntivo: *prima che tu vada*."),
    dict(id="m3-28-07", type="typed", topic="connettivi", level="B1", w=28, prompt=P28,
         stem="Prima ho finito i compiti, poi sono uscita. (dopo)",
         answer="Dopo aver finito i compiti, sono uscita",
         alt=["Dopo avere finito i compiti, sono uscita",
              "Sono uscita dopo aver finito i compiti",
              "Sono uscita dopo avere finito i compiti"],
         note="*dopo* pide infinitivo compuesto: *dopo aver finito*. «Dopo finire» es un calco que no existe."),
    dict(id="m3-28-08", type="typed", topic="connettivi", level="B1", w=28, prompt=P28,
         stem="Costa molto. Lo compro lo stesso. (anche se)",
         answer="Anche se costa molto, lo compro lo stesso",
         alt=["Anche se costa molto, lo compro",
              "Lo compro lo stesso, anche se costa molto",
              "Lo compro anche se costa molto",
              "Anche se costa tanto, lo compro lo stesso"],
         note="*anche se* va con indicativo y concede un hecho real; *lo stesso* (igual) lo refuerza. "
              "Con *benché* iría el congiuntivo: *benché costi molto*."),
    _fx("m3-28-10", 28, "connettivi", "B1", "parola_spagnola",
        "Il film è lungo, pero è molto bello.", "pero", "ma",
        "«Pero» es castellano: en italiano se dice *ma* o *però*, con tilde. *pero* sin tilde es el peral.",
        goodAlt=["però"]),
    _fx("m3-28-11", 28, "connettivi", "B1", "congiuntivo",
        "Anche se piova, esco lo stesso a correre.", "piova", "piove",
        "*anche se* va con indicativo: *anche se piove*. El congiuntivo es para *benché* o *sebbene*: "
        "*benché piova*."),
    dict(id="m3-28-12", type="translate", topic="connettivi", level="B1", w=28, prompt=TR,
         stem="Por lo que sé, el negocio abre a las nueve.",
         answer="Per quanto ne so, il negozio apre alle nove",
         alt=["Per quanto so, il negozio apre alle nove",
              "Che io sappia, il negozio apre alle nove"],
         note="*per quanto ne so* limita lo que afirmás: «por lo que sé». También se dice *che io sappia*, "
              "con congiuntivo."),

    # ================= Settimana 29: Congiuntivo passato =================
    dict(id="m3-29-01", type="translate", topic="congiuntivo passato", level="B2", w=29, prompt=TR,
         stem="Creo que Marta ya se fue.",
         answer="Credo che Marta sia già partita",
         alt=["Penso che Marta sia già partita",
              "Credo che Marta se ne sia già andata",
              "Penso che Marta se ne sia già andata",
              "Credo che Marta sia già andata via",
              "Penso che Marta sia già andata via",
              "Credo che Marta sia già uscita",
              "Penso che Marta sia già uscita"],
         note="Opinión de hoy sobre algo ya pasado: congiuntivo passato. *partire* va con *essere* "
              "y el participio concuerda con Marta: *sia partita*."),
    dict(id="m3-29-02", type="translate", topic="congiuntivo passato", level="B2", w=29, prompt=TR,
         stem="Me alegra que hayas aprobado el examen.",
         answer="Sono contento che tu abbia superato l'esame",
         alt=["Sono contenta che tu abbia superato l'esame",
              "Sono felice che tu abbia superato l'esame",
              "Mi fa piacere che tu abbia superato l'esame",
              "Sono contento che tu abbia passato l'esame",
              "Sono contenta che tu abbia passato l'esame",
              "Mi fa piacere che tu abbia passato l'esame"],
         note="Una emoción (*sono contento che*, *mi fa piacere che*) pide congiuntivo; el examen ya pasó, "
              "así que va el passato: *abbia superato*."),
    dict(id="m3-29-03", type="translate", topic="congiuntivo passato", level="B2", w=29, prompt=TR,
         stem="Dudo que hayan leído el contrato.",
         answer="Dubito che abbiano letto il contratto",
         alt=["Dubito che loro abbiano letto il contratto"],
         note="*dubitare che* pide congiuntivo. Lectura anterior al momento en que dudás: "
              "*abbiano letto*, con el participio irregular de *leggere*."),
    dict(id="m3-29-04", type="translate", topic="congiuntivo passato", level="B2", w=29, prompt=TR,
         stem="Es posible que se haya olvidado de la reunión.",
         answer="È possibile che si sia dimenticato della riunione",
         alt=["È possibile che si sia dimenticata della riunione",
              "Può darsi che si sia dimenticato della riunione",
              "Può darsi che si sia dimenticata della riunione",
              "È possibile che abbia dimenticato la riunione",
              "Può darsi che abbia dimenticato la riunione"],
         note="*dimenticarsi di* es reflexivo: va con *essere*, *si sia dimenticato della riunione*. "
              "Sin pronombre, *dimenticare* va con *avere*: *abbia dimenticato la riunione*."),
    dict(id="m3-29-05", type="translate", topic="congiuntivo passato", level="B2", w=29, prompt=TR,
         stem="Es la mejor película que vi este año.",
         answer="È il film più bello che io abbia visto quest'anno",
         alt=["È il miglior film che io abbia visto quest'anno",
              "È il film migliore che io abbia visto quest'anno",
              "È il film più bello che ho visto quest'anno",
              "È il miglior film che ho visto quest'anno",
              "È il film migliore che ho visto quest'anno"],
         note="Después de un superlativo el italiano cuidado usa congiuntivo: *il più bello che io abbia visto*. "
              "En el habla también se oye el indicativo (*che ho visto*)."),
    dict(id="m3-29-06", type="typed", topic="congiuntivo passato", level="B2", w=29, prompt=P29,
         stem="Hanno vinto la partita. (Sono contento che…)",
         answer="Sono contento che abbiano vinto la partita",
         alt=["Sono contento che loro abbiano vinto la partita",
              "Sono contenta che abbiano vinto la partita"],
         note="*sono contento che* + congiuntivo; el partido ya terminó, así que va el passato: "
              "*abbiano vinto*, con *avere* como en *hanno vinto*."),
    dict(id="m3-29-07", type="typed", topic="congiuntivo passato", level="B2", w=29, prompt=P29,
         stem="Gli è successo qualcosa. (Temo che…)",
         answer="Temo che gli sia successo qualcosa",
         note="*temere che* pide congiuntivo. *succedere* va con *essere*, como en el passato prossimo: "
              "*è successo → sia successo*."),
    dict(id="m3-29-08", type="typed", topic="congiuntivo passato", level="B2", w=29, prompt=P29,
         stem="Vi siete divertiti alla festa. (Spero che…)",
         answer="Spero che vi siate divertiti alla festa",
         alt=["Spero che vi siate divertite alla festa"],
         note="Los reflexivos van con *essere* también en el congiuntivo passato: *vi siete divertiti → "
              "vi siate divertiti*. El pronombre *vi* queda delante del auxiliar."),
    _fx("m3-29-09", 29, "congiuntivo passato", "B2", "congiuntivo",
        "Penso che Luca ha già finito.", "ha", "abbia",
        "*pensare che* pide congiuntivo; para algo ya hecho, congiuntivo passato: *abbia finito*. "
        "«Ha finito» es el calco de «creo que terminó»."),
    _fx("m3-29-10", 29, "congiuntivo passato", "B2", "ausiliare",
        "È strano che Giulia non abbia arrivata.", "abbia arrivata", "sia arrivata",
        "*arrivare* va con *essere* también en el congiuntivo passato: *sia arrivata*, con el participio "
        "concordado con Giulia."),
    _fx("m3-29-11", 29, "congiuntivo passato", "B2", "congiuntivo",
        "Dopo che sia partito, abbiamo pulito la casa.", "sia partito", "è partito",
        "*dopo che* habla de un hecho real: va con indicativo, *dopo che è partito*. El congiuntivo se oye "
        "por contagio de *prima che*, pero la norma lo desaconseja.",
        goodAlt=["è partita"]),
    dict(id="m3-29-12", type="translate", topic="congiuntivo passato", level="B2", w=29, prompt=TR,
         stem="Puede ser que hayan cerrado la ruta por la nieve.",
         answer="Può darsi che abbiano chiuso la strada per la neve",
         alt=["Può darsi che abbiano chiuso la strada a causa della neve",
              "È possibile che abbiano chiuso la strada per la neve",
              "È possibile che abbiano chiuso la strada a causa della neve",
              "Può darsi che abbiano chiuso l'autostrada per la neve"],
         note="*può darsi che* (puede ser que) pide congiuntivo; el cierre ya ocurrió: *abbiano chiuso*. "
              "La «ruta» rioplatense es *la strada* (o *l'autostrada*)."),

    # ================= Settimana 32: Concordanza dei tempi =================
    dict(id="m3-32-01", type="translate", topic="concordanza dei tempi", level="B2", w=32, prompt=TR,
         stem="Creía que ya habías terminado.",
         answer="Credevo che avessi già finito",
         alt=["Credevo che tu avessi già finito",
              "Pensavo che avessi già finito",
              "Pensavo che tu avessi già finito",
              "Credevo che avessi già terminato",
              "Pensavo che avessi già terminato"],
         note="Principal en pasado y acción anterior: congiuntivo trapassato, *avessi finito*. "
              "Es el «habías terminado» del castellano."),
    dict(id="m3-32-02", type="translate", topic="concordanza dei tempi", level="B2", w=32, prompt=TR,
         stem="Estaba seguro de que ella iba a llegar tarde.",
         answer="Ero sicuro che sarebbe arrivata tardi",
         alt=["Ero sicuro che lei sarebbe arrivata tardi",
              "Ero sicura che sarebbe arrivata tardi",
              "Ero sicura che lei sarebbe arrivata tardi",
              "Ero certo che sarebbe arrivata tardi",
              "Ero sicuro che sarebbe arrivata in ritardo"],
         note="Futuro visto desde el pasado: condizionale passato, *sarebbe arrivata*. "
              "«Arriverebbe» sería el calco del «llegaría» y está mal."),
    dict(id="m3-32-03", type="translate", topic="concordanza dei tempi", level="B2", w=32, prompt=TR,
         stem="Me gustaría que vinieras a cenar el sábado.",
         answer="Mi piacerebbe che tu venissi a cena sabato",
         alt=["Mi piacerebbe che venissi a cena sabato",
              "Vorrei che tu venissi a cena sabato",
              "Vorrei che venissi a cena sabato",
              "Mi piacerebbe che tu venissi a cena sabato prossimo",
              "Vorrei che tu venissi a cena sabato prossimo",
              "Mi piacerebbe che tu venissi a cenare sabato"],
         note="Con el principal en condizionale (*vorrei*, *mi piacerebbe*), lo simultáneo o posterior va en "
              "congiuntivo imperfetto: *che tu venissi*."),
    dict(id="m3-32-04", type="translate", topic="concordanza dei tempi", level="B2", w=32, prompt=TR,
         stem="Era importante que todos supieran la verdad.",
         answer="Era importante che tutti sapessero la verità",
         alt=["Era importante che tutti conoscessero la verità"],
         note="*era importante che* pide congiuntivo; principal en pasado y acción simultánea: imperfetto, "
              "*sapessero*."),
    dict(id="m3-32-05", type="translate", topic="concordanza dei tempi", level="B2", w=32, prompt=TR,
         stem="No sabía que se habían mudado.",
         answer="Non sapevo che si fossero trasferiti",
         alt=["Non sapevo che si erano trasferiti",
              "Non sapevo che si fossero trasferite",
              "Non sapevo che si erano trasferite",
              "Non sapevo che avessero traslocato",
              "Non sapevo che avevano traslocato"],
         note="Principal en pasado y acción anterior: trapassato. Tras *non sapevo che* valen el congiuntivo "
              "(*si fossero trasferiti*) y el indicativo (*si erano trasferiti*)."),
    dict(id="m3-32-06", type="typed", topic="concordanza dei tempi", level="B2", w=32, prompt=P32,
         stem="Penso che Marco abbia ragione. → Pensavo che…",
         answer="Pensavo che Marco avesse ragione",
         note="Al pasar el principal al pasado, lo simultáneo pasa al congiuntivo imperfetto: "
              "*abbia ragione → avesse ragione*."),
    dict(id="m3-32-07", type="typed", topic="concordanza dei tempi", level="B2", w=32, prompt=P32,
         stem="So che verrai. → Sapevo che…",
         answer="Sapevo che saresti venuto",
         alt=["Sapevo che saresti venuta"],
         note="El futuro, visto desde un principal en pasado, se vuelve condizionale passato: "
              "*verrai → saresti venuto*."),
    dict(id="m3-32-08", type="typed", topic="concordanza dei tempi", level="B2", w=32, prompt=P32,
         stem="Credo che sia uscita alle otto. → Credevo che…",
         answer="Credevo che fosse uscita alle otto",
         note="Principal en pasado y acción anterior: congiuntivo trapassato. El auxiliar *essere* pasa a "
              "*fosse* y el participio sigue concordado: *fosse uscita*."),
    dict(id="m3-32-09", type="typed", topic="concordanza dei tempi", level="B2", w=32, prompt=P32,
         stem="Penso: «Ho sbagliato strada». → Penso di…",
         answer="Penso di aver sbagliato strada",
         alt=["Penso di avere sbagliato strada"],
         note="Con el mismo sujeto no va *che*: *di* + infinitivo, y si la acción es anterior, infinitivo "
              "compuesto: *di aver sbagliato*."),
    _fx("m3-32-10", 32, "concordanza dei tempi", "B2", "tempo_verbale",
        "Credevo che Luca sia già partito.", "sia", "fosse",
        "Principal en pasado (*credevo*) y acción anterior: congiuntivo trapassato, *fosse già partito*. "
        "*sia partito* va con un principal en presente."),
    _fx("m3-32-11", 32, "concordanza dei tempi", "B2", "congiuntivo",
        "Vorrei che tu vieni con noi al mare.", "vieni", "venissi",
        "*vorrei che* pide congiuntivo, y con el principal en condizionale va el imperfetto: "
        "*vorrei che tu venissi*. «Vieni» es indicativo."),

    # ================= Settimana 33: Periodo ipotetico =================
    dict(id="m3-33-01", type="translate", topic="periodo ipotetico", level="B2", w=33, prompt=TR,
         stem="Si yo fuera vos, no aceptaría ese trabajo.",
         answer="Se fossi in te, non accetterei quel lavoro",
         alt=["Se io fossi in te, non accetterei quel lavoro",
              "Al posto tuo, non accetterei quel lavoro",
              "Se fossi al posto tuo, non accetterei quel lavoro",
              "Se fossi in te, quel lavoro non lo accetterei"],
         note="«Si yo fuera vos» se dice *se fossi in te* (o *al posto tuo*). Tipo II: congiuntivo imperfetto "
              "con el *se*, condizionale en la otra parte."),
    dict(id="m3-33-02", type="translate", topic="periodo ipotetico", level="B2", w=33, prompt=TR,
         stem="Si hubiera salido antes, no habría perdido el avión.",
         answer="Se fossi uscito prima, non avrei perso l'aereo",
         alt=["Se fossi uscita prima, non avrei perso l'aereo",
              "Se fossi partito prima, non avrei perso l'aereo",
              "Se fossi partita prima, non avrei perso l'aereo",
              "Se io fossi uscito prima, non avrei perso l'aereo"],
         note="Tipo III, imposible: congiuntivo trapassato (*fossi uscito*) + condizionale passato "
              "(*avrei perso*). *uscire* va con *essere*."),
    dict(id="m3-33-03", type="translate", topic="periodo ipotetico", level="B2", w=33, prompt=TR,
         stem="Si mañana hace buen tiempo, vamos a la playa.",
         answer="Se domani fa bel tempo, andiamo al mare",
         alt=["Se domani fa bel tempo, andiamo in spiaggia",
              "Se domani farà bel tempo, andremo al mare",
              "Se domani farà bel tempo, andremo in spiaggia",
              "Se domani c'è bel tempo, andiamo al mare",
              "Se domani fa bel tempo, andremo al mare"],
         note="Tipo I, real: indicativo en las dos partes, presente o futuro. Ir a la playa es *andare al mare* "
              "(o *in spiaggia*)."),
    dict(id="m3-33-04", type="translate", topic="periodo ipotetico", level="B2", w=33, prompt=TR,
         stem="Si hubieras estudiado medicina, ahora serías médico.",
         answer="Se avessi studiato medicina, ora saresti medico",
         alt=["Se avessi studiato medicina, adesso saresti medico",
              "Se avessi studiato medicina, ora saresti un medico",
              "Se avessi studiato medicina, adesso saresti un medico",
              "Se tu avessi studiato medicina, ora saresti medico",
              "Se avessi studiato medicina, ora faresti il medico"],
         note="Mixto: condición pasada (congiuntivo trapassato, *avessi studiato*) y consecuencia presente "
              "(condizionale presente, *saresti*)."),
    dict(id="m3-33-05", type="translate", topic="periodo ipotetico", level="B2", w=33, prompt=TR,
         stem="Si tuviera más tiempo, aprendería a tocar la guitarra.",
         answer="Se avessi più tempo, imparerei a suonare la chitarra",
         alt=["Se io avessi più tempo, imparerei a suonare la chitarra",
              "Imparerei a suonare la chitarra se avessi più tempo"],
         note="Tipo II: *se* + congiuntivo imperfetto (*avessi*) y condizionale (*imparerei*). "
              "Tocar un instrumento es *suonare*, no «toccare»."),
    dict(id="m3-33-06", type="translate", topic="periodo ipotetico", level="B2", w=33, prompt=TR,
         stem="No sé si mi hermano estaría de acuerdo.",
         answer="Non so se mio fratello sarebbe d'accordo",
         note="Ojo: este *se* no pone una condición, es el «si» de una pregunta indirecta. Por eso el "
              "condizionale está bien: *non so se sarebbe d'accordo*. La trampa está en el *se* hipotético."),
    dict(id="m3-33-07", type="typed", topic="periodo ipotetico", level="B2", w=33, prompt=P33,
         stem="Non ho soldi, quindi non viaggio. → Se…",
         answer="Se avessi soldi, viaggerei",
         alt=["Se avessi i soldi, viaggerei",
              "Se avessi dei soldi, viaggerei",
              "Se avessi soldi, viaggerei di più"],
         note="Hecho real negativo → hipótesis del tipo II: *se* + congiuntivo imperfetto (*avessi*) y "
              "condizionale presente (*viaggerei*)."),
    dict(id="m3-33-08", type="typed", topic="periodo ipotetico", level="B2", w=33, prompt=P33,
         stem="Non mi hai avvisato, così non sono venuto. → Se…",
         answer="Se mi avessi avvisato, sarei venuto",
         alt=["Se tu mi avessi avvisato, sarei venuto",
              "Se mi avessi avvisato, sarei venuta"],
         note="Pasado que ya no se puede cambiar → tipo III: congiuntivo trapassato (*avessi avvisato*) + "
              "condizionale passato (*sarei venuto*, con *essere*)."),
    dict(id="m3-33-09", type="typed", topic="periodo ipotetico", level="B2", w=33, prompt=P33,
         stem="Non è piovuto, così abbiamo fatto la gita. → Se…",
         answer="Se fosse piovuto, non avremmo fatto la gita",
         alt=["Se avesse piovuto, non avremmo fatto la gita"],
         note="Tipo III: *se fosse piovuto* + *non avremmo fatto*. *piovere* admite los dos auxiliares: "
              "*fosse piovuto* o *avesse piovuto*."),
    _fx("m3-33-10", 33, "periodo ipotetico", "B2", "periodo_ipotetico",
        "Se lo saprei, te lo direi.", "saprei", "sapessi",
        "Detrás del *se* que pone una condición va congiuntivo imperfetto: *se lo sapessi*. "
        "El condizionale queda en la otra parte: *te lo direi*."),
    _fx("m3-33-11", 33, "periodo ipotetico", "B2", "periodo_ipotetico",
        "Se avrebbe studiato, avrebbe superato l'esame.", "avrebbe studiato", "avesse studiato",
        "Tipo III: con el *se*, congiuntivo trapassato (*avesse studiato*); el condizionale passato "
        "va en la consecuencia (*avrebbe superato*)."),
    _fx("m3-33-12", 33, "periodo ipotetico", "B2", "condizionale",
        "Se avessi più tempo, venissi a trovarti.", "venissi", "verrei",
        "En el tipo II el congiuntivo va con el *se* y la consecuencia lleva condizionale: *se avessi più tempo, verrei*. "
        "Corregir de más también es un error."),

    # ================= Settimana 37: Passato remoto =================
    dict(id="m3-37-01", type="translate", topic="passato remoto", level="B2", w=37, prompt=TR,
         stem="Leonardo pintó la Última Cena en Milán.",
         answer="Leonardo dipinse l'Ultima Cena a Milano",
         alt=["Leonardo da Vinci dipinse l'Ultima Cena a Milano",
              "Leonardo dipinse il Cenacolo a Milano",
              "A Milano Leonardo dipinse l'Ultima Cena"],
         note="Hecho histórico cerrado: passato remoto. *dipingere* sigue el patrón 1-3-6: *dipinsi, dipinse, "
              "dipinsero*."),
    dict(id="m3-37-02", type="translate", topic="passato remoto", level="B2", w=37, prompt=TR,
         stem="Los romanos construyeron muchos puentes.",
         answer="I romani costruirono molti ponti",
         alt=["I Romani costruirono molti ponti",
              "Gli antichi romani costruirono molti ponti",
              "I romani costruirono tanti ponti"],
         note="*costruire* es regular en *-ire*: *costruirono*. En un texto escrito sobre historia antigua, "
              "lo normal es el passato remoto."),
    dict(id="m3-37-03", type="translate", topic="passato remoto", level="B2", w=37, prompt=TR,
         stem="Mi abuelo nació en Sicilia y vino a la Argentina en 1950.",
         answer="Mio nonno nacque in Sicilia e venne in Argentina nel 1950",
         alt=["Mio nonno nacque in Sicilia e arrivò in Argentina nel 1950",
              "Mio nonno nacque in Sicilia e emigrò in Argentina nel 1950",
              "Mio nonno nacque in Sicilia ed emigrò in Argentina nel 1950"],
         note="Dos irregulares del patrón 1-3-6: *nascere → nacque*, *venire → venne*. "
              "Con países, *in Argentina*, sin artículo; con años, *nel 1950*."),
    dict(id="m3-37-04", type="translate", topic="passato remoto", level="B2", w=37, prompt=TR,
         stem="Esa noche nadie durmió.",
         answer="Quella notte nessuno dormì",
         alt=["Nessuno dormì quella notte"],
         note="Verbo regular en *-ire*: *dormì*, con tilde. Sin tilde, *dormi* es «dormís» o «dormí» (imperativo)."),
    dict(id="m3-37-05", type="translate", topic="passato remoto", level="B2", w=37, prompt=TR,
         stem="Apenas lo supo, llamó a su madre.",
         answer="Appena lo seppe, chiamò sua madre",
         alt=["Non appena lo seppe, chiamò sua madre",
              "Appena lo seppe, telefonò a sua madre",
              "Non appena lo seppe, telefonò a sua madre"],
         note="*sapere* es irregular: *seppi, seppe, seppero*. *chiamare* lleva objeto directo (*chiamò sua "
              "madre*); *telefonare* lleva *a*."),
    dict(id="m3-37-06", type="typed", topic="passato remoto", level="B2", w=37, prompt=P37,
         stem="Nel 1969 l'uomo è arrivato sulla Luna.",
         answer="Nel 1969 l'uomo arrivò sulla Luna",
         note="Regular en *-are*: la tercera persona termina en *-ò*, con tilde: *arrivò*. "
              "El auxiliar desaparece: el passato remoto es una sola palabra."),
    dict(id="m3-37-07", type="typed", topic="passato remoto", level="B2", w=37, prompt=P37,
         stem="I miei bisnonni hanno avuto sette figli.",
         answer="I miei bisnonni ebbero sette figli",
         note="*avere* es irregular: *ebbi, avesti, ebbe, avemmo, aveste, ebbero*. "
              "Ojo con la doble *b*."),
    dict(id="m3-37-08", type="typed", topic="passato remoto", level="B2", w=37, prompt=P37,
         stem="Abbiamo messo tutto in valigia e siamo partiti.",
         answer="Mettemmo tutto in valigia e partimmo",
         note="En la primera del plural casi todos son regulares (salvo *essere*: *fummo*): *mettemmo*, *partimmo*. "
              "Lo irregular de *mettere* está en *misi, mise, misero*."),
    dict(id="m3-37-09", type="typed", topic="passato remoto", level="B2", w=37, prompt=P37,
         stem="Quel giorno ho letto la lettera e ho capito tutto.",
         answer="Quel giorno lessi la lettera e capii tutto",
         note="*leggere* cambia en *io*: *lessi*. *capire* es regular: *capii*, con dos *i*."),
    _fx("m3-37-10", 37, "passato remoto", "B2", "accento",
        "Il re parlo a lungo davanti al popolo.", "parlo", "parlò",
        "Sin tilde, *parlo* es presente («hablo»). La tercera persona del passato remoto lleva el acento "
        "en la última: *parlò*."),
    _fx("m3-37-11", 37, "passato remoto", "B2", "irregolare",
        "Mia nonna nascé in un piccolo paese di montagna.", "nascé", "nacque",
        "*nascere* es irregular en el passato remoto: *nacqui, nacque, nacquero*. «Nascé» no existe."),
    _fx("m3-37-12", 37, "passato remoto", "B2", "irregolare",
        "Gli invitati veniro tardi e se ne andarono presto.", "veniro", "vennero",
        "*venire* sigue el patrón 1-3-6 con doble *n*: *venni, venne, vennero*."),

    # ================= Settimana 38: Discorso indiretto =================
    dict(id="m3-38-01", type="translate", topic="discorso indiretto", level="B2", w=38, prompt=TR,
         stem="Me dijo que me iba a esperar en la estación.",
         answer="Mi ha detto che mi avrebbe aspettato alla stazione",
         alt=["Mi ha detto che mi avrebbe aspettata alla stazione",
              "Mi ha detto che mi avrebbe aspettato in stazione",
              "Mi ha detto che mi avrebbe aspettata in stazione",
              "Mi disse che mi avrebbe aspettato alla stazione",
              "Mi disse che mi avrebbe aspettato in stazione"],
         note="Lo que era futuro para el que hablaba, reportado en pasado, va en condizionale passato: "
              "*mi avrebbe aspettato*."),
    dict(id="m3-38-02", type="translate", topic="discorso indiretto", level="B2", w=38, prompt=TR,
         stem="Le pregunté a Pablo dónde vivía.",
         answer="Ho chiesto a Pablo dove abitasse",
         alt=["Ho chiesto a Pablo dove vivesse",
              "Ho chiesto a Pablo dove abitava",
              "Ho chiesto a Pablo dove viveva",
              "Chiesi a Pablo dove abitasse",
              "Chiesi a Pablo dove vivesse"],
         note="Pregunta indirecta con principal en pasado: el registro cuidado pide congiuntivo imperfetto "
              "(*dove abitasse*); en el habla vale el indicativo (*dove abitava*)."),
    dict(id="m3-38-03", type="translate", topic="discorso indiretto", level="B2", w=38, prompt=TR,
         stem="Nos pidió que no hiciéramos ruido.",
         answer="Ci ha chiesto di non fare rumore",
         alt=["Ci chiese di non fare rumore",
              "Ci ha chiesto che non facessimo rumore",
              "Ci chiese che non facessimo rumore",
              "Ci ha pregato di non fare rumore"],
         note="Una orden o un pedido reportado pasa a *di* + infinitivo: *ci ha chiesto di non fare rumore*. "
              "Más formal: *che non facessimo*."),
    dict(id="m3-38-04", type="translate", topic="discorso indiretto", level="B2", w=38, prompt=TR,
         stem="Dijo que el día anterior había estado enfermo.",
         answer="Ha detto che il giorno prima era stato male",
         alt=["Ha detto che il giorno prima era stato malato",
              "Disse che il giorno prima era stato male",
              "Disse che il giorno prima era stato malato",
              "Ha detto che il giorno prima stava male",
              "Ha detto che era stato male il giorno prima"],
         note="*ieri* pasa a *il giorno prima*, y el pasado del que hablaba retrocede al trapassato: "
              "*era stato male*."),
    dict(id="m3-38-05", type="translate", topic="discorso indiretto", level="B2", w=38, prompt=TR,
         stem="Me preguntó si quería ir al cine con ella.",
         answer="Mi ha chiesto se volevo andare al cinema con lei",
         alt=["Mi ha chiesto se volessi andare al cinema con lei",
              "Mi chiese se volevo andare al cinema con lei",
              "Mi chiese se volessi andare al cinema con lei"],
         note="La pregunta de sí o no se introduce con *se*. Con el principal en pasado, el presente "
              "pasa al imperfetto: *volevo* (o, más cuidado, *volessi*)."),
    dict(id="m3-38-06", type="typed", topic="discorso indiretto", level="B2", w=38, prompt=P38,
         stem="Marco: «Domani vado a Roma». → Marco ha detto che…",
         answer="Marco ha detto che il giorno dopo sarebbe andato a Roma",
         alt=["Marco ha detto che sarebbe andato a Roma il giorno dopo",
              "Marco ha detto che l'indomani sarebbe andato a Roma",
              "Marco ha detto che il giorno dopo andava a Roma",
              "Marco ha detto che sarebbe andato a Roma il giorno seguente"],
         note="Dos cambios: *domani → il giorno dopo* y el presente con valor de futuro → condizionale "
              "passato (*sarebbe andato*). En el habla también se oye *andava*."),
    dict(id="m3-38-07", type="typed", topic="discorso indiretto", level="B2", w=38, prompt=P38,
         stem="Lucia: «Ieri ho visto un film bellissimo». → Lucia ha detto che…",
         answer="Lucia ha detto che il giorno prima aveva visto un film bellissimo",
         alt=["Lucia ha detto che aveva visto un film bellissimo il giorno prima"],
         note="*ieri → il giorno prima*, y el passato prossimo retrocede al trapassato: *ho visto → aveva visto*."),
    dict(id="m3-38-08", type="typed", topic="discorso indiretto", level="B2", w=38, prompt=P38,
         stem="Il medico: «Bevi molta acqua!» → Il medico mi ha detto…",
         answer="Il medico mi ha detto di bere molta acqua",
         alt=["Il medico mi ha detto che bevessi molta acqua",
              "Il medico mi ha detto di bere tanta acqua"],
         note="El imperativo pasa a *di* + infinitivo: *bevi → di bere*. La versión con *che* + congiuntivo "
              "imperfetto (*che bevessi*) es más formal."),
    dict(id="m3-38-09", type="typed", topic="discorso indiretto", level="B2", w=38, prompt=P38,
         stem="Anna: «Questa casa è nostra». → Anna ha detto che…",
         answer="Anna ha detto che quella casa era loro",
         alt=["Anna ha detto che quella casa era la loro"],
         note="Cambian tres cosas: *questa → quella*, *è → era* y el posesivo de la persona: *nostra → loro*."),
    _fx("m3-38-10", 38, "discorso indiretto", "B2", "condizionale",
        "Mi ha detto che arriverà il giorno dopo.", "arriverà", "sarebbe arrivato",
        "Si se reporta en pasado, el futuro del que hablaba pasa a condizionale passato: *sarebbe arrivato*. "
        "*il giorno dopo* ya muestra que el punto de vista cambió.",
        goodAlt=["sarebbe arrivata"]),
    _fx("m3-38-11", 38, "discorso indiretto", "B2", "tempo_verbale",
        "Mi ha chiesto se sono libero quella sera.", "sono", "ero",
        "Con el principal en pasado, el presente de la pregunta retrocede: *se ero libero*, o en registro "
        "cuidado *se fossi libero*.",
        goodAlt=["fossi"]),
    _fx("m3-38-12", 38, "discorso indiretto", "B2", "pronome",
        "Paolo mi ha detto di aspettarmi alla fermata.", "aspettarmi", "aspettarlo",
        "Paolo dijo «Aspettami!»: ese *mi* es Paolo. Al reportarlo, la persona cambia: *mi ha detto di "
        "aspettarlo*, con el pronombre pegado al infinitivo."),
]
