# -*- coding: utf-8 -*-
"""Mejoras estructurales 2, Stagione 3: semanas 31 (condizionale passato)
y 36 (si passivante e si impersonale). Ejercicios que cierran el desfase
con la lección: usos 2 y 3, modal + essere, si con pronombres y compuestos."""

CE = "Elegí la forma correcta."
TR = "Traducí al italiano."
VA = "Trova l'errore: tocá la palabra que está mal y corregila."
CCP = "Completá con el condizionale passato del verbo entre paréntesis."

ITEMS = [
    # ============ Settimana 31: Condizionale passato ============
    dict(id="mj-31-01", type="choice", topic="condizionale passato", level="B2", w=31,
         prompt="Elegí la forma que presenta la noticia como no confirmada.",
         stem="Secondo il giornale, il ministro ___ ieri sera.",
         options=["si sarebbe dimesso", "si avrebbe dimesso", "sarebbe dimettersi"],
         answer="si sarebbe dimesso",
         note="Dimettersi es reflexivo: va con essere. El «habría» periodístico es el condizionale passato."),
    dict(id="mj-31-02", type="cloze", topic="condizionale passato", level="B2", w=31,
         prompt=CCP, stem="Secondo alcuni testimoni, i ladri ___ (fuggire) in moto.",
         answer="sarebbero fuggiti",
         note="Fuggire va con essere y el participio concuerda: i ladri → fuggiti. Noticia sin confirmar."),
    dict(id="mj-31-03", type="cloze", topic="condizionale passato", level="B2", w=31,
         prompt=CCP, stem="Stando alla polizia, il sospettato ___ (rubare) tre auto.",
         answer="avrebbe rubato",
         note="Rubare va con avere. Con «stando a» o «secondo» el hecho queda sin garantizar."),
    dict(id="mj-31-04", type="translate", topic="condizionale passato", level="B2", w=31,
         prompt=TR, stem="Según el diario, el presidente habría llegado ayer.",
         answer="Secondo il giornale, il presidente sarebbe arrivato ieri",
         alt=["Secondo il giornale il presidente sarebbe arrivato ieri",
              "Secondo il quotidiano, il presidente sarebbe arrivato ieri",
              "Stando al giornale, il presidente sarebbe arrivato ieri",
              "Il presidente sarebbe arrivato ieri, secondo il giornale",
              "Il presidente sarebbe arrivato ieri secondo il giornale"],
         note="El «habría» de la prensa = condizionale passato; arrivare con essere."),
    dict(id="mj-31-05", type="cloze", topic="condizionale passato", level="B2", w=31,
         prompt=CCP, stem="Al posto tuo, ieri non ___ (accettare) quella proposta.",
         answer="avrei accettato",
         note="Consejo tardío: «en tu lugar, ayer no la habría aceptado» = avrei accettato."),
    dict(id="mj-31-06", type="typed", topic="condizionale passato", level="B2", w=31,
         prompt=TR, stem="Tendrías que haberme llamado.",
         answer="Avresti dovuto chiamarmi",
         alt=["Avresti dovuto telefonarmi", "Mi avresti dovuto chiamare", "Mi avresti dovuto telefonare"],
         note="Reproche a otro: avresti dovuto + infinitivo. Con el pronombre pegado (chiamarmi) o delante del modal (mi avresti dovuto chiamare)."),
    dict(id="mj-31-07", type="choice", topic="condizionale passato", level="B2", w=31,
         prompt=CE, stem="Ieri Laura ___ partire alle sette, ma è rimasta a letto.",
         options=["sarebbe dovuta", "sarebbe dovuti", "sarebbero dovuta"],
         answer="sarebbe dovuta",
         note="Modal + partire: auxiliar essere y el participio concuerda con el sujeto (Laura → dovuta)."),
    dict(id="mj-31-08", type="cloze", topic="condizionale passato", level="B2", w=31,
         prompt=CCP, stem="Noi ___ (dovere) uscire prima di mezzogiorno.",
         answer="saremmo dovuti",
         alt=["avremmo dovuto", "saremmo dovute"],
         note="Con dovere + uscire, lo más cuidado es essere (saremmo dovuti uscire); avere también se acepta."),
    dict(id="mj-31-09", type="translate", topic="condizionale passato", level="B2", w=31,
         prompt=TR, stem="Debería habértelo dicho.",
         answer="Avrei dovuto dirtelo",
         alt=["Te lo avrei dovuto dire", "Avrei dovuto dirlo a te"],
         note="Arrepentimiento propio: avrei dovuto + infinitivo. Los pronombres se pegan al infinitivo (dirtelo) o van delante del modal."),
    dict(id="mj-31-10", type="translate", topic="condizionale passato", level="B2", w=31,
         prompt=TR, stem="Tendría que haberme levantado antes.",
         answer="Avrei dovuto alzarmi prima",
         alt=["Mi sarei dovuto alzare prima", "Sarei dovuto alzarmi prima"],
         note="Con el pronombre pegado, avere (avrei dovuto alzarmi); con el pronombre delante del modal, essere (mi sarei dovuto alzare)."),
    dict(id="mj-31-11", type="fixerr", topic="condizionale passato", level="B2", w=31, prompt=VA,
         cat="ausiliare", stem="Ieri avrei venuto volentieri, ma lavoravo.",
         bad="avrei venuto", good="sarei venuto",
         answer="Ieri sarei venuto volentieri, ma lavoravo.",
         note="Venire va con essere también en el condizionale passato: sarei venuto."),
    dict(id="mj-31-12", type="fixerr", topic="condizionale passato", level="B2", w=31, prompt=VA,
         cat="condizionale", stem="Mi ha promesso che verrebbe presto.",
         bad="verrebbe", good="sarebbe venuto",
         answer="Mi ha promesso che sarebbe venuto presto.",
         note="Futuro visto desde el pasado: condizionale passato, no el simple (calco del castellano «vendría»)."),
    dict(id="mj-31-13", type="cloze", topic="condizionale passato", level="B2", w=31,
         prompt="Completá con el condizionale passato reflexivo (incluí el pronombre).",
         stem="Al posto mio, tu ___ (informarsi) prima di firmare.",
         answer="ti saresti informato", alt=["ti saresti informata"],
         note="Los reflexivos van con essere: ti saresti informato/a."),
    dict(id="mj-31-14", type="translate", topic="condizionale passato", level="B2", w=31,
         prompt=TR, stem="Yo sabía que ibas a ganar.",
         answer="Sapevo che avresti vinto",
         alt=["Sapevo che tu avresti vinto"],
         note="Futuro en el pasado: sapevo che + condizionale passato (avresti vinto)."),

    # ============ Settimana 36: Si passivante e si impersonale ============
    dict(id="mj-36-01", type="choice", topic="si passivante", level="B2", w=36, prompt=CE,
         stem="Il caffè? ___ beve al banco, in piedi.",
         options=["Lo si", "Si lo", "Ci lo"], answer="Lo si",
         note="Los pronombres lo, la, li, le van antes de si: lo si beve."),
    dict(id="mj-36-03", type="cloze", topic="si passivante", level="B2", w=36,
         prompt="Completá con si + ne y el passato prossimo de parlare.",
         stem="Di quel film ___ molto.", answer="se n'è parlato",
         alt=["se ne è parlato"],
         note="Compuesto impersonal: se ne + è + participio, sin concordancia."),
    dict(id="mj-36-04", type="cloze", topic="si passivante", level="B2", w=36,
         prompt="Completá con si + passato prossimo.",
         stem="Alla festa ___ (bere) troppi spritz.", answer="si sono bevuti",
         note="Passivante compuesto: essere + participio concordado con el objeto (spritz, masculino plural)."),
    dict(id="mj-36-05", type="cloze", topic="si passivante", level="B2", w=36,
         prompt="Completá con si + passato prossimo.",
         stem="Quest'anno ___ (vendere) moltissime case.", answer="si sono vendute",
         note="El participio concuerda con el objeto: case → vendute."),
    dict(id="mj-36-06", type="choice", topic="si impersonale", level="B2", w=36, prompt=CE,
         stem="Al carnevale di Venezia ci si è ___ molto.",
         options=["divertiti", "divertito", "divertite"], answer="divertiti",
         note="Ci si è + participio en masculino plural: el impersonal con reflexivo."),
    dict(id="mj-36-07", type="cloze", topic="si impersonale", level="B2", w=36,
         prompt="Completá con si + passato prossimo.",
         stem="Ieri sera in quel ristorante ___ (mangiare) benissimo.",
         answer="si è mangiato",
         note="Sin objeto: impersonal, essere + participio en singular."),
    dict(id="mj-36-08", type="cloze", topic="si passivante", level="B2", w=36,
         prompt="Completá con el presente del modal.",
         stem="Ogni mese si ___ (dovere) pulire le finestre.", answer="devono",
         note="Con un modal y objeto plural concuerda el modal: si devono pulire le finestre."),
    dict(id="mj-36-09", type="translate", topic="si passivante", level="B2", w=36,
         prompt=TR, stem="En este bar el café se toma de pie.",
         answer="In questo bar il caffè si beve in piedi",
         alt=["In questo bar il caffè lo si beve in piedi", "In questo bar si beve il caffè in piedi",
              "In questo bar il caffè si prende in piedi", "In questo bar si prende il caffè in piedi",
              "In questo bar il caffè lo si prende in piedi"],
         note="Si passivante con objeto singular (il caffè → si beve); con pronombre, lo si beve."),
    dict(id="mj-36-10", type="translate", topic="si impersonale", level="B2", w=36,
         prompt=TR, stem="En este pueblo uno no se aburre nunca.",
         answer="In questo paese non ci si annoia mai",
         alt=["In questo paesino non ci si annoia mai", "In questo posto non ci si annoia mai"],
         note="Reflexivo + impersonal = ci si: annoiarsi → ci si annoia."),
    dict(id="mj-36-11", type="translate", topic="si passivante", level="B2", w=36,
         prompt=TR, stem="Ayer se habló mucho de este tema.",
         answer="Ieri di questo tema se n'è parlato molto",
         alt=["Di questo tema se n'è parlato molto ieri", "Ieri di questo tema se ne è parlato molto",
              "Di questo tema se ne è parlato molto ieri",
              "Ieri di questo argomento se n'è parlato molto",
              "Di questo argomento se n'è parlato molto ieri",
              "Ieri si è parlato molto di questo tema", "Ieri si è parlato molto di questo argomento"],
         note="Parlare di + tema se retoma con ne: si + ne = se ne; compuesto se n'è parlato."),
    dict(id="mj-36-12", type="fixerr", topic="si passivante", level="B2", w=36, prompt=VA,
         cat="accordo", stem="Ieri si è mangiato troppi dolci.",
         bad="si è mangiato", good="si sono mangiati",
         answer="Ieri si sono mangiati troppi dolci.",
         note="Hay objeto plural (dolci): passivante compuesto, si sono mangiati."),
    dict(id="mj-36-13", type="fixerr", topic="si passivante", level="B2", w=36, prompt=VA,
         cat="pronome", stem="La cupola si la vede da lontano.",
         bad="si la", good="la si",
         answer="La cupola la si vede da lontano.",
         note="El pronombre va antes de si: la si vede."),
    dict(id="mj-36-14", type="choice", topic="si toscano", level="B2", w=36,
         prompt="Un amigo toscano dice «Domani si parte». ¿Qué equivale?",
         stem="Domani si parte.",
         options=["Domani partiamo.", "Domani parte.", "Domani si è partiti in molti."],
         answer="Domani partiamo.",
         note="En el habla toscana, si + tercera singular reemplaza a noi."),
]
