# -*- coding: utf-8 -*-
"""Mejoras estructurales, Stagione 1: semana 6 (stare + gerundio, no
diptongación, essere/stare, tenere/salire) y semana 9 (medios de transporte,
preposiciones articuladas con lugares, per / da / tra)."""

CE = "Elegí la forma correcta."
CL = "Completá con la forma correcta."
TR = "Traducí al italiano."
FX = "Trova l'errore: tocá la palabra que está mal y corregila."

ITEMS = [
    # ================= Settimana 6: Presente irregolare =================
    dict(id="mj-06-01", type="cloze", topic="stare + gerundio", level="A1", w=6, prompt=CL,
         stem="Adesso Marco ___ (leggere) il giornale.", answer="sta leggendo",
         note="Acción en curso: stare + gerundio. Leggere es -ere, entonces -endo: leggendo."),
    dict(id="mj-06-02", type="choice", topic="stare + gerundio", level="A1", w=6, prompt=CE,
         stem="Cosa ___ facendo, ragazzi?", options=["state", "siete", "avete"], answer="state",
         note="El auxiliar del gerundio es stare, no essere: voi state facendo."),
    dict(id="mj-06-03", type="cloze", topic="stare + gerundio", level="A1", w=6, prompt=CL,
         stem="Noi ___ (studiare) in biblioteca.", answer="stiamo studiando",
         note="stare en noi (stiamo) + gerundio en -ando: stiamo studiando."),
    dict(id="mj-06-04", type="translate", topic="stare + gerundio", level="A1", w=6, prompt=TR,
         stem="Estoy escribiendo un mensaje.", answer="Sto scrivendo un messaggio",
         alt=["Io sto scrivendo un messaggio", "Sto scrivendo un messaggio."],
         note="Sto + scrivendo (scrivere → -endo). El pronombre io se omite."),
    dict(id="mj-06-05", type="fixerr", topic="stare + gerundio", level="A1", w=6, prompt=FX, cat="stare_gerundio",
         stem="Sono mangiando una pizza.", bad="Sono mangiando", good="Sto mangiando",
         answer="Sto mangiando una pizza.",
         note="La acción en curso se forma con stare, no con essere: sto mangiando."),
    dict(id="mj-06-06", type="cloze", topic="stare + gerundio", level="A1", w=6, prompt=CL,
         stem="Stai ___ un caffè? (bere)", answer="bevendo",
         note="Gerundio irregular: sale de la raíz larga bevere → bevendo."),
    dict(id="mj-06-07", type="choice", topic="no diptongación", level="A1", w=6, prompt=CE,
         stem="Stasera non ___ venire.", options=["posso", "puosso", "poso"], answer="posso",
         note="El italiano no diptonga: posso, no «puedo». La doble s es parte de la forma."),
    dict(id="mj-06-08", type="fixerr", topic="no diptongación", level="A1", w=6, prompt=FX, cat="dittongo",
         stem="Io duermo poco la notte.", bad="duermo", good="dormo",
         answer="Io dormo poco la notte.",
         note="Calco del castellano «duermo»: en italiano la o queda entera, dormo."),
    dict(id="mj-06-09", type="choice", topic="essere o stare", level="A1", w=6, prompt=CE,
         stem="Oggi io ___ molto stanco.", options=["sono", "sto", "ho"], answer="sono",
         note="Estados y cualidades van con essere: sono stanco. Stare queda para la salud y quedarse."),
    dict(id="mj-06-10", type="cloze", topic="essere o stare", level="A1", w=6, prompt=CL,
         stem="Mia madre ___ bene, grazie.", answer="sta",
         note="Salud: stare, y en tercera persona es sta."),
    dict(id="mj-06-11", type="fixerr", topic="essere o stare", level="A1", w=6, prompt=FX, cat="essere_stare",
         stem="Marco sta contento perché domani è sabato.", bad="sta contento", good="è contento",
         answer="Marco è contento perché domani è sabato.",
         note="Contento es un estado de ánimo: va con essere, no con stare."),
    dict(id="mj-06-12", type="cloze", topic="tenere e salire", level="A1", w=6, prompt=CL,
         stem="Loro ___ (salire) sul treno delle otto.", answer="salgono",
         note="salire mete la g en io y loro: salgo, salgono."),
    dict(id="mj-06-13", type="choice", topic="venire", level="A1", w=6, prompt=CE,
         stem="I miei amici ___ da Napoli.", options=["vengono", "venono", "veniscono"], answer="vengono",
         note="venire tiene la g en io y loro: vengo, vengono."),
    dict(id="mj-06-14", type="cloze", topic="rimanere", level="A1", w=6, prompt=CL,
         stem="Stasera io ___ (rimanere) a casa.", answer="rimango", alt=["resto"],
         note="rimanere mete la g en io: rimango. Restare (resto) también vale."),

    # ================= Settimana 9: Preposizioni di base =================
    dict(id="mj-09-01", type="choice", topic="a piedi", level="A2", w=9, prompt=CE,
         stem="Vado a scuola ___.", options=["a piedi", "in piedi", "per piedi"], answer="a piedi",
         note="«A pie» es a piedi. In piedi significa «de pie»."),
    dict(id="mj-09-02", type="choice", topic="medios de transporte", level="A2", w=9, prompt=CE,
         stem="Andiamo al mare ___ macchina.", options=["in", "con", "nella"], answer="in",
         note="El medio en general va con in y sin artículo: in macchina."),
    dict(id="mj-09-03", type="cloze", topic="medios de transporte", level="A2", w=9, prompt=CL,
         stem="Sara viaggia sempre ___ aereo.", answer="in", alt=["con l'", "con l’"],
         note="in treno, in autobus, in aereo: in + medio, sin artículo."),
    dict(id="mj-09-04", type="translate", topic="medios de transporte", level="A2", w=9, prompt=TR,
         stem="Voy a la oficina en bici.", answer="Vado in ufficio in bici",
         alt=["Vado in ufficio in bicicletta", "Vado all'ufficio in bici", "Vado all'ufficio in bicicletta", "Io vado in ufficio in bici"],
         note="Lugar de todos los días: in ufficio; medio: in bici, sin artículo."),
    dict(id="mj-09-05", type="fixerr", topic="a piedi", level="A2", w=9, prompt=FX, cat="a_piedi",
         stem="Torno a casa in piedi.", bad="in piedi", good="a piedi",
         answer="Torno a casa a piedi.",
         note="Andando se dice a piedi. In piedi es la posición «de pie»."),
    dict(id="mj-09-06", type="fixerr", topic="medios de transporte", level="A2", w=9, prompt=FX, cat="con_articolo",
         stem="Arrivo con treno delle nove.", bad="con treno", good="con il treno",
         answer="Arrivo con il treno delle nove.",
         note="Con un tren concreto, con + artículo: con il treno delle nove. Sin especificar: in treno."),
    dict(id="mj-09-07", type="cloze", topic="preposizioni articolate", level="A2", w=9, prompt=CL,
         stem="Il taxi parte ___ (da + la) stazione centrale.", answer="dalla",
         note="da + la = dalla: la preposición y el artículo se funden."),
    dict(id="mj-09-08", type="choice", topic="preposizioni articolate", level="A2", w=9, prompt=CE,
         stem="Le chiavi sono ___ tavolo.", options=["sul", "su il", "sullo"], answer="sul",
         note="su + il = sul. Regla: tavolo lleva il, no lo."),
    dict(id="mj-09-09", type="cloze", topic="preposizioni articolate", level="A2", w=9, prompt=CL,
         stem="Mia sorella arriva ___ (da + l') aeroporto.", answer="dall'", alt=["dall’"],
         note="da + l' = dall': se funde y se apostrofa."),
    dict(id="mj-09-10", type="fixerr", topic="da + persona", level="A2", w=9, prompt=FX, cat="da_persona",
         stem="Oggi pomeriggio vado al medico.", bad="al medico", good="dal medico",
         answer="Oggi pomeriggio vado dal medico.",
         note="A lo de una persona se va con da: dal medico."),
    dict(id="mj-09-11", type="choice", topic="tra / fra", level="A2", w=9, prompt=CE,
         stem="La lezione finisce ___ un'ora.", options=["tra", "da", "per"], answer="tra",
         note="Tra / fra + tiempo = dentro de: tra un'ora."),
    dict(id="mj-09-12", type="cloze", topic="da quanto tempo", level="A2", w=9, prompt=CL,
         stem="___ quanto tempo abiti a Torino?", answer="Da",
         note="«¿Desde hace cuánto?» es da quanto tempo, con presente."),
    dict(id="mj-09-13", type="translate", topic="presente + da", level="A2", w=9, prompt=TR,
         stem="Estudio inglés desde hace tres años.", answer="Studio inglese da tre anni",
         alt=["Io studio inglese da tre anni"],
         note="Lo que empezó y sigue: presente + da + tiempo."),
    dict(id="mj-09-14", type="cloze", topic="per + durata", level="A2", w=9, prompt=CL,
         stem="Resto a Roma ___ una settimana, poi torno a casa.", answer="per",
         note="Per = duración con final: per una settimana."),
]
