# -*- coding: utf-8 -*-
"""Mejoras estructurales 2, stagione 4 (K=4): semanas 40 (causativo),
42 (verbi e preposizioni), 47 (numerali, misure e quantità),
49 (registro alto e coesione) y 51 (ripasso generale C1)."""

CE = "Elegí la forma correcta."
TR = "Traducí al italiano."
CL = "Completá."
FX = "Trova l'errore: tocá la palabra que está mal y corregila."


def _tr(id, topic, lv, w, stem, answer, note, alt=None, typed=False):
    d = dict(id=id, type="typed" if typed else "translate", topic=topic, level=lv, w=w,
             prompt=TR, stem=stem, answer=answer, note=note)
    if alt:
        d["alt"] = alt
    return d


ITEMS = [
    # ================= Settimana 40: Il causativo =================
    dict(id="mj-40-01", type="cloze", topic="causativo", level="B2", w=40,
         prompt="Reemplazá «la macchina» por un pronombre.",
         stem="Faccio riparare la macchina dal meccanico. → ___ faccio riparare dal meccanico.",
         answer="La", alt=["la"],
         note="El pronombre va delante de fare, no del infinitivo: la faccio riparare (jamás «faccio ripararla»)."),
    dict(id="mj-40-02", type="cloze", topic="causativo", level="C1", w=40,
         prompt="Reemplazá «la relazione» y «a Sara» por pronombres combinados.",
         stem="Il capo fa scrivere la relazione a Sara. → Il capo ___ fa scrivere.",
         answer="gliela", alt=["Gliela"],
         note="El infinitivo ya tiene objeto (la relazione), así que quien escribe pasa a indirecto: gli + la = gliela."),
    dict(id="mj-40-03", type="choice", topic="causativo", level="C1", w=40, prompt=CE,
         stem="I miei occhiali? ___ dall'ottico.",
         options=["Li ho fatti riparare", "Gli ho fatti riparare", "Ho fatti riparare li"],
         answer="Li ho fatti riparare",
         note="El pronombre va delante de avere y el participio de fare concuerda con él: li ho fatti riparare."),
    dict(id="mj-40-04", type="fixerr", topic="causativo", level="B2", w=40, prompt=FX, cat="posizione_pronome",
         stem="Domani faccio venirlo a casa mia.", bad="faccio venirlo", good="lo faccio venire",
         answer="Domani lo faccio venire a casa mia.",
         note="Con fare conjugado el pronombre va delante de fare: lo faccio venire. Solo se pega si fare es infinitivo o imperativo: farlo venire, fallo venire."),
    dict(id="mj-40-05", type="fixerr", topic="causativo", level="B2", w=40, prompt=FX, cat="preposizione",
         stem="Il capo ha fatto lavorare a Marco tutto il sabato.", bad="lavorare a Marco",
         good="lavorare Marco",
         answer="Il capo ha fatto lavorare Marco tutto il sabato.",
         note="Lavorare no tiene objeto: quien trabaja es objeto directo y no lleva a. La a aparece solo si el infinitivo ya tiene objeto (far leggere il libro a Marco)."),
    dict(id="mj-40-06", type="cloze", topic="causativo", level="B2", w=40,
         prompt="Completá con la preposición articulada.",
         stem="Si è fatto tagliare i capelli ___ parrucchiere di via Roma.",
         answer="dal",
         note="Con farsi + infinitivo, quien hace la acción va siempre con da: dal parrucchiere."),
    _tr("mj-40-07", "causativo", "C1", 40, "No lo dejaron entrar.", "Non l'hanno lasciato entrare.",
        "Lasciare + infinitivo intransitivo: lo, la, li, le delante del verbo conjugado.",
        alt=["Non lo hanno lasciato entrare.", "Non l'hanno lasciato entrare"]),
    _tr("mj-40-08", "causativo", "C1", 40, "Avisame apenas sepas algo.", "Fammi sapere appena sai qualcosa.",
        "Far sapere = avisar. Se dice fammi sapere; tras appena, el italiano usa presente o futuro.",
        alt=["Fammi sapere appena saprai qualcosa.", "Fammi sapere non appena sai qualcosa.",
             "Avvisami appena sai qualcosa.", "Avvisami appena saprai qualcosa.",
             "Avvisami non appena sai qualcosa.", "Avvisami non appena saprai qualcosa.",
             "Fammi sapere non appena saprai qualcosa.", "Fammi sapere appena sai qualcosa"], typed=True),
    dict(id="mj-40-09", type="cloze", topic="causativo", level="C1", w=40,
         prompt="Completá con el imperativo de fare y los pronombres (mostrámelas).",
         stem="Le foto delle vacanze? ___ vedere, dai!", answer="Fammele", alt=["fammele"],
         note="Imperativo informal: fa' + mi + le se pegan y mi pasa a me: fammele."),
    dict(id="mj-40-10", type="choice", topic="causativo", level="B2", w=40, prompt=CE,
         stem="Mio figlio ha quindici anni: di notte non ___ uscire da solo.",
         options=["lo lascio", "gli lascio", "ci lascio"], answer="lo lascio",
         note="Uscire no lleva objeto: quien sale es directo (lo lascio uscire), igual que con fare."),
    dict(id="mj-40-11", type="choice", topic="causativo", level="C1", w=40, prompt=CE,
         stem="Questi documenti sono urgenti: devo ___ firmare oggi al direttore.",
         options=["farli", "farlo", "far li"], answer="farli",
         note="Con un modal el pronombre se pega a far(e) o va delante del modal: devo farli firmare / li devo far firmare."),
    dict(id="mj-40-12", type="fixerr", topic="causativo", level="C1", w=40, prompt=FX, cat="participio_accordo",
         stem="Le mie scarpe? Le ho fatto riparare ieri.", bad="fatto", good="fatte",
         answer="Le mie scarpe? Le ho fatte riparare ieri.",
         note="El participio de fare concuerda con el pronombre directo que va delante: le ho fatte riparare."),
    dict(id="mj-40-13", type="cloze", topic="causativo", level="C1", w=40,
         prompt="Completá con la expresión fija en passato prossimo.",
         stem="Dopo la litigata Paolo non si è più ___.", answer="fatto vivo",
         alt=["fatto sentire", "fatto vedere"],
         note="Farsi vivo = dar señales de vida. Variantes: también se dice farsi sentire o farsi vedere."),

    # ================= Settimana 42: Verbi e preposizioni =================
    dict(id="mj-42-01", type="cloze", topic="verbi e preposizioni", level="C1", w=42,
         prompt="Completá con la preposición.",
         stem="Dopo mesi di dubbi si è finalmente deciso ___ partire.", answer="a",
         note="Decidersi a (por fin animarse a) lleva a, mientras decidere lleva di: ho deciso di partire."),
    dict(id="mj-42-02", type="choice", topic="verbi e preposizioni", level="B2", w=42,
         prompt="Elegí la forma que significa «terminó peleándose con todos».",
         stem="Alla fine ha finito ___ con tutti.",
         options=["per litigare", "di litigare", "a litigare"], answer="per litigare",
         note="Finire per + infinitivo = acabar haciendo algo. Contraste: finire di = terminar de hacerlo."),
    dict(id="mj-42-03", type="fixerr", topic="verbi e preposizioni", level="B2", w=42, prompt=FX, cat="preposizione",
         stem="Ho smesso a fumare l'anno scorso.", bad="a fumare", good="di fumare",
         answer="Ho smesso di fumare l'anno scorso.",
         note="Smettere lleva di: smettere di fumare. Cominciare, continuare y mettersi llevan a."),
    dict(id="mj-42-04", type="cloze", topic="verbi e preposizioni", level="B2", w=42,
         prompt="Completá con la preposición.",
         stem="Quest'estate penso ___ trasferirmi a Roma.", answer="di",
         note="Pensare di + infinitivo = pensar hacer algo. Con un nombre es pensare a: penso a te."),
    _tr("mj-42-05", "verbi e preposizioni", "B2", 42, "Me acostumbré a levantarme temprano.",
        "Mi sono abituato ad alzarmi presto.",
        "Abituarsi a + infinitivo; ad ante la vocal a. Reflexivo: essere.",
        alt=["Mi sono abituata ad alzarmi presto", "Mi sono abituato ad alzarmi presto",
             "Mi sono abituata ad alzarmi presto."]),
    dict(id="mj-42-06", type="fixerr", topic="verbi e preposizioni", level="B2", w=42, prompt=FX, cat="preposizione",
         stem="Stasera preferisco di restare a casa.", bad="di restare", good="restare",
         answer="Stasera preferisco restare a casa.",
         note="Preferire, como los modales, va directo con el infinitivo: preferisco restare."),
    dict(id="mj-42-07", type="choice", topic="mail formal", level="C1", w=42, prompt=CE,
         stem="Gentile dottoressa, ___ di confermare la Sua presenza entro lunedì.",
         options=["La prego", "La chiedo", "La rivolgo"], answer="La prego",
         note="Pregare lleva objeto directo (La prego di); chiedere, indirecto (Le chiedo di)."),
    dict(id="mj-42-08", type="cloze", topic="mail formal", level="C1", w=42,
         prompt="Completá con la preposición.",
         stem="Secondo il contratto, siamo tenuti ___ pagare la penale.", answer="a",
         note="Essere tenuto a + infinitivo = estar obligado a. Registro: es una fórmula formal y administrativa."),
    dict(id="mj-42-09", type="cloze", topic="mail formal", level="C1", w=42,
         prompt="Completá con la preposición.",
         stem="Mi riservo ___ valutare ulteriori azioni.", answer="di",
         note="Riservarsi di + infinitivo = reservarse el derecho de. Uso: fórmula de cierre de la carta formal."),
    dict(id="mj-42-10", type="cloze", topic="mail formal", level="C1", w=42,
         prompt="Completá con la preposición articulada.",
         stem="Per informazioni, si prega di rivolgersi ___ sportello numero cinque.",
         answer="allo",
         note="Rivolgersi a: a + lo = allo (sportello, con s + consonante)."),
    _tr("mj-42-11", "mail formal", "C1", 42,
        "Le ruego que me envíe el certificado antes del viernes.",
        "La prego di inviarmi il certificato entro venerdì.",
        "La prego di + infinitivo (pronombre directo) y el pronombre del infinitivo se pega: inviarmi.",
        alt=["La prego di mandarmi il certificato entro venerdì.",
             "La prego di inviarmi il certificato prima di venerdì.",
             "La prego di mandarmi il certificato prima di venerdì.",
             "La prego di volermi inviare il certificato entro venerdì.",], typed=True),
    _tr("mj-42-12", "mail formal", "C1", 42,
        "Adjunto encontrará el formulario completo; quedo a disposición para cualquier aclaración.",
        "In allegato trova il modulo compilato; resto a disposizione per qualsiasi chiarimento.",
        "In allegato = adjunto; resto a disposizione per + sustantivo cierra el mail.",
        alt=["In allegato troverà il modulo compilato; resto a disposizione per qualsiasi chiarimento.",
             "In allegato trova il modulo compilato; resto a disposizione per qualunque chiarimento.",
             "In allegato troverà il modulo compilato; resto a disposizione per qualunque chiarimento.",
             "In allegato trova il modulo compilato; resto a disposizione per ogni chiarimento.",
             "In allegato troverà il modulo compilato; resto a disposizione per ogni chiarimento.",
             "In allegato trova il modulo completo; resto a disposizione per qualsiasi chiarimento.",
             "In allegato troverà il modulo completo; resto a disposizione per qualsiasi chiarimento.",
             "Allego il modulo compilato; resto a disposizione per qualsiasi chiarimento.",
             "Allego il modulo compilato; resto a disposizione per qualunque chiarimento."], typed=True),
    dict(id="mj-42-13", type="fixerr", topic="mail formal", level="C1", w=42, prompt=FX, cat="preposizione",
         stem="Secondo il regolamento, siamo tenuti di comunicare ogni variazione.", bad="tenuti di",
         good="tenuti a",
         answer="Secondo il regolamento, siamo tenuti a comunicare ogni variazione.",
         note="Essere tenuto a + infinitivo. Di no."),
    dict(id="mj-42-14", type="fixerr", topic="mail formal", level="C1", w=42, prompt=FX, cat="pronome",
         stem="Con la presente Le prego di inviarmi copia del verbale.", bad="Le prego", good="La prego",
         answer="Con la presente La prego di inviarmi copia del verbale.",
         note="Pregare pide pronombre directo (La), no indirecto: La prego di."),

    # ================= Settimana 47: Numerali, misure e quantità =================
    dict(id="mj-47-01", type="choice", topic="numerali", level="B2", w=47, prompt=CE,
         stem="Il ___ maggio è la festa dei lavoratori.",
         options=["primo", "uno", "prima"], answer="primo",
         note="En las fechas solo el día uno es ordinal: il primo maggio, pero il due maggio."),
    dict(id="mj-47-02", type="cloze", topic="numerali", level="B2", w=47,
         prompt="Escribí el ordinal (23.ª).",
         stem="Marta è arrivata ___ alla maratona di Torino.", answer="ventitreesima",
         note="Desde el 11 se agrega -esimo al número; ventitré conserva la -tre: ventitreesima."),
    dict(id="mj-47-03", type="choice", topic="numerali", level="C1", w=47, prompt=CE,
         stem="In frigo ci sono ___ uova.",
         options=["delle", "dei", "del"], answer="delle",
         note="Uovo hace el plural femenino: le uova. Por eso el partitivo es delle uova."),
    dict(id="mj-47-04", type="choice", topic="numerali", level="B2", w=47, prompt=CE,
         stem="Ho invitato qualche ___ del corso.",
         options=["amico", "amici", "amiche"], answer="amico",
         note="Qualche va siempre con sustantivo singular, aunque el sentido sea plural."),
    dict(id="mj-47-05", type="cloze", topic="numerali", level="C1", w=47,
         prompt="Completá con la preposición articulada.",
         stem="Il tasso di disoccupazione è sceso dal 9 ___ 7 per cento.", answer="al",
         note="Passare / scendere da... a...: dal 9 al 7 per cento."),
    dict(id="mj-47-06", type="fixerr", topic="numerali", level="B2", w=47, prompt=FX, cat="preposizione",
         stem="C'erano una ventina persone in sala.", bad="ventina persone", good="ventina di persone",
         answer="C'erano una ventina di persone in sala.",
         note="Los colectivos aproximados (una ventina, una decina, un centinaio) piden di + sustantivo."),
    dict(id="mj-47-07", type="fixerr", topic="numerali", level="B2", w=47, prompt=FX, cat="accordo",
         stem="Abbiamo aspettato due ore e mezzo.", bad="e mezzo", good="e mezza",
         answer="Abbiamo aspettato due ore e mezza.",
         note="Después de e, mezzo concuerda con lo contado: due ore e mezza, pero un chilo e mezzo."),
    dict(id="mj-47-08", type="choice", topic="numerali", level="C1", w=47, prompt=CE,
         stem="Il prezzo è raddoppiato: oggi costa ___ del 2020.",
         options=["il doppio", "la doppia", "i doppi"], answer="il doppio",
         note="Il doppio, il triplo: múltiplos con artículo masculino."),
    dict(id="mj-47-09", type="choice", topic="numerali", level="C1", w=47, prompt=CE,
         stem="Nel 2023 il PIL è cresciuto ___ due punti percentuali.",
         options=["di", "al", "del"], answer="di",
         note="Di + cifra dice cuánto cambió (di due punti); al + porcentaje dice dónde se llegó (è sceso al 4%)."),
    _tr("mj-47-10", "numerali", "C1", 47, "Los precios subieron un 3,2% en un año.",
        "I prezzi sono aumentati del 3,2% in un anno.",
        "Aumentare del + porcentaje. Coma decimal y artículo contraído: del 3,2%.",
        alt=["I prezzi sono aumentati del 3,2 per cento in un anno.", "I prezzi sono saliti del 3,2% in un anno.",
             "I prezzi sono cresciuti del 3,2% in un anno.", "I prezzi sono saliti del 3,2 per cento in un anno.",
             "I prezzi sono cresciuti del 3,2 per cento in un anno.",
             "I prezzi sono aumentati del 3,2% nell'arco di un anno.",
             "I prezzi sono aumentati del 3,2% in un anno"], typed=True),
    _tr("mj-47-11", "numerali", "C1", 47, "Más de un tercio de las empresas cerró en 2020.",
        "Oltre un terzo delle imprese ha chiuso nel 2020.",
        "Oltre / più di + fracción; el sujeto es «un terzo delle imprese» y el verbo va en singular (el plural también se oye).",
        alt=["Oltre un terzo delle imprese hanno chiuso nel 2020.", "Più di un terzo delle imprese hanno chiuso nel 2020.",
             "Più di un terzo delle imprese ha chiuso nel 2020.", "Oltre un terzo delle imprese ha chiuso nel 2020",
             "Più di un terzo delle aziende ha chiuso nel 2020.", "Oltre un terzo delle aziende ha chiuso nel 2020."]),
    _tr("mj-47-12", "numerali", "C1", 47, "El desempleo pasó del 9 al 7 por ciento.",
        "La disoccupazione è passata dal 9 al 7 per cento.",
        "Passare da... a...; disoccupazione es femenino: è passata.",
        alt=["La disoccupazione è scesa dal 9 al 7 per cento.", "La disoccupazione è passata dal 9% al 7%.",
             "La disoccupazione è scesa dal 9% al 7%.", "Il tasso di disoccupazione è passato dal 9 al 7 per cento.",
             "Il tasso di disoccupazione è sceso dal 9 al 7 per cento."], typed=True),
    _tr("mj-47-13", "numerali", "C1", 47, "Vinieron unas veinte personas, pero la mitad se fue temprano.",
        "Sono venute una ventina di persone, ma metà se n'è andata presto.",
        "Una ventina di + plural; metà + verbo en singular, con el participio femenino singular.",
        alt=["Sono venute una ventina di persone, ma la metà se n'è andata presto.",
             "Sono venute circa venti persone, ma metà se n'è andata presto.",
             "Sono venute circa venti persone, ma la metà se n'è andata presto.",
             "È venuta una ventina di persone, ma metà se n'è andata presto.",
             "È venuta una ventina di persone, ma la metà se n'è andata presto.",
             "Sono venute una ventina di persone, ma metà è andata via presto.",
             "Sono venute una ventina di persone, ma metà se ne sono andate presto.",
             "Sono venute una ventina di persone, ma la metà se ne sono andate presto."], typed=True),
    _tr("mj-47-14", "numerali", "B2", 47, "Dame doscientos gramos de jamón y medio kilo de queso.",
        "Mi dai due etti di prosciutto e mezzo chilo di formaggio?",
        "En el mostrador se piden due etti (200 g) y mezzo chilo, con di.",
        alt=["Dammi due etti di prosciutto e mezzo chilo di formaggio.", "Mi dai due etti di prosciutto e mezzo chilo di formaggio",
             "Mi dà due etti di prosciutto e mezzo chilo di formaggio?", "Mi dia due etti di prosciutto e mezzo chilo di formaggio.",
             "Dammi duecento grammi di prosciutto e mezzo chilo di formaggio.",
             "Mi dai duecento grammi di prosciutto e mezzo chilo di formaggio?",
             "Mi dà duecento grammi di prosciutto e mezzo chilo di formaggio?",
             "Mi dia duecento grammi di prosciutto e mezzo chilo di formaggio.",
             "Mi dai due etti di prosciutto e mezzo chilo di formaggio, per favore.",
             "Vorrei due etti di prosciutto e mezzo chilo di formaggio."]),

    # ================= Settimana 49: Registro alto e coesione =================
    dict(id="mj-49-01", type="choice", topic="registro alto", level="C1", w=49, prompt=CE,
         stem="I costi sono aumentati; ___, molte famiglie hanno rinunciato alle cure.",
         options=["di conseguenza", "per contro", "altresì"], answer="di conseguenza",
         note="Di conseguenza introduce el resultado. Per contro opone y altresì suma."),
    dict(id="mj-49-02", type="cloze", topic="registro alto", level="B2", w=49,
         prompt="Completá con el congiuntivo.",
         stem="Benché il progetto ___ (essere) costoso, verrà approvato.", answer="sia",
         note="Benché pide congiuntivo: benché sia costoso."),
    dict(id="mj-49-03", type="cloze", topic="registro alto", level="C1", w=49,
         prompt="Completá con el congiuntivo (dos formas posibles).",
         stem="Qualora ___ (esserci) problemi, avvisateci subito.", answer="ci siano",
         alt=["ci fossero"],
         note="Qualora = en caso de que: congiuntivo (presente o imperfetto)."),
    dict(id="mj-49-04", type="cloze", topic="registro alto", level="B2", w=49,
         prompt="Completá con el congiuntivo.",
         stem="Ti scrivo affinché tu ___ (sapere) come stanno le cose.", answer="sappia",
         note="Affinché (= para que) pide congiuntivo: affinché tu sappia."),
    dict(id="mj-49-05", type="fixerr", topic="registro alto", level="B2", w=49, prompt=FX, cat="congiuntivo",
         stem="Benché è tardi, continuiamo a lavorare.", bad="è", good="sia",
         answer="Benché sia tardi, continuiamo a lavorare.",
         note="Benché pide siempre congiuntivo: benché sia tardi."),
    dict(id="mj-49-06", type="fixerr", topic="registro alto", level="C1", w=49, prompt=FX, cat="lessico",
         stem="Te lo ripeto per che tu capisca.", bad="per che", good="affinché",
         answer="Te lo ripeto affinché tu capisca.",
         note="«Para que» no se traduce per che: la conjunción es affinché, con congiuntivo."),
    dict(id="mj-49-07", type="fixerr", topic="registro alto", level="C1", w=49, prompt=FX, cat="congiuntivo",
         stem="Anche se sia tardi, io resto ancora un po'.", bad="sia", good="è",
         answer="Anche se è tardi, io resto ancora un po'.",
         note="Anche se pide indicativo en lo real (anche se è tardi); con congiuntivo solo en hipótesis: anche se fosse tardi."),
    dict(id="mj-49-08", type="choice", topic="registro alto", level="C1", w=49, prompt=CE,
         stem="___ della fabbrica ha lasciato senza lavoro cento persone.",
         options=["La chiusura", "La chiudizione", "La chiusione"], answer="La chiusura",
         note="Nominalización: chiudere → la chiusura (sufijo -ura)."),
    dict(id="mj-49-09", type="cloze", topic="registro alto", level="C1", w=49,
         prompt="Convertí el verbo en sustantivo.",
         stem="La ___ (ridurre) della spesa pubblica è stata approvata dal parlamento.",
         answer="riduzione",
         note="Ridurre → riduzione (-zione). El sujeto del verbo pasa a un complemento con di: della spesa."),
    dict(id="mj-49-10", type="choice", topic="registro alto", level="C1", w=49, prompt=CE,
         stem="___ possibile, si preferiscono le riunioni a distanza.",
         options=["Laddove", "Malgrado", "Nonostante"], answer="Laddove",
         note="Laddove + adjetivo = condición (laddove possibile = si es posible). Malgrado y nonostante piden un sustantivo."),
    dict(id="mj-49-11", type="choice", topic="registro alto", level="C1", w=49, prompt=CE,
         stem="___ le difficoltà, l'azienda ha chiuso l'anno in utile.",
         options=["Malgrado", "Benché", "Sebbene"], answer="Malgrado",
         note="Malgrado + sustantivo (le difficoltà). Benché y sebbene piden un verbo en congiuntivo."),
    _tr("mj-49-12", "registro alto", "C1", 49, "A pesar del mal tiempo, la ceremonia se realizó igual.",
        "Malgrado il maltempo, la cerimonia si è svolta ugualmente.",
        "Malgrado + sustantivo, sin preposición. Svolgersi = tener lugar.",
        alt=["Nonostante il maltempo, la cerimonia si è svolta ugualmente.",
             "Malgrado il maltempo, la cerimonia si è svolta comunque.",
             "Nonostante il maltempo, la cerimonia si è svolta comunque.",
             "Malgrado il maltempo, la cerimonia si è svolta lo stesso.",
             "Nonostante il maltempo, la cerimonia si è svolta lo stesso.",
             "Malgrado il maltempo, la cerimonia ha avuto luogo ugualmente.",
             "Nonostante il maltempo, la cerimonia ha avuto luogo ugualmente.",
             "Malgrado il maltempo, la cerimonia ha avuto luogo comunque.",
             "Nonostante il maltempo, la cerimonia ha avuto luogo comunque.",
             "Malgrado il maltempo, la cerimonia ha avuto luogo lo stesso.",
             "Nonostante il maltempo, la cerimonia ha avuto luogo lo stesso.",
             "Malgrado il maltempo, la cerimonia si è tenuta ugualmente.",
             "Nonostante il maltempo, la cerimonia si è tenuta ugualmente.",
             "Malgrado il maltempo, la cerimonia si è tenuta comunque.",
             "Nonostante il maltempo, la cerimonia si è tenuta comunque.",
             "Malgrado il maltempo, la cerimonia si è tenuta lo stesso.",
             "Nonostante il maltempo, la cerimonia si è tenuta lo stesso."], typed=True),
    _tr("mj-49-13", "registro alto", "C1", 49, "Aunque el proyecto es costoso, conviene aprobarlo.",
        "Benché il progetto sia costoso, conviene approvarlo.",
        "Benché + congiuntivo. Con anche se iría el indicativo.",
        alt=["Sebbene il progetto sia costoso, conviene approvarlo.",
             "Nonostante il progetto sia costoso, conviene approvarlo.",
             "Anche se il progetto è costoso, conviene approvarlo.",
             "Benché il progetto sia costoso, conviene approvarlo"], typed=True),
    _tr("mj-49-14", "registro alto", "C1", 49, "El aumento de los precios preocupa a los economistas.",
        "L'aumento dei prezzi preoccupa gli economisti.",
        "Nominalización: aumentare → l'aumento, con di + complemento (dei prezzi).",
        alt=["L'aumento dei prezzi preoccupa gli economisti", "L'incremento dei prezzi preoccupa gli economisti.",
             "L'incremento dei prezzi preoccupa gli economisti"]),

    # ================= Settimana 51: Ripasso generale C1 =================
    dict(id="mj-51-01", type="cloze", topic="ripasso", level="C1", w=51,
         prompt="Completá con pronombre + passato prossimo de fare.",
         stem="La facciata? ___ ridipingere da un'impresa.", answer="L'ho fatta",
         alt=["l'ho fatta"],
         note="Causativo: el pronombre va delante de avere y el participio concuerda: l'ho fatta ridipingere."),
    dict(id="mj-51-02", type="choice", topic="ripasso", level="B2", w=51,
         prompt="Elegí el verbo que expresa obligación (se debe completar).",
         stem="Il modulo ___ compilato entro venerdì.",
         options=["va", "viene", "è stato"], answer="va",
         note="Andare + participio = obligación: va compilato. Venire indica acción en curso; essere stato, acción hecha."),
    dict(id="mj-51-03", type="cloze", topic="ripasso", level="B2", w=51,
         prompt="Completá con el si passivante.",
         stem="In questa libreria ___ (vendere) libri usati.", answer="si vendono",
         note="Si passivante: el verbo concuerda con lo que se vende (libri): si vendono."),
    dict(id="mj-51-04", type="fixerr", topic="ripasso", level="B2", w=51, prompt=FX, cat="accordo",
         stem="In ufficio si usa molti programmi diversi.", bad="si usa", good="si usano",
         answer="In ufficio si usano molti programmi diversi.",
         note="Con un sustantivo plural el verbo del si passivante también va en plural."),
    dict(id="mj-51-05", type="choice", topic="ripasso", level="B2", w=51, prompt=CE,
         stem="Il pane? ___ compro io, tu prendi il vino.",
         options=["Lo", "Ne", "Gli"], answer="Lo",
         note="Dislocación a la izquierda: el objeto adelantado se retoma con el pronombre directo lo."),
    dict(id="mj-51-06", type="fixerr", topic="ripasso", level="C1", w=51, prompt=FX, cat="ci_ne",
         stem="Di problemi non ho, grazie.", bad="non ho", good="non ne ho",
         answer="Di problemi non ne ho, grazie.",
         note="Con «di + sustantivo» adelantado, el pronombre ne es obligatorio: di problemi non ne ho."),
    dict(id="mj-51-07", type="choice", topic="ripasso", level="C1", w=51, prompt=CE,
         stem="Sei tu che ___ sbagliato, non io.",
         options=["hai", "ha", "è"], answer="hai",
         note="En la escindida el verbo del che concuerda con el sujeto focalizado: sei tu che hai sbagliato."),
    dict(id="mj-51-08", type="fixerr", topic="ripasso", level="B2", w=51, prompt=FX, cat="periodo_ipotetico",
         stem="Se avrei studiato di più, ora sarei più tranquillo.", bad="avrei studiato", good="avessi studiato",
         answer="Se avessi studiato di più, ora sarei più tranquillo.",
         note="Después de se hipotético va congiuntivo, nunca condicional: se avessi studiato."),
    dict(id="mj-51-09", type="choice", topic="ripasso", level="C1", w=51, prompt=CE,
         stem="Se fossi stato più prudente, adesso non ___ in ospedale.",
         options=["sarei", "sarei stato", "fossi"], answer="sarei",
         note="Periodo mixto: condición pasada (trapassato) y efecto presente (condizionale presente): adesso non sarei in ospedale."),
    dict(id="mj-51-10", type="cloze", topic="ripasso", level="B2", w=51,
         prompt="Completá con el congiuntivo imperfetto.",
         stem="Ieri, sebbene ___ (essere, loro) stanchi, hanno finito il lavoro.", answer="fossero",
         note="Sebbene pide congiuntivo; la principal está en pasado, así que va el imperfetto: fossero."),
    dict(id="mj-51-11", type="choice", topic="ripasso", level="B2", w=51, prompt=CE,
         stem="___ piove, esco lo stesso.",
         options=["Anche se", "Benché", "Nonostante"], answer="Anche se",
         note="Anche se va con indicativo (piove). Benché y nonostante pedirían congiuntivo."),
    _tr("mj-51-12", "ripasso", "C1", 51, "Los documentos? Se los hice firmar al director.",
        "I documenti? Li ho fatti firmare al direttore.",
        "Causativo con pronombre: li ho fatti firmare (el participio concuerda). También glieli ho fatti firmare.",
        alt=["I documenti? Glieli ho fatti firmare.", "I documenti? Li ho fatti firmare dal direttore.",
             "I documenti? Glieli ho fatti firmare al direttore.", "I documenti? Glieli ho fatti firmare dal direttore.",
             "I documenti? Li ho fatti firmare al direttore", "I documenti li ho fatti firmare al direttore.", "I documenti li ho fatti firmare dal direttore."],
        typed=True),
    _tr("mj-51-13", "ripasso", "C1", 51, "Estas reglas deben respetarse siempre.",
        "Queste regole vanno rispettate sempre.",
        "Andare + participio expresa obligación y el participio concuerda: vanno rispettate.",
        alt=["Queste regole vanno sempre rispettate.", "Queste regole devono essere rispettate sempre.",
             "Queste regole devono essere sempre rispettate.", "Queste regole si devono rispettare sempre.", "Queste regole devono sempre essere rispettate.",
             "Queste regole vanno rispettate sempre"]),
    _tr("mj-51-14", "ripasso", "C1", 51, "Si hubiera estudiado más, ahora estaría más tranquilo.",
        "Se avessi studiato di più, ora sarei più tranquillo.",
        "Periodo mixto: se + trapassato del congiuntivo y condizionale presente.",
        alt=["Se avessi studiato di più, adesso sarei più tranquillo.",
             "Se avessi studiato di più, ora sarei più tranquilla.",
             "Se avessi studiato di più, adesso sarei più tranquilla.",
             "Se avessi studiato di più, ora sarei più sereno.",
             "Se avessi studiato di più, adesso sarei più sereno.",
             "Se avessi studiato di più, ora sarei più serena.",
             "Se avessi studiato di più, adesso sarei più serena."], typed=True),
]
