# -*- coding: utf-8 -*-
"""Pragmática explícita: ocho microlecciones (semanas 8, 14, 20, 25, 31, 36,
44 y 48) y la variación del italiano hablado (48).

La gramática dice qué es correcto; la pragmática, qué es adecuado.  Cada
ítem pone una situación y tres versiones de la misma frase: la brusca, la
adecuada y la exagerada (Taguchi 2015; Plonsky & Zhuang 2019: la
instrucción explícita de pragmática rinde más que la implícita).  La nota
dice qué efecto hace cada una.  La teoría está en el bloque de pragmática de
cada lección (tools/it/lessons/).

Cada opción usa solo la gramática ya vista en su semana (tools/it/sillabo.py
lo comprueba al armar el curso).
"""

P = "Elegí la opción adecuada a la situación."
V = "¿Escrito formal, hablado o los dos?"


def _it(n, w, level, stem, good, rude, over, note):
    return dict(id="pr-%02d-%02d" % (w, n), type="choice", topic="pragmatica", level=level, w=w,
                prompt=P, stem=stem, stemEs=True, options=[good, rude, over], answer=good, note=note)


ITEMS = [
    # ================= Semana 8: pedir y atenuar =================
    _it(1, 8, "A1", "En la calle, a una señora que no conocés: querés saber dónde está la estación.",
        "Mi scusi, sa dov'è la stazione?",
        "Dov'è la stazione?",
        "Mi scusi tanto, signora, mi scusi davvero: per caso sa dov'è la stazione? Per favore, per favore.",
        "Adecuada: *mi scusi* + pregunta es lo normal con una desconocida. Brusca: sin ninguna fórmula suena seco, como una orden. Exagerada: tres disculpas y dos *per favore* suenan a súplica."),
    _it(2, 8, "A1", "En el bar, al barista: querés un café.",
        "Un caffè, per favore.",
        "Voglio un caffè.",
        "Mi scusi, per caso è possibile avere un caffè, se non è un problema?",
        "Adecuada: *un caffè, per favore* es lo que dice todo el mundo. Brusca: *voglio* es gramatical, pero suena a capricho. Exagerada: pedir permiso para un café en un bar suena raro: es su trabajo."),
    _it(3, 8, "A1", "En clase, no entendiste lo que dijo la profesora.",
        "Mi scusi, può ripetere, per favore?",
        "Cosa?",
        "Mi scusi, professoressa, sono proprio un disastro: per caso può ripetere tutto, per favore?",
        "Adecuada: disculpa + *può ripetere?* con usted. Brusca: *Cosa?* solo va entre amigos. Exagerada: rebajarse (*sono un disastro*) no hace falta para pedir que repita."),
    _it(4, 8, "A1", "A un compañero de clase: no tenés lapicera.",
        "Scusa, per caso hai una penna?",
        "Voglio una penna.",
        "Scusa, scusa tanto, per caso, se è possibile, hai una penna? Solo una, per favore!",
        "Adecuada: *scusa* (vos) y *per caso* suavizan. Brusca: *voglio una penna* suena a exigencia. Exagerada: tanta disculpa por una lapicera suena a burla."),
    _it(5, 8, "A1", "En la calle, a un chico de tu edad: querés saber la hora.",
        "Scusa, sai che ore sono?",
        "Ehi, tu! Che ore sono?",
        "Mi scusi, signore, per caso Lei sa che ore sono, per favore?",
        "Adecuada: entre gente joven se tutea, con *scusa*. Brusca: *Ehi, tu!* suena a pelea. Exagerada: *signore* y *Lei* a alguien de tu edad suenan a broma o a distancia."),
    _it(6, 8, "A1", "En el negocio, a la vendedora: querés saber si tienen la cartera en negro.",
        "Mi scusi, avete questa borsa in nero?",
        "Voglio questa borsa in nero.",
        "Mi scusi, signora, mi scusi tanto: per caso, se non è un problema, avete questa borsa in nero?",
        "Adecuada: *mi scusi* + pregunta directa. Brusca: *voglio* es una orden. Exagerada: tanto rodeo para una pregunta de todos los días suena falso."),
    _it(7, 8, "A1", "Tocás la puerta del despacho de un profesor.",
        "Posso entrare?",
        "Entro.",
        "Mi scusi, mi scusi tanto, per caso posso entrare un attimo, se è possibile, per favore?",
        "Adecuada: *posso entrare?* pide permiso. Brusca: *entro* anuncia sin preguntar. Exagerada: tantas fórmulas para entrar a un despacho suenan a nervios."),
    _it(8, 8, "A1", "A un turista en la plaza: querés que te saque una foto.",
        "Mi scusi, può fare una foto, per favore?",
        "Una foto!",
        "Mi scusi tanto, signore, per caso, solo se è possibile, può fare una piccola foto, per favore? Solo una!",
        "Adecuada: *mi scusi* + *può…?* + *per favore*. Brusca: *Una foto!* suena a orden. Exagerada: *una piccola foto, solo una* suena a súplica."),
    _it(9, 8, "A1", "En el tren, un señor está sentado en tu asiento.",
        "Mi scusi, questo è il mio posto.",
        "È il mio posto!",
        "Mi scusi tanto, signore, forse non capisco bene, ma per caso questo è il mio posto? Mi scusi!",
        "Adecuada: *mi scusi* + el hecho, sin enojo. Brusca: la exclamación sin disculpa suena a acusación. Exagerada: tanta duda hace que no se entienda que el lugar es tuyo."),
    _it(10, 8, "A1", "En la trattoria, al mozo: querés la cuenta.",
        "Il conto, per favore.",
        "Il conto!",
        "Mi scusi, per caso possiamo avere il conto, se è possibile, quando ha un attimo, per favore?",
        "Adecuada: *il conto, per favore*, con un gesto si está lejos. Brusca: sin *per favore* es una orden. Exagerada: tantas condiciones para la cuenta sobran."),
    _it(11, 8, "A1", "Por teléfono, necesitás un momento para buscar una lapicera.",
        "Un attimo, per favore.",
        "Adesso no!",
        "Mi scusi, mi scusi tanto, un attimo, un piccolo attimo solo, per favore, un attimo!",
        "Adecuada: *un attimo, per favore*. Brusca: *adesso no!* corta al otro. Exagerada: repetir *un attimo* cinco veces pone nervioso a cualquiera."),

    # ================= Semana 14: invitar, aceptar, rechazar =================
    _it(1, 14, "A2", "Querés invitar a una compañera de trabajo al cine esta noche.",
        "Ti va di venire al cinema stasera?",
        "Stasera vieni al cinema con me.",
        "Mi scusi tantissimo, so che è molto occupata, ma se per caso un giorno Le va, forse, magari, vuole venire...?",
        "Adecuada: *ti va di…?* invita y deja la puerta abierta. Brusca: el presente afirmativo suena a orden. Exagerada: tanto rodeo, y además con *Lei*, no se entiende que es una invitación."),
    _it(2, 14, "A2", "Un amigo te invita a una fiesta y no podés ir.",
        "Mi dispiace, ma sabato non posso: ho già un impegno.",
        "No.",
        "Oddio, mi dispiace tantissimo, sono proprio distrutto, non puoi capire quanto mi dispiace, davvero, scusami mille volte...",
        "Adecuada: disculpa + motivo, aunque sea vago. Brusca: un *no* seco es un desplante. Exagerada: tanto drama por una fiesta suena falso."),
    _it(3, 14, "A2", "Te invitan a tomar un café y tenés ganas.",
        "Sì, volentieri!",
        "Va bene.",
        "Sì, sì, certo, assolutamente, è un onore enorme, grazie infinite!",
        "Adecuada: *volentieri* acepta con gusto. Brusca: *va bene* solo suena a que te da igual. Exagerada: *un onore* para un café suena a ironía."),
    _it(4, 14, "A2", "Un vecino te invita a cenar; no podés ahora, pero sí otro día.",
        "Purtroppo stasera non posso. Magari un'altra volta?",
        "Stasera no.",
        "Purtroppo stasera no, ma magari domani, o dopodomani, o sabato, o quando vuole Lei, anche tutti i giorni!",
        "Adecuada: *purtroppo* + motivo + *magari un'altra volta* deja abierta la invitación. Brusca: *stasera no* cierra. Exagerada: ofrecer todos los días suena a desesperación."),
    _it(5, 14, "A2", "Querés proponerle a tu hermano salir a correr el domingo.",
        "Domenica ti va di andare a correre?",
        "Domenica corri con me.",
        "Scusa se ti disturbo, lo so che sei stanco, ma se per caso domenica ti va, forse, possiamo...",
        "Adecuada: *ti va di…?* es la invitación entre familia y amigos. Brusca: suena a orden. Exagerada: tanta disculpa con tu hermano suena rara."),
    _it(6, 14, "A2", "Una amiga te propone ir a bailar y no te gusta bailar.",
        "Grazie, ma ballare non mi piace molto. Andiamo a bere qualcosa?",
        "Ballare è stupido.",
        "Ballare? Oddio, no, mai, per carità, lo odio con tutto il cuore!",
        "Adecuada: agradecés, das el motivo y proponés otra cosa. Brusca: criticar el plan ofende a quien lo propone. Exagerada: tanto rechazo suena a desprecio."),
    _it(7, 14, "A2", "Tu jefe te invita a un almuerzo de trabajo y podés ir.",
        "Grazie, vengo volentieri.",
        "Ok.",
        "Grazie mille, grazie davvero, è un piacere enorme, non vedo l'ora, grazie ancora!",
        "Adecuada: *grazie, vengo volentieri* es cordial y justo. Brusca: *ok* solo, a un jefe, suena desganado. Exagerada: tanto agradecimiento suena a adulación."),
    _it(8, 14, "A2", "Un conocido te insiste por tercera vez para ir a su casa; no querés, sin ofenderlo.",
        "Mi dispiace, in questo periodo sono molto impegnato.",
        "Non mi va di venire da te.",
        "Mi dispiace tantissimo, sono impegnatissimo, ho mille cose, non ho mai tempo, davvero mai, mai, mai!",
        "Adecuada: el motivo general (*sono impegnato*) rechaza sin herir. Brusca: *non mi va* es sincero, pero duele. Exagerada: tanto *mai* suena a excusa que nadie cree."),
    _it(9, 14, "A2", "Tu compañera de departamento propone pedir pizza; te encanta la idea.",
        "Sì, dai, buona idea!",
        "Va bene, come vuoi.",
        "Sì! Sì! Che idea fantastica, straordinaria, la migliore idea del mondo!",
        "Adecuada: *sì, dai* acepta con ganas. Brusca: *come vuoi* suena a que te resignás. Exagerada: *la migliore idea del mondo* para una pizza suena a ironía."),
    _it(10, 14, "A2", "Te invitan a un recital de un grupo que no conocés; no estás seguro.",
        "Non so, ci penso e ti faccio sapere.",
        "Non conosco quel gruppo.",
        "Non so, forse sì, forse no, dipende, vediamo, non lo so proprio, magari, chissà...",
        "Adecuada: *ti faccio sapere* (te aviso) pide tiempo con claridad. Brusca: *non lo conosco* suena a desinterés. Exagerada: tantas dudas no dicen nada."),
    _it(11, 14, "A2", "Un colega te invita a tomar algo después del trabajo; no podés, pero querés que vuelva a invitarte.",
        "Oggi non posso, purtroppo. Ma la prossima volta vengo!",
        "Oggi no.",
        "Oggi non posso, ma ti giuro che la prossima volta vengo, sicuro, sicurissimo, promesso!",
        "Adecuada: *purtroppo* + promesa simple. Brusca: *oggi no* no deja claro que querés ir otro día. Exagerada: jurar y prometer por un trago suena a excusa."),

    # ================= Semana 20: pedir con cortesía en escala =================
    _it(1, 20, "B1", "En un hotel, a la recepcionista: la habitación da a una calle ruidosa.",
        "Sarebbe possibile avere una camera più tranquilla?",
        "Voglio un'altra camera.",
        "Mi scusi tantissimo, so che è difficile, ma sarebbe forse per caso possibile, se non disturbo, cambiare camera?",
        "Adecuada: *sarebbe possibile* pide sin exigir. Brusca: *voglio* suena a queja. Exagerada: tanto *forse, per caso, se non disturbo* esconde el pedido."),
    _it(2, 20, "B1", "En la mesa, a un amigo: querés la sal.",
        "Mi passi il sale?",
        "Il sale!",
        "Ti dispiacerebbe, se non è troppo disturbo, passarmi gentilmente il sale?",
        "Adecuada: entre amigos alcanza *mi passi…?*. Brusca: *Il sale!* es una orden. Exagerada: *ti dispiacerebbe* para la sal suena a burla."),
    _it(3, 20, "B1", "En el tren, a un desconocido: querés que cierre la ventanilla.",
        "Scusi, potrebbe chiudere il finestrino?",
        "Chiudi il finestrino!",
        "Mi scusi, signore, Le dispiacerebbe moltissimo, se per caso non è un problema per Lei, chiudere il finestrino?",
        "Adecuada: *potrebbe* es la medida justa con un desconocido. Brusca: el imperativo, y encima con *tu*, a un desconocido es una orden. Exagerada: tanto rodeo para una ventanilla suena irónico."),
    _it(4, 20, "B1", "Un auto bloquea la salida de tu garaje; el dueño está en el bar de al lado.",
        "Le dispiacerebbe spostare la macchina? Devo uscire.",
        "Sposti subito la macchina!",
        "Mi scusi tantissimo se La disturbo, sono mortificato, ma per caso sarebbe così gentile da spostare forse la macchina?",
        "Adecuada: *le dispiacerebbe* + el motivo: es un favor grande a un desconocido. Brusca: *subito* y el imperativo empiezan una pelea. Exagerada: *sono mortificato* cuando el que molesta es él suena a sumisión."),
    _it(5, 20, "B1", "En un negocio, a la vendedora: querés un par de zapatos en otro número.",
        "Vorrei provare queste scarpe nel 38.",
        "Dammi il 38.",
        "Scusi, sarebbe per caso possibile, se non è troppo disturbo, provare forse queste scarpe nel 38?",
        "Adecuada: *vorrei* es la fórmula del negocio. Brusca: *dammi* con tú a una vendedora es de mala educación. Exagerada: probarse zapatos no necesita tantos permisos."),
    _it(6, 20, "B1", "A un amigo: querés que te preste la bici, y te da un poco de vergüenza pedírsela.",
        "Non è che mi presteresti la bici per domani?",
        "Prestami la bici.",
        "Egregio amico, Le chiederei l'enorme cortesia di prestarmi la bicicletta.",
        "Adecuada: *non è che…?* + condizionale es el pedido tímido entre amigos. Brusca: el imperativo pide como si fuera obligación. Exagerada: el *Lei* y *infinitamente grato* con un amigo suenan a broma."),
    _it(7, 20, "B1", "En una oficina pública: querés cambiar la fecha de tu turno.",
        "Sarebbe possibile spostare l'appuntamento a lunedì?",
        "Spostatemi l'appuntamento a lunedì.",
        "Mi scusi, mi perdoni, so che siete occupatissimi, ma forse sarebbe possibile, solo se non è un problema...",
        "Adecuada: *sarebbe possibile* es la fórmula de las oficinas. Brusca: el imperativo a la ventanilla no ayuda. Exagerada: tanta disculpa y no se entiende qué fecha querés."),
    _it(8, 20, "B1", "En clase de italiano: querés que el profesor hable más despacio.",
        "Potrebbe parlare un po' più piano, per favore?",
        "Parli più piano!",
        "Professore, mi perdoni, sono terribilmente lento, Le dispiacerebbe tantissimo parlare forse un pochino più piano?",
        "Adecuada: *potrebbe* + *un po'* suaviza. Brusca: el imperativo con exclamación suena a reproche. Exagerada: rebajarse (*sono terribilmente lento*) no hace falta."),
    _it(9, 20, "B1", "En el bar, pedís un vaso de agua de la canilla.",
        "Mi porterebbe un bicchiere d'acqua, per favore?",
        "Acqua.",
        "Mi scusi tantissimo, Le dispiacerebbe moltissimo portarmi, se possibile, un bicchiere d'acqua?",
        "Adecuada: *mi porterebbe…?* con *per favore* es amable. Brusca: una sola palabra suena a orden. Exagerada: *le dispiacerebbe moltissimo* por un vaso de agua sobra."),
    _it(10, 20, "B1", "Por mail, a la secretaría de la universidad: pedís un certificado.",
        "Vorrei richiedere un certificato di iscrizione.",
        "Mandatemi un certificato di iscrizione.",
        "Umilmente oserei chiedere, se non è troppo disturbo, un piccolo certificato di iscrizione.",
        "Adecuada: *vorrei richiedere* es el registro de un mail formal. Brusca: el imperativo, por escrito, suena exigente. Exagerada: *umilmente oserei* suena a siglo XIX."),
    _it(11, 20, "B1", "A tu compañera de trabajo: querés que te ayude con un informe.",
        "Mi daresti una mano con questa relazione?",
        "Aiutami con questa relazione.",
        "Scusami tanto, lo so che sei stanchissima, mi vergogno, ma forse potresti per caso aiutarmi un pochino?",
        "Adecuada: *mi daresti una mano?* es el pedido amable entre colegas. Brusca: el imperativo suena a orden. Exagerada: tanta vergüenza hace incómodo el pedido."),

    # ================= Semana 25: opinar y matizar =================
    _it(1, 25, "B1", "En una charla, das tu opinión sobre la comida del restorán nuevo.",
        "Secondo me è buona, ma un po' cara.",
        "È cara, punto.",
        "Forse, non so, magari, mi sembra che possa essere, in un certo senso, abbastanza buona, forse...",
        "Adecuada: *secondo me* presenta la opinión como tuya, con matiz. Brusca: *punto* cierra la charla. Exagerada: tantos matices no dicen nada."),
    _it(2, 25, "B1", "Tu amigo dice que el tren es más rápido que el auto; vos no estás de acuerdo.",
        "Capisco, però secondo me in macchina si fa prima.",
        "Hai torto.",
        "Hai ragione, hai assolutamente ragione, anche se forse, chissà, non so, magari la macchina...",
        "Adecuada: concedés (*capisco*) y después das tu idea. Brusca: *hai torto* ataca a la persona. Exagerada: darle la razón y después dudar confunde."),
    _it(3, 25, "B1", "En una reunión, crees que la propuesta de un colega es buena.",
        "Mi sembra che sia una buona proposta.",
        "Va bene.",
        "Mi sembra assolutamente la proposta più geniale del mondo, un capolavoro!",
        "Adecuada: *mi sembra che* + congiuntivo da tu opinión con suavidad. Brusca: *va bene* suena a desinterés. Exagerada: el elogio excesivo suena a adulación o a ironía."),
    _it(4, 25, "B1", "Un amigo te pregunta si va a llover; tenés la impresión de que sí.",
        "Mi sa che piove, prendi l'ombrello.",
        "Pioverà. È sicuro.",
        "Non so, forse, può darsi, chissà, magari piove, magari no, non si sa mai...",
        "Adecuada: *mi sa che* (me da que) es la suposición coloquial, con indicativo. Brusca: *è sicuro* promete lo que no sabés. Exagerada: tantas dudas no ayudan a decidir."),
    _it(5, 25, "B1", "En clase, no estás seguro de que tu respuesta sea correcta.",
        "Non so se sia giusto, ma io direi «andato».",
        "È «andato».",
        "Scusate, sicuramente sbaglio, sono un disastro, non so niente, ma forse, chissà, «andato»?",
        "Adecuada: *non so se* + congiuntivo y *direi* matizan sin esconder la respuesta. Brusca: afirmar lo que no sabés. Exagerada: rebajarse tanto hace dudar a todos."),
    _it(6, 25, "B1", "Una amiga te muestra una foto de su nuevo corte de pelo; no te encanta.",
        "Mi sembra un po' corto, ma ti sta bene.",
        "È brutto.",
        "È bellissimo, stupendo, meraviglioso, il più bel taglio del mondo!",
        "Adecuada: una crítica suave (*un po'*) y algo positivo. Brusca: *è brutto* hiere. Exagerada: tanto elogio no se lo cree nadie."),
    _it(7, 25, "B1", "Un vecino propone pintar el edificio de rosa; no te convence.",
        "Non so se sia la scelta migliore. Che ne dite del bianco?",
        "Il rosa è ridicolo.",
        "Il rosa? Ma siete impazziti? È la peggiore idea della storia dell'umanità!",
        "Adecuada: dudar (*non so se*) y proponer otra cosa. Brusca: *ridicolo* ofende a quien lo propuso. Exagerada: el drama convierte una opinión en una pelea."),
    _it(8, 25, "B1", "En una entrevista de trabajo te preguntan qué pensás del trabajo remoto.",
        "Penso che sia utile, soprattutto per chi abita lontano.",
        "Mi piace, e basta.",
        "Penso, credo, immagino, suppongo che possa forse essere utile, ma non ne sono sicuro...",
        "Adecuada: *penso che* + congiuntivo y un motivo. Brusca: *e basta* no argumenta. Exagerada: cuatro verbos de opinión seguidos suenan inseguros."),
    _it(9, 25, "B1", "Tu hermano cree que vas a aprobar el examen; vos no estás tan seguro.",
        "Spero di sì, ma non ne sono sicuro.",
        "No, non lo passo.",
        "Speriamo, speriamo tanto, speriamo davvero, speriamo proprio con tutto il cuore!",
        "Adecuada: *spero di sì* + la duda. Brusca: la negación seca corta el ánimo. Exagerada: tanto *speriamo* suena a pánico."),
    _it(10, 25, "B1", "Una compañera dice que el italiano es fácil; vos pensás que tiene partes difíciles.",
        "Da un certo punto di vista sì, però il congiuntivo non è facile.",
        "Non è vero.",
        "Facile? Ma cosa dici? È la lingua più difficile del mondo, impossibile!",
        "Adecuada: concedés una parte y matizás. Brusca: *non è vero* niega sin dar motivo. Exagerada: *impossibile* exagera tanto que pierde fuerza."),
    _it(11, 25, "B1", "Te preguntan qué película elegir; te da un poco lo mismo, pero preferís la comedia.",
        "Direi la commedia, ma per me va bene anche l'altra.",
        "La commedia.",
        "Non so, decidete voi, per me è uguale, tutto va bene, qualsiasi cosa, davvero...",
        "Adecuada: *direi* da tu preferencia y deja lugar a los otros. Brusca: la respuesta seca parece imponer. Exagerada: no opinar nada tampoco ayuda."),

    # ================= Semana 31: quejarse y reclamar =================
    _it(1, 31, "B2", "El lavarropas que compraste hace una semana no funciona. Volvés al negocio.",
        "Mi scusi, ma la lavatrice che ho comprato non funziona. Vorrei cambiarla.",
        "Questa lavatrice è una schifezza! Voglio i miei soldi!",
        "Mi scusi tantissimo se La disturbo, forse è colpa mia, ma la lavatrice magari non funziona benissimo...",
        "Adecuada: el hecho y lo que pedís, con firmeza. Brusca: el insulto al producto pone al vendedor a la defensiva. Exagerada: echarte la culpa debilita tu reclamo."),
    _it(2, 31, "B2", "En el restorán, el plato llega frío.",
        "Scusi, il piatto è freddo. Potrebbe riscaldarlo?",
        "Questo piatto è immangiabile!",
        "Scusi, non vorrei sembrare esigente, sicuramente è colpa mia che sono arrivato tardi, ma forse il piatto...",
        "Adecuada: el hecho + un pedido concreto. Brusca: *immangiabile* ofende a la cocina. Exagerada: disculparse por el error del otro no resuelve nada."),
    _it(3, 31, "B2", "Por mail, a la compañía de luz: te cobraron dos veces la misma factura.",
        "Le scrivo per segnalare che la fattura di marzo mi è stata addebitata due volte.",
        "Siete dei ladri: mi avete rubato i soldi!",
        "Con infinita umiltà, e scusandomi per il disturbo, mi permetto di far forse notare un possibile piccolo errore...",
        "Adecuada: *Le scrivo per segnalare* es la fórmula del reclamo escrito. Brusca: la acusación no se puede sostener por escrito. Exagerada: tanta humildad esconde el error."),
    _it(4, 31, "B2", "El paquete que esperabas para el viernes no llegó y nadie te avisó.",
        "Mi aspettavo che arrivasse venerdì. Non è possibile che nessuno mi abbia avvisato.",
        "Siete degli incapaci, come sempre.",
        "Non importa, figuriamoci, può succedere a tutti, anzi mi scuso io per il disturbo...",
        "Adecuada: lo que esperabas y la queja concreta. Brusca: *incapaci, come sempre* generaliza e insulta. Exagerada: si no reclamás, nadie lo resuelve."),
    _it(5, 31, "B2", "Tu vecino pone música fuerte todas las noches a la una.",
        "Mi scusi, ma la musica di notte si sente molto. Potrebbe abbassarla dopo le undici?",
        "Se non abbassa la musica chiamo la polizia!",
        "Scusi se esisto, lo so che sono noioso, ma forse la musica, qualche volta, se non Le dispiace...",
        "Adecuada: *mi scusi, ma* + el hecho + un pedido razonable. Brusca: empezar con amenazas cierra el diálogo. Exagerada: *scusi se esisto* le quita peso a tu queja."),
    _it(6, 31, "B2", "En la ventanilla te piden por tercera vez el mismo documento.",
        "Questo documento l'ho già portato due volte. Potrebbe controllare, per favore?",
        "È una vergogna! Esigo di parlare con il direttore!",
        "Va bene, nessun problema, lo porto anche una quarta volta, non si preoccupi...",
        "Adecuada: el hecho con calma y un pedido concreto. Brusca: *esigo* y *vergogna* son para cuando lo amable ya no funcionó. Exagerada: aceptarlo todo no resuelve el problema."),
    _it(7, 31, "B2", "En el hotel, la habitación no está limpia.",
        "Mi dispiace, ma la camera non è stata pulita. Si potrebbe sistemare?",
        "Che schifo, questa camera è un porcile!",
        "Scusi se mi permetto, forse è solo una mia impressione, ma magari la camera...",
        "Adecuada: el hecho, sin exagerar, y lo que pedís. Brusca: *porcile* (chiquero) ofende. Exagerada: presentar un hecho como impresión debilita el reclamo."),
    _it(8, 31, "B2", "Un colega entregó tarde su parte y te hizo quedar mal con el jefe.",
        "Mi dispiace dirtelo, ma per il ritardo ho avuto problemi con il capo.",
        "Per colpa tua ho fatto una figuraccia. Sei un disastro!",
        "Non fa niente, figurati, anzi, è colpa mia che non ti ho ricordato la data...",
        "Adecuada: *mi dispiace dirtelo, ma* nombra el problema sin atacar. Brusca: *sei un disastro* ataca a la persona. Exagerada: cargar con su culpa no cambia nada."),
    _it(9, 31, "B2", "En el supermercado, en la caja te cobraron un precio distinto del de la góndola.",
        "Scusi, sullo scaffale il prezzo era più basso. Può controllare?",
        "Mi state truffando!",
        "Scusi, non vorrei sembrare pignolo, sicuramente mi sbaglio, ma forse, chissà, il prezzo...",
        "Adecuada: el hecho y un pedido concreto. Brusca: *truffando* (estafando) acusa sin saber si es un error. Exagerada: *sicuramente mi sbaglio* invita a que no te hagan caso."),
    _it(10, 31, "B2", "Por mail, reclamás a un curso online que nunca te mandó el certificado.",
        "Nonostante le mie richieste, non ho ancora ricevuto il certificato. Resto in attesa di un Vostro riscontro.",
        "Vi ho scritto mille volte e non rispondete mai. Siete ridicoli.",
        "Chiedo umilmente perdono per l'insistenza, e mi rendo conto di essere forse inopportuno, ma...",
        "Adecuada: *nonostante* + el hecho + *resto in attesa* cierra un reclamo formal. Brusca: *ridicoli* no se escribe en un mail. Exagerada: pedir perdón por reclamar lo que es tuyo sobra."),
    _it(11, 31, "B2", "El taxista tomó un camino mucho más largo.",
        "Mi scusi, ma non era più breve passare per il centro?",
        "Lei mi sta prendendo in giro!",
        "Mi scusi, non voglio offenderLa, è sicuramente la strada migliore, però forse, magari...",
        "Adecuada: la pregunta retórica señala el problema sin acusar. Brusca: *mi sta prendendo in giro* acusa. Exagerada: darle la razón antes de reclamar anula el reclamo."),

    # ================= Semana 36: acuerdo parcial, interrumpir, tomar la palabra =================
    _it(1, 36, "B2", "En una reunión, tu jefa propone trabajar el sábado; estás de acuerdo a medias.",
        "Ha ragione sulla scadenza, però il sabato per molti è difficile.",
        "No, il sabato no.",
        "Ha perfettamente ragione, come sempre, ha ragione su tutto, anche se forse, magari, il sabato...",
        "Adecuada: concedés una parte (*ha ragione su…*) y después el *però*. Brusca: el *no* seco a una jefa cierra la discusión. Exagerada: tanta adulación antes del desacuerdo suena falsa."),
    _it(2, 36, "B2", "Tu amigo habla hace diez minutos y necesitás decir algo urgente.",
        "Scusa se ti interrompo: posso dire una cosa?",
        "Basta, adesso parlo io.",
        "Scusami tantissimo, perdonami, mi dispiace moltissimo interromperti, ma se per caso potessi...",
        "Adecuada: *scusa se ti interrompo* pide el turno. Brusca: *basta* corta de golpe. Exagerada: tanta disculpa y el mensaje urgente no llega."),
    _it(3, 36, "B2", "En un debate, alguien no te deja terminar.",
        "Fammi finire, per favore.",
        "Stai zitto!",
        "Ti prego, ti supplico, lasciami finire almeno questa frase, solo questa...",
        "Adecuada: *fammi finire* defiende tu turno sin pelear. Brusca: *stai zitto* es un insulto. Exagerada: suplicar te quita autoridad."),
    _it(4, 36, "B2", "En clase se discute si conviene vivir en la ciudad o en el campo; ves ventajas en las dos.",
        "Da un lato in città c'è tutto, dall'altro in campagna si vive meglio.",
        "La città è meglio, fine.",
        "Non so, dipende, forse la città, forse la campagna, ognuno ha ragione, tutto è relativo...",
        "Adecuada: *da un lato… dall'altro* ordena las dos caras. Brusca: *fine* no argumenta. Exagerada: *tutto è relativo* no dice nada."),
    _it(5, 36, "B2", "Tu compañera de proyecto propone un plan; te gusta, pero falta el presupuesto.",
        "L'idea mi piace, però dobbiamo pensare anche ai costi.",
        "Non funzionerà mai.",
        "È un'idea geniale, fantastica, straordinaria, però, se posso permettermi, forse i costi...",
        "Adecuada: el elogio corto y la objeción concreta. Brusca: *non funzionerà mai* descarta todo. Exagerada: el elogio inflado hace sospechar del *però*."),
    _it(6, 36, "B2", "En una charla entre amigos, alguien interrumpe y querés seguir.",
        "Aspetta, finisco un attimo e poi parli tu.",
        "Non interrompermi sempre!",
        "Scusa, scusa, ti chiedo scusa, ma posso finire? Se non ti dispiace? Solo un secondo?",
        "Adecuada: *aspetta* + la promesa del turno. Brusca: *sempre* convierte un momento en un reproche. Exagerada: pedir permiso tantas veces para tu propio turno sobra."),
    _it(7, 36, "B2", "En una reunión querés volver a un tema que quedó sin cerrar.",
        "Come dicevo prima, sul budget non abbiamo deciso niente.",
        "Nessuno mi ascolta: il budget!",
        "Scusate, scusate, perdonate, so che non interessa a nessuno, ma forse, il budget...",
        "Adecuada: *come dicevo* retoma sin reproche. Brusca: *nessuno mi ascolta* acusa a todos. Exagerada: *non interessa a nessuno* resta fuerza a tu tema."),
    _it(8, 36, "B2", "Tu abuelo dice que antes todo era mejor; estás de acuerdo solo en parte.",
        "In parte hai ragione, nonno, però oggi ci sono anche cose migliori.",
        "Non è vero, nonno, oggi è tutto meglio.",
        "Hai ragione, nonno, hai ragione su tutto, ma proprio su tutto, anche se magari...",
        "Adecuada: *in parte hai ragione, però…* respeta y matiza. Brusca: le negás todo. Exagerada: darle la razón en todo y después dudar confunde."),
    _it(9, 36, "B2", "En clase, querés tomar la palabra después de otro compañero.",
        "Posso aggiungere una cosa?",
        "Adesso tocca a me.",
        "Scusate, se posso, se non disturbo, se il professore permette, vorrei forse, se possibile...",
        "Adecuada: *posso aggiungere una cosa?* pide el turno en una frase. Brusca: *tocca a me* reclama como en un juego. Exagerada: tantas condiciones y el turno pasa."),
    _it(10, 36, "B2", "Un amigo dice que el fútbol es una pérdida de tiempo; vos pensás que no del todo.",
        "Sì, ma per molti è anche un modo di stare insieme.",
        "Dici solo stupidaggini.",
        "Sì, sì, hai assolutamente ragione, è una perdita di tempo totale, però forse, un pochino...",
        "Adecuada: *sì, ma* concede y agrega tu punto. Brusca: *stupidaggini* ataca. Exagerada: darle toda la razón y retroceder no sostiene tu idea."),
    _it(11, 36, "B2", "En una videollamada, dos personas hablan a la vez y querés ordenar.",
        "Scusate, parliamo uno alla volta, altrimenti non si capisce.",
        "Silenzio!",
        "Scusate, per favore, se non vi dispiace, se è possibile, magari, forse, uno alla volta...",
        "Adecuada: *uno alla volta* + el motivo. Brusca: *silenzio!* es una orden de maestra. Exagerada: tantas fórmulas y nadie te escucha."),

    # ================= Semana 44: ironía y sobreentendidos =================
    _it(1, 44, "C1", "Tu amigo llega dos horas tarde. Querés marcárselo con humor, sin pelear.",
        "Complimenti per la puntualità!",
        "Sei un maleducato, arrivi sempre tardi.",
        "Oh, ecco il campione mondiale della puntualità, il re degli orologi, applausi, applausi!",
        "Adecuada: la ironía corta (*complimenti*) marca el reproche sin pelea. Brusca: el insulto directo abre una discusión. Exagerada: la ironía estirada se vuelve burla y ofende."),
    _it(2, 44, "C1", "Una amiga cocinó un risotto que te gustó mucho; querés elogiarla con naturalidad.",
        "Non male, davvero!",
        "Buono.",
        "È il risotto più straordinario della storia dell'umanità, un capolavoro assoluto!",
        "Adecuada: *non male, davvero* es un elogio italiano: quita peso para sonar sincero. Brusca: *buono* solo suena a desgano. Exagerada: tanto elogio suena a ironía."),
    _it(3, 44, "C1", "Un colega te dice «grazie» por un favor pequeño.",
        "Figurati!",
        "Prego, ma la prossima volta fallo da solo.",
        "Ma ti prego, non dirlo nemmeno, è stato un onore immenso, lo rifarei mille volte!",
        "Adecuada: *figurati!* quita importancia al favor. Brusca: el reproche arruina el favor. Exagerada: *un onore immenso* suena a burla."),
    _it(4, 44, "C1", "Tu hermano propone que pagues vos la cena de todos. Lo rechazás en broma.",
        "Io? Ma va'!",
        "No, pagate voi, non sono mica una banca.",
        "Io? Io pagare? Ma siete impazziti? Ma scherziamo? Ma per chi mi avete preso?",
        "Adecuada: *ma va'!* rechaza riendo. Brusca: la frase es correcta, pero en serio suena a enojo. Exagerada: tantas preguntas seguidas convierten la broma en escena."),
    _it(5, 44, "C1", "En el trabajo, alguien rompe la impresora por tercera vez. Comentás con un colega.",
        "Bella roba, di nuovo!",
        "Chi l'ha rotta è un incompetente.",
        "Magnifico, splendido, straordinario! Che meraviglia di giornata, la stampante di nuovo rotta!",
        "Adecuada: *bella roba!* es la queja irónica breve. Brusca: acusar a alguien en voz alta crea un problema. Exagerada: tanto adjetivo suena a ataque."),
    _it(6, 44, "C1", "Un amigo te pregunta si su nuevo jefe es inteligente; pensás que no mucho.",
        "Diciamo che non è proprio un genio.",
        "È stupido.",
        "È un genio assoluto, un Einstein, un Leonardo, il cervello del secolo!",
        "Adecuada: el *understatement* (*non è proprio un genio*) dice «es poco vivo» con elegancia. Brusca: *stupido* es un insulto. Exagerada: la ironía desmedida es cruel."),
    _it(7, 44, "C1", "Un desconocido en una oficina te trata mal. Querés responder sin ironía.",
        "Scusi, ma non mi sembra il modo di parlare.",
        "Complimenti per la gentilezza!",
        "Oh, che gentilezza squisita, che educazione raffinata, davvero un modello!",
        "Adecuada: con un desconocido, lo directo y cortés funciona mejor. La ironía (*complimenti per la gentilezza*) se lee como agresión y escala. Exagerada: la ironía larga es un insulto."),
    _it(8, 44, "C1", "Te preguntan cómo estuvo una película bastante mala.",
        "Non è il massimo, diciamo.",
        "Una schifezza totale.",
        "Il peggiore film di tutti i tempi, un disastro cosmico, un crimine contro l'umanità!",
        "Adecuada: *non è il massimo* critica con suavidad. Brusca: *schifezza* es fuerte si al otro le gustó. Exagerada: el drama cómico puede ofender a quien la eligió."),
    _it(9, 44, "C1", "Tu compañera de departamento dejó otra vez los platos sin lavar. Le hablás con humor.",
        "Vedo che i piatti si lavano da soli, eh?",
        "Sei una sporcacciona.",
        "Ah, che bello vivere in un museo di piatti sporchi, la mia collezione preferita, grazie davvero!",
        "Adecuada: la ironía breve marca el problema sin herir. Brusca: el insulto rompe la convivencia. Exagerada: el sarcasmo largo suena a rencor."),
    _it(10, 44, "C1", "Un amigo te cuenta que aprobó el examen más difícil del año.",
        "Mica male! Complimenti, davvero.",
        "Era facile.",
        "Incredibile! Impossibile! Non ci credo! Sei un mostro! Sei il migliore del mondo!",
        "Adecuada: *mica male* + *complimenti, davvero* suena sincero. Brusca: *era facile* le quita mérito. Exagerada: tanta exclamación puede sonar a sorpresa ofensiva."),
    _it(11, 44, "C1", "Tu jefe te pregunta si podés quedarte hasta las diez esta noche. No querés, y no es momento de ironías.",
        "Stasera purtroppo non posso, ma domani resto volentieri di più.",
        "Certo, figuriamoci, non ho una vita!",
        "Ma certo, con immenso piacere, è il mio sogno restare in ufficio fino alle dieci!",
        "Adecuada: con un superior, lo directo y cortés, con una alternativa. Brusca: la ironía (*non ho una vita*) a un jefe es riesgosa. Exagerada: el sarcasmo se nota y ofende."),

    # ================= Semana 48: tu, Lei, voi y el cambio de registro =================
    _it(1, 48, "C1", "Una colega mayor, a la que tratás de usted, te propone tutearse. Aceptás.",
        "Volentieri! Allora ti do del tu.",
        "Ok.",
        "Ma che onore immenso, non me lo merito, grazie infinite, sono commosso!",
        "Adecuada: aceptar con naturalidad y pasar al *tu* enseguida. Brusca: *ok* solo suena frío. Exagerada: tanto agradecimiento convierte un gesto normal en ceremonia."),
    _it(2, 48, "C1", "Conocés al padre de tu pareja, de unos 60 años. Primer saludo.",
        "Buongiorno, piacere di conoscerLa.",
        "Ciao, come va?",
        "Illustrissimo signore, è per me un onore immenso fare la Sua conoscenza.",
        "Adecuada: *Lei* y *piacere* son lo normal hasta que él proponga el *tu*. Brusca: *ciao, come va?* es demasiado confianzudo. Exagerada: *illustrissimo* suena a carta del siglo XIX."),
    _it(3, 48, "C1", "Un chico de 20 años en un bar de estudiantes te trata de usted y querés que te tutee.",
        "Dammi pure del tu!",
        "Non chiamarmi signore, sono giovane!",
        "Sarei infinitamente lieto se Lei volesse, con la Sua cortesia, darmi del tu.",
        "Adecuada: *dammi pure del tu* ofrece el tuteo con naturalidad. Brusca: el reproche lo hace sentir mal por ser educado. Exagerada: pedir el *tu* con tanta formalidad es una contradicción graciosa."),
    _it(4, 48, "C1", "En una oficina, a un funcionario que no conocés. No sabés si es licenciado.",
        "Buongiorno, dottore. Avrei bisogno di un'informazione.",
        "Senti, mi serve un'informazione.",
        "Egregio e illustrissimo dottore, mi permetto umilmente di disturbarLa...",
        "Adecuada: *dottore* es la fórmula segura en una oficina, con *Lei*. Brusca: *senti* y el *tu* son demasiado confianzudos. Exagerada: *egregio e illustrissimo* es de carta formal, no de ventanilla."),
    _it(5, 48, "C1", "Tu profesora de la universidad, con la que te tuteás en clase, te escribe un mail formal. Contestás.",
        "Gentile professoressa, La ringrazio per la risposta.",
        "Ciao prof, grazie!",
        "Illustrissima e stimatissima professoressa, Le porgo i miei più devoti ringraziamenti.",
        "Adecuada: si ella escribe formal, se contesta formal: *Gentile professoressa*, *Lei*. Brusca: *ciao prof* por mail cambia el registro sin permiso. Exagerada: *devoti ringraziamenti* suena a otro siglo."),
    _it(6, 48, "C1", "Hablás con una señora mayor del sur que te trata de *voi* a vos solo.",
        "Buongiorno, signora. Come sta?",
        "Perché mi dà del voi? Sono una persona sola.",
        "Buongiorno, signora, come state? State bene? Voi siete molto gentile, vi ringrazio.",
        "Adecuada: respondés con el *Lei* estándar; su *voi* de cortesía es regional y se entiende. Brusca: corregirla es de mala educación. Exagerada: imitar su *voi* suena a burla."),
    _it(7, 48, "C1", "En una reunión, el director te dice «diamoci del tu». Unos minutos después le hablás.",
        "Marco, secondo te va bene così?",
        "Direttore, secondo Lei va bene così?",
        "Carissimo Marco, amico mio, secondo te va benissimo così, vero?",
        "Adecuada: si te ofreció el *tu*, usalo con su nombre. Brusca (fría): volver al *Lei* y al cargo rechaza su gesto. Exagerada: *carissimo, amico mio* se toma una confianza que no te dio."),
    _it(8, 48, "C1", "En un negocio, la vendedora es joven y te tutea. Le respondés.",
        "Sì, grazie, prendo questa.",
        "Mi dia del Lei, per favore.",
        "Sì, grazie, carissima, tesoro, prendo questa, sei un amore!",
        "Adecuada: en muchos negocios jóvenes se tutea; seguís sin marcarlo. Brusca: pedir el *Lei* marca distancia (a veces está bien, pero suena seco). Exagerada: *tesoro, sei un amore* se toma demasiada confianza."),
    _it(9, 48, "C1", "Escribís a un grupo de compañeros de curso para organizar una cena.",
        "Ragazzi, venerdì cena insieme? Chi c'è?",
        "Venerdì cena. Venite.",
        "Gentili colleghi, con la presente mi pregio di invitarVi a una cena conviviale venerdì.",
        "Adecuada: *ragazzi* y *voi* son el registro de un grupo de amigos. Brusca: la orden sin pregunta. Exagerada: *mi pregio di invitarVi* es burocrático en un chat."),
    _it(10, 48, "C1", "Tu vecina, con la que siempre te trataste de usted, te pide un favor muy personal.",
        "Certo, signora, con piacere. Mi dica pure.",
        "Certo, dimmi.",
        "Ma certo, signora carissima, per Lei farei qualsiasi cosa al mondo, qualsiasi!",
        "Adecuada: mantener el *Lei* hasta que alguien proponga cambiar. Brusca: pasar al *tu* de golpe. Exagerada: *qualsiasi cosa al mondo* promete de más."),
    _it(11, 48, "C1", "En una entrevista de trabajo, el entrevistador te habla de *tu* desde el principio.",
        "Grazie, per me va benissimo il tu.",
        "Preferisco il Lei, grazie.",
        "Che bello, finalmente qualcuno alla mano! Allora, caro, dimmi tutto!",
        "Adecuada: seguir su registro con naturalidad. Brusca: pedir el *Lei* cuando él eligió el *tu* marca distancia justo cuando buscás caerle bien. Exagerada: *caro, dimmi tutto* te toma una confianza que no corresponde."),
]

# ================= Semana 48: el italiano neostandard =================
# «Entendelo siempre, escribilo nunca»: ¿escrito formal, hablado o los dos?
_OPT = ["solo hablado", "escrito formal y hablado", "solo escrito formal"]


def _var(n, sent, ans, note):
    return dict(id="pr-48-v%02d" % n, type="choice", topic="neostandard", level="C1", w=48,
                prompt=V, stem=sent, options=list(_OPT), answer=ans, note=note)


ITEMS += [
    _var(1, "A Maria gli ho detto di venire.", "solo hablado",
         "*Gli* por *le* (a ella) es muy común hablando; por escrito, *le ho detto*. Entendelo siempre, escribilo nunca."),
    _var(2, "Le ho detto di venire.", "escrito formal y hablado",
         "*Le* (a ella) es la forma estándar: sirve en todos los registros."),
    _var(3, "Penso che è una buona idea.", "solo hablado",
         "Tras *penso che*, lo estándar es el congiuntivo: *penso che sia*. El indicativo es frecuente en la charla."),
    _var(4, "A me mi piace molto.", "solo hablado",
         "*A me mi* repite el pronombre: en la charla es común; por escrito, *a me piace* o *mi piace*."),
    _var(5, "Lui è partito ieri.", "escrito formal y hablado",
         "*Lui* como sujeto ya es estándar; *egli* solo aparece en textos antiguos o muy formales."),
    _var(6, "Ci ho fame.", "solo hablado",
         "*Ci ho* (tengo) es del habla informal; por escrito, *ho fame*."),
    _var(7, "Egli sostiene che il progetto sia valido.", "solo escrito formal",
         "*Egli* es escrito y formal; hablando suena a libro viejo. En la charla, *lui*."),
    _var(8, "La casa che ci abito è in centro.", "solo hablado",
         "El *che* que sirve para todo (*che polivalente*) es del habla; por escrito, *la casa in cui abito*."),
    _var(9, "Se lo sapevo, venivo.", "solo hablado",
         "El imperfetto en el periodo hipotético (*se lo sapevo, venivo*) es muy común hablando; por escrito, *se l'avessi saputo, sarei venuto*."),
    _var(10, "Dico loro la verità.", "solo escrito formal",
         "*Loro* después del verbo es la forma cuidada, sobre todo escrita; hablando se dice *gli dico la verità*."),
    _var(11, "Il libro, l'ho letto ieri.", "escrito formal y hablado",
         "La dislocación con pronombre (*il libro, l'ho letto*) es neostandard aceptado: se oye en todas partes y se escribe en textos no burocráticos."),
    _var(12, "Mo' arrivo.", "solo hablado",
         "*Mo'* (ahora) es del centro y del sur, solo hablado; por escrito, *adesso* o *ora*."),
]
