# -*- coding: utf-8 -*-
"""Refuerzo 2: ejercicios propios para las semanas que el nuevo orden dejó
con poco material del libro: 16 riflessivi al passato, 35 passiva,
37 passato remoto, 38 discorso indiretto, 44 gerundio e participio,
47 numerali.
"""

CE = "Elegí la forma correcta."
TR = "Traducí al italiano."

ITEMS = [
    # ================= Settimana 16: Riflessivi al passato =================
    dict(id="rf2-16-01", type="choice", topic="riflessivi passato", level="A2",
         prompt=CE, stem="Stamattina Anna ___ alle sette.",
         options=["si è alzata", "si ha alzata", "è alzata"], answer="si è alzata",
         note="Todos los reflexivos van con essere, y el participio concuerda con el sujeto."),
    dict(id="rf2-16-02", type="choice", topic="riflessivi passato", level="A2",
         prompt=CE, stem="Ieri sera ___ molto alla festa.",
         options=["ci siamo divertiti", "ci abbiamo divertiti", "siamo divertito"],
         answer="ci siamo divertiti",
         note="divertirsi → ci siamo divertiti: essere y participio en plural."),
    dict(id="rf2-16-03", type="cloze", topic="riflessivi passato", level="A2",
         prompt="Completá con el passato prossimo del verbo reflexivo.",
         stem="Marco e Luca ___ (conoscersi) a Roma.", answer="si sono conosciuti",
         note="Recíproco: se conocieron el uno al otro. Con essere, en plural."),
    dict(id="rf2-16-04", type="cloze", topic="riflessivi passato", level="A2",
         prompt="Completá con el passato prossimo del verbo reflexivo.",
         stem="Giulia ___ (lavarsi) le mani.", answer="si è lavata",
         alt=["si è lavate"],
         note="Aun con objeto directo va con essere; lo normal es concordar con el sujeto."),
    dict(id="rf2-16-05", type="choice", topic="riflessivi passato", level="A2",
         prompt="Elegí la forma correcta (habla un hombre).",
         stem="Non ___ del problema.",
         options=["mi sono accorto", "mi ho accorto", "sono accorto"], answer="mi sono accorto",
         note="accorgersi di = darse cuenta de. Participio irregular: accorto."),
    dict(id="rf2-16-06", type="translate", topic="riflessivi passato", level="A2",
         prompt=TR, stem="Me olvidé las llaves.",
         answer="Mi sono dimenticato le chiavi",
         alt=["Mi sono dimenticata le chiavi", "Ho dimenticato le chiavi"],
         note="dimenticarsi con essere; dimenticare sin pronombre, con avere."),
    dict(id="rf2-16-07", type="translate", topic="riflessivi passato", level="A2",
         prompt=TR, stem="Nos casamos en 2015.",
         answer="Ci siamo sposati nel 2015", alt=["Ci siamo sposate nel 2015"],
         note="sposarsi con essere. Con los años va «nel»: nel 2015."),
    dict(id="rf2-16-08", type="cloze", topic="riflessivi passato", level="A2",
         prompt="Completá con el passato prossimo del verbo reflexivo.",
         stem="Le ragazze ___ (svegliarsi) tardi.", answer="si sono svegliate",
         note="Sujeto femenino plural: svegliate."),
    dict(id="rf2-16-09", type="choice", topic="riflessivi passato", level="A2",
         prompt="Elegí la forma correcta (le hablás a un hombre).",
         stem="Perché ___? Eri stanco?",
         options=["ti sei fermato", "ti hai fermato", "sei fermato"], answer="ti sei fermato",
         note="fermarsi = detenerse. Reflexivo: essere."),
    dict(id="rf2-16-10", type="cloze", topic="riflessivi passato", level="A2",
         prompt="Completá con el passato prossimo del verbo reflexivo.",
         stem="Voi ___ (vestirsi) in fretta.", answer="vi siete vestiti",
         alt=["vi siete vestite"],
         note="vestirsi → vi siete vestiti (o vestite, si son todas mujeres)."),
    dict(id="rf2-16-11", type="choice", topic="riflessivi passato", level="A2",
         prompt="Elegí el auxiliar.",
         stem="Mi ___ dovuto alzare presto.", options=["sono", "ho", "è"], answer="sono",
         note="Con el pronombre delante del modal, auxiliar essere: mi sono dovuto alzare. "
              "Con el pronombre pegado, avere: ho dovuto alzarmi."),
    dict(id="rf2-16-12", type="choice", topic="riflessivi passato", level="A2",
         prompt=CE, stem="Sabato scorso Paola e io ___ in centro.",
         options=["ci siamo incontrate", "si sono incontrate", "ci abbiamo incontrate"],
         answer="ci siamo incontrate",
         note="Paola e io = noi: ci siamo. Dos mujeres: incontrate."),

    # ================= Settimana 35: La voce passiva =================
    dict(id="rf2-35-01", type="choice", topic="passivo", level="B2",
         prompt=CE, stem="Il barone rampante ___ da Calvino nel 1957.",
         options=["è stato scritto", "ha stato scritto", "è scritto stato"],
         answer="è stato scritto",
         note="Pasiva en passato prossimo: è stato + participio, concordado con el sujeto."),
    dict(id="rf2-35-02", type="choice", topic="passivo", level="B2",
         prompt="Elegí la forma que subraya el proceso.",
         stem="Le lettere ___ ogni mattina alle nove.",
         options=["vengono consegnate", "vengono consegnati", "vanno consegnato"],
         answer="vengono consegnate",
         note="venire + participio: pasiva de proceso, solo en tiempos simples."),
    dict(id="rf2-35-03", type="cloze", topic="passivo", level="B2",
         prompt="Completá con andare + participio (= hay que, debe).",
         stem="Questo modulo ___ (firmare) entro domani.", answer="va firmato",
         note="andare + participio expresa obligación: va firmato = hay que firmarlo."),
    dict(id="rf2-35-04", type="choice", topic="passivo", level="B2",
         prompt=CE, stem="La chiesa ___ costruita nel Settecento.",
         options=["è stata", "ha stata", "è stato"], answer="è stata",
         note="La chiesa es femenino: è stata costruita."),
    dict(id="rf2-35-05", type="translate", topic="passivo", level="B2",
         prompt=TR, stem="La ventana fue rota por los chicos.",
         answer="La finestra è stata rotta dai ragazzi",
         alt=["La finestra è stata rotta dai bambini", "La finestra fu rotta dai ragazzi",
              "La finestra è stata rotta dai bimbi"],
         note="El agente va con «da»: dai ragazzi."),
    dict(id="rf2-35-06", type="cloze", topic="passivo", level="B2",
         prompt="Completá con la pasiva de proceso (venire + participio).",
         stem="I biglietti ___ (vendere) solo online.", answer="vengono venduti",
         alt=["sono venduti"],
         note="venire + participio concordado: vengono venduti."),
    dict(id="rf2-35-07", type="choice", topic="passivo", level="B2",
         prompt=CE, stem="Il ladro ___ arrestato ieri sera.",
         options=["è stato", "è venuto", "ha stato"], answer="è stato",
         note="En tiempos compuestos la pasiva va con essere: venire solo en tiempos simples."),
    dict(id="rf2-35-08", type="choice", topic="passivo", level="B2",
         prompt="Elegí la preposición del agente.",
         stem="La Gioconda è stata dipinta ___ Leonardo.", options=["da", "di", "per"],
         answer="da",
         note="El agente de la pasiva va con «da» (no «por»)."),
    dict(id="rf2-35-09", type="cloze", topic="passivo", level="B2",
         prompt="Completá con andare + participio (= no deben).",
         stem="Questi errori non ___ (ripetere).", answer="vanno ripetuti",
         note="*andare* + participio = obligación en pasiva: *non vanno ripetuti* («no hay que repetirlos»), con participio concordado con *errori*."),
    dict(id="rf2-35-10", type="translate", topic="passivo", level="B2",
         prompt=TR, stem="El museo es visitado por miles de turistas.",
         answer="Il museo è visitato da migliaia di turisti",
         alt=["Il museo viene visitato da migliaia di turisti"],
         note="La pasiva va con *essere* y el agente con *da*: *è visitato da migliaia di turisti*. «Miles de» = *migliaia di*."),
    dict(id="rf2-35-11", type="choice", topic="passivo", level="B2",
         prompt="Elegí la versión pasiva de «Marco ha invitato Laura».",
         stem="___", options=["Laura è stata invitata da Marco",
                              "Laura ha stato invitata da Marco",
                              "Laura è stato invitato da Marco"],
         answer="Laura è stata invitata da Marco",
         note="El objeto pasa a sujeto y el participio concuerda con él: invitata."),
    dict(id="rf2-35-12", type="choice", topic="passivo", level="B2",
         prompt=CE, stem="La riunione ___ rimandata a lunedì.",
         options=["è stata", "ha stata", "è stato"], answer="è stata",
         note="rimandare = posponer. La riunione, femenino: è stata rimandata."),

    # ================= Settimana 37: Passato remoto =================
    dict(id="rf2-37-01", type="choice", topic="passato remoto", level="B2",
         prompt=CE, stem="Dante ___ a Firenze nel 1265.",
         options=["nacque", "nascé", "nasceva"], answer="nacque",
         note="nascere, irregular en el patrón 1-3-3: nacqui, nascesti, nacque."),
    dict(id="rf2-37-02", type="choice", topic="passato remoto", level="B2",
         prompt=CE, stem="Garibaldi ___ la Sicilia nel 1860.",
         options=["conquistò", "conquistà", "conquistava"], answer="conquistò",
         note="-are → -ò en la tercera persona, con tilde."),
    dict(id="rf2-37-03", type="cloze", topic="passato remoto", level="B2",
         prompt="Completá con el passato remoto.",
         stem="Quando ___ (vedere) la lettera, Maria pianse.", answer="vide",
         note="vedere: vidi, vedesti, vide, vedemmo, vedeste, videro."),
    dict(id="rf2-37-04", type="choice", topic="passato remoto", level="B2",
         prompt=CE, stem="Io ___ la verità solo molti anni dopo.",
         options=["seppi", "sapei", "sapetti"], answer="seppi",
         note="sapere: seppi, sapesti, seppe, sapemmo, sapeste, seppero."),
    dict(id="rf2-37-05", type="cloze", topic="passato remoto", level="B2",
         prompt="Completá con el passato remoto.",
         stem="I soldati ___ (partire) all'alba.", answer="partirono",
         note="-ire regular: partii, partisti, partì, partimmo, partiste, partirono."),
    dict(id="rf2-37-06", type="choice", topic="passato remoto", level="B2",
         prompt=CE, stem="Tu ___ il primo a capirlo.",
         options=["fosti", "fusti", "fui"], answer="fosti",
         note="essere: fui, fosti, fu, fummo, foste, furono."),
    dict(id="rf2-37-07", type="cloze", topic="passato remoto", level="B2",
         prompt="Completá con el passato remoto.",
         stem="Quella notte noi ___ (avere) molta paura.", answer="avemmo",
         note="avere: ebbi, avesti, ebbe, avemmo, aveste, ebbero."),
    dict(id="rf2-37-08", type="choice", topic="passato remoto", level="B2",
         prompt="Elegí el trapassato remoto.",
         stem="Dopo che ___, uscirono.",
         options=["ebbero mangiato", "ebbero mangiati", "furono mangiato"],
         answer="ebbero mangiato",
         note="Trapassato remoto: passato remoto del auxiliar + participio, tras «dopo che», «appena»."),
    dict(id="rf2-37-09", type="choice", topic="passato remoto", level="B2",
         prompt=CE, stem="Lui ___ tutto e se ne andò.",
         options=["disse", "dicette", "dicì"], answer="disse",
         note="dire: dissi, dicesti, disse, dicemmo, diceste, dissero."),
    dict(id="rf2-37-10", type="cloze", topic="passato remoto", level="B2",
         prompt="Completá con el passato remoto.",
         stem="Colombo ___ (arrivare) in America nel 1492.", answer="arrivò",
         note="Relato histórico: passato remoto. arrivare → arrivò."),
    dict(id="rf2-37-11", type="choice", topic="passato remoto", level="B2",
         prompt="¿Qué forma es «fecero»?",
         stem="Gli operai fecero sciopero per tre giorni.",
         options=["passato remoto de fare", "imperfetto de fare", "futuro de fare"],
         answer="passato remoto de fare",
         note="fare: feci, facesti, fece, facemmo, faceste, fecero."),
    dict(id="rf2-37-12", type="cloze", topic="passato remoto", level="B2",
         prompt="Completá con el passato remoto.",
         stem="Voi ___ (venire) troppo tardi.", answer="veniste",
         note="venire: venni, venisti, venne, venimmo, veniste, vennero."),

    # ================= Settimana 38: Discorso indiretto =================
    dict(id="rf2-38-01", type="choice", topic="discorso indiretto", level="B2",
         prompt="Pasalo a discurso indirecto.",
         stem="«Sono stanco», disse Luca. → Luca disse che ___ stanco.",
         options=["era", "è stato", "sarà"], answer="era",
         note="Presente → imperfetto cuando el verbo que introduce está en pasado."),
    dict(id="rf2-38-02", type="choice", topic="discorso indiretto", level="B2",
         prompt="Pasalo a discurso indirecto.",
         stem="«Ho perso il treno», disse Anna. → Anna disse che ___ il treno.",
         options=["aveva perso", "ha perso", "perdeva"], answer="aveva perso",
         note="Passato prossimo → trapassato prossimo."),
    dict(id="rf2-38-03", type="choice", topic="discorso indiretto", level="B2",
         prompt="Pasalo a discurso indirecto.",
         stem="«Verrò domani», disse Paolo. → Paolo disse che ___ il giorno dopo.",
         options=["sarebbe venuto", "verrebbe", "verrà"], answer="sarebbe venuto",
         note="Futuro visto desde el pasado → condizionale passato, no simple."),
    dict(id="rf2-38-04", type="choice", topic="discorso indiretto", level="B2",
         prompt="Pasalo a discurso indirecto.",
         stem="«Aspettami!», mi disse Carlo. → Carlo mi disse ___.",
         options=["di aspettarlo", "che aspettami", "aspettarlo"], answer="di aspettarlo",
         note="Imperativo → di + infinitivo, y el pronombre cambia: mi → lo."),
    dict(id="rf2-38-05", type="cloze", topic="discorso indiretto", level="B2",
         prompt="Completá el discurso indirecto.",
         stem="«Abito qui», disse Marta. → Marta disse che abitava ___.", answer="lì",
         alt=["là"],
         note="qui → lì: el lugar cambia cuando lo cuenta otro."),
    dict(id="rf2-38-06", type="choice", topic="discorso indiretto", level="B2",
         prompt="Pasalo a discurso indirecto.",
         stem="«Oggi piove», disse. → Disse che ___ pioveva.",
         options=["quel giorno", "oggi", "domani"], answer="quel giorno",
         note="oggi → quel giorno; ieri → il giorno prima; domani → il giorno dopo."),
    dict(id="rf2-38-07", type="cloze", topic="discorso indiretto", level="B2",
         prompt="Completá el discurso indirecto: ¿cómo queda «domani»?",
         stem="«Domani parto», disse Gianni. → Gianni disse che sarebbe partito ___.",
         answer="il giorno dopo", alt=["l'indomani", "il giorno seguente"],
         note="domani → il giorno dopo (o l'indomani)."),
    dict(id="rf2-38-08", type="choice", topic="discorso indiretto", level="B2",
         prompt="Pasalo a pregunta indirecta.",
         stem="Mi chiese: «Dove vai?» → Mi chiese dove ___.",
         options=["andavo", "andrò", "vadano"], answer="andavo",
         note="Pregunta indirecta tras un verbo en pasado: el presente pasa a imperfetto."),
    dict(id="rf2-38-09", type="translate", topic="discorso indiretto", level="B2",
         prompt=TR, stem="Dijo que estaba cansada.",
         answer="Ha detto che era stanca", alt=["Disse che era stanca"],
         note="«Estaba» = era: imperfetto, igual que en castellano."),
    dict(id="rf2-38-10", type="choice", topic="discorso indiretto", level="B2",
         prompt="Pasalo a discurso indirecto.",
         stem="«Questo libro è mio», disse. → Disse che ___ libro era suo.",
         options=["quel", "questo", "codesto"], answer="quel",
         note="questo → quello, y el posesivo cambia de persona: mio → suo."),
    dict(id="rf2-38-11", type="choice", topic="discorso indiretto", level="B2",
         prompt="Pasalo a discurso indirecto.",
         stem="«Chiamerò più tardi», disse. → Disse che ___ più tardi.",
         options=["avrebbe chiamato", "chiamerebbe", "chiamerà"], answer="avrebbe chiamato",
         note="Futuro → condizionale passato: el «llamaría» del castellano es «avrebbe chiamato»."),
    dict(id="rf2-38-12", type="cloze", topic="discorso indiretto", level="B2",
         prompt="Completá el discurso indirecto.",
         stem="«Studiate!», ci disse il professore. → Il professore ci disse ___.",
         answer="di studiare",
         note="Imperativo → di + infinitivo."),

    # ================= Settimana 44: Gerundio e participio =================
    dict(id="rf2-44-01", type="choice", topic="gerundio", level="C1",
         prompt=CE, stem="___ la strada, ho visto un incidente.",
         options=["Attraversando", "Attraversato", "Attraversare"], answer="Attraversando",
         note="Gerundio con el mismo sujeto: mientras cruzaba."),
    dict(id="rf2-44-02", type="choice", topic="participio", level="C1",
         prompt=CE, stem="___ i compiti, siamo usciti.",
         options=["Finiti", "Finendo", "Finire"], answer="Finiti",
         note="Participio absoluto: una vez terminados los deberes. Concuerda con «compiti»."),
    dict(id="rf2-44-03", type="cloze", topic="gerundio", level="C1",
         prompt="Completá con el gerundio.",
         stem="___ (fare) sport, si sta meglio.", answer="Facendo",
         note="fare → facendo, igual que facevo y facciamo: se usa la raíz larga del verbo."),
    dict(id="rf2-44-04", type="choice", topic="gerundio", level="C1",
         prompt=CE, stem="Pur ___ molto, non è ingrassato.",
         options=["mangiando", "mangiato", "mangiare"], answer="mangiando",
         note="pur + gerundio = aunque: aunque come mucho."),
    dict(id="rf2-44-05", type="choice", topic="gerundio", level="C1",
         prompt=CE, stem="___ tardi, non abbiamo trovato posto.",
         options=["Essendo arrivati", "Avendo arrivato", "Arrivando stati"],
         answer="Essendo arrivati",
         note="Gerundio compuesto: essendo/avendo + participio. arrivare va con essere."),
    dict(id="rf2-44-06", type="cloze", topic="participio", level="C1",
         prompt="Completá con el participio pasado.",
         stem="___ (dire) questo, se ne andò.", answer="Detto",
         note="Participio absoluto: dicho esto."),
    dict(id="rf2-44-07", type="translate", topic="gerundio", level="C1",
         prompt=TR, stem="Estudiando se aprende.", answer="Studiando si impara",
         alt=["Studiando s'impara"],
         note="Gerundio de modo, como en castellano."),
    dict(id="rf2-44-08", type="choice", topic="participio", level="C1",
         prompt=CE, stem="___ la lettera, la mise in tasca.",
         options=["Letta", "Letto", "Leggendo"], answer="Letta",
         note="Participio absoluto concordado con «lettera»: letta."),
    dict(id="rf2-44-09", type="choice", topic="gerundio", level="C1",
         prompt=CE, stem="Avendo ___ tutto, se ne andò.",
         options=["detto", "dicendo", "dire"], answer="detto",
         note="Gerundio compuesto: avendo + participio."),
    dict(id="rf2-44-10", type="cloze", topic="gerundio", level="C1",
         prompt="Completá con el gerundio.",
         stem="Sto ___ (leggere) un bel libro.", answer="leggendo",
         note="stare + gerundio: acción en curso."),
    dict(id="rf2-44-11", type="translate", topic="participio", level="C1",
         prompt=TR, stem="Terminada la reunión, nos fuimos.",
         answer="Finita la riunione, siamo andati via",
         alt=["Finita la riunione, ce ne siamo andati", "Finita la riunione, siamo usciti",
              "Terminata la riunione, siamo andati via", "Terminata la riunione, ce ne siamo andati"],
         note="Participio absoluto, igual que en castellano: finita la riunione."),
    dict(id="rf2-44-12", type="choice", topic="gerundio", level="C1",
         prompt=CE, stem="Non ___ capito, ha chiesto di nuovo.",
         options=["avendo", "essendo", "avuto"], answer="avendo",
         note="capire va con avere: non avendo capito."),

    # ================= Settimana 47: Numerali, misure e quantità =================
    dict(id="rf2-47-01", type="choice", topic="numerali", level="B1",
         prompt="Elegí el número.", stem="due terzi",
         options=["2/3", "3/2", "23"], answer="2/3",
         note="Fracciones: numerador cardinal, denominador ordinal (un terzo, tre quarti)."),
    dict(id="rf2-47-02", type="cloze", topic="numerali", level="B1",
         prompt="Completá (25 %).",
         stem="Il venticinque ___ cento degli studenti è straniero.", answer="per",
         note="Porcentaje: il venticinque per cento, con artículo."),
    dict(id="rf2-47-03", type="choice", topic="numerali", level="B1",
         prompt=CE, stem="Ho comprato ___ di uova.",
         options=["una dozzina", "un dozzina", "una dozzine"], answer="una dozzina",
         note="Las cantidades aproximadas o colectivas llevan *di*: *una dozzina di uova*, «una docena de»."),
    dict(id="rf2-47-04", type="choice", topic="numerali", level="B1",
         prompt=CE, stem="C'erano ___ di persone in piazza.",
         options=["migliaia", "migliai", "mille"], answer="migliaia",
         note="un migliaio, due migliaia: el plural es femenino en -a."),
    dict(id="rf2-47-05", type="cloze", topic="numerali", level="B1",
         prompt="Completá (1,5 kg).",
         stem="Un chilo e ___ di pane, per favore.", answer="mezzo",
         note="un chilo e mezzo; mezzo después del sustantivo no cambia."),
    dict(id="rf2-47-06", type="choice", topic="numerali", level="B1",
         prompt="¿Cuántos minutos son «tre quarti d'ora»?", stem="tre quarti d'ora",
         options=["quarantacinque", "trentacinque", "settantacinque"], answer="quarantacinque",
         note="*un quarto d'ora* son 15 minutos, así que *tre quarti d'ora* son 45: el italiano cuenta en cuartos de hora."),
    dict(id="rf2-47-07", type="choice", topic="numerali", level="B1",
         prompt=CE, stem="Mi serve un ___ di scarpe nuove.",
         options=["paio", "paia", "pari"], answer="paio",
         note="un paio (singular), due paia (plural irregular)."),
    dict(id="rf2-47-08", type="translate", topic="numerali", level="B1",
         prompt=TR, stem="Unas cien personas.", answer="Un centinaio di persone",
         alt=["Circa cento persone"],
         note="-ina / -aio para cantidades aproximadas: una decina, un centinaio."),
    dict(id="rf2-47-09", type="choice", topic="numerali", level="B1",
         prompt=CE, stem="Il Novecento è il ___ secolo.",
         options=["ventesimo", "diciannovesimo", "novecentesimo"], answer="ventesimo",
         note="Il Novecento = los años 1900 = el siglo XX (ventesimo)."),
    dict(id="rf2-47-10", type="choice", topic="numerali", level="B1",
         prompt="Elegí la forma correcta (unos diez días).", stem="Resto una ___ di giorni.",
         options=["decina", "decima", "diecina"], answer="decina",
         note="*-ina* forma números aproximados: *una decina* («unos diez»); *decima* es el ordinal «décima»."),
    dict(id="rf2-47-11", type="choice", topic="numerali", level="B1",
         prompt=CE, stem="È arrivato ___ (3.º).",
         options=["terzo", "tre", "terzino"], answer="terzo",
         note="Ordinales: primo, secondo, terzo… decimo; después, -esimo."),
    dict(id="rf2-47-12", type="cloze", topic="numerali", level="B1",
         prompt="Completá (½).",
         stem="Ho bevuto ___ bicchiere di vino.", answer="mezzo",
         note="mezzo delante del sustantivo concuerda: mezzo bicchiere, mezza bottiglia."),
]
